/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Auxiliar_Movimientos extends javax.swing.JPanel {

    /**
     * Creates new form Auxiliar_Movimientos
     */
    public Auxiliar_Movimientos() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha de Consulta", "Rango de Cuentas", "Periodo", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblAMovimientos.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAMovimientos = new javax.swing.JTable();
        btnAddAMovimientos = new javax.swing.JButton();
        btnEditAMovimientos = new javax.swing.JButton();
        btnDeleteAMovimientos = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jPanel1ComponentRemoved(evt);
            }
        });

        tblAMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAMovimientos);

        btnAddAMovimientos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddAMovimientos.setForeground(new java.awt.Color(26, 61, 99));
        btnAddAMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddAMovimientos.setText("Añadir");
        btnAddAMovimientos.addActionListener(this::btnAddAMovimientosActionPerformed);

        btnEditAMovimientos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditAMovimientos.setForeground(new java.awt.Color(26, 61, 99));
        btnEditAMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditAMovimientos.setText("Editar");
        btnEditAMovimientos.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditAMovimientos.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditAMovimientos.addActionListener(this::btnEditAMovimientosActionPerformed);

        btnDeleteAMovimientos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteAMovimientos.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteAMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteAMovimientos.setText("Eliminar");
        btnDeleteAMovimientos.addActionListener(this::btnDeleteAMovimientosActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddAMovimientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditAMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteAMovimientos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditAMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel1ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentRemoved

    private void btnAddAMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAMovimientosActionPerformed
       mostrarDialogoAuxiliar();
    }//GEN-LAST:event_btnAddAMovimientosActionPerformed

    private void btnEditAMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAMovimientosActionPerformed
        JOptionPane.showMessageDialog(this, "Esta pantalla es de reportes contables. Para editar una póliza, usa el módulo de 'Captura de Pólizas'.");
    }//GEN-LAST:event_btnEditAMovimientosActionPerformed

    private void btnDeleteAMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAMovimientosActionPerformed
       JOptionPane.showMessageDialog(this, "No se pueden eliminar registros desde el Auxiliar de Movimientos.");
    }//GEN-LAST:event_btnDeleteAMovimientosActionPerformed

private void mostrarDialogoAuxiliar() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Auxiliar de Movimientos", true);
        dialogo.setSize(950, 680);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. DATOS DE SELECCIÓN (Filtros superiores) ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createEtchedBorder());
        pnlSel.setBounds(10, 10, 915, 140);

        // Bloque Izquierdo
        pnlSel.add(new JLabel("Compañía")).setBounds(15, 15, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12"})).setBounds(105, 15, 80, 25);
        pnlSel.add(new JLabel("UNIDAD ESCOLAR BENAVENTE, A.C.")).setBounds(195, 15, 250, 25);

        pnlSel.add(new JLabel("Cuenta Inicial")).setBounds(15, 45, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(105, 45, 150, 25);

        pnlSel.add(new JLabel("Cuenta Final")).setBounds(15, 75, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(105, 75, 150, 25);

        pnlSel.add(new JLabel("Fecha Inicial")).setBounds(15, 105, 80, 25);
        pnlSel.add(new JTextField("04/06/2026")).setBounds(105, 105, 90, 25);

        pnlSel.add(new JLabel("Fecha Final")).setBounds(210, 105, 70, 25);
        pnlSel.add(new JTextField("04/06/2026")).setBounds(290, 105, 90, 25);

        // Bloque Central
        JCheckBox chkTodosCC = new JCheckBox("Todos los Centros de Costos");
        chkTodosCC.setBounds(460, 15, 200, 25);
        pnlSel.add(chkTodosCC);

        pnlSel.add(new JLabel("Tipo de Moneda")).setBounds(460, 45, 100, 25);
        pnlSel.add(new JComboBox<>(new String[]{"MXP"})).setBounds(570, 45, 80, 25);

        pnlSel.add(new JLabel("Tipo Contab.")).setBounds(460, 75, 100, 25);
        pnlSel.add(new JComboBox<>(new String[]{"MN"})).setBounds(570, 75, 80, 25);

        pnlSel.add(new JLabel("Tipo de Movimiento")).setBounds(460, 105, 110, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(570, 105, 80, 25);

        // Bloque Derecho (Sub-Subcuenta)
        JPanel pnlSub = new JPanel(null);
        pnlSub.setBorder(BorderFactory.createTitledBorder("Sub-Subcuenta"));
        pnlSub.setBounds(680, 10, 220, 85);
        
        pnlSub.add(new JLabel("Tipo")).setBounds(15, 20, 50, 25);
        pnlSub.add(new JComboBox<>(new String[]{""})).setBounds(75, 20, 130, 25);
        
        pnlSub.add(new JLabel("Número")).setBounds(15, 50, 50, 25);
        pnlSub.add(new JComboBox<>(new String[]{""})).setBounds(75, 50, 130, 25);
        
        pnlSel.add(pnlSub);

        // Botón Filtrar
        JButton btnFiltra = new JButton("Filtrar Información");
        btnFiltra.setBounds(680, 100, 220, 30);
        pnlSel.add(btnFiltra);

        dialogo.add(pnlSel);

        // --- 2. TABLA AUXILIAR ---
        // Pongo columnas contables estándar para un auxiliar
        JTable tblAuxiliar = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Cuenta", "Fecha", "Tipo", "Póliza", "Concepto", "Referencia", "Cargo", "Abono", "Saldo"}
        ));
        tblAuxiliar.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        
        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createEtchedBorder());
        pnlTabla.setBounds(10, 160, 915, 390);
        
        JScrollPane scrollAuxiliar = new JScrollPane(tblAuxiliar);
        scrollAuxiliar.setBounds(10, 10, 895, 370);
        pnlTabla.add(scrollAuxiliar);
        
        dialogo.add(pnlTabla);

        // --- 3. BOTONES INFERIORES ---
        JButton btnExportar = new JButton("Exporta");
        btnExportar.setBounds(300, 570, 100, 40);
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(420, 570, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(540, 570, 100, 40);

        dialogo.add(btnExportar);
        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 4. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Buscando movimientos en el rango de fechas y cuentas... (Simulación)");
            // Aquí iría tu query SQL para llenar la tabla
        });

        btnExportar.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Exportando auxiliar a Excel (.xlsx)... (Simulación)");
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando auxiliar de movimientos a la impresora... (Simulación)");
        });

        // --- 5. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAMovimientos;
    private javax.swing.JButton btnDeleteAMovimientos;
    private javax.swing.JButton btnEditAMovimientos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAMovimientos;
    // End of variables declaration//GEN-END:variables
}
