/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Balanza_Comprobacion extends javax.swing.JPanel {

    /**
     * Creates new form Balanza_Comprobacion
     */
    public Balanza_Comprobacion() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha de Consulta", "Año", "Período", "Rango de Cuentas", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblBComprobacion.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBComprobacion = new javax.swing.JTable();
        btnAddBC = new javax.swing.JButton();
        btnEditBC = new javax.swing.JButton();
        btnDeleteBC = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblBComprobacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBComprobacion);

        btnAddBC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddBC.setForeground(new java.awt.Color(26, 61, 99));
        btnAddBC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddBC.setText("Añadir");
        btnAddBC.addActionListener(this::btnAddBCActionPerformed);

        btnEditBC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditBC.setForeground(new java.awt.Color(26, 61, 99));
        btnEditBC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditBC.setText("Editar");
        btnEditBC.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditBC.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditBC.addActionListener(this::btnEditBCActionPerformed);

        btnDeleteBC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteBC.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteBC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteBC.setText("Eliminar");
        btnDeleteBC.addActionListener(this::btnDeleteBCActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddBC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteBC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditBC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteBC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBCActionPerformed
        mostrarDialogoBalanza();
    }//GEN-LAST:event_btnAddBCActionPerformed

    private void btnEditBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBCActionPerformed
       JOptionPane.showMessageDialog(this, "Las balanzas de comprobación son reportes calculados. No pueden editarse directamente.");
    }//GEN-LAST:event_btnEditBCActionPerformed

    private void btnDeleteBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBCActionPerformed
        JOptionPane.showMessageDialog(this, "No se pueden eliminar datos desde un generador de reportes.");
    }//GEN-LAST:event_btnDeleteBCActionPerformed

private void mostrarDialogoBalanza() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Balanza de Comprobación", true);
        dialogo.setSize(950, 680);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. DATOS DE SELECCIÓN (Panel Superior) ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createEtchedBorder());
        pnlSel.setBounds(10, 10, 915, 150);

        // Bloque Izquierdo
        pnlSel.add(new JLabel("Compañía")).setBounds(20, 15, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12"})).setBounds(100, 15, 70, 25);
        pnlSel.add(new JLabel("UNIDAD ESCOLAR BENAVENTE, A.C.")).setBounds(180, 15, 250, 25);

        pnlSel.add(new JLabel("De la cuenta")).setBounds(20, 50, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(100, 50, 150, 25);

        pnlSel.add(new JLabel("A la cuenta")).setBounds(20, 85, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(100, 85, 150, 25);

        // Niveles (Radio Buttons 1 al 9)
        pnlSel.add(new JLabel("Nivel")).setBounds(20, 120, 50, 25);
        ButtonGroup bgNivel = new ButtonGroup();
        int xPosNivel = 70;
        for (int i = 1; i <= 9; i++) {
            JRadioButton rb = new JRadioButton(String.valueOf(i));
            if(i == 1) rb.setSelected(true); // Selecciona el nivel 1 por defecto
            rb.setBounds(xPosNivel, 120, 40, 25);
            bgNivel.add(rb);
            pnlSel.add(rb);
            xPosNivel += 45;
        }

        // Bloque Central
        JCheckBox chkTodosCC = new JCheckBox("Todos los Centros de Costos");
        chkTodosCC.setBounds(500, 15, 200, 25);
        pnlSel.add(chkTodosCC);

        pnlSel.add(new JLabel("Tipo Moneda")).setBounds(550, 50, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{"MXP"})).setBounds(640, 50, 70, 25);

        pnlSel.add(new JLabel("Tipo Contab.")).setBounds(550, 85, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{"MN"})).setBounds(640, 85, 70, 25);

        // Bloque Derecho (Año, Periodo, Checks, Botón)
        JPanel pnlDerecho = new JPanel(null);
        pnlDerecho.setBorder(BorderFactory.createEtchedBorder());
        pnlDerecho.setBounds(730, 10, 175, 130);

        pnlDerecho.add(new JLabel("Año")).setBounds(10, 10, 40, 25);
        pnlDerecho.add(new JTextField("2026")).setBounds(60, 10, 80, 25);

        pnlDerecho.add(new JLabel("Período")).setBounds(10, 40, 50, 25);
        pnlDerecho.add(new JTextField("5")).setBounds(60, 40, 80, 25);

        JCheckBox chkMostrarCargos = new JCheckBox("Mostrar Cargos/Creditos", true);
        chkMostrarCargos.setBounds(10, 70, 160, 20);
        JCheckBox chkIncluirCeros = new JCheckBox("Incluir Saldos en Ceros");
        chkIncluirCeros.setBounds(10, 95, 160, 20);

        pnlDerecho.add(chkMostrarCargos);
        pnlDerecho.add(chkIncluirCeros);
        pnlSel.add(pnlDerecho);

        // --- BOTÓN FILTRAR ---
        JButton btnFiltra = new JButton("Filtrar Información");
        btnFiltra.setBounds(730, 150, 175, 30);
        dialogo.add(btnFiltra);

        dialogo.add(pnlSel);

        // --- 2. TABLA DE BALANZA ---
        JTable tblBalanza = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Cuenta", "Descripción", "Saldo Inicial", "Cargos", "Créditos", "Saldo Final"}
        ));
        
        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createEtchedBorder());
        pnlTabla.setBounds(10, 190, 915, 360);
        
        JScrollPane scrollBalanza = new JScrollPane(tblBalanza);
        scrollBalanza.setBounds(10, 10, 895, 340);
        pnlTabla.add(scrollBalanza);
        
        dialogo.add(pnlTabla);

        // --- 3. BOTONES INFERIORES ---
        JButton btnExportar = new JButton("Exporta");
        btnExportar.setBounds(300, 580, 100, 40);
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(420, 580, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(540, 580, 100, 40);

        dialogo.add(btnExportar);
        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 4. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Calculando saldos iniciales y finales de la Balanza... (Simulación)");
            // Lógica SQL para llenar tblBalanza
        });

        btnExportar.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Exportando Balanza de Comprobación a Excel (.xlsx)... (Simulación)");
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando Balanza a la impresora... (Simulación)");
        });

        // --- 5. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBC;
    private javax.swing.JButton btnDeleteBC;
    private javax.swing.JButton btnEditBC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBComprobacion;
    // End of variables declaration//GEN-END:variables
}
