/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Balance_Compañia extends javax.swing.JPanel {

    /**
     * Creates new form Balance_Compañia
     */
    public Balance_Compañia() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha de Consulta", "Año", "Período", "Nivel", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblBCompañia.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBCompañia = new javax.swing.JTable();
        btnAddBCompañia = new javax.swing.JButton();
        btnEditBCompañia = new javax.swing.JButton();
        btnDeleteBCompañia = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblBCompañia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBCompañia);

        btnAddBCompañia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddBCompañia.setForeground(new java.awt.Color(26, 61, 99));
        btnAddBCompañia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddBCompañia.setText("Añadir");
        btnAddBCompañia.addActionListener(this::btnAddBCompañiaActionPerformed);

        btnEditBCompañia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditBCompañia.setForeground(new java.awt.Color(26, 61, 99));
        btnEditBCompañia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditBCompañia.setText("Editar");
        btnEditBCompañia.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditBCompañia.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditBCompañia.addActionListener(this::btnEditBCompañiaActionPerformed);

        btnDeleteBCompañia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteBCompañia.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteBCompañia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteBCompañia.setText("Eliminar");
        btnDeleteBCompañia.addActionListener(this::btnDeleteBCompañiaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddBCompañia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditBCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteBCompañia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditBCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteBCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBCompañiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBCompañiaActionPerformed
        mostrarDialogoBalance();
    }//GEN-LAST:event_btnAddBCompañiaActionPerformed

    private void btnEditBCompañiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBCompañiaActionPerformed
       JOptionPane.showMessageDialog(this, "El Balance por Compañía es un reporte calculado, no permite edición manual.");
    }//GEN-LAST:event_btnEditBCompañiaActionPerformed

    private void btnDeleteBCompañiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBCompañiaActionPerformed
      JOptionPane.showMessageDialog(this, "No se pueden eliminar registros contables desde el visor de reportes.");
    }//GEN-LAST:event_btnDeleteBCompañiaActionPerformed
private void mostrarDialogoBalance() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Balance por Compañía", true);
        dialogo.setSize(850, 600);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. DATOS DE SELECCIÓN (Panel Superior) ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createEtchedBorder());
        pnlSel.setBounds(10, 10, 815, 110);

        // Compañía, Año, Periodo
        pnlSel.add(new JLabel("Compañía")).setBounds(20, 15, 70, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12"})).setBounds(90, 15, 60, 25);
        pnlSel.add(new JLabel("UNIDAD ESCOLAR BENAVENTE, A.C.")).setBounds(160, 15, 250, 25);

        pnlSel.add(new JLabel("Año")).setBounds(20, 45, 50, 25);
        pnlSel.add(new JTextField("2026")).setBounds(90, 45, 60, 25);

        pnlSel.add(new JLabel("Periodo")).setBounds(20, 75, 60, 25);
        pnlSel.add(new JTextField("5")).setBounds(90, 75, 60, 25);

        // Niveles (1 al 9)
        pnlSel.add(new JLabel("Nivel")).setBounds(180, 75, 40, 25);
        ButtonGroup bgNivel = new ButtonGroup();
        int xPosNivel = 220;
        for (int i = 1; i <= 9; i++) {
            JRadioButton rb = new JRadioButton(String.valueOf(i));
            if(i == 3) rb.setSelected(true); // Seleccionado el nivel 3 por defecto (según la imagen)
            rb.setBounds(xPosNivel, 75, 40, 25);
            bgNivel.add(rb);
            pnlSel.add(rb);
            xPosNivel += 40;
        }

        // Tipo de Contabilidad
        pnlSel.add(new JLabel("Tipo de Cont.")).setBounds(480, 45, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{"MN"})).setBounds(570, 45, 60, 25);

        // Botones laterales del panel
        JButton btnSelecciona = new JButton("Selecciona");
        btnSelecciona.setBounds(650, 25, 140, 25);
        pnlSel.add(btnSelecciona);

        JButton btnFiltra = new JButton("Filtrar Información");
        btnFiltra.setBounds(650, 60, 140, 25);
        pnlSel.add(btnFiltra);

        dialogo.add(pnlSel);

        // --- 2. TABLA DE BALANCE ---
        JTable tblBalance = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Cuenta", "Descripción", "Saldo"}
        ));
        
        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createEtchedBorder());
        pnlTabla.setBounds(10, 130, 815, 360);
        
        JScrollPane scrollBalance = new JScrollPane(tblBalance);
        scrollBalance.setBounds(10, 10, 795, 340);
        pnlTabla.add(scrollBalance);
        
        dialogo.add(pnlTabla);

        // --- 3. BOTONES INFERIORES ---
        JButton btnExportar = new JButton("Exporta");
        btnExportar.setBounds(250, 505, 100, 40);
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(370, 505, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(490, 505, 100, 40);

        dialogo.add(btnExportar);
        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 4. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnSelecciona.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Abre ventana para seleccionar cuentas específicas... (Simulación)");
        });

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Calculando y agrupando el Balance por Compañía... (Simulación)");
            // Aquí iría la lógica SQL para llenar tblBalance
        });

        btnExportar.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Exportando Balance a Excel (.xlsx)... (Simulación)");
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando Balance a la impresora... (Simulación)");
        });

        // --- 5. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBCompañia;
    private javax.swing.JButton btnDeleteBCompañia;
    private javax.swing.JButton btnEditBCompañia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBCompañia;
    // End of variables declaration//GEN-END:variables
}
