/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Becas_Convenio extends javax.swing.JPanel {

    /**
     * Creates new form Becas_Convenio
     */
    public Becas_Convenio() {
        initComponents();
    }
private void cargarTablaBecas() {
        // 1. Arreglamos las columnas por código
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Clave", "Descripción", "Tipo Inst.", "Tipo", "Institución", "Autorizante", "Usuario", "Fecha Mod."}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        jTable1.setModel(modelo);

        // 2. Cargamos los datos
        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                // ATENCIÓN: Cambia 'tabla_becas' por tu tabla real
                String sql = "SELECT clave, descripcion, tipo_inst, tipo, institucion, autorizante, usuario, fecha_mod FROM tabla_becas";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[8]; 
                    fila[0] = rs.getString("clave");
                    fila[1] = rs.getString("descripcion");
                    fila[2] = rs.getString("tipo_inst");
                    fila[3] = rs.getString("tipo");
                    fila[4] = rs.getString("institucion");
                    fila[5] = rs.getString("autorizante");
                    fila[6] = rs.getString("usuario");
                    fila[7] = rs.getString("fecha_mod");
                    modelo.addRow(fila);
                }
                rs.close(); ps.close(); db.Cerrar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddBConvenio = new javax.swing.JButton();
        btnEditBConvenio = new javax.swing.JButton();
        btnDeleteBConvenio = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnAddBConvenio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddBConvenio.setForeground(new java.awt.Color(26, 61, 99));
        btnAddBConvenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddBConvenio.setText("Añadir");
        btnAddBConvenio.addActionListener(this::btnAddBConvenioActionPerformed);

        btnEditBConvenio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditBConvenio.setForeground(new java.awt.Color(26, 61, 99));
        btnEditBConvenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditBConvenio.setText("Editar");
        btnEditBConvenio.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditBConvenio.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditBConvenio.addActionListener(this::btnEditBConvenioActionPerformed);

        btnDeleteBConvenio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteBConvenio.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteBConvenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteBConvenio.setText("Eliminar");
        btnDeleteBConvenio.addActionListener(this::btnDeleteBConvenioActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddBConvenio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditBConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteBConvenio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditBConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteBConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBConvenioActionPerformed
      mostrarDialogoBeca(false);
    }//GEN-LAST:event_btnAddBConvenioActionPerformed

    private void btnEditBConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBConvenioActionPerformed
      if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un registro para editar.");
            return;
        }
        mostrarDialogoBeca(true);
    }//GEN-LAST:event_btnEditBConvenioActionPerformed

    private void btnDeleteBConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBConvenioActionPerformed
      int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un registro para eliminar.");
            return;
        }

        String clave = jTable1.getValueAt(fila, 0).toString();
        String desc = jTable1.getValueAt(fila, 1).toString();
        
        int resp = JOptionPane.showConfirmDialog(this, "¿Eliminar Beca/Convenio: " + desc + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    // ATENCIÓN: Cambia por el nombre real de tu tabla
                    String sql = "DELETE FROM tabla_becas WHERE clave = ?";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, clave);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Registro eliminado.");
                        cargarTablaBecas();
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteBConvenioActionPerformed
private void mostrarDialogoBeca(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Becas y Convenios" : "Agregar Becas y Convenios";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(680, 600); // Ventana más ancha para que quepa la tabla de detalles
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. SECCIÓN SUPERIOR ---
        JLabel lblClave = new JLabel("Clave");
        lblClave.setBounds(20, 15, 80, 25);
        JTextField txtClave = new JTextField();
        txtClave.setBounds(100, 15, 100, 25);
        if (modoEdicion) txtClave.setEditable(false);

        JLabel lblDesc = new JLabel("Descripción");
        lblDesc.setBounds(20, 45, 80, 25);
        JTextField txtDesc = new JTextField();
        txtDesc.setBounds(100, 45, 450, 25);

        dialogo.add(lblClave); dialogo.add(txtClave);
        dialogo.add(lblDesc); dialogo.add(txtDesc);

        // --- 2. PESTAÑAS Y MARCOS ---
        JTabbedPane pestanas = new JTabbedPane();
        pestanas.setBounds(15, 85, 635, 400);

        JPanel pnlGenerales = new JPanel(null);

        // >> Marco: Tipo Institución
        JPanel pnlTipoInst = new JPanel(null);
        pnlTipoInst.setBorder(BorderFactory.createTitledBorder("Tipo Institución"));
        pnlTipoInst.setBounds(10, 10, 420, 50);

        JRadioButton rbPropias = new JRadioButton("Propias de la Institución", true);
        rbPropias.setBounds(10, 20, 160, 20);
        JRadioButton rbOtras = new JRadioButton("Otras Instituciones");
        rbOtras.setBounds(175, 20, 140, 20);
        JRadioButton rbEmpresas = new JRadioButton("Empresas");
        rbEmpresas.setBounds(320, 20, 90, 20);

        ButtonGroup bgInst = new ButtonGroup();
        bgInst.add(rbPropias); bgInst.add(rbOtras); bgInst.add(rbEmpresas);
        pnlTipoInst.add(rbPropias); pnlTipoInst.add(rbOtras); pnlTipoInst.add(rbEmpresas);

        // >> Marco: Tipo (Beca / Convenio)
        JPanel pnlTipoBeca = new JPanel(null);
        pnlTipoBeca.setBorder(BorderFactory.createTitledBorder("Tipo"));
        pnlTipoBeca.setBounds(440, 10, 175, 50);

        JRadioButton rbBeca = new JRadioButton("Beca", true);
        rbBeca.setBounds(10, 20, 60, 20);
        JRadioButton rbConvenio = new JRadioButton("Convenio");
        rbConvenio.setBounds(80, 20, 80, 20);

        ButtonGroup bgTipo = new ButtonGroup();
        bgTipo.add(rbBeca); bgTipo.add(rbConvenio);
        pnlTipoBeca.add(rbBeca); pnlTipoBeca.add(rbConvenio);

        // >> Sección Media: Institución y Autorizante (Simulando el recuadro)
        JPanel pnlMid = new JPanel(null);
        pnlMid.setBorder(BorderFactory.createEtchedBorder());
        pnlMid.setBounds(10, 70, 605, 75);

        JLabel lblClaveInst = new JLabel("Clave de Institución");
        lblClaveInst.setBounds(10, 10, 120, 25);
        JComboBox<String> cmbClaveInst = new JComboBox<>(new String[]{"CSAC", "OTRO"});
        cmbClaveInst.setBounds(130, 10, 80, 25);
        JLabel lblDescInst = new JLabel("COLEGIO SALESIANO, A.C.");
        lblDescInst.setBounds(220, 10, 300, 25);

        JLabel lblAut = new JLabel("Autorizante");
        lblAut.setBounds(10, 40, 120, 25);
        JComboBox<String> cmbAut = new JComboBox<>(new String[]{"58", "59"});
        cmbAut.setBounds(130, 40, 80, 25);
        JLabel lblDescAut = new JLabel("JOSE DE JESUS AMBROSIO RAMIREZ ARAGON");
        lblDescAut.setBounds(220, 40, 300, 25);

        pnlMid.add(lblClaveInst); pnlMid.add(cmbClaveInst); pnlMid.add(lblDescInst);
        pnlMid.add(lblAut); pnlMid.add(cmbAut); pnlMid.add(lblDescAut);

        // >> Sección Inferior: Captura de Detalle y Tabla
        JPanel pnlDetalle = new JPanel(null);
        pnlDetalle.setBorder(BorderFactory.createEtchedBorder());
        pnlDetalle.setBounds(10, 155, 605, 205);

        // Títulos de captura
        JLabel l1 = new JLabel("Sec"); l1.setBounds(10, 10, 30, 20);
        JLabel l2 = new JLabel("Tipo Concepto"); l2.setBounds(50, 10, 90, 20);
        JLabel l3 = new JLabel("Descripción"); l3.setBounds(150, 10, 90, 20);
        JLabel l4 = new JLabel("% Descuento"); l4.setBounds(300, 10, 80, 20);
        JLabel l5 = new JLabel("Fecha Inicial"); l5.setBounds(390, 10, 80, 20);
        JLabel l6 = new JLabel("Fecha Final"); l6.setBounds(480, 10, 80, 20);
        pnlDetalle.add(l1); pnlDetalle.add(l2); pnlDetalle.add(l3); 
        pnlDetalle.add(l4); pnlDetalle.add(l5); pnlDetalle.add(l6);

        // Campos de captura
        JTextField txtSec = new JTextField("3"); txtSec.setBounds(10, 30, 30, 25);
        JComboBox<String> cmbConcepto = new JComboBox<>(new String[]{"I", "C"}); cmbConcepto.setBounds(50, 30, 90, 25);
        JTextField txtDescDet = new JTextField(); txtDescDet.setBounds(150, 30, 140, 25);
        JTextField txtPorc = new JTextField("0.00"); txtPorc.setBounds(300, 30, 80, 25);
        JTextField txtFecIni = new JTextField("04/06/2026"); txtFecIni.setBounds(390, 30, 80, 25);
        JTextField txtFecFin = new JTextField("04/06/2026"); txtFecFin.setBounds(480, 30, 80, 25);
        JButton btnOk = new JButton("OK"); btnOk.setBounds(565, 30, 30, 25);
        
        pnlDetalle.add(txtSec); pnlDetalle.add(cmbConcepto); pnlDetalle.add(txtDescDet);
        pnlDetalle.add(txtPorc); pnlDetalle.add(txtFecIni); pnlDetalle.add(txtFecFin); pnlDetalle.add(btnOk);

        // Tabla interna de Detalles
        JTable tblDetalle = new JTable();
        DefaultTableModel modDetalle = new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Sec", "Tpo Cp", "Descripción", "Porc. Descuento", "Fec Vig Ini", "Fec Vig Fin"}
        );
        tblDetalle.setModel(modDetalle);
        JScrollPane scrollDetalle = new JScrollPane(tblDetalle);
        scrollDetalle.setBounds(10, 65, 585, 130);
        pnlDetalle.add(scrollDetalle);

        // Lógica súper rápida para que el botón "OK" agregue a la tablita interna visualmente
        btnOk.addActionListener(e -> {
            modDetalle.addRow(new Object[]{
                txtSec.getText(), cmbConcepto.getSelectedItem().toString(), txtDescDet.getText(), 
                txtPorc.getText(), txtFecIni.getText(), txtFecFin.getText()
            });
            txtSec.setText(String.valueOf(modDetalle.getRowCount() + 1)); // Incrementa secuencia
            txtDescDet.setText("");
        });

        // Agregamos todo a la pestaña principal
        pnlGenerales.add(pnlTipoInst); pnlGenerales.add(pnlTipoBeca);
        pnlGenerales.add(pnlMid); pnlGenerales.add(pnlDetalle);

        pestanas.addTab("Datos Generales", pnlGenerales);
        dialogo.add(pestanas);

        // --- 3. BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(200, 500, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(330, 500, 100, 40);

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        // --- 4. SI ES MODO EDICIÓN, CARGAMOS LOS DATOS ---
        if (modoEdicion) {
            int fila = jTable1.getSelectedRow();
            txtClave.setText(jTable1.getValueAt(fila, 0).toString());
            txtDesc.setText(jTable1.getValueAt(fila, 1).toString());
            // Aquí simularías cargar los detalles en la tablita interna `modDetalle`
        }

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnAceptar.addActionListener(e -> {
            String clave = txtClave.getText().trim();
            if (clave.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "La clave no puede estar vacía.");
                return;
            }

            // Aquí va tu código SQL INSERT o UPDATE para la tabla maestra y los detalles
            JOptionPane.showMessageDialog(dialogo, "Beca/Convenio guardado (Simulación).");
            
            dialogo.dispose();
            cargarTablaBecas(); 
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBConvenio;
    private javax.swing.JButton btnDeleteBConvenio;
    private javax.swing.JButton btnEditBConvenio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
