/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Becas_Convenio extends javax.swing.JPanel {

    /**
     * Creates new form Becas_Convenio
     */
    public Becas_Convenio() {
        initComponents();
        cargarTablaBecas();
    }
   private void cargarTablaBecas() {
        // 1. Arreglamos las columnas por código para que coincidan con la DB
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Clave", "Descripción", "Tipo Inst.", "Tipo", "Cve Institución", "Autorizante", "Usuario", "Fecha Mod.", "Hora Mod."}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblBConvenio.setModel(modelo);

        // 2. Cargamos los datos de la tabla tesbege
        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                String sql = "SELECT CBECA, DBECA, TINST, TBECA, CINST, NAUT, USER, FEAC, HOAC FROM tesbege";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[9]; 
                    fila[0] = rs.getString("CBECA");
                    fila[1] = rs.getString("DBECA");
                    fila[2] = rs.getString("TINST");
                    fila[3] = rs.getString("TBECA");
                    fila[4] = rs.getString("CINST");
                    fila[5] = rs.getString("NAUT");
                    fila[6] = rs.getString("USER");
                    fila[7] = rs.getString("FEAC");
                    fila[8] = rs.getString("HOAC");
                    modelo.addRow(fila);
                }
                rs.close(); ps.close(); db.Cerrar();
                
                adaptarTamañoColumnas();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla de Becas: " + e.getMessage());
        }
    }

    // --- MÉTODO PARA AUTO-AJUSTAR ANCHO DE COLUMNAS ---
    private void adaptarTamañoColumnas() {
        tblBConvenio.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        
        for (int i = 0; i < tblBConvenio.getColumnCount(); i++) {
            javax.swing.table.TableColumn columna = tblBConvenio.getColumnModel().getColumn(i);
            int anchoPreferido = 50; 
            
            java.awt.Component compCabecera = tblBConvenio.getTableHeader().getDefaultRenderer()
                    .getTableCellRendererComponent(tblBConvenio, columna.getHeaderValue(), false, false, 0, i);
            anchoPreferido = Math.max(anchoPreferido, compCabecera.getPreferredSize().width + 10);
            
            for (int r = 0; r < tblBConvenio.getRowCount(); r++) {
                javax.swing.table.TableCellRenderer renderizador = tblBConvenio.getCellRenderer(r, i);
                java.awt.Component c = tblBConvenio.prepareRenderer(renderizador, r, i);
                anchoPreferido = Math.max(anchoPreferido, c.getPreferredSize().width + 15); 
            }
            columna.setPreferredWidth(anchoPreferido); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBConvenio = new javax.swing.JTable();
        btnAddBConvenio = new javax.swing.JButton();
        btnEditBConvenio = new javax.swing.JButton();
        btnDeleteBConvenio = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblBConvenio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Clave", "Descripcion", "Tipo", "Tipo Inst.", "Cve Institucion", "Autorizante", "Usuario", "Fecha. Ult. Act.", "Hora. Ult. Act."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBConvenio);

        btnAddBConvenio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddBConvenio.setForeground(new java.awt.Color(26, 61, 99));
        btnAddBConvenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddBConvenio.setText("Añadir");
        btnAddBConvenio.addActionListener(this::btnAddBConvenioActionPerformed);

        btnEditBConvenio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditBConvenio.setForeground(new java.awt.Color(26, 61, 99));
        btnEditBConvenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditBConvenio.setText("Editar");
        btnEditBConvenio.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditBConvenio.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditBConvenio.addActionListener(this::btnEditBConvenioActionPerformed);

        btnDeleteBConvenio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteBConvenio.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteBConvenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteBConvenio.setText("Eliminar");
        btnDeleteBConvenio.addActionListener(this::btnDeleteBConvenioActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddBConvenio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditBConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteBConvenio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditBConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteBConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBConvenioActionPerformed
      mostrarDialogoBeca(false);
    }//GEN-LAST:event_btnAddBConvenioActionPerformed

    private void btnEditBConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBConvenioActionPerformed
     if (tblBConvenio.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un registro para editar.");
            return;
        }
        mostrarDialogoBeca(true);
    }//GEN-LAST:event_btnEditBConvenioActionPerformed

    private void btnDeleteBConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBConvenioActionPerformed
     int fila = tblBConvenio.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un registro para eliminar.");
            return;
        }

        String clave = tblBConvenio.getValueAt(fila, 0).toString();
        String desc = tblBConvenio.getValueAt(fila, 1).toString();
        
        int resp = JOptionPane.showConfirmDialog(this, "¿Eliminar Beca/Convenio: " + desc + "?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    String sql = "DELETE FROM tesbege WHERE CBECA = ?";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, clave);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Registro eliminado correctamente.");
                        cargarTablaBecas();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró el registro para eliminar.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteBConvenioActionPerformed
private void mostrarDialogoBeca(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Becas y Convenios" : "Agregar Becas y Convenios";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(680, 600); 
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- CLASE LOCAL PARA REUTILIZAR EL BUSCADOR FLOTANTE ---
        class BuscadorFlotante {
            void configurar(JTextField txtClave, JTextField txtDesc, JButton boton, Object[][] datos) {
                String[] columnas = {"Clave", "Descripción"};
                Runnable mostrarPopup = () -> {
                    javax.swing.JPopupMenu popup = new javax.swing.JPopupMenu();
                    popup.setFocusable(false);
                    javax.swing.table.DefaultTableModel mod = new javax.swing.table.DefaultTableModel(datos, columnas) {
                        @Override public boolean isCellEditable(int r, int c) { return false; }
                    };
                    javax.swing.JTable tabla = new javax.swing.JTable(mod);
                    tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                    tabla.getColumnModel().getColumn(0).setPreferredWidth(80);
                    tabla.getColumnModel().getColumn(1).setPreferredWidth(250);

                    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(mod);
                    tabla.setRowSorter(sorter);

                    tabla.addMouseListener(new java.awt.event.MouseAdapter() {
                        @Override
                        public void mouseReleased(java.awt.event.MouseEvent me) {
                            int viewRow = tabla.getSelectedRow();
                            if (viewRow != -1) {
                                int modelRow = tabla.convertRowIndexToModel(viewRow);
                                txtClave.setText(mod.getValueAt(modelRow, 0).toString());
                                if (txtDesc != null) {
                                    txtDesc.setText(mod.getValueAt(modelRow, 1).toString());
                                }
                                popup.setVisible(false);
                            }
                        }
                    });
                    javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(tabla);
                    scroll.setPreferredSize(new java.awt.Dimension(320, 150));
                    popup.add(scroll);

                    String texto = txtClave.getText().trim();
                    if (!texto.isEmpty()) sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto));
                    popup.show(txtClave, 0, txtClave.getHeight());
                    txtClave.requestFocus();
                };

                boton.addActionListener(e -> { txtClave.setText(""); mostrarPopup.run(); });
                txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
                    @Override
                    public void keyReleased(java.awt.event.KeyEvent e) {
                        int c = e.getKeyCode();
                        if (c == 27 || c == 10 || c == 38 || c == 40 || c == 37 || c == 39 || c == 9) return;
                        mostrarPopup.run();
                    }
                });
            }
        }
        BuscadorFlotante buscador = new BuscadorFlotante();

        // --- CARGA DE DATOS PARA LOS BUSCADORES ---
        java.util.function.Function<String, Object[][]> cargarDatos = (query) -> {
            java.util.List<Object[]> lista = new java.util.ArrayList<>();
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps = con.prepareStatement(query);
                    ResultSet rs = ps.executeQuery();
                    while(rs.next()) lista.add(new Object[]{rs.getString(1), rs.getString(2)});
                    rs.close(); ps.close(); db.Cerrar();
                }
            } catch(Exception e) {}
            return lista.toArray(new Object[0][0]);
        };

        // Arreglos de datos desde la BD
        Object[][] dInst = cargarDatos.apply("SELECT CVE, DES FROM tmclas WHERE TBL = 'CINS' ORDER BY CVE");
        Object[][] dAut = cargarDatos.apply("SELECT NEMP, NOME FROM tgemp ORDER BY NEMP");
        Object[][] dCon = cargarDatos.apply("SELECT CVE, DES FROM tmclas WHERE TBL = 'TCPT' ORDER BY CVE");

        // --- 1. SECCIÓN SUPERIOR ---
        JLabel lblClave = new JLabel("Clave");
        lblClave.setBounds(20, 15, 80, 25);
        JTextField txtClave = new JTextField();
        txtClave.setBounds(100, 15, 100, 25);
        if (modoEdicion) txtClave.setEditable(false); // Bloquear clave en edición

        JLabel lblDesc = new JLabel("Descripción");
        lblDesc.setBounds(20, 45, 80, 25);
        JTextField txtDesc = new JTextField();
        txtDesc.setBounds(100, 45, 450, 25);

        dialogo.add(lblClave); dialogo.add(txtClave);
        dialogo.add(lblDesc); dialogo.add(txtDesc);

        // --- 2. PESTAÑAS Y MARCOS ---
        JTabbedPane pestanas = new JTabbedPane();
        pestanas.setBounds(15, 85, 635, 400);

        JPanel pnlGenerales = new JPanel(null);

        // >> Marco: Tipo Institución
        JPanel pnlTipoInst = new JPanel(null);
        pnlTipoInst.setBorder(BorderFactory.createTitledBorder("Tipo Institución"));
        pnlTipoInst.setBounds(10, 10, 420, 50);

        JRadioButton rbPropias = new JRadioButton("Propias de la Institución", true);
        rbPropias.setBounds(10, 20, 160, 20);
        JRadioButton rbOtras = new JRadioButton("Otras Instituciones");
        rbOtras.setBounds(175, 20, 140, 20);
        JRadioButton rbEmpresas = new JRadioButton("Empresas");
        rbEmpresas.setBounds(320, 20, 90, 20);

        ButtonGroup bgInst = new ButtonGroup();
        bgInst.add(rbPropias); bgInst.add(rbOtras); bgInst.add(rbEmpresas);
        pnlTipoInst.add(rbPropias); pnlTipoInst.add(rbOtras); pnlTipoInst.add(rbEmpresas);

        // >> Marco: Tipo (Beca / Convenio)
        JPanel pnlTipoBeca = new JPanel(null);
        pnlTipoBeca.setBorder(BorderFactory.createTitledBorder("Tipo"));
        pnlTipoBeca.setBounds(440, 10, 175, 50);

        JRadioButton rbBeca = new JRadioButton("Beca", true);
        rbBeca.setBounds(10, 20, 60, 20);
        JRadioButton rbConvenio = new JRadioButton("Convenio");
        rbConvenio.setBounds(80, 20, 80, 20);

        ButtonGroup bgTipo = new ButtonGroup();
        bgTipo.add(rbBeca); bgTipo.add(rbConvenio);
        pnlTipoBeca.add(rbBeca); pnlTipoBeca.add(rbConvenio);

        // >> Sección Media: Institución y Autorizante
        JPanel pnlMid = new JPanel(null);
        pnlMid.setBorder(BorderFactory.createEtchedBorder());
        pnlMid.setBounds(10, 70, 605, 75);

        // Buscador Clave de Institución
        JLabel lblClaveInst = new JLabel("Clave de Institución");
        lblClaveInst.setBounds(10, 10, 120, 25);
        JTextField txtCveInst = new JTextField();
        txtCveInst.setBounds(130, 10, 60, 25);
        JButton btnCveInst = new JButton("▼");
        btnCveInst.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10));
        btnCveInst.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCveInst.setBounds(190, 10, 20, 25);
        JTextField txtDescInst = new JTextField();
        txtDescInst.setBounds(215, 10, 375, 25);
        txtDescInst.setEditable(false); txtDescInst.setBackground(new java.awt.Color(240,240,240));
        buscador.configurar(txtCveInst, txtDescInst, btnCveInst, dInst);

        // Buscador Autorizante
        JLabel lblAut = new JLabel("Autorizante");
        lblAut.setBounds(10, 40, 120, 25);
        JTextField txtAut = new JTextField();
        txtAut.setBounds(130, 40, 60, 25);
        JButton btnAut = new JButton("▼");
        btnAut.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10));
        btnAut.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAut.setBounds(190, 40, 20, 25);
        JTextField txtDescAut = new JTextField();
        txtDescAut.setBounds(215, 40, 375, 25);
        txtDescAut.setEditable(false); txtDescAut.setBackground(new java.awt.Color(240,240,240));
        buscador.configurar(txtAut, txtDescAut, btnAut, dAut);

        pnlMid.add(lblClaveInst); pnlMid.add(txtCveInst); pnlMid.add(btnCveInst); pnlMid.add(txtDescInst);
        pnlMid.add(lblAut); pnlMid.add(txtAut); pnlMid.add(btnAut); pnlMid.add(txtDescAut);

        // >> Sección Inferior: Captura de Detalle y Tabla
        JPanel pnlDetalle = new JPanel(null);
        pnlDetalle.setBorder(BorderFactory.createEtchedBorder());
        pnlDetalle.setBounds(10, 155, 605, 205);

        // Títulos de captura
        JLabel l1 = new JLabel("Sec"); l1.setBounds(10, 10, 30, 20);
        JLabel l2 = new JLabel("Tipo Concepto"); l2.setBounds(50, 10, 90, 20);
        JLabel l3 = new JLabel("Descripción"); l3.setBounds(145, 10, 90, 20);
        JLabel l4 = new JLabel("% Descuento"); l4.setBounds(300, 10, 80, 20);
        JLabel l5 = new JLabel("Fecha Inicial"); l5.setBounds(390, 10, 80, 20);
        JLabel l6 = new JLabel("Fecha Final"); l6.setBounds(480, 10, 80, 20);
        pnlDetalle.add(l1); pnlDetalle.add(l2); pnlDetalle.add(l3); 
        pnlDetalle.add(l4); pnlDetalle.add(l5); pnlDetalle.add(l6);

        // Campos de captura (Incluye Buscador Tipo Concepto y JDateChoosers)
        JTextField txtSec = new JTextField("1"); 
        txtSec.setBounds(10, 30, 30, 25);
        
        JTextField txtTipoCp = new JTextField(); 
        txtTipoCp.setBounds(50, 30, 40, 25);
        JButton btnTipoCp = new JButton("▼"); 
        btnTipoCp.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10)); 
        btnTipoCp.setMargin(new java.awt.Insets(0,0,0,0)); 
        btnTipoCp.setBounds(90, 30, 20, 25);
        JTextField txtDescDet = new JTextField(); 
        txtDescDet.setBounds(115, 30, 175, 25);
        txtDescDet.setEditable(false); txtDescDet.setBackground(new java.awt.Color(240,240,240));
        buscador.configurar(txtTipoCp, txtDescDet, btnTipoCp, dCon);
        
        JTextField txtPorc = new JTextField("0.00"); 
        txtPorc.setBounds(300, 30, 80, 25);
        
        com.toedter.calendar.JDateChooser txtFecIni = new com.toedter.calendar.JDateChooser();
        txtFecIni.setDateFormatString("yyyy-MM-dd"); 
        txtFecIni.setBounds(390, 30, 85, 25);
        
        com.toedter.calendar.JDateChooser txtFecFin = new com.toedter.calendar.JDateChooser();
        txtFecFin.setDateFormatString("yyyy-MM-dd"); 
        txtFecFin.setBounds(480, 30, 85, 25);
        
        JButton btnOk = new JButton("OK"); 
        btnOk.setBounds(570, 30, 30, 25);
        btnOk.setMargin(new java.awt.Insets(0,0,0,0));
        
        pnlDetalle.add(txtSec); pnlDetalle.add(txtTipoCp); pnlDetalle.add(btnTipoCp); pnlDetalle.add(txtDescDet);
        pnlDetalle.add(txtPorc); pnlDetalle.add(txtFecIni); pnlDetalle.add(txtFecFin); pnlDetalle.add(btnOk);

        // Tabla interna de Detalles (Visual)
        JTable tblDetalle = new JTable();
        DefaultTableModel modDetalle = new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Sec", "Tpo Cp", "Descripción", "Porc. Descuento", "Fec Vig Ini", "Fec Vig Fin"}
        );
        tblDetalle.setModel(modDetalle);
        JScrollPane scrollDetalle = new JScrollPane(tblDetalle);
        scrollDetalle.setBounds(10, 65, 585, 130);
        pnlDetalle.add(scrollDetalle);

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");

        btnOk.addActionListener(e -> {
            String fi = txtFecIni.getDate() != null ? sdf.format(txtFecIni.getDate()) : "";
            String ff = txtFecFin.getDate() != null ? sdf.format(txtFecFin.getDate()) : "";

            modDetalle.addRow(new Object[]{
                txtSec.getText(), txtTipoCp.getText(), txtDescDet.getText(), 
                txtPorc.getText(), fi, ff
            });
            txtSec.setText(String.valueOf(modDetalle.getRowCount() + 1)); 
            txtDescDet.setText("");
            txtTipoCp.setText("");
        });

        pnlGenerales.add(pnlTipoInst); pnlGenerales.add(pnlTipoBeca);
        pnlGenerales.add(pnlMid); pnlGenerales.add(pnlDetalle);

        pestanas.addTab("Datos Generales", pnlGenerales);
        dialogo.add(pestanas);

        // --- 3. BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(200, 500, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(330, 500, 100, 40);

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        // --- 4. SI ES MODO EDICIÓN, CARGAMOS LOS DATOS ---
        if (modoEdicion) {
            int fila = tblBConvenio.getSelectedRow();
            String claveSel = tblBConvenio.getValueAt(fila, 0).toString();
            
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps = con.prepareStatement("SELECT DBECA, TINST, TBECA, CINST, NAUT FROM tesbege WHERE CBECA = ?");
                    ps.setString(1, claveSel);
                    ResultSet rs = ps.executeQuery();
                    
                    if (rs.next()) {
                        txtClave.setText(claveSel);
                        txtDesc.setText(rs.getString("DBECA") != null ? rs.getString("DBECA") : "");
                        
                        String tipoBeca = rs.getString("TBECA");
                        if ("C".equalsIgnoreCase(tipoBeca)) {
                            rbConvenio.setSelected(true);
                        } else {
                            rbBeca.setSelected(true);
                        }
                        
                        String tipoInst = rs.getString("TINST");
                        if ("O".equalsIgnoreCase(tipoInst)) rbOtras.setSelected(true);
                        else if ("E".equalsIgnoreCase(tipoInst)) rbEmpresas.setSelected(true);
                        else rbPropias.setSelected(true);
                        
                        txtCveInst.setText(rs.getString("CINST") != null ? rs.getString("CINST") : "");
                        txtAut.setText(rs.getString("NAUT") != null ? rs.getString("NAUT") : "");

                        // Consultar descripciones de los buscadores si es edición
                        try {
                            PreparedStatement p1 = con.prepareStatement("SELECT DES FROM tmclas WHERE TBL='CINS' AND CVE=?");
                            p1.setString(1, txtCveInst.getText());
                            ResultSet r1 = p1.executeQuery();
                            if(r1.next()) txtDescInst.setText(r1.getString("DES"));
                            r1.close(); p1.close();
                            
                            PreparedStatement p2 = con.prepareStatement("SELECT NOME FROM tgemp WHERE NEMP=?");
                            p2.setString(1, txtAut.getText());
                            ResultSet r2 = p2.executeQuery();
                            if(r2.next()) txtDescAut.setText(r2.getString("NOME"));
                            r2.close(); p2.close();
                        } catch(Exception ignored) {}
                    }
                    rs.close(); ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                // Silencioso
            }
        }

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnAceptar.addActionListener(e -> {
            String clave = txtClave.getText().trim();
            String desc = txtDesc.getText().trim();
            
            String tipoBeca = rbBeca.isSelected() ? "B" : "C";
            String tipoInst = rbPropias.isSelected() ? "P" : (rbOtras.isSelected() ? "O" : "E");
            
            String cveInst = txtCveInst.getText().trim();
            String autorizante = txtAut.getText().trim();

            if (clave.isEmpty() || desc.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "La clave y la descripción son obligatorias.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps;
                    if (modoEdicion) {
                        String sql = "UPDATE tesbege SET DBECA=?, TBECA=?, TINST=?, CINST=?, NAUT=? WHERE CBECA=?";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, desc);
                        ps.setString(2, tipoBeca);
                        ps.setString(3, tipoInst);
                        ps.setString(4, cveInst);
                        ps.setString(5, autorizante);
                        ps.setString(6, clave);
                    } else {
                        String sql = "INSERT INTO tesbege (CBECA, DBECA, TBECA, TINST, CINST, NAUT) VALUES (?, ?, ?, ?, ?, ?)";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, clave);
                        ps.setString(2, desc);
                        ps.setString(3, tipoBeca);
                        ps.setString(4, tipoInst);
                        ps.setString(5, cveInst);
                        ps.setString(6, autorizante);
                    }

                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(dialogo, "Beca/Convenio guardado con éxito.");
                        dialogo.dispose();
                        cargarTablaBecas(); 
                    } else {
                        JOptionPane.showMessageDialog(dialogo, "No se pudo guardar la información.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialogo, "Error SQL: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBConvenio;
    private javax.swing.JButton btnDeleteBConvenio;
    private javax.swing.JButton btnEditBConvenio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBConvenio;
    // End of variables declaration//GEN-END:variables
}
