/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.Dashboard;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 * Cancela recibos escolares y restablece los saldos de sus conceptos.
 *
 * @author b17za
 */
public class Cancelacion_Recibos extends javax.swing.JPanel {
    private String usuarioLogueado = "Admin";

    /**
     * Crea el módulo con el usuario predeterminado.
     */
    public Cancelacion_Recibos() {
        initComponents();
        configurarModulo();
    }

    /**
     * Crea el módulo para el usuario autenticado.
     *
     * @param usuarioLogueado alias del usuario que inició sesión
     */
    public Cancelacion_Recibos(String usuarioLogueado) {
        if (usuarioLogueado != null && !usuarioLogueado.trim().isEmpty()) {
            this.usuarioLogueado = usuarioLogueado.trim();
        }
        initComponents();
        configurarModulo();
    }

    private void configurarModulo() {
        btnAddCRecibos.setText("Cancelar recibo");
        btnEditCRecibos.setVisible(false);
        btnDeleteCRecibos.setVisible(false);
        cargarTablaHistorialCancelaciones();
    }

    private String obtenerUsuarioActivo() {
        Window ventana = SwingUtilities.getWindowAncestor(this);
        if (ventana instanceof Dashboard dashboard) {
            return dashboard.getUsuarioCodigo();
        }
        return usuarioLogueado;
    }

    private void cargarTablaHistorialCancelaciones() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Compañía", "C. Costos", "Num Recibo", "Matrícula", "Motivo", "Fecha", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblCConceptos.setModel(modelo);

        String sql = "SELECT CIA,CC,NREC,MAT,MCAN,MAX(FEAC) AS FECHA," +
                "MAX(HOAC) AS HORA,MAX(USER) AS USUARIO FROM tesralu " +
                "WHERE COALESCE(MCAN,'')<>'' GROUP BY CIA,CC,NREC,MAT,MCAN " +
                "ORDER BY FECHA DESC,HORA DESC,NREC DESC";
        try (Connection con = ConDB.getConnection();
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    modelo.addRow(new Object[]{
                        rs.getString("CIA"), rs.getString("CC"), rs.getString("NREC"),
                        rs.getString("MAT"), rs.getString("MCAN"),
                        rs.getString("FECHA") + " " + rs.getString("HORA"),
                        rs.getString("USUARIO")
                    });
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCConceptos = new javax.swing.JTable();
        btnAddCRecibos = new javax.swing.JButton();
        btnEditCRecibos = new javax.swing.JButton();
        btnDeleteCRecibos = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblCConceptos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCConceptos);

        btnAddCRecibos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCRecibos.setForeground(new java.awt.Color(26, 61, 99));
        btnAddCRecibos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddCRecibos.setText("Añadir");
        btnAddCRecibos.addActionListener(this::btnAddCRecibosActionPerformed);

        btnEditCRecibos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditCRecibos.setForeground(new java.awt.Color(26, 61, 99));
        btnEditCRecibos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditCRecibos.setText("Editar");
        btnEditCRecibos.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditCRecibos.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditCRecibos.addActionListener(this::btnEditCRecibosActionPerformed);

        btnDeleteCRecibos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteCRecibos.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteCRecibos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteCRecibos.setText("Eliminar");
        btnDeleteCRecibos.addActionListener(this::btnDeleteCRecibosActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddCRecibos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCRecibos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCRecibos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCRecibos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCRecibos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCRecibos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCRecibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCRecibosActionPerformed
        mostrarDialogoCancelacionRecibos(false);
    }//GEN-LAST:event_btnAddCRecibosActionPerformed

    private void btnEditCRecibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCRecibosActionPerformed
        JOptionPane.showMessageDialog(this, "Un recibo cancelado no puede modificarse.");
    }//GEN-LAST:event_btnEditCRecibosActionPerformed

    private void btnDeleteCRecibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCRecibosActionPerformed
       JOptionPane.showMessageDialog(this, "El historial de recibos cancelados no se puede eliminar por control de auditoría.");
    }//GEN-LAST:event_btnDeleteCRecibosActionPerformed

private void mostrarDialogoCancelacionRecibos(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Cancelación de Recibos", true);
        dialogo.setSize(850, 520);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- CLASE LOCAL BUSCADOR FLOTANTE ---
        class BuscadorFlotante {
            void configurar(JTextField txtClave, JTextField txtDesc, JButton boton, Object[][] datos, String[] columnas, int[] anchos) {
                Runnable mostrarPopup = () -> {
                    javax.swing.JPopupMenu popup = new javax.swing.JPopupMenu();
                    popup.setFocusable(false);
                    javax.swing.table.DefaultTableModel mod = new javax.swing.table.DefaultTableModel(datos, columnas) {
                        @Override public boolean isCellEditable(int r, int c) { return false; }
                    };
                    javax.swing.JTable tabla = new javax.swing.JTable(mod);
                    tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                    for (int i = 0; i < anchos.length; i++) {
                        tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                    }

                    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(mod);
                    tabla.setRowSorter(sorter);

                    tabla.addMouseListener(new java.awt.event.MouseAdapter() {
                        @Override
                        public void mouseReleased(java.awt.event.MouseEvent me) {
                            int viewRow = tabla.getSelectedRow();
                            if (viewRow != -1) {
                                int modelRow = tabla.convertRowIndexToModel(viewRow);
                                txtClave.setText(mod.getValueAt(modelRow, 0).toString());
                                if (txtDesc != null && mod.getColumnCount() >= 2) {
                                    txtDesc.setText(mod.getValueAt(modelRow, 1).toString());
                                }
                                popup.setVisible(false);
                            }
                        }
                    });
                    
                    int widthTotal = 0; for(int w : anchos) widthTotal += w;
                    javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(tabla);
                    scroll.setPreferredSize(new java.awt.Dimension(widthTotal + 20, 150));
                    popup.add(scroll);

                    String texto = txtClave.getText().trim();
                    if (!texto.isEmpty()) sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto));
                    popup.show(txtClave, 0, txtClave.getHeight());
                    txtClave.requestFocus();
                };

                boton.addActionListener(e -> { txtClave.setText(""); mostrarPopup.run(); });
                txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
                    @Override
                    public void keyReleased(java.awt.event.KeyEvent e) {
                        int c = e.getKeyCode();
                        if (c == 27 || c == 10 || c == 38 || c == 40 || c == 37 || c == 39 || c == 9) return;
                        mostrarPopup.run();
                    }
                });
            }
        }
        BuscadorFlotante buscador = new BuscadorFlotante();

        // --- CARGA DE DATOS PARA BUSCADORES ---
        java.util.function.BiFunction<String, Integer, Object[][]> cargarDatosMultiple = (query, numCols) -> {
            java.util.List<Object[]> lista = new java.util.ArrayList<>();
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps = con.prepareStatement(query);
                    ResultSet rs = ps.executeQuery();
                    while(rs.next()) {
                        Object[] row = new Object[numCols];
                        for(int i=0; i<numCols; i++) row[i] = rs.getString(i+1);
                        lista.add(row);
                    }
                    rs.close(); ps.close(); db.Cerrar();
                }
            } catch(Exception e) {}
            return lista.toArray(new Object[0][0]);
        };

        Object[][] dMatricula = cargarDatosMultiple.apply(
                "SELECT MAT,MAX(APATE),MAX(AMATE),MAX(NOMA) FROM tesalum " +
                "GROUP BY MAT ORDER BY MAT", 4);
        Object[][] dMotivo    = cargarDatosMultiple.apply("SELECT CVE, DES FROM tmclas WHERE TBL = 'MCAN' ORDER BY CVE", 2);

        // --- 1. DATOS DE SELECCIÓN ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createTitledBorder("Datos de selección"));
        pnlSel.setBounds(10, 10, 810, 90);

        pnlSel.add(new JLabel("Compañía")).setBounds(20, 20, 70, 25);
        JComboBox<String> cmbCia = new JComboBox<>();
        cmbCia.setBounds(90, 20, 60, 25);
        
        pnlSel.add(new JLabel("C. Costos")).setBounds(220, 20, 70, 25);
        JComboBox<String> cmbCC = new JComboBox<>();
        cmbCC.setBounds(290, 20, 80, 25);

        // Llenar Combos Dinámicamente
        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();
            if (con != null) {
                ResultSet rsCia = con.prepareStatement("SELECT CIA FROM tmcias ORDER BY CIA").executeQuery();
                while(rsCia.next()) cmbCia.addItem(rsCia.getString("CIA"));
                rsCia.close();

                ResultSet rsCC = con.prepareStatement(
                        "SELECT DISTINCT CVE FROM tgcc WHERE COALESCE(CVE,'')<>'' ORDER BY CVE")
                        .executeQuery();
                while(rsCC.next()) cmbCC.addItem(rsCC.getString("CVE"));
                rsCC.close();
                
                db.Cerrar();
            }
        } catch (Exception ex) {}

        pnlSel.add(cmbCia);
        pnlSel.add(cmbCC);

        // Buscador Matrícula (4 Columnas)
        pnlSel.add(new JLabel("Matrícula")).setBounds(20, 55, 70, 25);
        JTextField txtMatricula = new JTextField(); txtMatricula.setBounds(90, 55, 80, 25);
        JButton btnMatricula = new JButton("▼"); btnMatricula.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10)); btnMatricula.setMargin(new java.awt.Insets(0, 0, 0, 0)); btnMatricula.setBounds(170, 55, 20, 25);
        buscador.configurar(txtMatricula, null, btnMatricula, dMatricula, new String[]{"Matrícula", "A. Paterno", "A. Materno", "Nombre"}, new int[]{80, 120, 120, 150});
        pnlSel.add(txtMatricula); pnlSel.add(btnMatricula);

        pnlSel.add(new JLabel("Fecha Inicial")).setBounds(220, 55, 80, 25);
        com.toedter.calendar.JDateChooser txtFecIni = new com.toedter.calendar.JDateChooser();
        txtFecIni.setDateFormatString("dd/MM/yyyy"); txtFecIni.setBounds(300, 55, 110, 25);
        pnlSel.add(txtFecIni);

        pnlSel.add(new JLabel("Fecha Final")).setBounds(430, 55, 80, 25);
        com.toedter.calendar.JDateChooser txtFecFin = new com.toedter.calendar.JDateChooser();
        txtFecFin.setDateFormatString("dd/MM/yyyy"); txtFecFin.setBounds(510, 55, 110, 25);
        pnlSel.add(txtFecFin);

        JButton btnFiltra = new JButton("Filtra Información");
        btnFiltra.setBounds(650, 50, 140, 30);
        pnlSel.add(btnFiltra);

        dialogo.add(pnlSel);

        // --- 2. MOTIVO DE CANCELACIÓN ---
        JLabel lblMotivo = new JLabel("Motivo de Cancelación");
        lblMotivo.setBounds(150, 110, 150, 25);
        
        JTextField txtMotivo = new JTextField(); txtMotivo.setBounds(300, 110, 50, 25);
        JButton btnMotivo = new JButton("▼"); btnMotivo.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10)); btnMotivo.setMargin(new java.awt.Insets(0, 0, 0, 0)); btnMotivo.setBounds(350, 110, 20, 25);
        JTextField txtMotivoDesc = new JTextField(); txtMotivoDesc.setBounds(375, 110, 420, 25); txtMotivoDesc.setEditable(false); txtMotivoDesc.setBackground(new java.awt.Color(240,240,240));
        buscador.configurar(txtMotivo, txtMotivoDesc, btnMotivo, dMotivo, new String[]{"Clave", "Descripción"}, new int[]{60, 350});

        dialogo.add(lblMotivo);
        dialogo.add(txtMotivo);
        dialogo.add(btnMotivo);
        dialogo.add(txtMotivoDesc);

        // --- 3. TABLA DE RECIBOS SIN CONTABILIZAR ---
        DefaultTableModel modRecibosPendientes = new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Compañía", "C. Costos", "Descripción", "Ciclo Escolar", "Matrícula", "Num Recibo", "Tipo", "Fec Recibo", "Moneda", "Importe Pagado", "Partidas"}
        ) {
            @Override public boolean isCellEditable(int row, int column) { return false; }
        };
        JTable tblRecibosPendientes = new JTable(modRecibosPendientes);
        tblRecibosPendientes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Recibos Sin Contabilizar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pnlTabla.setBounds(10, 150, 810, 250);
        
        JScrollPane scrollRecibos = new JScrollPane(tblRecibosPendientes);
        scrollRecibos.setBounds(10, 20, 790, 220);
        pnlTabla.add(scrollRecibos);
        
        dialogo.add(pnlTabla);

        // --- 4. BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(310, 420, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(430, 420, 100, 40);

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        // BUSCAR RECIBOS A CANCELAR EN LA BASE DE DATOS (tesralu)
        btnFiltra.addActionListener(e -> {
            modRecibosPendientes.setRowCount(0);
            
            String cia = cmbCia.getSelectedItem() != null ? cmbCia.getSelectedItem().toString() : "";
            String cc = cmbCC.getSelectedItem() != null ? cmbCC.getSelectedItem().toString() : "";
            String matricula = txtMatricula.getText().trim();

            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String fIni = txtFecIni.getDate() != null ? sdf.format(txtFecIni.getDate()) : "";
            String fFin = txtFecFin.getDate() != null ? sdf.format(txtFecFin.getDate()) : "";

            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    StringBuilder sql = new StringBuilder(
                            "SELECT CIA,CC,CONCAT(COUNT(*),' CONCEPTO(S)') AS DCPTO," +
                            "CESC,MAT,NREC,TREC,FREC,MAX(CMON) AS CMON," +
                            "SUM(IPAGMN) AS IMPORTE,COUNT(*) AS PARTIDAS FROM tesralu " +
                            "WHERE COALESCE(MCAN,'')='' AND IPAGMN>0 " +
                            "AND COALESCE(RELPOL,0)=0 AND COALESCE(RELPOC,0)=0 " +
                            "AND COALESCE(NFAC,0)=0");
                    
                    if (!cia.isEmpty()) sql.append(" AND CIA = ?");
                    if (!cc.isEmpty()) sql.append(" AND CC = ?");
                    if (!matricula.isEmpty()) sql.append(" AND MAT = ?");
                    if (!fIni.isEmpty() && !fFin.isEmpty()) sql.append(" AND FREC BETWEEN ? AND ?");

                    sql.append(" GROUP BY CIA,CC,CESC,MAT,NREC,TREC,FREC " +
                            "ORDER BY FREC DESC,NREC DESC");

                    PreparedStatement ps = con.prepareStatement(sql.toString());
                    int p = 1;
                    if (!cia.isEmpty()) ps.setString(p++, cia);
                    if (!cc.isEmpty()) ps.setString(p++, cc);
                    if (!matricula.isEmpty()) ps.setString(p++, matricula);
                    if (!fIni.isEmpty() && !fFin.isEmpty()) {
                        ps.setString(p++, fIni);
                        ps.setString(p++, fFin);
                    }

                    ResultSet rs = ps.executeQuery();
                    java.text.DecimalFormat df = new java.text.DecimalFormat("#,##0.00");

                    while (rs.next()) {
                        Object[] fila = new Object[11];
                        fila[0] = rs.getString("CIA");
                        fila[1] = rs.getString("CC");
                        fila[2] = rs.getString("DCPTO");
                        fila[3] = rs.getString("CESC");
                        fila[4] = rs.getString("MAT");
                        fila[5] = rs.getString("NREC");
                        fila[6] = rs.getString("TREC");
                        fila[7] = rs.getString("FREC");
                        fila[8] = rs.getString("CMON");
                        fila[9] = df.format(rs.getDouble("IMPORTE"));
                        fila[10] = rs.getInt("PARTIDAS");
                        modRecibosPendientes.addRow(fila);
                    }
                    rs.close(); ps.close(); db.Cerrar();

                    if (modRecibosPendientes.getRowCount() == 0) {
                        JOptionPane.showMessageDialog(dialogo, "No se encontraron recibos pendientes por cancelar con esos filtros.", "Información", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialogo, "Error al buscar recibos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        // PROCESAR LA CANCELACIÓN CON BLOQUEO COMPATIBLE CON TABLAS MYISAM
        btnAceptar.addActionListener(e -> {
            int filaSel = tblRecibosPendientes.getSelectedRow();
            if (filaSel == -1) {
                JOptionPane.showMessageDialog(dialogo, "Seleccione un recibo de la tabla para cancelar.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (txtMotivo.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "Debe especificar un Motivo de Cancelación.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String nRecibo = tblRecibosPendientes.getValueAt(filaSel, 5).toString();
            String ciaRecibo = tblRecibosPendientes.getValueAt(filaSel, 0).toString();
            String ccRecibo = tblRecibosPendientes.getValueAt(filaSel, 1).toString();
            String cicloRecibo = tblRecibosPendientes.getValueAt(filaSel, 3).toString();
            String matricula = tblRecibosPendientes.getValueAt(filaSel, 4).toString();
            String tipoRecibo = tblRecibosPendientes.getValueAt(filaSel, 6).toString();
            String partidas = tblRecibosPendientes.getValueAt(filaSel, 10).toString();
            String importe = tblRecibosPendientes.getValueAt(filaSel, 9).toString();
            String motivoCode = txtMotivo.getText().trim();

            int confirm = JOptionPane.showConfirmDialog(dialogo, 
                "¿Está seguro de cancelar el recibo " + nRecibo + " del alumno " + matricula + "?\n" +
                "Se cancelarán " + partidas + " partidas por $" + importe +
                " y se recalcularán sus saldos.",
                "Confirmar Cancelación", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                Connection con = null;
                boolean tablasBloqueadas = false;
                boolean cancelado = false;
                try {
                    con = ConDB.getConnection();
                    try (PreparedStatement ps = con.prepareStatement(
                            "LOCK TABLES tescalu WRITE,tesralu WRITE,tespalu WRITE")) {
                        ps.execute();
                        tablasBloqueadas = true;
                    }
                    String usuario = obtenerUsuarioActivo();
                    Set<Integer> conceptos = new TreeSet<>();

                    String llaveRecibo = "CIA=? AND CC=? AND CESC=? AND MAT=? AND NREC=? AND TREC=?";
                    String sqlConceptos = "SELECT IDCPT FROM tesralu WHERE " + llaveRecibo +
                            " AND COALESCE(MCAN,'')='' ORDER BY IDCPT";
                    try (PreparedStatement ps = con.prepareStatement(sqlConceptos)) {
                        ps.setString(1, ciaRecibo);
                        ps.setString(2, ccRecibo);
                        ps.setString(3, cicloRecibo);
                        ps.setString(4, matricula);
                        ps.setString(5, nRecibo);
                        ps.setString(6, tipoRecibo);
                        try (ResultSet rs = ps.executeQuery()) {
                            while (rs.next()) conceptos.add(rs.getInt("IDCPT"));
                        }
                    }
                    if (conceptos.isEmpty()) {
                        throw new SQLException("El recibo ya fue cancelado o ya no está disponible.");
                    }

                    String sqlBloqueaSaldo = "SELECT IDCPT FROM tescalu " +
                            "WHERE CIA=? AND CC=? AND CESC=? AND MAT=? AND IDCPT=?";
                    for (int idConcepto : conceptos) {
                        try (PreparedStatement ps = con.prepareStatement(sqlBloqueaSaldo)) {
                            ps.setString(1, ciaRecibo);
                            ps.setString(2, ccRecibo);
                            ps.setString(3, cicloRecibo);
                            ps.setString(4, matricula);
                            ps.setInt(5, idConcepto);
                            try (ResultSet rs = ps.executeQuery()) {
                                if (!rs.next()) {
                                    throw new SQLException("No se encontró el concepto " + idConcepto + ".");
                                }
                            }
                        }
                    }

                    String sqlCancelRalu = "UPDATE tesralu SET MCAN=?,USER=?,FEAC=CURDATE()," +
                            "HOAC=DATE_FORMAT(NOW(),'%r') WHERE " + llaveRecibo +
                            " AND COALESCE(MCAN,'')=''";
                    try (PreparedStatement ps = con.prepareStatement(sqlCancelRalu)) {
                        ps.setString(1, motivoCode);
                        ps.setString(2, usuario);
                        ps.setString(3, ciaRecibo);
                        ps.setString(4, ccRecibo);
                        ps.setString(5, cicloRecibo);
                        ps.setString(6, matricula);
                        ps.setString(7, nRecibo);
                        ps.setString(8, tipoRecibo);
                        if (ps.executeUpdate() == 0) {
                            throw new SQLException("No se encontró el recibo vigente para cancelar.");
                        }
                    }

                    String sqlCancelPalu = "UPDATE tespalu SET MCAN=?,USER=?,FEAC=CURDATE()," +
                            "HOAC=DATE_FORMAT(NOW(),'%r') WHERE " + llaveRecibo +
                            " AND COALESCE(MCAN,'')=''";
                    try (PreparedStatement ps = con.prepareStatement(sqlCancelPalu)) {
                        ps.setString(1, motivoCode);
                        ps.setString(2, usuario);
                        ps.setString(3, ciaRecibo);
                        ps.setString(4, ccRecibo);
                        ps.setString(5, cicloRecibo);
                        ps.setString(6, matricula);
                        ps.setString(7, nRecibo);
                        ps.setString(8, tipoRecibo);
                        ps.executeUpdate();
                    }

                    String sqlPagado = "SELECT COALESCE(SUM(IPAGMN),0) AS PAGADO FROM tesralu " +
                            "WHERE CIA=? AND CC=? AND CESC=? AND MAT=? AND IDCPT=? " +
                            "AND COALESCE(MCAN,'')=''";
                    String sqlSaldo = "UPDATE tescalu SET IPAGMN=LEAST(COALESCE(IMPTMN,0),?)," +
                            "IPENMN=GREATEST(COALESCE(IMPTMN,0)-?,0),USER=?,FEAC=CURDATE()," +
                            "HOAC=DATE_FORMAT(NOW(),'%r') " +
                            "WHERE CIA=? AND CC=? AND CESC=? AND MAT=? AND IDCPT=?";

                    for (int idConcepto : conceptos) {
                        double pagado;
                        try (PreparedStatement ps = con.prepareStatement(sqlPagado)) {
                            ps.setString(1, ciaRecibo);
                            ps.setString(2, ccRecibo);
                            ps.setString(3, cicloRecibo);
                            ps.setString(4, matricula);
                            ps.setInt(5, idConcepto);
                            try (ResultSet rs = ps.executeQuery()) {
                                rs.next();
                                pagado = rs.getDouble("PAGADO");
                            }
                        }
                        try (PreparedStatement ps = con.prepareStatement(sqlSaldo)) {
                            ps.setDouble(1, pagado);
                            ps.setDouble(2, pagado);
                            ps.setString(3, usuario);
                            ps.setString(4, ciaRecibo);
                            ps.setString(5, ccRecibo);
                            ps.setString(6, cicloRecibo);
                            ps.setString(7, matricula);
                            ps.setInt(8, idConcepto);
                            if (ps.executeUpdate() != 1) {
                                throw new SQLException("No se pudo recalcular el concepto " + idConcepto + ".");
                            }
                        }
                    }
                    cancelado = true;
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(dialogo, "Error al procesar la cancelación: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                } finally {
                    if (con != null) {
                        if (tablasBloqueadas) {
                            try (PreparedStatement ps = con.prepareStatement("UNLOCK TABLES")) {
                                ps.execute();
                            } catch (Exception ignored) {}
                        }
                        try {
                            con.close();
                        } catch (Exception ignored) {}
                    }
                }
                if (cancelado) {
                    JOptionPane.showMessageDialog(dialogo,
                            "Recibo cancelado y saldos recalculados correctamente.",
                            "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    btnFiltra.doClick();
                    cargarTablaHistorialCancelaciones();
                }
            }
        });

        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCRecibos;
    private javax.swing.JButton btnDeleteCRecibos;
    private javax.swing.JButton btnEditCRecibos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCConceptos;
    // End of variables declaration//GEN-END:variables
}
