/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Captura_Polizas extends javax.swing.JPanel {

    /**
     * Creates new form Captura_Polizas
     */
    public Captura_Polizas() {
        initComponents();
    }
private void cargarTablaPolizas() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Compañía", "Núm Póliza", "Tipo", "Fecha", "Descripción", "Cargos", "Créditos", "Diferencia"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblCPolizas.setModel(modelo);

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                // ATENCIÓN: Cambia por tu tabla real de encabezados de póliza
                String sql = "SELECT compania, num_poliza, tipo_poliza, fecha, descripcion, total_cargos, total_creditos, diferencia FROM tabla_polizas";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[8]; 
                    fila[0] = rs.getString("compania");
                    fila[1] = rs.getString("num_poliza");
                    fila[2] = rs.getString("tipo_poliza");
                    fila[3] = rs.getString("fecha");
                    fila[4] = rs.getString("descripcion");
                    fila[5] = rs.getString("total_cargos");
                    fila[6] = rs.getString("total_creditos");
                    fila[7] = rs.getString("diferencia");
                    modelo.addRow(fila);
                }
                rs.close(); ps.close(); db.Cerrar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar el historial de pólizas: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCPolizas = new javax.swing.JTable();
        btnAddCPolizas = new javax.swing.JButton();
        btnEditCPolizas = new javax.swing.JButton();
        btnDeleteCPolizas = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblCPolizas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCPolizas);

        btnAddCPolizas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCPolizas.setForeground(new java.awt.Color(26, 61, 99));
        btnAddCPolizas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddCPolizas.setText("Añadir");
        btnAddCPolizas.addActionListener(this::btnAddCPolizasActionPerformed);

        btnEditCPolizas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditCPolizas.setForeground(new java.awt.Color(26, 61, 99));
        btnEditCPolizas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditCPolizas.setText("Editar");
        btnEditCPolizas.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditCPolizas.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditCPolizas.addActionListener(this::btnEditCPolizasActionPerformed);

        btnDeleteCPolizas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteCPolizas.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteCPolizas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteCPolizas.setText("Eliminar");
        btnDeleteCPolizas.addActionListener(this::btnDeleteCPolizasActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddCPolizas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCPolizas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCPolizas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCPolizas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCPolizas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCPolizas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCPolizasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCPolizasActionPerformed
      mostrarDialogoPoliza(false); // Falso = Nueva Póliza
    }//GEN-LAST:event_btnAddCPolizasActionPerformed

    private void btnEditCPolizasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCPolizasActionPerformed
if (tblCPolizas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una póliza para ver/editar su detalle.");
            return;
        }
        mostrarDialogoPoliza(true); // Verdadero = Editar Póliza existente
    }//GEN-LAST:event_btnEditCPolizasActionPerformed

    private void btnDeleteCPolizasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCPolizasActionPerformed
        int fila = tblCPolizas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una póliza para eliminar/cancelar.");
            return;
        }

        String numPoliza = tblCPolizas.getValueAt(fila, 1).toString();
        
        int resp = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar la póliza número: " + numPoliza + "?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    // ATENCIÓN: Cambia por tu tabla real
                    String sql = "DELETE FROM tabla_polizas WHERE num_poliza = ?";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, numPoliza);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Póliza eliminada correctamente.");
                        cargarTablaPolizas();
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar la póliza: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteCPolizasActionPerformed
private void mostrarDialogoPoliza(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Póliza" : "Captura de Pólizas";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(980, 720);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- PESTAÑAS PRINCIPALES ---
        JTabbedPane pestanas = new JTabbedPane();
        pestanas.setBounds(10, 10, 945, 590);

        JPanel pnlConsultaPolizas = new JPanel(null); // Pestaña 1 (Vacía en la imagen)
        JPanel pnlCaptura = new JPanel(null);         // Pestaña 2 (Activa)
        JPanel pnlModelo = new JPanel(null);          // Pestaña 3 (Vacía en la imagen)

        // ==========================================
        // DISEÑO DE LA PESTAÑA: "Consulta de Póliza" (Captura)
        // ==========================================
        
        // --- 1. CABECERA DE LA PÓLIZA ---
        pnlCaptura.add(new JLabel("Compañía")).setBounds(20, 20, 80, 25);
        JComboBox<String> cmbCia = new JComboBox<>(new String[]{"12"}); cmbCia.setBounds(110, 20, 80, 25);
        pnlCaptura.add(cmbCia);

        pnlCaptura.add(new JLabel("Tipo Pol.")).setBounds(20, 50, 80, 25);
        pnlCaptura.add(new JComboBox<>(new String[]{""})).setBounds(110, 50, 80, 25);

        pnlCaptura.add(new JLabel("Tipo de Cont.")).setBounds(20, 80, 80, 25);
        pnlCaptura.add(new JComboBox<>(new String[]{""})).setBounds(110, 80, 80, 25);

        pnlCaptura.add(new JLabel("Tipo Moneda")).setBounds(20, 110, 80, 25);
        pnlCaptura.add(new JComboBox<>(new String[]{"MXP"})).setBounds(110, 110, 80, 25);

        pnlCaptura.add(new JLabel("Núm. Poliza")).setBounds(250, 20, 80, 25);
        JTextField txtNumPoliza = new JTextField(); txtNumPoliza.setBounds(330, 20, 80, 25);
        pnlCaptura.add(txtNumPoliza);

        pnlCaptura.add(new JLabel("Fecha")).setBounds(470, 20, 50, 25);
        pnlCaptura.add(new JTextField("04/06/2026")).setBounds(530, 20, 90, 25);

        pnlCaptura.add(new JLabel("Año")).setBounds(660, 0, 40, 20);
        pnlCaptura.add(new JTextField("2026")).setBounds(650, 20, 50, 25);
        
        pnlCaptura.add(new JLabel("Periodo")).setBounds(720, 0, 50, 20);
        pnlCaptura.add(new JTextField("6")).setBounds(720, 20, 40, 25);

        pnlCaptura.add(new JLabel("Descripción")).setBounds(450, 50, 80, 25);
        JTextField txtDesc = new JTextField(); txtDesc.setBounds(530, 50, 390, 25);
        pnlCaptura.add(txtDesc);

        // --- 2. BARRA DE CAPTURA RÁPIDA (Fila de ingreso de partidas) ---
        JPanel pnlPartida = new JPanel(null);
        pnlPartida.setBorder(BorderFactory.createEtchedBorder());
        pnlPartida.setBounds(10, 145, 920, 55);

        String[] headersPartida = {"No.", "Centro Costo", "Cuenta", "Concepto", "Tipo SSC", "SubSubCta", "Importe", "Unidades", "U.M."};
        int[] xPosPartida = {10, 50, 150, 270, 450, 550, 650, 750, 830};
        int[] widthsPartida = {35, 90, 110, 170, 90, 90, 90, 70, 50};

        for (int i = 0; i < headersPartida.length; i++) {
            pnlPartida.add(new JLabel(headersPartida[i])).setBounds(xPosPartida[i], 5, widthsPartida[i], 15);
            if (i == 1 || i == 3 || i == 4 || i == 8) { // Algunos son ComboBox
                pnlPartida.add(new JComboBox<>(new String[]{""})).setBounds(xPosPartida[i], 20, widthsPartida[i], 25);
            } else { // Otros son TextField
                pnlPartida.add(new JTextField(i==6 || i==7 ? "0.00" : (i==0 ? "1" : ""))).setBounds(xPosPartida[i], 20, widthsPartida[i], 25);
            }
        }
        JButton btnOk = new JButton("OK"); btnOk.setBounds(885, 20, 25, 25);
        pnlPartida.add(btnOk);
        pnlCaptura.add(pnlPartida);

        // --- 3. TABLA DEL DETALLE CONTABLE ---
        JTable tblDetallePoliza = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"No.", "Cuenta", "Explicación", "Tpo SSC", "Sub-Sub", "Cargo", "Crédito", "Unidades"}
        ));
        JScrollPane scrollDetalle = new JScrollPane(tblDetallePoliza);
        scrollDetalle.setBounds(10, 205, 920, 280);
        pnlCaptura.add(scrollDetalle);

        // --- 4. TOTALES (Cuadratura) ---
        JPanel pnlTotales = new JPanel(null);
        pnlTotales.setBorder(BorderFactory.createEtchedBorder());
        pnlTotales.setBounds(10, 490, 920, 60);

        pnlTotales.add(new JLabel("Cargos")).setBounds(30, 20, 60, 25);
        JTextField txtCargos = new JTextField("0.00"); txtCargos.setBounds(90, 20, 120, 25);
        txtCargos.setHorizontalAlignment(JTextField.RIGHT); txtCargos.setEditable(false);
        pnlTotales.add(txtCargos);

        pnlTotales.add(new JLabel("Créditos")).setBounds(330, 20, 60, 25);
        JTextField txtCreditos = new JTextField("0.00"); txtCreditos.setBounds(390, 20, 120, 25);
        txtCreditos.setHorizontalAlignment(JTextField.RIGHT); txtCreditos.setEditable(false);
        pnlTotales.add(txtCreditos);

        pnlTotales.add(new JLabel("Diferencia")).setBounds(630, 20, 70, 25);
        JTextField txtDif = new JTextField("0.00"); txtDif.setBounds(700, 20, 120, 25);
        txtDif.setHorizontalAlignment(JTextField.RIGHT); txtDif.setEditable(false);
        pnlTotales.add(txtDif);

        pnlCaptura.add(pnlTotales);

        // Agregamos las pestañas
        pestanas.addTab("Consulta de Pólizas", pnlConsultaPolizas);
        pestanas.addTab("Consulta de Póliza", pnlCaptura);
        pestanas.addTab("Pólizas Modelo", pnlModelo);
        pestanas.setSelectedIndex(1); // Dejamos activa la pestaña de en medio

        dialogo.add(pestanas);

        // --- 5. BOTONES INFERIORES ---
        JButton btnGuardar = new JButton("Guardar");
        btnGuardar.setBounds(380, 620, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(500, 620, 100, 40);

        dialogo.add(btnGuardar);
        dialogo.add(btnSalir);

        // --- 6. SI ES EDICIÓN ---
        if (modoEdicion) {
            int fila = tblCPolizas.getSelectedRow();
            txtNumPoliza.setText(tblCPolizas.getValueAt(fila, 1).toString());
            txtNumPoliza.setEditable(false); // Bloqueamos el número de póliza
            txtDesc.setText(tblCPolizas.getValueAt(fila, 4).toString());
            // Faltaría cargar el detalle (las partidas) a la tabla tblDetallePoliza usando SQL
        }

        // --- 7. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnOk.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Partida agregada a la cuadrícula inferior (Simulación).");
        });

        btnGuardar.addActionListener(e -> {
            if (txtNumPoliza.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "El número de póliza es requerido.");
                return;
            }
            JOptionPane.showMessageDialog(dialogo, "Póliza guardada exitosamente (Simulación).");
            dialogo.dispose();
            cargarTablaPolizas(); 
        });

        // --- 8. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCPolizas;
    private javax.swing.JButton btnDeleteCPolizas;
    private javax.swing.JButton btnEditCPolizas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCPolizas;
    // End of variables declaration//GEN-END:variables
}
