/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Color;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Catalogo_Cuentas_Bancarias extends javax.swing.JPanel {

    /**
     * Creates new form Catalogo_Cuentas_Bancarias
     */
    public Catalogo_Cuentas_Bancarias() {
        initComponents();
        cargarTablaCuentas();
    }
private void cargarTablaCuentas() {
        DefaultTableModel modelo = (DefaultTableModel) tblCCBancarias.getModel();
        modelo.setRowCount(0); 

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                // Consulta a la tabla tmcban
                String sql = "SELECT CIA, CCTA, CBCO, CBAN, CSIG, CMON, USER, FEAC, HOAC FROM tmcban";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[10]; 
                    fila[0] = rs.getString("CIA");
                    fila[1] = rs.getString("CCTA");
                    fila[2] = "NO. CUENTA - " + rs.getString("CBAN"); // Simulamos la descripción
                    fila[3] = rs.getString("CBCO");
                    fila[4] = rs.getString("CBAN");
                    fila[5] = rs.getString("CSIG");
                    fila[6] = rs.getString("CMON");
                    fila[7] = rs.getString("USER");
                    fila[8] = rs.getString("FEAC");
                    fila[9] = rs.getString("HOAC");
                    modelo.addRow(fila);
                }
                rs.close(); ps.close(); db.Cerrar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBg = new javax.swing.JPanel();
        btnDeleteCCBancarias = new javax.swing.JButton();
        btnEditCCBancarias = new javax.swing.JButton();
        btnAddCCBancarias = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCCBancarias = new javax.swing.JTable();

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));

        btnDeleteCCBancarias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteCCBancarias.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteCCBancarias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteCCBancarias.setText("Eliminar");
        btnDeleteCCBancarias.addActionListener(this::btnDeleteCCBancariasActionPerformed);

        btnEditCCBancarias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditCCBancarias.setForeground(new java.awt.Color(26, 61, 99));
        btnEditCCBancarias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditCCBancarias.setText("Editar");
        btnEditCCBancarias.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditCCBancarias.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditCCBancarias.addActionListener(this::btnEditCCBancariasActionPerformed);

        btnAddCCBancarias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCCBancarias.setForeground(new java.awt.Color(26, 61, 99));
        btnAddCCBancarias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddCCBancarias.setText("Añadir");
        btnAddCCBancarias.addActionListener(this::btnAddCCBancariasActionPerformed);

        tblCCBancarias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Compañia", "Cuenta Contable", "Descripcion", "Banco", "Cuenta Bancaria", "Cheque Sig.", "Moneda", "Usuario Mod.", "Fecha Mod.", "Hora Mod."
            }
        ));
        jScrollPane1.setViewportView(tblCCBancarias);

        javax.swing.GroupLayout pnlBgLayout = new javax.swing.GroupLayout(pnlBg);
        pnlBg.setLayout(pnlBgLayout);
        pnlBgLayout.setHorizontalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddCCBancarias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCCBancarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCCBancarias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBgLayout.setVerticalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCCBancarias, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCCBancarias, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCCBancarias, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCCBancariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCCBancariasActionPerformed
       mostrarDialogoCuentaBancaria(false);
    }//GEN-LAST:event_btnAddCCBancariasActionPerformed

    private void btnDeleteCCBancariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCCBancariasActionPerformed
   int fila = tblCCBancarias.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una cuenta para eliminar.");
            return;
        }

        String cia = tblCCBancarias.getValueAt(fila, 0).toString(); 
        String cuentaContable = tblCCBancarias.getValueAt(fila, 1).toString(); 
        
        int resp = JOptionPane.showConfirmDialog(this, 
                "¿Seguro que deseas eliminar la cuenta " + cuentaContable + " de la compañía " + cia + "?", 
                "Confirmar", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    // Borramos utilizando las 2 llaves primarias
                    PreparedStatement ps = con.prepareStatement("DELETE FROM tmcban WHERE CIA = ? AND CCTA = ?");
                    ps.setString(1, cia);
                    ps.setString(2, cuentaContable);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Cuenta eliminada.");
                        cargarTablaCuentas(); // Refrescamos la tabla
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró el registro para eliminar.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteCCBancariasActionPerformed

    private void btnEditCCBancariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCCBancariasActionPerformed
      if (tblCCBancarias.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una cuenta para editar.");
            return;
        }
        mostrarDialogoCuentaBancaria(true);
    }//GEN-LAST:event_btnEditCCBancariasActionPerformed
private void mostrarDialogoCuentaBancaria(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Cuenta Bancaria" : "Cuentas Bancarias";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(550, 520);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. SECCIÓN SUPERIOR ---
        JLabel lblCia = new JLabel("Compañía");
        lblCia.setBounds(20, 15, 100, 25);
        JComboBox<String> cmbCia = new JComboBox<>(new String[]{"12", "13"});
        cmbCia.setBounds(130, 15, 70, 25);
        JLabel lblCiaDesc = new JLabel("UNIDAD ESCOLAR BENAVENTE, A.C.");
        lblCiaDesc.setBounds(210, 15, 250, 25);

        JLabel lblCtaContable = new JLabel("Cuenta Contable");
        lblCtaContable.setBounds(20, 45, 100, 25);
        JComboBox<String> cmbCtaContable = new JComboBox<>(new String[]{"12-1010201-013", "12-1010201-014", ""});
        cmbCtaContable.setEditable(true); 
        cmbCtaContable.setBounds(130, 45, 130, 25);
        JLabel lblCtaDesc = new JLabel("");
        lblCtaDesc.setBounds(270, 45, 250, 25);

        // Bloqueamos llaves primarias en edición
        if (modoEdicion) {
            cmbCia.setEnabled(false);
            cmbCtaContable.setEnabled(false);
        }

        dialogo.add(lblCia); dialogo.add(cmbCia); dialogo.add(lblCiaDesc);
        dialogo.add(lblCtaContable); dialogo.add(cmbCtaContable); dialogo.add(lblCtaDesc);

        // --- 2. PESTAÑAS (TABS) ---
        JTabbedPane pestanas = new JTabbedPane();
        pestanas.setBounds(15, 90, 500, 330);

        JPanel pnlGenerales = new JPanel(null);

        // >> Marco: Información de Cuenta
        JPanel pnlInfo = new JPanel(null);
        pnlInfo.setBorder(BorderFactory.createTitledBorder("Información de Cuenta"));
        pnlInfo.setBounds(10, 10, 475, 180);

        JLabel lblBanco = new JLabel("Banco");
        lblBanco.setBounds(20, 25, 100, 25);
        JComboBox<String> cmbBanco = new JComboBox<>(new String[]{"BCM", "AFI", "SAN"});
        cmbBanco.setBounds(130, 25, 70, 25);
        JLabel lblBancoDesc = new JLabel("BANCO");
        lblBancoDesc.setBounds(210, 25, 200, 25);

        JLabel lblCtaBan = new JLabel("Cuenta Bancaria");
        lblCtaBan.setBounds(20, 60, 100, 25);
        JTextField txtCtaBan = new JTextField();
        txtCtaBan.setBounds(130, 60, 250, 25);

        JLabel lblSucursal = new JLabel("Sucursal Bancaria");
        lblSucursal.setBounds(20, 95, 120, 25);
        JTextField txtSucursal = new JTextField();
        txtSucursal.setBounds(130, 95, 250, 25);

        JLabel lblCheque = new JLabel("Cheque Siguiente");
        lblCheque.setBounds(20, 135, 110, 25);
        JTextField txtCheque = new JTextField("0");
        txtCheque.setBounds(130, 135, 80, 25);

        JLabel lblMoneda = new JLabel("Moneda");
        lblMoneda.setBounds(310, 135, 60, 25);
        JComboBox<String> cmbMoneda = new JComboBox<>(new String[]{"MXP", "USD"});
        cmbMoneda.setBounds(370, 135, 80, 25);

        pnlInfo.add(lblBanco); pnlInfo.add(cmbBanco); pnlInfo.add(lblBancoDesc);
        pnlInfo.add(lblCtaBan); pnlInfo.add(txtCtaBan);
        pnlInfo.add(lblSucursal); pnlInfo.add(txtSucursal);
        pnlInfo.add(lblCheque); pnlInfo.add(txtCheque);
        pnlInfo.add(lblMoneda); pnlInfo.add(cmbMoneda);

        // >> Marco: Formato
        JPanel pnlFormato = new JPanel(null);
        pnlFormato.setBorder(BorderFactory.createTitledBorder("Formato"));
        pnlFormato.setBounds(10, 200, 475, 80);

        JLabel lblFormato = new JLabel("Formato de Cheque");
        lblFormato.setBounds(20, 30, 120, 25);
        JComboBox<String> cmbFormato = new JComboBox<>(new String[]{"01", "02"});
        cmbFormato.setBounds(140, 30, 60, 25);
        JLabel lblFormatoDesc = new JLabel("CHEQUE");
        lblFormatoDesc.setBounds(210, 30, 250, 25);

        pnlFormato.add(lblFormato); pnlFormato.add(cmbFormato); pnlFormato.add(lblFormatoDesc);

        pnlGenerales.add(pnlInfo);
        pnlGenerales.add(pnlFormato);

        pestanas.addTab("Datos Generales", pnlGenerales);
        pestanas.addTab("Contratos y/o Convenios", new JPanel()); 

        dialogo.add(pestanas);

        // --- 3. BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(150, 430, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(280, 430, 100, 40);

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        // --- 4. SI ES MODO EDICIÓN, CARGAMOS LOS DATOS ---
        if (modoEdicion) {
            int fila = tblCCBancarias.getSelectedRow();
            
            String cia = tblCCBancarias.getValueAt(fila, 0) != null ? tblCCBancarias.getValueAt(fila, 0).toString() : "";
            String ctaContable = tblCCBancarias.getValueAt(fila, 1) != null ? tblCCBancarias.getValueAt(fila, 1).toString() : "";
            
            cmbCia.setSelectedItem(cia);
            cmbCtaContable.setSelectedItem(ctaContable);
            cmbBanco.setSelectedItem(tblCCBancarias.getValueAt(fila, 3) != null ? tblCCBancarias.getValueAt(fila, 3).toString() : "");
            txtCtaBan.setText(tblCCBancarias.getValueAt(fila, 4) != null ? tblCCBancarias.getValueAt(fila, 4).toString() : "");
            txtCheque.setText(tblCCBancarias.getValueAt(fila, 5) != null ? tblCCBancarias.getValueAt(fila, 5).toString() : "0");
            cmbMoneda.setSelectedItem(tblCCBancarias.getValueAt(fila, 6) != null ? tblCCBancarias.getValueAt(fila, 6).toString() : "");

            // Buscamos los datos extra (Sucursal y Formato) directo en la BD
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps = con.prepareStatement("SELECT SBAN, TFIC FROM tmcban WHERE CIA = ? AND CCTA = ?");
                    ps.setString(1, cia);
                    ps.setString(2, ctaContable);
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()) {
                        txtSucursal.setText(rs.getString("SBAN") != null ? rs.getString("SBAN") : "");
                        cmbFormato.setSelectedItem(rs.getString("TFIC") != null ? rs.getString("TFIC") : "");
                    }
                    rs.close(); ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                // Ignorar si no se pudieron cargar los datos adicionales
            }
        }

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnAceptar.addActionListener(e -> {
            String cia = cmbCia.getSelectedItem() != null ? cmbCia.getSelectedItem().toString() : "";
            String ctaContable = cmbCtaContable.getSelectedItem() != null ? cmbCtaContable.getSelectedItem().toString() : "";
            String banco = cmbBanco.getSelectedItem() != null ? cmbBanco.getSelectedItem().toString() : "";
            String ctaBan = txtCtaBan.getText().trim();
            String sucursal = txtSucursal.getText().trim();
            String cheque = txtCheque.getText().trim().isEmpty() ? "0" : txtCheque.getText().trim();
            String moneda = cmbMoneda.getSelectedItem() != null ? cmbMoneda.getSelectedItem().toString() : "";
            String formato = cmbFormato.getSelectedItem() != null ? cmbFormato.getSelectedItem().toString() : "";

            if (cia.isEmpty() || ctaContable.isEmpty() || ctaBan.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "La Compañía, Cuenta Contable y Cuenta Bancaria son obligatorias.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps;
                    
                    if (modoEdicion) {
                        // UPDATE 
                        String sql = "UPDATE tmcban SET CBCO=?, CBAN=?, SBAN=?, CSIG=?, CMON=?, TFIC=? WHERE CIA=? AND CCTA=?";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, banco);
                        ps.setString(2, ctaBan);
                        ps.setString(3, sucursal);
                        ps.setString(4, cheque);
                        ps.setString(5, moneda);
                        ps.setString(6, formato);
                        ps.setString(7, cia);
                        ps.setString(8, ctaContable);
                    } else {
                        // INSERT
                        String sql = "INSERT INTO tmcban (CIA, CCTA, CBCO, CBAN, SBAN, CSIG, CMON, TFIC) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, cia);
                        ps.setString(2, ctaContable);
                        ps.setString(3, banco);
                        ps.setString(4, ctaBan);
                        ps.setString(5, sucursal);
                        ps.setString(6, cheque);
                        ps.setString(7, moneda);
                        ps.setString(8, formato);
                    }

                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(dialogo, "Cuenta Bancaria guardada con éxito.");
                        dialogo.dispose();
                        cargarTablaCuentas(); 
                    } else {
                        JOptionPane.showMessageDialog(dialogo, "No se pudo guardar la información.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialogo, "Error SQL: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCCBancarias;
    private javax.swing.JButton btnDeleteCCBancarias;
    private javax.swing.JButton btnEditCCBancarias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JTable tblCCBancarias;
    // End of variables declaration//GEN-END:variables
}
