/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Catalogo_Tipo_Alumno extends javax.swing.JPanel {

    /**
     * Creates new form Catalogo_Tipo_Alumno
     */
    public Catalogo_Tipo_Alumno() {
        initComponents();
    }
private void cargarTablaTiposAlumno() {
        // 1. Arreglamos las columnas de la tabla por código
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Compañía", "Tipo Alumno", "Descripción", "C. Costo", "Cuenta", "Usuario", "Fec Ult Act", "Hora Ult Act"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        jTable2.setModel(modelo);

        // 2. Cargamos los datos
        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                // ATENCIÓN: Cambia 'tabla_tipos_alumno' por tu tabla real
                String sql = "SELECT compania, tipo_alumno, descripcion, centro_costo, cuenta, usuario, fecha_mod, hora_mod FROM tabla_tipos_alumno";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[8]; 
                    fila[0] = rs.getString("compania");
                    fila[1] = rs.getString("tipo_alumno");
                    fila[2] = rs.getString("descripcion");
                    fila[3] = rs.getString("centro_costo");
                    fila[4] = rs.getString("cuenta");
                    fila[5] = rs.getString("usuario");
                    fila[6] = rs.getString("fecha_mod");
                    fila[7] = rs.getString("hora_mod");
                    modelo.addRow(fila);
                }
                rs.close(); ps.close(); db.Cerrar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnAddTAlumno = new javax.swing.JButton();
        btnEditTAlumno = new javax.swing.JButton();
        btnDeleteTAlumno = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnAddTAlumno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddTAlumno.setForeground(new java.awt.Color(26, 61, 99));
        btnAddTAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddTAlumno.setText("Añadir");
        btnAddTAlumno.addActionListener(this::btnAddTAlumnoActionPerformed);

        btnEditTAlumno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditTAlumno.setForeground(new java.awt.Color(26, 61, 99));
        btnEditTAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditTAlumno.setText("Editar");
        btnEditTAlumno.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditTAlumno.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditTAlumno.addActionListener(this::btnEditTAlumnoActionPerformed);

        btnDeleteTAlumno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteTAlumno.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteTAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteTAlumno.setText("Eliminar");
        btnDeleteTAlumno.addActionListener(this::btnDeleteTAlumnoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddTAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditTAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteTAlumno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditTAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteTAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTAlumnoActionPerformed
        mostrarDialogoTipoAlumno(false);
    }//GEN-LAST:event_btnAddTAlumnoActionPerformed

    private void btnEditTAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTAlumnoActionPerformed
if (jTable2.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un tipo de alumno para editar.");
            return;
        }
        mostrarDialogoTipoAlumno(true);
    }//GEN-LAST:event_btnEditTAlumnoActionPerformed

    private void btnDeleteTAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTAlumnoActionPerformed
        int fila = jTable2.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un tipo de alumno para eliminar.");
            return;
        }

        String compania = jTable2.getValueAt(fila, 0).toString();
        String tipoAlumno = jTable2.getValueAt(fila, 1).toString();
        String desc = jTable2.getValueAt(fila, 2).toString();
        
        int resp = JOptionPane.showConfirmDialog(this, "¿Eliminar el tipo de alumno: " + desc + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    // ATENCIÓN: Cambia por tu tabla real
                    String sql = "DELETE FROM tabla_tipos_alumno WHERE compania = ? AND tipo_alumno = ?";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, compania);
                    ps.setString(2, tipoAlumno);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Tipo de alumno eliminado.");
                        cargarTablaTiposAlumno();
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteTAlumnoActionPerformed

private void mostrarDialogoTipoAlumno(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Tipo de Alumno" : "Agregar Tipo de Alumno";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(480, 320);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. SECCIÓN SUPERIOR ---
        JLabel lblCia = new JLabel("Compañía");
        lblCia.setBounds(20, 15, 80, 25);
        JComboBox<String> cmbCia = new JComboBox<>(new String[]{"12"});
        cmbCia.setBounds(90, 15, 60, 25);
        JLabel lblCiaDesc = new JLabel("UNIDAD ESCOLAR BENAVENTE, A.C.");
        lblCiaDesc.setBounds(160, 15, 250, 25);

        dialogo.add(lblCia); dialogo.add(cmbCia); dialogo.add(lblCiaDesc);

        // --- 2. MARCO CENTRAL ---
        JPanel pnlCentral = new JPanel(null);
        pnlCentral.setBorder(BorderFactory.createEtchedBorder());
        pnlCentral.setBounds(15, 55, 435, 145);

        JLabel lblTipo = new JLabel("Tipo de Alumno");
        lblTipo.setBounds(15, 15, 100, 25);
        JTextField txtTipo = new JTextField();
        txtTipo.setBounds(120, 15, 80, 25);

        JLabel lblDesc = new JLabel("Descripción");
        lblDesc.setBounds(15, 50, 100, 25);
        JTextField txtDesc = new JTextField();
        txtDesc.setBounds(120, 50, 300, 25);

        // Etiquetas sobre los combos
        JLabel lblTitCC = new JLabel("Centro de Costo");
        lblTitCC.setBounds(15, 85, 100, 20);
        JComboBox<String> cmbCC = new JComboBox<>(new String[]{"", "12100", "12200"});
        cmbCC.setBounds(15, 105, 90, 25);

        JLabel lblTitCta = new JLabel("Cuenta Contable");
        lblTitCta.setBounds(150, 85, 120, 20);
        JComboBox<String> cmbCta = new JComboBox<>(new String[]{"", "1011000-001", "1011000-002"});
        cmbCta.setBounds(150, 105, 130, 25);

        if (modoEdicion) {
            cmbCia.setEnabled(false);
            txtTipo.setEditable(false); // Llave primaria
        }

        pnlCentral.add(lblTipo); pnlCentral.add(txtTipo);
        pnlCentral.add(lblDesc); pnlCentral.add(txtDesc);
        pnlCentral.add(lblTitCC); pnlCentral.add(cmbCC);
        pnlCentral.add(lblTitCta); pnlCentral.add(cmbCta);

        dialogo.add(pnlCentral);

        // --- 3. BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(120, 220, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(240, 220, 100, 40);

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        // --- 4. SI ES MODO EDICIÓN, CARGAMOS LOS DATOS ---
        if (modoEdicion) {
            int fila = jTable2.getSelectedRow();
            // Asegúrate de que los índices coinciden con la tabla
            cmbCia.setSelectedItem(jTable2.getValueAt(fila, 0).toString());
            txtTipo.setText(jTable2.getValueAt(fila, 1).toString());
            txtDesc.setText(jTable2.getValueAt(fila, 2).toString());
            
            // Si la celda de CC no es nula, la seleccionamos
            Object valCC = jTable2.getValueAt(fila, 3);
            if (valCC != null) cmbCC.setSelectedItem(valCC.toString());
            
            Object valCta = jTable2.getValueAt(fila, 4);
            if (valCta != null) cmbCta.setSelectedItem(valCta.toString());
        }

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnAceptar.addActionListener(e -> {
            String tipo = txtTipo.getText().trim();
            if (tipo.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "El tipo de alumno es obligatorio.");
                return;
            }

            // Aquí va la lógica SQL (INSERT / UPDATE)
            JOptionPane.showMessageDialog(dialogo, "Tipo de Alumno guardado (Simulación).");
            
            dialogo.dispose();
            cargarTablaTiposAlumno(); 
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTAlumno;
    private javax.swing.JButton btnDeleteTAlumno;
    private javax.swing.JButton btnEditTAlumno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
