/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Color;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Catalogo_Cuentas extends javax.swing.JPanel {

    /**
     * Creates new form Cuentas_Bancarias
     */
    public Catalogo_Cuentas() {
        initComponents();
        cargarTablaCuentas();
    }
private void cargarTablaCuentas() {
        DefaultTableModel modelo = (DefaultTableModel) tblCCuentas.getModel();
        modelo.setRowCount(0); 

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                // Traemos los 18 campos exactos que tienes en tu diseño de columnas
                String sql = "SELECT CIA, CCTA, CDES, CNIV, TCTA, STIP, CMAY, CC01, CC02, CC03, CC04, CC05, CC06, CC, AUX, USER, FEAC, HOAC FROM tmctas";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[18]; 
                    fila[0] = rs.getString("CIA");
                    fila[1] = rs.getString("CCTA");
                    fila[2] = rs.getString("CDES");
                    fila[3] = rs.getString("CNIV");
                    fila[4] = rs.getString("TCTA"); 
                    fila[5] = rs.getString("STIP"); 
                    fila[6] = rs.getString("CMAY"); 
                    fila[7] = rs.getString("CC01"); // Clasif 1
                    fila[8] = rs.getString("CC02"); // Clasif 2
                    fila[9] = rs.getString("CC03"); // Clasif 3
                    fila[10] = rs.getString("CC04"); // Clasif 4
                    fila[11] = rs.getString("CC05"); // Clasif 5
                    fila[12] = rs.getString("CC06"); // Clasif 6
                    fila[13] = rs.getString("CC");   // Centro de cuenta
                    fila[14] = rs.getString("AUX");  // Subcuenta
                    fila[15] = rs.getString("USER");
                    fila[16] = rs.getString("FEAC");
                    fila[17] = rs.getString("HOAC");

                    modelo.addRow(fila);
                }
                rs.close(); ps.close(); db.Cerrar();
                
                // ¡Llamamos a la magia para ajustar los anchos!
                adaptarTamañoColumnas();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar el Catálogo de Cuentas: " + e.getMessage());
        }
    }

    // --- MÉTODO PARA AUTO-AJUSTAR ANCHO DE COLUMNAS ---
    private void adaptarTamañoColumnas() {
        tblCCuentas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); // Apagamos el ajuste automático por defecto
        
        for (int i = 0; i < tblCCuentas.getColumnCount(); i++) {
            javax.swing.table.TableColumn columna = tblCCuentas.getColumnModel().getColumn(i);
            int anchoPreferido = 50; // Ancho mínimo
            
            // Evaluamos el ancho del título de la columna
            java.awt.Component compCabecera = tblCCuentas.getTableHeader().getDefaultRenderer()
                    .getTableCellRendererComponent(tblCCuentas, columna.getHeaderValue(), false, false, 0, i);
            anchoPreferido = Math.max(anchoPreferido, compCabecera.getPreferredSize().width + 10);
            
            // Evaluamos el ancho del contenido de cada fila
            for (int r = 0; r < tblCCuentas.getRowCount(); r++) {
                javax.swing.table.TableCellRenderer renderizador = tblCCuentas.getCellRenderer(r, i);
                java.awt.Component c = tblCCuentas.prepareRenderer(renderizador, r, i);
                anchoPreferido = Math.max(anchoPreferido, c.getPreferredSize().width + 15); // +15 de margen visual
            }
            
            columna.setPreferredWidth(anchoPreferido); // Aplicamos el ancho perfecto
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddCCuentas = new javax.swing.JButton();
        btnEditCCuentas = new javax.swing.JButton();
        btnDeleteCCuentas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCCuentas = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAddCCuentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCCuentas.setForeground(new java.awt.Color(26, 61, 99));
        btnAddCCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddCCuentas.setText("Añadir");
        btnAddCCuentas.addActionListener(this::btnAddCCuentasActionPerformed);

        btnEditCCuentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditCCuentas.setForeground(new java.awt.Color(26, 61, 99));
        btnEditCCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditCCuentas.setText("Editar");
        btnEditCCuentas.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditCCuentas.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditCCuentas.addActionListener(this::btnEditCCuentasActionPerformed);

        btnDeleteCCuentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteCCuentas.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteCCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteCCuentas.setText("Eliminar");
        btnDeleteCCuentas.addActionListener(this::btnDeleteCCuentasActionPerformed);

        tblCCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Compañia", "Cuenta", "Descripcion", "Nivel", "Tipo", "SubTipo", "MayDet", "Clasif. 1", "Clasif. 2", "Clasif. 3", "Clasif. 4", "Clasif. 5", "Clasif. 6", "Centro de Cuenta", "SubCuenta", "Usuario", "Fecha Mod.", "Hora Mod."
            }
        ));
        jScrollPane1.setViewportView(tblCCuentas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddCCuentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCCuentas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCCuentasActionPerformed
   mostrarDialogoCuenta(false);
    }//GEN-LAST:event_btnAddCCuentasActionPerformed

    private void btnEditCCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCCuentasActionPerformed
       if (tblCCuentas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una cuenta de la tabla para editar.");
            return;
        }
        mostrarDialogoCuenta(true);
    }//GEN-LAST:event_btnEditCCuentasActionPerformed

    private void btnDeleteCCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCCuentasActionPerformed
       int fila = tblCCuentas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una cuenta para eliminar.");
            return;
        }

        String cia = tblCCuentas.getValueAt(fila, 0).toString();
        String ccta = tblCCuentas.getValueAt(fila, 1).toString();
        String desc = tblCCuentas.getValueAt(fila, 2).toString();
        
        int resp = JOptionPane.showConfirmDialog(this, 
            "¿Seguro que deseas eliminar la cuenta:\n" + ccta + " - " + desc + "?", 
            "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    String sql = "DELETE FROM tmctas WHERE CIA = ? AND CCTA = ?";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, cia);
                    ps.setString(2, ccta);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Cuenta contable eliminada correctamente.");
                        cargarTablaCuentas(); 
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró la cuenta para eliminar.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteCCuentasActionPerformed

private void mostrarDialogoCuenta(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Cuenta" : "Agregar Cuenta";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(560, 520);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. PANEL SUPERIOR ---
        JPanel pnlTop = new JPanel(null);
        pnlTop.setBorder(BorderFactory.createEtchedBorder());
        pnlTop.setBounds(10, 10, 525, 170);

        JLabel lblCve = new JLabel("Cve. Cuenta");
        lblCve.setBounds(20, 15, 80, 25);
        JTextField txtCve = new JTextField();
        txtCve.setBounds(120, 15, 80, 25);
        txtCve.setEditable(false); // Generalmente es autogenerado por la BD (ICTA)

        JLabel lblCia = new JLabel("Compañía");
        lblCia.setBounds(20, 45, 80, 25);
        JComboBox<String> cmbCia = new JComboBox<>(new String[]{"12", "13"});
        cmbCia.setBounds(120, 45, 60, 25);

        JLabel lblEstructura = new JLabel("Centro Costo             Cuenta                SubCuenta");
        lblEstructura.setBounds(120, 70, 300, 20);
        
        JLabel lblCuenta = new JLabel("Cuenta");
        lblCuenta.setBounds(20, 90, 80, 25);
        JComboBox<String> cmbCC = new JComboBox<>(new String[]{"12", "13"});
        cmbCC.setBounds(120, 90, 60, 25);
        JLabel lblGuion1 = new JLabel("-"); lblGuion1.setBounds(185, 90, 10, 25);
        JTextField txtCtaObj = new JTextField();
        txtCtaObj.setBounds(195, 90, 80, 25);
        JLabel lblGuion2 = new JLabel("-"); lblGuion2.setBounds(280, 90, 10, 25);
        JTextField txtSubCta = new JTextField("000");
        txtSubCta.setBounds(290, 90, 50, 25);

        // Bloqueamos llaves primarias en edición
        if (modoEdicion) {
            cmbCia.setEnabled(false);
            cmbCC.setEnabled(false);
            txtCtaObj.setEditable(false);
            txtSubCta.setEditable(false);
        }

        JLabel lblTCont = new JLabel("Tipo de Contab.");
        lblTCont.setBounds(20, 120, 100, 25);
        JComboBox<String> cmbTCont = new JComboBox<>(new String[]{"MN", "USD"});
        cmbTCont.setBounds(120, 120, 60, 25);

        JLabel lblDesc = new JLabel("Descripción");
        lblDesc.setBounds(20, 150, 80, 25);
        JTextField txtDesc = new JTextField();
        txtDesc.setBounds(120, 150, 380, 25);

        // Se hace un poco más grande el panel para que quepa la descripción
        pnlTop.setBounds(10, 10, 525, 190);
        lblDesc.setBounds(20, 150, 80, 25);
        txtDesc.setBounds(120, 150, 380, 25);

        pnlTop.add(lblCve); pnlTop.add(txtCve);
        pnlTop.add(lblCia); pnlTop.add(cmbCia);
        pnlTop.add(lblEstructura);
        pnlTop.add(lblCuenta); pnlTop.add(cmbCC); pnlTop.add(lblGuion1); pnlTop.add(txtCtaObj); pnlTop.add(lblGuion2); pnlTop.add(txtSubCta);
        pnlTop.add(lblTCont); pnlTop.add(cmbTCont);
        pnlTop.add(lblDesc); pnlTop.add(txtDesc);
        dialogo.add(pnlTop);

        // --- 2. PESTAÑAS (TABS) ---
        JTabbedPane pestanas = new JTabbedPane();
        pestanas.setBounds(10, 210, 525, 190);

        // >> Pestaña Niveles
        JPanel pnlNiveles = new JPanel(null);

        // Marco interno niveles
        JPanel pnlRadios = new JPanel(null);
        pnlRadios.setBounds(120, 10, 380, 70);
        pnlRadios.setBackground(new java.awt.Color(200, 200, 200)); // Simula el fondo gris de tu imagen

        JLabel lblNivel = new JLabel("Nivel");
        lblNivel.setBounds(20, 20, 50, 25);
        pnlNiveles.add(lblNivel);

        ButtonGroup bgNivel = new ButtonGroup();
        JRadioButton[] rNivel = new JRadioButton[9];
        int xPos = 10;
        for (int i = 0; i < 9; i++) {
            rNivel[i] = new JRadioButton(String.valueOf(i + 1));
            rNivel[i].setBounds(xPos, 10, 35, 20);
            rNivel[i].setOpaque(false);
            bgNivel.add(rNivel[i]);
            pnlRadios.add(rNivel[i]);
            xPos += 40;
        }
        rNivel[4].setSelected(true); // Default Nivel 5

        ButtonGroup bgMayDet = new ButtonGroup();
        JRadioButton rbMayor = new JRadioButton("Cuenta de Mayor");
        rbMayor.setBounds(30, 40, 130, 20); rbMayor.setOpaque(false);
        JRadioButton rbDetalle = new JRadioButton("Cuenta Detalle", true);
        rbDetalle.setBounds(200, 40, 130, 20); rbDetalle.setOpaque(false);
        bgMayDet.add(rbMayor); bgMayDet.add(rbDetalle);
        pnlRadios.add(rbMayor); pnlRadios.add(rbDetalle);

        pnlNiveles.add(pnlRadios);

        JLabel lblClasGen = new JLabel("Clasif. General");
        lblClasGen.setBounds(20, 95, 90, 25);
        JComboBox<String> cmbClasGen = new JComboBox<>(new String[]{"100 Activo", "200 Pasivo", "300 Capital"});
        cmbClasGen.setBounds(120, 95, 120, 25);

        JLabel lblClasDet = new JLabel("Clasif. Detallada");
        lblClasDet.setBounds(20, 125, 90, 25);
        JComboBox<String> cmbClasDet = new JComboBox<>(new String[]{"010", "020", "030", "040"});
        cmbClasDet.setBounds(120, 125, 120, 25);

        pnlNiveles.add(lblClasGen); pnlNiveles.add(cmbClasGen);
        pnlNiveles.add(lblClasDet); pnlNiveles.add(cmbClasDet);

        pestanas.addTab("Niveles", pnlNiveles);
        pestanas.addTab("Fiscal", new JPanel());
        pestanas.addTab("Clasificaciones I", new JPanel());
        pestanas.addTab("Clasificaciones II", new JPanel());
        dialogo.add(pestanas);

        // --- 3. BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(150, 420, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(280, 420, 100, 40);

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        // --- 4. SI ES EDICIÓN, LLENAMOS LOS DATOS ---
        // Guardaremos la CCTA original para poder hacer el UPDATE en caso de que cambien algo
        final String cctaOriginal; 
        
        if (modoEdicion) {
            int fila = tblCCuentas.getSelectedRow();
            
            String cia = tblCCuentas.getValueAt(fila, 0) != null ? tblCCuentas.getValueAt(fila, 0).toString() : "";
            cctaOriginal = tblCCuentas.getValueAt(fila, 1) != null ? tblCCuentas.getValueAt(fila, 1).toString() : ""; // 12-1040101-000
            
            cmbCia.setSelectedItem(cia);
            txtDesc.setText(tblCCuentas.getValueAt(fila, 2) != null ? tblCCuentas.getValueAt(fila, 2).toString() : "");
            
            // Nivel
            String nivelStr = tblCCuentas.getValueAt(fila, 3) != null ? tblCCuentas.getValueAt(fila, 3).toString() : "5";
            try {
                int n = Integer.parseInt(nivelStr);
                if (n >= 1 && n <= 9) rNivel[n - 1].setSelected(true);
            } catch (Exception e) {}

            // Clasificaciones
            cmbClasGen.setSelectedItem(tblCCuentas.getValueAt(fila, 4) != null ? tblCCuentas.getValueAt(fila, 4).toString() : "");
            cmbClasDet.setSelectedItem(tblCCuentas.getValueAt(fila, 5) != null ? tblCCuentas.getValueAt(fila, 5).toString() : "");
            
            // Mayor/Detalle
            String mayDet = tblCCuentas.getValueAt(fila, 6) != null ? tblCCuentas.getValueAt(fila, 6).toString() : "D";
            if (mayDet.equalsIgnoreCase("M")) rbMayor.setSelected(true);
            else rbDetalle.setSelected(true);

            // Centros y cuentas
            cmbCC.setSelectedItem(tblCCuentas.getValueAt(fila, 7) != null ? tblCCuentas.getValueAt(fila, 7).toString() : "");
            txtSubCta.setText(tblCCuentas.getValueAt(fila, 8) != null ? tblCCuentas.getValueAt(fila, 8).toString() : "000");

            // Extraemos CTAOBJ de CCTA (Ej. "12-1040101-000" -> "1040101")
            String[] partesCcta = cctaOriginal.split("-");
            if (partesCcta.length >= 2) {
                txtCtaObj.setText(partesCcta[1]);
            }
        } else {
            cctaOriginal = "";
        }

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnAceptar.addActionListener(e -> {
            String cia = cmbCia.getSelectedItem().toString();
            String cc = cmbCC.getSelectedItem().toString();
            String ctaObj = txtCtaObj.getText().trim();
            String subCta = txtSubCta.getText().trim();
            String desc = txtDesc.getText().trim();
            String tCont = cmbTCont.getSelectedItem().toString();
            
            String clasGen = cmbClasGen.getSelectedItem() != null ? cmbClasGen.getSelectedItem().toString() : "";
            String clasDet = cmbClasDet.getSelectedItem() != null ? cmbClasDet.getSelectedItem().toString() : "";
            String mayDet = rbMayor.isSelected() ? "M" : "D";
            
            String nivel = "1";
            for (int i = 0; i < 9; i++) {
                if (rNivel[i].isSelected()) {
                    nivel = String.valueOf(i + 1);
                    break;
                }
            }

            if (ctaObj.isEmpty() || desc.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "La cuenta y la descripción son obligatorias.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Armamos los strings combinados que requiere la BD
            String cctaGenerada = cia + "-" + ctaObj + "-" + subCta;
            String objAuxGenerado = ctaObj + "-" + subCta;

           try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps;
                    
                    if (modoEdicion) {
                        // En UPDATE solo actualizamos los que sabemos que pudieron cambiar
                        String sql = "UPDATE tmctas SET CDES=?, CNIV=?, TCONT=?, TCTA=?, STIP=?, CMAY=?, CC=?, CTAOBJ=?, AUX=?, OBJAUX=? WHERE CIA=? AND CCTA=?";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, desc);
                        ps.setString(2, nivel);
                        ps.setString(3, tCont);
                        ps.setString(4, clasGen);
                        ps.setString(5, clasDet);
                        ps.setString(6, mayDet);
                        ps.setString(7, cc);
                        ps.setString(8, ctaObj);
                        ps.setString(9, subCta);
                        ps.setString(10, objAuxGenerado);
                        ps.setString(11, cia);
                        ps.setString(12, cctaOriginal); 
                    } else {
                        // INSERT Mapeando ABSOLUTAMENTE TODAS las columnas de tu BD
                        String sql = "INSERT INTO tmctas ("
                                + "CIA, CCTA, CDES, CNIV, TCONT, TCTA, STIP, CMAY, CC, CTAOBJ, AUX, OBJAUX, "
                                + "ICTA, NATCTA, CODAGR, CC01, CC02, CC03, CC04, CC05, CC06, CC07, CC08, CC09, CC10, CTAEXP"
                                + ") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, cia);
                        ps.setString(2, cctaGenerada);
                        ps.setString(3, desc);
                        ps.setString(4, nivel);
                        ps.setString(5, tCont);
                        ps.setString(6, clasGen);
                        ps.setString(7, clasDet);
                        ps.setString(8, mayDet);
                        ps.setString(9, cc);
                        ps.setString(10, ctaObj);
                        ps.setString(11, subCta);
                        ps.setString(12, objAuxGenerado);
                        // Los demás ya están definidos como NULL directo en el string de SQL
                    }

                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(dialogo, "Cuenta contable guardada con éxito.");
                        dialogo.dispose();
                        cargarTablaCuentas(); 
                    } else {
                        JOptionPane.showMessageDialog(dialogo, "No se pudo guardar la información.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialogo, "Error SQL: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCCuentas;
    private javax.swing.JButton btnDeleteCCuentas;
    private javax.swing.JButton btnEditCCuentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCCuentas;
    // End of variables declaration//GEN-END:variables
}
