/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Catalogo_Empleados extends javax.swing.JPanel {

    /**
     * Creates new form Catalogo_Empleados
     */
    public Catalogo_Empleados() {
        initComponents();
        cargarTablaEmpleados();
    }
    
   private void cargarTablaEmpleados() {
        DefaultTableModel modelo = (DefaultTableModel) tblEmpleados.getModel();
        modelo.setRowCount(0); // Limpia la tabla antes de cargar nuevos datos

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                // ATENCIÓN: Cambia 'tu_tabla_empleados' por el nombre real de tu tabla (ej. tgem, empleados, etc.)
                String sql = "SELECT NEMP, NOME, TEL, CD, EDO, CIA, CC, USER, FEAC, HOAC FROM tgemp";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[10]; 
                    fila[0] = rs.getString("NEMP");
                    fila[1] = rs.getString("NOME");
                    fila[2] = rs.getString("TEL");
                    fila[3] = rs.getString("CD");
                    fila[4] = rs.getString("EDO");
                    fila[5] = rs.getString("CIA");
                    fila[6] = rs.getString("CC");
                    fila[7] = rs.getString("USER"); 
                    fila[8] = rs.getString("FEAC"); 
                    fila[9] = rs.getString("HOAC"); 

                    modelo.addRow(fila);
                }
                rs.close(); 
                ps.close(); 
                db.Cerrar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla de Empleados: " + e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        btnAddEmpleados = new javax.swing.JButton();
        btnEditEmpleados = new javax.swing.JButton();
        btnDeleteEmpleados = new javax.swing.JButton();

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Nombre", "Telefono", "Ciudad", "Estado", "Compañia", "Centro", "Usuario", "Fecha Mod.", "Hora Mod."
            }
        ));
        tblEmpleados.setGridColor(new java.awt.Color(0, 0, 0));
        tblEmpleados.setShowGrid(true);
        jScrollPane1.setViewportView(tblEmpleados);

        btnAddEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddEmpleados.setForeground(new java.awt.Color(26, 61, 99));
        btnAddEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddEmpleados.setText("Añadir");
        btnAddEmpleados.addActionListener(this::btnAddEmpleadosActionPerformed);

        btnEditEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditEmpleados.setForeground(new java.awt.Color(26, 61, 99));
        btnEditEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditEmpleados.setText("Editar");
        btnEditEmpleados.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditEmpleados.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditEmpleados.addActionListener(this::btnEditEmpleadosActionPerformed);

        btnDeleteEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteEmpleados.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteEmpleados.setText("Eliminar");
        btnDeleteEmpleados.addActionListener(this::btnDeleteEmpleadosActionPerformed);

        javax.swing.GroupLayout pnlBgLayout = new javax.swing.GroupLayout(pnlBg);
        pnlBg.setLayout(pnlBgLayout);
        pnlBgLayout.setHorizontalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddEmpleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnDeleteEmpleados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBgLayout.setVerticalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpleadosActionPerformed
     mostrarDialogoEmpleado(false);
    }//GEN-LAST:event_btnAddEmpleadosActionPerformed

    private void btnDeleteEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmpleadosActionPerformed
    int fila = tblEmpleados.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un empleado para eliminar.");
            return;
        }

        String numEmp = tblEmpleados.getValueAt(fila, 0).toString();
        String nombre = tblEmpleados.getValueAt(fila, 1).toString();
        
        int resp = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar al empleado:\n" + nombre + "?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    // Consulta adaptada a tu tabla tgemp
                    String sql = "DELETE FROM tgemp WHERE NEMP = ?";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, numEmp);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Empleado eliminado correctamente.");
                        cargarTablaEmpleados(); // Refrescamos la tabla
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró el registro para eliminar.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteEmpleadosActionPerformed

    private void btnEditEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEmpleadosActionPerformed
        int fila = tblEmpleados.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un empleado para eliminar.");
            return;
        }

        String numEmp = tblEmpleados.getValueAt(fila, 0).toString();
        String nombre = tblEmpleados.getValueAt(fila, 1).toString();
        
        int resp = JOptionPane.showConfirmDialog(this, "¿Eliminar al empleado: " + nombre + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    // ATENCIÓN: Cambia 'tabla_empleados' por tu nombre real
                    String sql = "DELETE FROM tabla_empleados WHERE num_emp = ?";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, numEmp);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Empleado eliminado.");
                        cargarTablaEmpleados();
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEditEmpleadosActionPerformed

  private void mostrarDialogoEmpleado(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Empleado" : "Agregar Empleado";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(550, 580);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. SECCIÓN SUPERIOR ---
        JPanel pnlTop = new JPanel(null);
        pnlTop.setBorder(BorderFactory.createEtchedBorder());
        pnlTop.setBounds(15, 10, 365, 140);

        JLabel lblNumEmp = new JLabel("Núm. Emp.");
        lblNumEmp.setBounds(15, 10, 80, 20);
        JTextField txtNumEmp = new JTextField();
        txtNumEmp.setBounds(15, 30, 80, 25);
        if (modoEdicion) txtNumEmp.setEditable(false);

        JLabel lblRfcTop = new JLabel("R.F.C.");
        lblRfcTop.setBounds(110, 10, 80, 20);
        JTextField txtRfcTop = new JTextField();
        txtRfcTop.setBounds(110, 30, 200, 25);

        JLabel lblTratamiento = new JLabel("Tratamiento");
        lblTratamiento.setBounds(15, 65, 80, 25);
        JComboBox<String> cmbTratamiento = new JComboBox<>(new String[]{"", "Sr.", "Sra.", "Srita.", "Dr.", "Ing."});
        cmbTratamiento.setBounds(90, 65, 80, 25);

        JLabel lblNombre = new JLabel("Nombre");
        lblNombre.setBounds(15, 100, 60, 25); 
        JTextField txtNombre = new JTextField();
        txtNombre.setBounds(90, 100, 270, 25);
        
        pnlTop.add(lblNumEmp); pnlTop.add(txtNumEmp);
        pnlTop.add(lblRfcTop); pnlTop.add(txtRfcTop);
        pnlTop.add(lblTratamiento); pnlTop.add(cmbTratamiento);
        pnlTop.add(lblNombre); pnlTop.add(txtNombre);
        
        dialogo.add(pnlTop);

        JLabel lblFoto = new JLabel("Foto No Disponible", javax.swing.SwingConstants.CENTER);
        lblFoto.setBorder(BorderFactory.createLineBorder(java.awt.Color.GRAY));
        lblFoto.setBounds(390, 15, 90, 110);
        dialogo.add(lblFoto);

        // --- 2. PESTAÑAS (TABS) ---
        JTabbedPane pestanas = new JTabbedPane();
        pestanas.setBounds(15, 160, 500, 320);

        // >> Pestaña 1: Datos Generales
        JPanel pnlGenerales = new JPanel(null);

        JLabel lblCalle = new JLabel("Calle");
        lblCalle.setBounds(20, 20, 60, 25);
        JTextField txtCalle = new JTextField();
        txtCalle.setBounds(90, 20, 380, 25);

        JLabel lblColonia = new JLabel("Colonia");
        lblColonia.setBounds(20, 60, 60, 25);
        JTextField txtColonia = new JTextField();
        txtColonia.setBounds(90, 60, 380, 25);

        JLabel lblPob = new JLabel("Población");
        lblPob.setBounds(20, 100, 70, 25);
        JComboBox<String> cmbPob = new JComboBox<>(new String[]{"", "TEH", "PUE", "CDMX"}); // Agrega tus opciones de ciudad
        cmbPob.setBounds(90, 100, 70, 25);
        JTextField txtPobDesc = new JTextField();
        txtPobDesc.setBounds(170, 100, 150, 25);

        JLabel lblEdo = new JLabel("Estado");
        lblEdo.setBounds(20, 140, 70, 25);
        JComboBox<String> cmbEdo = new JComboBox<>(new String[]{"", "PUE", "VER", "MEX"}); // Agrega tus opciones de estado
        cmbEdo.setBounds(90, 140, 70, 25);
        JTextField txtEdoDesc = new JTextField();
        txtEdoDesc.setBounds(170, 140, 150, 25);

        JLabel lblPais = new JLabel("País");
        lblPais.setBounds(20, 180, 70, 25);
        JComboBox<String> cmbPais = new JComboBox<>(new String[]{"", "MEX", "USA"});
        cmbPais.setBounds(90, 180, 70, 25);
        JTextField txtPaisDesc = new JTextField();
        txtPaisDesc.setBounds(170, 180, 150, 25);

        JLabel lblCp = new JLabel("Código Postal");
        lblCp.setBounds(300, 220, 90, 25);
        JTextField txtCp = new JTextField();
        txtCp.setBounds(390, 220, 80, 25);

        JLabel lblImss = new JLabel("Núm IMSS");
        lblImss.setBounds(20, 250, 70, 25);
        JTextField txtImss = new JTextField();
        txtImss.setBounds(90, 250, 120, 25);

        JLabel lblCurp = new JLabel("C.U.R.P.");
        lblCurp.setBounds(230, 250, 50, 25);
        JTextField txtCurp = new JTextField();
        txtCurp.setBounds(280, 250, 190, 25);

        JLabel lblTel = new JLabel("Teléfono");
        lblTel.setBounds(20, 280, 60, 25);
        JComboBox<String> cmbTelTipo = new JComboBox<>(new String[]{"PAR", "CEL"});
        cmbTelTipo.setBounds(90, 280, 60, 25);
        JTextField txtTel = new JTextField();
        txtTel.setBounds(160, 280, 310, 25);

        pnlGenerales.add(lblCalle); pnlGenerales.add(txtCalle);
        pnlGenerales.add(lblColonia); pnlGenerales.add(txtColonia);
        pnlGenerales.add(lblPob); pnlGenerales.add(cmbPob); pnlGenerales.add(txtPobDesc);
        pnlGenerales.add(lblEdo); pnlGenerales.add(cmbEdo); pnlGenerales.add(txtEdoDesc);
        pnlGenerales.add(lblPais); pnlGenerales.add(cmbPais); pnlGenerales.add(txtPaisDesc);
        pnlGenerales.add(lblCp); pnlGenerales.add(txtCp);
        pnlGenerales.add(lblImss); pnlGenerales.add(txtImss);
        pnlGenerales.add(lblCurp); pnlGenerales.add(txtCurp);
        pnlGenerales.add(lblTel); pnlGenerales.add(cmbTelTipo); pnlGenerales.add(txtTel);

        JPanel pnlAdicional = new JPanel(null);

        pestanas.addTab("Datos Generales", pnlGenerales);
        pestanas.addTab("Información Adicional", pnlAdicional);
        dialogo.add(pestanas);

        // --- 3. BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(150, 490, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(280, 490, 100, 40);

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        // --- 4. CARGAR DATOS SI ES EDICIÓN ---
        if (modoEdicion) {
            int fila = tblEmpleados.getSelectedRow();
            // Evitamos errores de NullPointerException si la celda está vacía
            txtNumEmp.setText(tblEmpleados.getValueAt(fila, 0) != null ? tblEmpleados.getValueAt(fila, 0).toString() : "");
            txtNombre.setText(tblEmpleados.getValueAt(fila, 1) != null ? tblEmpleados.getValueAt(fila, 1).toString() : "");
            txtTel.setText(tblEmpleados.getValueAt(fila, 2) != null ? tblEmpleados.getValueAt(fila, 2).toString() : "");
            
            // Asignar combos basándose en el texto de la tabla
            String ciudad = tblEmpleados.getValueAt(fila, 3) != null ? tblEmpleados.getValueAt(fila, 3).toString() : "";
            cmbPob.setSelectedItem(ciudad);
            
            String estado = tblEmpleados.getValueAt(fila, 4) != null ? tblEmpleados.getValueAt(fila, 4).toString() : "";
            cmbEdo.setSelectedItem(estado);
        }

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnAceptar.addActionListener(e -> {
            String numEmp = txtNumEmp.getText().trim();
            String nombre = txtNombre.getText().trim();
            String telefono = txtTel.getText().trim();
            String ciudad = cmbPob.getSelectedItem() != null ? cmbPob.getSelectedItem().toString() : "";
            String estado = cmbEdo.getSelectedItem() != null ? cmbEdo.getSelectedItem().toString() : "";

            // Validación mínima
            if (numEmp.isEmpty() || nombre.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "El Número de Empleado y Nombre son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps;
                    
                    if (modoEdicion) {
                        // ACTUALIZAR (UPDATE)
                        String sql = "UPDATE tgemp SET NOME = ?, TEL = ?, CD = ?, EDO = ? WHERE NEMP = ?";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, nombre);
                        ps.setString(2, telefono);
                        ps.setString(3, ciudad);
                        ps.setString(4, estado);
                        ps.setString(5, numEmp);
                    } else {
                        // NUEVO (INSERT)
                        String sql = "INSERT INTO tgemp (NEMP, NOME, TEL, CD, EDO) VALUES (?, ?, ?, ?, ?)";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, numEmp);
                        ps.setString(2, nombre);
                        ps.setString(3, telefono);
                        ps.setString(4, ciudad);
                        ps.setString(5, estado);
                    }

                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(dialogo, "Operación guardada con éxito.");
                        dialogo.dispose();
                        cargarTablaEmpleados(); // Refresca la tabla principal automáticamente
                    } else {
                        JOptionPane.showMessageDialog(dialogo, "No se pudo guardar la información.");
                    }
                    ps.close();
                    db.Cerrar();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialogo, "Error al guardar en base de datos: " + ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
            }
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmpleados;
    private javax.swing.JButton btnDeleteEmpleados;
    private javax.swing.JButton btnEditEmpleados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JTable tblEmpleados;
    // End of variables declaration//GEN-END:variables
}
