/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Catalogo_Tipo_Alumno extends javax.swing.JPanel {

    /**
     * Creates new form Catalogo_Tipo_Alumno
     */
    public Catalogo_Tipo_Alumno() {
        initComponents();
        cargarTablaTiposAlumno();
    }
private void cargarTablaTiposAlumno() {
        // 1. Arreglamos las columnas de la tabla por código para coincidir con la BD
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Compañía", "Tipo Alumno", "Descripción", "C. Costo", "Cuenta", "Usuario", "Fec Ult Act", "Hora Ult Act"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblCTAlumno.setModel(modelo);

        // 2. Cargamos los datos reales de tesalutp
        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                String sql = "SELECT CIA, TALU, DES, CC, CTA, USER, FEAC, HOAC FROM tesalutp";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[8]; 
                    fila[0] = rs.getString("CIA");
                    fila[1] = rs.getString("TALU");
                    fila[2] = rs.getString("DES");
                    fila[3] = rs.getString("CC");
                    fila[4] = rs.getString("CTA");
                    fila[5] = rs.getString("USER");
                    fila[6] = rs.getString("FEAC");
                    fila[7] = rs.getString("HOAC");
                    modelo.addRow(fila);
                }
                rs.close(); ps.close(); db.Cerrar();
                
                adaptarTamañoColumnas();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla de Tipos de Alumno: " + e.getMessage());
        }
    }

    // --- MÉTODO PARA AUTO-AJUSTAR ANCHO DE COLUMNAS ---
    private void adaptarTamañoColumnas() {
        tblCTAlumno.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        
        for (int i = 0; i < tblCTAlumno.getColumnCount(); i++) {
            javax.swing.table.TableColumn columna = tblCTAlumno.getColumnModel().getColumn(i);
            int anchoPreferido = 50; 
            
            java.awt.Component compCabecera = tblCTAlumno.getTableHeader().getDefaultRenderer()
                    .getTableCellRendererComponent(tblCTAlumno, columna.getHeaderValue(), false, false, 0, i);
            anchoPreferido = Math.max(anchoPreferido, compCabecera.getPreferredSize().width + 10);
            
            for (int r = 0; r < tblCTAlumno.getRowCount(); r++) {
                javax.swing.table.TableCellRenderer renderizador = tblCTAlumno.getCellRenderer(r, i);
                java.awt.Component c = tblCTAlumno.prepareRenderer(renderizador, r, i);
                anchoPreferido = Math.max(anchoPreferido, c.getPreferredSize().width + 15); 
            }
            columna.setPreferredWidth(anchoPreferido); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCTAlumno = new javax.swing.JTable();
        btnAddTAlumno = new javax.swing.JButton();
        btnEditTAlumno = new javax.swing.JButton();
        btnDeleteTAlumno = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblCTAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Compañia", "Tipo Alumno", "Descripcion", "C. Costo", "Cuenta", "Usuario", "Fec. Ult. Act.", "Hora. Ult. Act"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCTAlumno);

        btnAddTAlumno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddTAlumno.setForeground(new java.awt.Color(26, 61, 99));
        btnAddTAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddTAlumno.setText("Añadir");
        btnAddTAlumno.addActionListener(this::btnAddTAlumnoActionPerformed);

        btnEditTAlumno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditTAlumno.setForeground(new java.awt.Color(26, 61, 99));
        btnEditTAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditTAlumno.setText("Editar");
        btnEditTAlumno.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditTAlumno.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditTAlumno.addActionListener(this::btnEditTAlumnoActionPerformed);

        btnDeleteTAlumno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteTAlumno.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteTAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteTAlumno.setText("Eliminar");
        btnDeleteTAlumno.addActionListener(this::btnDeleteTAlumnoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddTAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditTAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteTAlumno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditTAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteTAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTAlumnoActionPerformed
        mostrarDialogoTipoAlumno(false);
    }//GEN-LAST:event_btnAddTAlumnoActionPerformed

    private void btnEditTAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTAlumnoActionPerformed
if (tblCTAlumno.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un tipo de alumno para editar.");
            return;
        }
        mostrarDialogoTipoAlumno(true);
    }//GEN-LAST:event_btnEditTAlumnoActionPerformed

    private void btnDeleteTAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTAlumnoActionPerformed
      int fila = tblCTAlumno.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un tipo de alumno para eliminar.");
            return;
        }

        String cia = tblCTAlumno.getValueAt(fila, 0).toString();
        String tipoAlumno = tblCTAlumno.getValueAt(fila, 1).toString();
        String desc = tblCTAlumno.getValueAt(fila, 2).toString();
        
        int resp = JOptionPane.showConfirmDialog(this, "¿Eliminar el tipo de alumno: " + desc + "?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    // Eliminamos usando las 2 llaves primarias
                    String sql = "DELETE FROM tesalutp WHERE CIA = ? AND TALU = ?";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, cia);
                    ps.setString(2, tipoAlumno);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Tipo de alumno eliminado correctamente.");
                        cargarTablaTiposAlumno();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró el registro para eliminar.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteTAlumnoActionPerformed

  private void mostrarDialogoTipoAlumno(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Tipo de Alumno" : "Agregar Tipo de Alumno";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(480, 320);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- CLASE LOCAL PARA REUTILIZAR EL BUSCADOR FLOTANTE ---
        class BuscadorFlotante {
            void configurar(JTextField txtClave, JTextField txtDesc, JButton boton, Object[][] datos) {
                String[] columnas = {"Clave", "Descripción"};
                Runnable mostrarPopup = () -> {
                    javax.swing.JPopupMenu popup = new javax.swing.JPopupMenu();
                    popup.setFocusable(false);
                    javax.swing.table.DefaultTableModel mod = new javax.swing.table.DefaultTableModel(datos, columnas) {
                        @Override public boolean isCellEditable(int r, int c) { return false; }
                    };
                    javax.swing.JTable tabla = new javax.swing.JTable(mod);
                    tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                    tabla.getColumnModel().getColumn(0).setPreferredWidth(100);
                    tabla.getColumnModel().getColumn(1).setPreferredWidth(250);

                    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(mod);
                    tabla.setRowSorter(sorter);

                    tabla.addMouseListener(new java.awt.event.MouseAdapter() {
                        @Override
                        public void mouseReleased(java.awt.event.MouseEvent me) {
                            int viewRow = tabla.getSelectedRow();
                            if (viewRow != -1) {
                                int modelRow = tabla.convertRowIndexToModel(viewRow);
                                txtClave.setText(mod.getValueAt(modelRow, 0).toString());
                                if (txtDesc != null) {
                                    txtDesc.setText(mod.getValueAt(modelRow, 1).toString());
                                }
                                popup.setVisible(false);
                            }
                        }
                    });
                    javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(tabla);
                    scroll.setPreferredSize(new java.awt.Dimension(350, 150));
                    popup.add(scroll);

                    String texto = txtClave.getText().trim();
                    if (!texto.isEmpty()) sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto));
                    popup.show(txtClave, 0, txtClave.getHeight());
                    txtClave.requestFocus();
                };

                boton.addActionListener(e -> { txtClave.setText(""); mostrarPopup.run(); });
                txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
                    @Override
                    public void keyReleased(java.awt.event.KeyEvent e) {
                        int c = e.getKeyCode();
                        if (c == 27 || c == 10 || c == 38 || c == 40 || c == 37 || c == 39 || c == 9) return;
                        mostrarPopup.run();
                    }
                });
            }
        }
        BuscadorFlotante buscador = new BuscadorFlotante();

        // --- CARGA DE DATOS PARA LOS BUSCADORES ---
        java.util.function.Function<String, Object[][]> cargarDatos = (query) -> {
            java.util.List<Object[]> lista = new java.util.ArrayList<>();
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps = con.prepareStatement(query);
                    ResultSet rs = ps.executeQuery();
                    while(rs.next()) lista.add(new Object[]{rs.getString(1), rs.getString(2)});
                    rs.close(); ps.close(); db.Cerrar();
                }
            } catch(Exception e) {}
            return lista.toArray(new Object[0][0]);
        };

        Object[][] dCC = cargarDatos.apply("SELECT CVE, DES1 FROM tgcc ORDER BY CVE");
        Object[][] dCta = cargarDatos.apply("SELECT CCTA, CDES FROM tmctas ORDER BY CCTA");

        // --- 1. SECCIÓN SUPERIOR ---
        JLabel lblCia = new JLabel("Compañía");
        lblCia.setBounds(20, 15, 80, 25);
        JComboBox<String> cmbCia = new JComboBox<>();
        cmbCia.setBounds(90, 15, 60, 25);
        JLabel lblCiaDesc = new JLabel();
        lblCiaDesc.setBounds(160, 15, 250, 25);

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();
            if (con != null) {
                ResultSet rs = con.prepareStatement("SELECT CIA, NCIA FROM tmcias").executeQuery();
                while(rs.next()){ 
                    cmbCia.addItem(rs.getString("CIA")); 
                    lblCiaDesc.setText(rs.getString("NCIA")); 
                }
                rs.close(); db.Cerrar();
            }
        } catch (Exception ex) {}

        dialogo.add(lblCia); dialogo.add(cmbCia); dialogo.add(lblCiaDesc);

        // --- 2. MARCO CENTRAL ---
        JPanel pnlCentral = new JPanel(null);
        pnlCentral.setBorder(BorderFactory.createEtchedBorder());
        pnlCentral.setBounds(15, 55, 435, 145);

        JLabel lblTipo = new JLabel("Tipo de Alumno");
        lblTipo.setBounds(15, 15, 100, 25);
        JTextField txtTipo = new JTextField();
        txtTipo.setBounds(120, 15, 80, 25);

        JLabel lblDesc = new JLabel("Descripción");
        lblDesc.setBounds(15, 50, 100, 25);
        JTextField txtDesc = new JTextField();
        txtDesc.setBounds(120, 50, 300, 25);

        // Buscador Centro de Costo
        JLabel lblTitCC = new JLabel("Centro de Costo");
        lblTitCC.setBounds(15, 85, 100, 20);
        JTextField txtCC = new JTextField();
        txtCC.setBounds(15, 105, 60, 25);
        JButton btnCC = new JButton("▼");
        btnCC.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10));
        btnCC.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCC.setBounds(75, 105, 20, 25);
        buscador.configurar(txtCC, null, btnCC, dCC);

        // Buscador Cuenta Contable
        JLabel lblTitCta = new JLabel("Cuenta Contable");
        lblTitCta.setBounds(150, 85, 120, 20);
        JTextField txtCta = new JTextField();
        txtCta.setBounds(150, 105, 110, 25);
        JButton btnCta = new JButton("▼");
        btnCta.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10));
        btnCta.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCta.setBounds(260, 105, 20, 25);
        buscador.configurar(txtCta, null, btnCta, dCta);

        if (modoEdicion) {
            cmbCia.setEnabled(false);
            txtTipo.setEditable(false); // Llave primaria bloqueada
        }

        pnlCentral.add(lblTipo); pnlCentral.add(txtTipo);
        pnlCentral.add(lblDesc); pnlCentral.add(txtDesc);
        pnlCentral.add(lblTitCC); pnlCentral.add(txtCC); pnlCentral.add(btnCC);
        pnlCentral.add(lblTitCta); pnlCentral.add(txtCta); pnlCentral.add(btnCta);

        dialogo.add(pnlCentral);

        // --- 3. BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(120, 220, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(240, 220, 100, 40);

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        // --- 4. SI ES MODO EDICIÓN, CARGAMOS LOS DATOS ---
        if (modoEdicion) {
            int fila = tblCTAlumno.getSelectedRow();
            String ciaSel = tblCTAlumno.getValueAt(fila, 0).toString();
            String tipoSel = tblCTAlumno.getValueAt(fila, 1).toString();
            
            cmbCia.setSelectedItem(ciaSel);
            txtTipo.setText(tipoSel);
            
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps = con.prepareStatement("SELECT DES, CC, CTA FROM tesalutp WHERE CIA=? AND TALU=?");
                    ps.setString(1, ciaSel);
                    ps.setString(2, tipoSel);
                    ResultSet rs = ps.executeQuery();
                    
                    if (rs.next()) {
                        txtDesc.setText(rs.getString("DES") != null ? rs.getString("DES") : "");
                        txtCC.setText(rs.getString("CC") != null ? rs.getString("CC") : "");
                        txtCta.setText(rs.getString("CTA") != null ? rs.getString("CTA") : "");
                    }
                    rs.close(); ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                // Falla silenciosa en la carga
            }
        }

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnAceptar.addActionListener(e -> {
            String cia = cmbCia.getSelectedItem().toString();
            String tipo = txtTipo.getText().trim();
            String desc = txtDesc.getText().trim();
            String cc = txtCC.getText().trim();
            String cta = txtCta.getText().trim();
            
            if (tipo.isEmpty() || desc.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "El tipo de alumno y la descripción son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps;
                    if (modoEdicion) {
                        String sql = "UPDATE tesalutp SET DES=?, CC=?, CTA=? WHERE CIA=? AND TALU=?";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, desc);
                        ps.setString(2, cc);
                        ps.setString(3, cta);
                        ps.setString(4, cia);
                        ps.setString(5, tipo);
                    } else {
                        String sql = "INSERT INTO tesalutp (CIA, TALU, DES, CC, CTA) VALUES (?, ?, ?, ?, ?)";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, cia);
                        ps.setString(2, tipo);
                        ps.setString(3, desc);
                        ps.setString(4, cc);
                        ps.setString(5, cta);
                    }

                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(dialogo, "Tipo de Alumno guardado con éxito.");
                        dialogo.dispose();
                        cargarTablaTiposAlumno(); 
                    } else {
                        JOptionPane.showMessageDialog(dialogo, "No se pudo guardar la información.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialogo, "Error SQL: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTAlumno;
    private javax.swing.JButton btnDeleteTAlumno;
    private javax.swing.JButton btnEditTAlumno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCTAlumno;
    // End of variables declaration//GEN-END:variables
}
