/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Ciclos_Escolares extends javax.swing.JPanel {

    /**
     * Creates new form Ciclos_Escolares
     */
    public Ciclos_Escolares() {
        initComponents();
        cargarTablaCiclos();
    }
    private void cargarTablaCiclos() {
        DefaultTableModel modelo = (DefaultTableModel) tblCEscolar.getModel();
        modelo.setRowCount(0); 

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                // Consulta con los nombres reales de la tabla tescesc
                String sql = "SELECT CIA, CC, CESC, CDSC, FINI, FFIN, USER, FEAC, HOAC FROM tescesc";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[9]; 
                    fila[0] = rs.getString("CIA");
                    fila[1] = rs.getString("CC");
                    fila[2] = rs.getString("CESC");
                    fila[3] = rs.getString("CDSC");
                    fila[4] = rs.getString("FINI");
                    fila[5] = rs.getString("FFIN");
                    fila[6] = rs.getString("USER");
                    fila[7] = rs.getString("FEAC");
                    fila[8] = rs.getString("HOAC");

                    modelo.addRow(fila);
                }
                rs.close(); ps.close(); db.Cerrar();
                
                // ¡Llamamos a la magia para ajustar los anchos!
                adaptarTamañoColumnas();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla de Ciclos Escolares: " + e.getMessage());
        }
    }

    // --- MÉTODO PARA AUTO-AJUSTAR ANCHO DE COLUMNAS ---
    private void adaptarTamañoColumnas() {
        tblCEscolar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        
        for (int i = 0; i < tblCEscolar.getColumnCount(); i++) {
            javax.swing.table.TableColumn columna = tblCEscolar.getColumnModel().getColumn(i);
            int anchoPreferido = 50; 
            
            java.awt.Component compCabecera = tblCEscolar.getTableHeader().getDefaultRenderer()
                    .getTableCellRendererComponent(tblCEscolar, columna.getHeaderValue(), false, false, 0, i);
            anchoPreferido = Math.max(anchoPreferido, compCabecera.getPreferredSize().width + 10);
            
            for (int r = 0; r < tblCEscolar.getRowCount(); r++) {
                javax.swing.table.TableCellRenderer renderizador = tblCEscolar.getCellRenderer(r, i);
                java.awt.Component c = tblCEscolar.prepareRenderer(renderizador, r, i);
                anchoPreferido = Math.max(anchoPreferido, c.getPreferredSize().width + 15); 
            }
            
            columna.setPreferredWidth(anchoPreferido); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCEscolar = new javax.swing.JTable();
        btnAddCEscolar = new javax.swing.JButton();
        btnEditCEscolar = new javax.swing.JButton();
        btnDeleteCEscolar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblCEscolar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Compañia", "Centro Costos", "Ciclo Escolar", "Descripción", "Fech. Inicial", "Fech. Final", "Usuario", "Fech. Ult. Act", "Hora. Ult. Act"
            }
        ));
        jScrollPane1.setViewportView(tblCEscolar);

        btnAddCEscolar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCEscolar.setForeground(new java.awt.Color(26, 61, 99));
        btnAddCEscolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddCEscolar.setText("Añadir");
        btnAddCEscolar.addActionListener(this::btnAddCEscolarActionPerformed);

        btnEditCEscolar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditCEscolar.setForeground(new java.awt.Color(26, 61, 99));
        btnEditCEscolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditCEscolar.setText("Editar");
        btnEditCEscolar.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditCEscolar.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditCEscolar.addActionListener(this::btnEditCEscolarActionPerformed);

        btnDeleteCEscolar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteCEscolar.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteCEscolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteCEscolar.setText("Eliminar");
        btnDeleteCEscolar.addActionListener(this::btnDeleteCEscolarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddCEscolar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCEscolar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCEscolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCEscolarActionPerformed
       mostrarDialogoCiclo(false);
    }//GEN-LAST:event_btnAddCEscolarActionPerformed

    private void btnDeleteCEscolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCEscolarActionPerformed
      int fila = tblCEscolar.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un ciclo escolar para eliminar.");
            return;
        }

        String compania = tblCEscolar.getValueAt(fila, 0).toString();
        String cc = tblCEscolar.getValueAt(fila, 1).toString();
        String ciclo = tblCEscolar.getValueAt(fila, 2).toString();
        String desc = tblCEscolar.getValueAt(fila, 3).toString();
        
        int resp = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar el ciclo:\n" + desc + "?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    // Borramos utilizando las 3 llaves primarias
                    String sql = "DELETE FROM tescesc WHERE CIA = ? AND CC = ? AND CESC = ?";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, compania);
                    ps.setString(2, cc);
                    ps.setString(3, ciclo);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Ciclo escolar eliminado correctamente.");
                        cargarTablaCiclos(); // Refrescamos la tabla
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró el registro para eliminar.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteCEscolarActionPerformed

    private void btnEditCEscolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCEscolarActionPerformed
       if (tblCEscolar.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un ciclo escolar para editar.");
            return;
        }
        mostrarDialogoCiclo(true);
    }//GEN-LAST:event_btnEditCEscolarActionPerformed
private void mostrarDialogoCiclo(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Ciclo Escolar" : "Agregar Ciclo Escolar";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(550, 600);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. SECCIÓN SUPERIOR ---
        JLabel lblCia = new JLabel("Compañía");
        lblCia.setBounds(20, 15, 80, 25);
        JComboBox<String> cmbCia = new JComboBox<>(new String[]{"12", "13"});
        cmbCia.setBounds(110, 15, 60, 25);
        JLabel lblCiaDesc = new JLabel("UNIDAD ESCOLAR BENAVENTE, A.C.");
        lblCiaDesc.setBounds(180, 15, 250, 25);

        JLabel lblCC = new JLabel("Centro Costos");
        lblCC.setBounds(20, 45, 90, 25);
        JComboBox<String> cmbCC = new JComboBox<>(new String[]{"12100", "12200", "12300", "12400"}); // Opciones de tu BD
        cmbCC.setBounds(110, 45, 80, 25);
        JLabel lblCCDesc = new JLabel("UNIDAD ESCOLAR BENAVENTE");
        lblCCDesc.setBounds(200, 45, 250, 25);

        JLabel lblCiclo = new JLabel("Ciclo");
        lblCiclo.setBounds(20, 75, 80, 25);
        JTextField txtCiclo = new JTextField();
        txtCiclo.setBounds(110, 75, 80, 25);

        JLabel lblDesc = new JLabel("Descripción");
        lblDesc.setBounds(20, 105, 80, 25);
        JTextField txtDesc = new JTextField();
        txtDesc.setBounds(110, 105, 380, 25);

        // Bloqueamos llaves primarias en edición
        if (modoEdicion) {
            cmbCia.setEnabled(false);
            cmbCC.setEnabled(false);
            txtCiclo.setEditable(false); 
        }

        dialogo.add(lblCia); dialogo.add(cmbCia); dialogo.add(lblCiaDesc);
        dialogo.add(lblCC); dialogo.add(cmbCC); dialogo.add(lblCCDesc);
        dialogo.add(lblCiclo); dialogo.add(txtCiclo);
        dialogo.add(lblDesc); dialogo.add(txtDesc);

        // --- 2. PESTAÑAS Y MARCOS ---
        JTabbedPane pestanas = new JTabbedPane();
        pestanas.setBounds(15, 145, 500, 350);

        JPanel pnlGenerales = new JPanel(null);

        // >> Marco: Vigencia del Ciclo Escolar
        JPanel pnlVigencia = new JPanel(null);
        pnlVigencia.setBorder(BorderFactory.createTitledBorder("Vigencia del Ciclo Escolar"));
        pnlVigencia.setBounds(10, 10, 475, 90);

        JLabel lblFecIni = new JLabel("Fecha Inicial");
        lblFecIni.setBounds(120, 20, 80, 25);
        JTextField txtFecIni = new JTextField(); 
        txtFecIni.setBounds(200, 20, 80, 25);

        JLabel lblFecFin = new JLabel("Fecha Final");
        lblFecFin.setBounds(300, 20, 80, 25);
        JTextField txtFecFin = new JTextField();
        txtFecFin.setBounds(370, 20, 80, 25);

        JLabel lblRef = new JLabel("Código utilizado en Referencias Bancarias");
        lblRef.setBounds(20, 55, 250, 25);
        JTextField txtRef = new JTextField();
        txtRef.setBounds(270, 55, 80, 25);

        pnlVigencia.add(lblFecIni); pnlVigencia.add(txtFecIni);
        pnlVigencia.add(lblFecFin); pnlVigencia.add(txtFecFin);
        pnlVigencia.add(lblRef); pnlVigencia.add(txtRef);

        // >> Marco: Anualidad
        JPanel pnlAnualidad = new JPanel(null);
        pnlAnualidad.setBorder(BorderFactory.createTitledBorder("Anualidad"));
        pnlAnualidad.setBounds(10, 110, 475, 60);

        JLabel lblFecLim = new JLabel("Fecha Límite Anualidad");
        lblFecLim.setBounds(20, 20, 140, 25);
        JTextField txtFecLim = new JTextField();
        txtFecLim.setBounds(160, 20, 80, 25);

        JLabel lblDescAnu = new JLabel("% Descuento Anualidad");
        lblDescAnu.setBounds(260, 20, 140, 25);
        JTextField txtDescAnu = new JTextField("0");
        txtDescAnu.setBounds(400, 20, 50, 25);

        pnlAnualidad.add(lblFecLim); pnlAnualidad.add(txtFecLim);
        pnlAnualidad.add(lblDescAnu); pnlAnualidad.add(txtDescAnu);

        // >> Marco: Políticas del Ciclo Escolar
        JPanel pnlPoliticas = new JPanel(null);
        pnlPoliticas.setBorder(BorderFactory.createTitledBorder("Establece Políticas del Ciclo Escolar"));
        pnlPoliticas.setBounds(10, 180, 475, 60);
        JButton btnPol = new JButton("Políticas de Cobranza");
        btnPol.setBounds(300, 20, 160, 25);
        pnlPoliticas.add(btnPol);

        // >> Marco: Plan de Estudios
        JPanel pnlPlan = new JPanel(null);
        pnlPlan.setBorder(BorderFactory.createTitledBorder("Plan de Estudios"));
        pnlPlan.setBounds(10, 250, 475, 60);
        JButton btnPlan = new JButton("Plan de Estudios");
        btnPlan.setBounds(300, 20, 160, 25);
        pnlPlan.add(btnPlan);

        pnlGenerales.add(pnlVigencia); pnlGenerales.add(pnlAnualidad);
        pnlGenerales.add(pnlPoliticas); pnlGenerales.add(pnlPlan);

        pestanas.addTab("Datos Generales", pnlGenerales);
        pestanas.addTab("Incorporación", new JPanel()); // Pestaña vacía
        dialogo.add(pestanas);

        // --- 3. BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(150, 505, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(280, 505, 100, 40);

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        // --- 4. SI ES MODO EDICIÓN, CARGAMOS LOS DATOS ---
        if (modoEdicion) {
            int fila = tblCEscolar.getSelectedRow();
            String cia = tblCEscolar.getValueAt(fila, 0).toString();
            String cc = tblCEscolar.getValueAt(fila, 1).toString();
            String ciclo = tblCEscolar.getValueAt(fila, 2).toString();

            cmbCia.setSelectedItem(cia);
            cmbCC.setSelectedItem(cc);
            txtCiclo.setText(ciclo);
            txtDesc.setText(tblCEscolar.getValueAt(fila, 3) != null ? tblCEscolar.getValueAt(fila, 3).toString() : "");
            txtFecIni.setText(tblCEscolar.getValueAt(fila, 4) != null ? tblCEscolar.getValueAt(fila, 4).toString() : "");
            txtFecFin.setText(tblCEscolar.getValueAt(fila, 5) != null ? tblCEscolar.getValueAt(fila, 5).toString() : "");

            // Buscamos los datos extra directo en la BD
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps = con.prepareStatement("SELECT CODREF, FLIMA, PDSCA FROM tescesc WHERE CIA = ? AND CC = ? AND CESC = ?");
                    ps.setString(1, cia);
                    ps.setString(2, cc);
                    ps.setString(3, ciclo);
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()) {
                        txtRef.setText(rs.getString("CODREF") != null ? rs.getString("CODREF") : "");
                        txtFecLim.setText(rs.getString("FLIMA") != null ? rs.getString("FLIMA") : "");
                        txtDescAnu.setText(rs.getString("PDSCA") != null ? rs.getString("PDSCA") : "0");
                    }
                    rs.close(); ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                // Ignorar si no se pudieron cargar los datos adicionales
            }
        }

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnAceptar.addActionListener(e -> {
            String cia = cmbCia.getSelectedItem().toString();
            String cc = cmbCC.getSelectedItem().toString();
            String ciclo = txtCiclo.getText().trim();
            String desc = txtDesc.getText().trim();
            String fecIni = txtFecIni.getText().trim();
            String fecFin = txtFecFin.getText().trim();
            String ref = txtRef.getText().trim();
            String fecLim = txtFecLim.getText().trim();
            String descAnu = txtDescAnu.getText().trim().isEmpty() ? "0" : txtDescAnu.getText().trim();

            if (ciclo.isEmpty() || desc.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "El ciclo y la descripción son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps;
                    
                    if (modoEdicion) {
                        // UPDATE 
                        String sql = "UPDATE tescesc SET CDSC=?, FINI=?, FFIN=?, CODREF=?, FLIMA=?, PDSCA=? WHERE CIA=? AND CC=? AND CESC=?";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, desc);
                        ps.setString(2, fecIni);
                        ps.setString(3, fecFin);
                        ps.setString(4, ref);
                        ps.setString(5, fecLim);
                        ps.setString(6, descAnu);
                        ps.setString(7, cia);
                        ps.setString(8, cc);
                        ps.setString(9, ciclo);
                    } else {
                        // INSERT
                        String sql = "INSERT INTO tescesc (CIA, CC, CESC, CDSC, FINI, FFIN, CODREF, FLIMA, PDSCA) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, cia);
                        ps.setString(2, cc);
                        ps.setString(3, ciclo);
                        ps.setString(4, desc);
                        ps.setString(5, fecIni);
                        ps.setString(6, fecFin);
                        ps.setString(7, ref);
                        ps.setString(8, fecLim);
                        ps.setString(9, descAnu);
                    }

                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(dialogo, "Ciclo Escolar guardado con éxito.");
                        dialogo.dispose();
                        cargarTablaCiclos(); 
                    } else {
                        JOptionPane.showMessageDialog(dialogo, "No se pudo guardar la información.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialogo, "Error SQL: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCEscolar;
    private javax.swing.JButton btnDeleteCEscolar;
    private javax.swing.JButton btnEditCEscolar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCEscolar;
    // End of variables declaration//GEN-END:variables
}
