/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.Dashboard;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Ciclos_Escolares extends javax.swing.JPanel {
private String usuarioLogueado = "Admin";
    /**
     * Creates new form Ciclos_Escolares
     */
    public Ciclos_Escolares(String usuarioLogueado) {
        if (usuarioLogueado != null && !usuarioLogueado.trim().isEmpty()) {
            this.usuarioLogueado = usuarioLogueado.trim();
        }
        initComponents();
        cargarTablaCiclos();
    }
    
    public Ciclos_Escolares() {
        initComponents();
        cargarTablaCiclos();
    }
    
    private String obtenerUsuarioActivo() {
        if (this.usuarioLogueado != null && !this.usuarioLogueado.equals("Admin")) {
            return this.usuarioLogueado;
        }
        Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof Dashboard dash) {
            return dash.getUsuarioCodigo();
        }
        return this.usuarioLogueado;
    }
    private void cargarTablaCiclos() {
        DefaultTableModel modelo = (DefaultTableModel) tblCEscolar.getModel();
        modelo.setRowCount(0); 

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                // Consulta con los nombres reales de la tabla tescesc
                String sql = "SELECT CIA, CC, CESC, CDSC, FINI, FFIN, USER, FEAC, HOAC FROM tescesc";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[9]; 
                    fila[0] = rs.getString("CIA");
                    fila[1] = rs.getString("CC");
                    fila[2] = rs.getString("CESC");
                    fila[3] = rs.getString("CDSC");
                    fila[4] = rs.getString("FINI");
                    fila[5] = rs.getString("FFIN");
                    fila[6] = rs.getString("USER");
                    fila[7] = rs.getString("FEAC");
                    fila[8] = rs.getString("HOAC");

                    modelo.addRow(fila);
                }
                rs.close(); ps.close(); db.Cerrar();
                
                // ¡Llamamos a la magia para ajustar los anchos!
                adaptarTamañoColumnas();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla de Ciclos Escolares: " + e.getMessage());
        }
    }

    // --- MÉTODO PARA AUTO-AJUSTAR ANCHO DE COLUMNAS ---
    private void adaptarTamañoColumnas() {
        tblCEscolar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        
        for (int i = 0; i < tblCEscolar.getColumnCount(); i++) {
            javax.swing.table.TableColumn columna = tblCEscolar.getColumnModel().getColumn(i);
            int anchoPreferido = 50; 
            
            java.awt.Component compCabecera = tblCEscolar.getTableHeader().getDefaultRenderer()
                    .getTableCellRendererComponent(tblCEscolar, columna.getHeaderValue(), false, false, 0, i);
            anchoPreferido = Math.max(anchoPreferido, compCabecera.getPreferredSize().width + 10);
            
            for (int r = 0; r < tblCEscolar.getRowCount(); r++) {
                javax.swing.table.TableCellRenderer renderizador = tblCEscolar.getCellRenderer(r, i);
                java.awt.Component c = tblCEscolar.prepareRenderer(renderizador, r, i);
                anchoPreferido = Math.max(anchoPreferido, c.getPreferredSize().width + 15); 
            }
            
            columna.setPreferredWidth(anchoPreferido); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCEscolar = new javax.swing.JTable();
        btnAddCEscolar = new javax.swing.JButton();
        btnEditCEscolar = new javax.swing.JButton();
        btnDeleteCEscolar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblCEscolar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Compañia", "Centro Costos", "Ciclo Escolar", "Descripción", "Fech. Inicial", "Fech. Final", "Usuario", "Fech. Ult. Act", "Hora. Ult. Act"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCEscolar);

        btnAddCEscolar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCEscolar.setForeground(new java.awt.Color(26, 61, 99));
        btnAddCEscolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddCEscolar.setText("Añadir");
        btnAddCEscolar.addActionListener(this::btnAddCEscolarActionPerformed);

        btnEditCEscolar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditCEscolar.setForeground(new java.awt.Color(26, 61, 99));
        btnEditCEscolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditCEscolar.setText("Editar");
        btnEditCEscolar.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditCEscolar.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditCEscolar.addActionListener(this::btnEditCEscolarActionPerformed);

        btnDeleteCEscolar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteCEscolar.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteCEscolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteCEscolar.setText("Eliminar");
        btnDeleteCEscolar.addActionListener(this::btnDeleteCEscolarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddCEscolar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCEscolar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCEscolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCEscolarActionPerformed
       mostrarDialogoCiclo(false);
    }//GEN-LAST:event_btnAddCEscolarActionPerformed

    private void btnDeleteCEscolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCEscolarActionPerformed
      int fila = tblCEscolar.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un ciclo escolar para eliminar.");
            return;
        }

        String compania = tblCEscolar.getValueAt(fila, 0).toString();
        String cc = tblCEscolar.getValueAt(fila, 1).toString();
        String ciclo = tblCEscolar.getValueAt(fila, 2).toString();
        String desc = tblCEscolar.getValueAt(fila, 3).toString();
        
        int resp = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar el ciclo:\n" + desc + "?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    // Borramos utilizando las 3 llaves primarias
                    String sql = "DELETE FROM tescesc WHERE CIA = ? AND CC = ? AND CESC = ?";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, compania);
                    ps.setString(2, cc);
                    ps.setString(3, ciclo);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Ciclo escolar eliminado correctamente.");
                        cargarTablaCiclos(); // Refrescamos la tabla
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró el registro para eliminar.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteCEscolarActionPerformed

    private void btnEditCEscolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCEscolarActionPerformed
       if (tblCEscolar.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un ciclo escolar para editar.");
            return;
        }
        mostrarDialogoCiclo(true);
    }//GEN-LAST:event_btnEditCEscolarActionPerformed
private void mostrarDialogoCiclo(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Ciclo Escolar" : "Agregar Ciclo Escolar";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(550, 600);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. SECCIÓN SUPERIOR ---
        JLabel lblCia = new JLabel("Compañía");
        lblCia.setBounds(20, 15, 80, 25);
        JComboBox<String> cmbCia = new JComboBox<>(new String[]{"12", "13"});
        cmbCia.setBounds(110, 15, 60, 25);
        JLabel lblCiaDesc = new JLabel("UNIDAD ESCOLAR BENAVENTE, A.C.");
        lblCiaDesc.setBounds(180, 15, 250, 25);

        JLabel lblCC = new JLabel("Centro Costos");
        lblCC.setBounds(20, 45, 90, 25);
        JComboBox<String> cmbCC = new JComboBox<>(new String[]{"12100", "12200", "12300", "12400"});
        cmbCC.setBounds(110, 45, 80, 25);
        JLabel lblCCDesc = new JLabel("UNIDAD ESCOLAR BENAVENTE");
        lblCCDesc.setBounds(200, 45, 250, 25);

        JLabel lblCiclo = new JLabel("Ciclo");
        lblCiclo.setBounds(20, 75, 80, 25);
        JTextField txtCiclo = new JTextField();
        txtCiclo.setBounds(110, 75, 80, 25);

        JLabel lblDesc = new JLabel("Descripción");
        lblDesc.setBounds(20, 105, 80, 25);
        JTextField txtDesc = new JTextField();
        txtDesc.setBounds(110, 105, 380, 25);

        if (modoEdicion) {
            cmbCia.setEnabled(false);
            cmbCC.setEnabled(false);
            txtCiclo.setEditable(false); 
        }

        dialogo.add(lblCia); dialogo.add(cmbCia); dialogo.add(lblCiaDesc);
        dialogo.add(lblCC); dialogo.add(cmbCC); dialogo.add(lblCCDesc);
        dialogo.add(lblCiclo); dialogo.add(txtCiclo);
        dialogo.add(lblDesc); dialogo.add(txtDesc);

        // --- 2. PESTAÑAS Y MARCOS ---
        JTabbedPane pestanas = new JTabbedPane();
        pestanas.setBounds(15, 145, 500, 350);

        // ==========================================
        // >> PESTAÑA 1: DATOS GENERALES
        // ==========================================
        JPanel pnlGenerales = new JPanel(null);
// Sub-panel: Vigencia del Ciclo Escolar (ambos con JDateChooser)
        JPanel pnlVigencia = new JPanel(null);
        pnlVigencia.setBorder(BorderFactory.createTitledBorder("Vigencia del Ciclo Escolar"));
        pnlVigencia.setBounds(10, 10, 475, 90);

        pnlVigencia.add(new JLabel("Fecha Inicial")).setBounds(50, 20, 80, 25);
        com.toedter.calendar.JDateChooser txtFecIni = new com.toedter.calendar.JDateChooser();
        txtFecIni.setDateFormatString("dd/MM/yyyy");
        txtFecIni.setDate(new java.util.Date());
        txtFecIni.setBounds(130, 20, 110, 25);
        pnlVigencia.add(txtFecIni);

        pnlVigencia.add(new JLabel("Fecha Final")).setBounds(270, 20, 70, 25);
        com.toedter.calendar.JDateChooser txtFecFin = new com.toedter.calendar.JDateChooser();
        txtFecFin.setDateFormatString("dd/MM/yyyy");
        txtFecFin.setDate(new java.util.Date());
        txtFecFin.setBounds(350, 20, 110, 25);
        pnlVigencia.add(txtFecFin);

        pnlVigencia.add(new JLabel("Código utilizado en Referencias Bancarias")).setBounds(15, 55, 230, 25);
        JTextField txtRef = new JTextField();
        txtRef.setBounds(250, 55, 100, 25);
        pnlVigencia.add(txtRef);

        pnlGenerales.add(pnlVigencia);
      

        JPanel pnlAnualidad = new JPanel(null);
        pnlAnualidad.setBorder(BorderFactory.createTitledBorder("Anualidad"));
        pnlAnualidad.setBounds(10, 110, 475, 60);
        
        JLabel lblFecLim = new JLabel("Fecha Límite Anualidad"); lblFecLim.setBounds(15, 20, 130, 25);
        com.toedter.calendar.JDateChooser txtFecLim = new com.toedter.calendar.JDateChooser();
        txtFecLim.setDateFormatString("dd/MM/yyyy");
        txtFecLim.setDate(new java.util.Date());
        txtFecLim.setBounds(150, 20, 110, 25);

        JLabel lblDescAnu = new JLabel("% Descuento Anualidad"); lblDescAnu.setBounds(275, 20, 140, 25);
        JTextField txtDescAnu = new JTextField("0"); txtDescAnu.setBounds(415, 20, 50, 25);
        
        pnlAnualidad.add(lblFecLim); pnlAnualidad.add(txtFecLim);
        pnlAnualidad.add(lblDescAnu); pnlAnualidad.add(txtDescAnu);

        JPanel pnlPoliticas = new JPanel(null);
        pnlPoliticas.setBorder(BorderFactory.createTitledBorder("Establece Políticas del Ciclo Escolar"));
        pnlPoliticas.setBounds(10, 180, 475, 60);
        JButton btnPol = new JButton("Políticas de Cobranza"); btnPol.setBounds(300, 20, 160, 25);
        pnlPoliticas.add(btnPol);

        JPanel pnlPlan = new JPanel(null);
        pnlPlan.setBorder(BorderFactory.createTitledBorder("Plan de Estudios"));
        pnlPlan.setBounds(10, 250, 475, 60);
        JButton btnPlan = new JButton("Plan de Estudios"); btnPlan.setBounds(300, 20, 160, 25);
        pnlPlan.add(btnPlan);

        pnlGenerales.add(pnlVigencia); pnlGenerales.add(pnlAnualidad);
        pnlGenerales.add(pnlPoliticas); pnlGenerales.add(pnlPlan);

        // ==========================================
        // >> PESTAÑA 2: INCORPORACIÓN
        // ==========================================
        JPanel pnlIncorporacion = new JPanel(null);

        JPanel pnlDetallesInc = new JPanel(null);
        pnlDetallesInc.setBorder(BorderFactory.createTitledBorder("Detalles de Incorporación"));
        pnlDetallesInc.setBounds(10, 10, 475, 300);

        JLabel lblSecInc = new JLabel("Sec"); lblSecInc.setBounds(20, 20, 40, 20);
        JTextField txtSecInc = new JTextField(); txtSecInc.setBounds(20, 40, 40, 25);

        JLabel lblInc = new JLabel("Incorporación"); lblInc.setBounds(70, 20, 100, 20);
        JComboBox<String> cmbInc = new JComboBox<>(new String[]{"", "SEP", "UNAM", "UAP"}); 
        cmbInc.setBounds(70, 40, 100, 25);
        cmbInc.setEditable(true);

        JLabel lblFormatoInc = new JLabel("Formato"); lblFormatoInc.setBounds(180, 20, 100, 20);
        JTextField txtFormatoInc = new JTextField(); txtFormatoInc.setBounds(180, 40, 230, 25);

        JButton btnOkInc = new JButton("OK"); 
        btnOkInc.setBounds(415, 40, 50, 25);

        pnlDetallesInc.add(lblSecInc); pnlDetallesInc.add(txtSecInc);
        pnlDetallesInc.add(lblInc); pnlDetallesInc.add(cmbInc);
        pnlDetallesInc.add(lblFormatoInc); pnlDetallesInc.add(txtFormatoInc);
        pnlDetallesInc.add(btnOkInc);

        DefaultTableModel modInc = new DefaultTableModel(new Object[][]{}, new String[]{"Sec", "Incorporación", "Formato"});
        JTable tblInc = new JTable(modInc);
        JScrollPane scrollInc = new JScrollPane(tblInc);
        scrollInc.setBounds(20, 75, 445, 205);
        pnlDetallesInc.add(scrollInc);

        pnlIncorporacion.add(pnlDetallesInc);

        pestanas.addTab("Datos Generales", pnlGenerales);
        pestanas.addTab("Incorporación", pnlIncorporacion);
        dialogo.add(pestanas);

        // --- 3. BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(150, 505, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(280, 505, 100, 40);

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        // --- 4. SI ES MODO EDICIÓN, CARGAMOS LOS DATOS ---
        if (modoEdicion) {
            int fila = tblCEscolar.getSelectedRow();
            if (fila != -1) {
                String cia = tblCEscolar.getValueAt(fila, 0).toString();
                String cc = tblCEscolar.getValueAt(fila, 1).toString();
                String ciclo = tblCEscolar.getValueAt(fila, 2).toString();

                cmbCia.setSelectedItem(cia);
                cmbCC.setSelectedItem(cc);
                txtCiclo.setText(ciclo);
                txtDesc.setText(tblCEscolar.getValueAt(fila, 3) != null ? tblCEscolar.getValueAt(fila, 3).toString() : "");

                java.text.SimpleDateFormat sdfParser = new java.text.SimpleDateFormat("yyyy-MM-dd");

                try {
                    ConDB db = new ConDB();
                    Connection con = db.Conectar();
                    if (con != null) {
                        PreparedStatement ps = con.prepareStatement("SELECT FINI, FFIN, CODREF, FLIMA, PDSCA FROM tescesc WHERE CIA = ? AND CC = ? AND CESC = ?");
                        ps.setString(1, cia);
                        ps.setString(2, cc);
                        ps.setString(3, ciclo);
                        ResultSet rs = ps.executeQuery();
                        if (rs.next()) {
                            if (rs.getString("FINI") != null) txtFecIni.setDate(sdfParser.parse(rs.getString("FINI")));
                            if (rs.getString("FFIN") != null) txtFecFin.setDate(sdfParser.parse(rs.getString("FFIN")));
                            if (rs.getString("FLIMA") != null) txtFecLim.setDate(sdfParser.parse(rs.getString("FLIMA")));
                            txtRef.setText(rs.getString("CODREF") != null ? rs.getString("CODREF") : "");
                            txtDescAnu.setText(rs.getString("PDSCA") != null ? rs.getString("PDSCA") : "0");
                        }
                        rs.close(); ps.close(); db.Cerrar();
                    }
                } catch (Exception e) {}
            }
        }

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnOkInc.addActionListener(e -> {
            String sec = txtSecInc.getText().trim();
            String inc = cmbInc.getSelectedItem() != null ? cmbInc.getSelectedItem().toString() : "";
            String format = txtFormatoInc.getText().trim();

            if (!sec.isEmpty() && !inc.isEmpty()) {
                modInc.addRow(new Object[]{sec, inc, format});
                txtSecInc.setText("");
                txtFormatoInc.setText("");
                cmbInc.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(dialogo, "Ingresa al menos la Sec y la Incorporación.");
            }
        });

        btnAceptar.addActionListener(e -> {
            String cia = cmbCia.getSelectedItem().toString();
            String cc = cmbCC.getSelectedItem().toString();
            String ciclo = txtCiclo.getText().trim();
            String desc = txtDesc.getText().trim();

            java.text.SimpleDateFormat sdfSql = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String fecIni = txtFecIni.getDate() != null ? sdfSql.format(txtFecIni.getDate()) : sdfSql.format(new java.util.Date());
            String fecFin = txtFecFin.getDate() != null ? sdfSql.format(txtFecFin.getDate()) : sdfSql.format(new java.util.Date());
            String fecLim = txtFecLim.getDate() != null ? sdfSql.format(txtFecLim.getDate()) : sdfSql.format(new java.util.Date());

            String ref = txtRef.getText().trim();
            String descAnu = txtDescAnu.getText().trim().isEmpty() ? "0" : txtDescAnu.getText().trim();
            String usrActivo = obtenerUsuarioActivo();

            if (ciclo.isEmpty() || desc.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "El ciclo y la descripción son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps;
                    
                    if (modoEdicion) {
                        String sql = "UPDATE tescesc SET CDSC=?, FINI=?, FFIN=?, CODREF=?, FLIMA=?, PDSCA=?, USER=?, FEAC=CURDATE(), HOAC=DATE_FORMAT(NOW(), '%r') WHERE CIA=? AND CC=? AND CESC=?";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, desc); ps.setString(2, fecIni); ps.setString(3, fecFin);
                        ps.setString(4, ref); ps.setString(5, fecLim); ps.setString(6, descAnu);
                        ps.setString(7, usrActivo); ps.setString(8, cia); ps.setString(9, cc); ps.setString(10, ciclo);
                    } else {
                        String sql = "INSERT INTO tescesc (CIA, CC, CESC, CDSC, FINI, FFIN, CODREF, FLIMA, PDSCA, USER, FEAC, HOAC) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURDATE(), DATE_FORMAT(NOW(), '%r'))";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, cia); ps.setString(2, cc); ps.setString(3, ciclo);
                        ps.setString(4, desc); ps.setString(5, fecIni); ps.setString(6, fecFin);
                        ps.setString(7, ref); ps.setString(8, fecLim); ps.setString(9, descAnu);
                        ps.setString(10, usrActivo);
                    }

                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(dialogo, "Ciclo Escolar guardado con éxito.");
                        dialogo.dispose();
                        cargarTablaCiclos(); 
                    } else {
                        JOptionPane.showMessageDialog(dialogo, "No se pudo guardar la información.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialogo, "Error SQL: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCEscolar;
    private javax.swing.JButton btnDeleteCEscolar;
    private javax.swing.JButton btnEditCEscolar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCEscolar;
    // End of variables declaration//GEN-END:variables
}
