/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Color;
import java.awt.Font;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Clasificaciones extends javax.swing.JPanel {

    /**
     * Creates new form Clasificaciones
     */
    public Clasificaciones() {
        initComponents();
        cargarTablaClasificaciones();
    }
    
   private void cargarTablaClasificaciones() {
        DefaultTableModel modelo = (DefaultTableModel) tblClasificaciones.getModel();
        modelo.setRowCount(0); 

        try (Connection con = new ConDB().Conectar()) {
            if (con != null) {
                String sql = "SELECT TBL, DES, USER, FEAC, HOAC FROM tmclasge ORDER BY TBL ASC";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[5]; 
                    fila[0] = rs.getString("TBL");
                    fila[1] = rs.getString("DES");
                    fila[2] = rs.getString("USER") != null ? rs.getString("USER") : "";
                    fila[3] = rs.getString("FEAC") != null ? rs.getString("FEAC") : "";
                    fila[4] = rs.getString("HOAC") != null ? rs.getString("HOAC") : "";
                    modelo.addRow(fila);
                }
                rs.close(); 
                ps.close();
                adaptarTamañoColumnas();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla de Clasificaciones: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void adaptarTamañoColumnas() {
        tblClasificaciones.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        
        for (int i = 0; i < tblClasificaciones.getColumnCount(); i++) {
            javax.swing.table.TableColumn columna = tblClasificaciones.getColumnModel().getColumn(i);
            int anchoPreferido = 80; 
            
            java.awt.Component compCabecera = tblClasificaciones.getTableHeader().getDefaultRenderer()
                    .getTableCellRendererComponent(tblClasificaciones, columna.getHeaderValue(), false, false, 0, i);
            anchoPreferido = Math.max(anchoPreferido, compCabecera.getPreferredSize().width + 20);
            
            for (int r = 0; r < tblClasificaciones.getRowCount(); r++) {
                javax.swing.table.TableCellRenderer renderizador = tblClasificaciones.getCellRenderer(r, i);
                java.awt.Component c = tblClasificaciones.prepareRenderer(renderizador, r, i);
                anchoPreferido = Math.max(anchoPreferido, c.getPreferredSize().width + 20); 
            }
            
            columna.setPreferredWidth(anchoPreferido); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClasificaciones = new javax.swing.JTable();
        btnAddClasificaciones = new javax.swing.JButton();
        btnEditClasificaciones = new javax.swing.JButton();
        btnDeleteClasificaciones = new javax.swing.JButton();

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));

        tblClasificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tabla", "Descripcion", "Usuario", "Fecha. Ult. Act.", "Hora. Ult. Act."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClasificaciones.setGridColor(new java.awt.Color(0, 0, 0));
        tblClasificaciones.setShowGrid(true);
        jScrollPane1.setViewportView(tblClasificaciones);

        btnAddClasificaciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddClasificaciones.setForeground(new java.awt.Color(26, 61, 99));
        btnAddClasificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddClasificaciones.setText("Añadir");
        btnAddClasificaciones.addActionListener(this::btnAddClasificacionesActionPerformed);

        btnEditClasificaciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditClasificaciones.setForeground(new java.awt.Color(26, 61, 99));
        btnEditClasificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditClasificaciones.setText("Editar");
        btnEditClasificaciones.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditClasificaciones.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditClasificaciones.addActionListener(this::btnEditClasificacionesActionPerformed);

        btnDeleteClasificaciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteClasificaciones.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteClasificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteClasificaciones.setText("Eliminar");
        btnDeleteClasificaciones.addActionListener(this::btnDeleteClasificacionesActionPerformed);

        javax.swing.GroupLayout pnlBgLayout = new javax.swing.GroupLayout(pnlBg);
        pnlBg.setLayout(pnlBgLayout);
        pnlBgLayout.setHorizontalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddClasificaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditClasificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnDeleteClasificaciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBgLayout.setVerticalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddClasificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditClasificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteClasificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddClasificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClasificacionesActionPerformed
       mostrarDialogoClasificacion(false);
    }//GEN-LAST:event_btnAddClasificacionesActionPerformed

    private void btnDeleteClasificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteClasificacionesActionPerformed
       int fila = tblClasificaciones.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una clasificación para eliminar.");
            return;
        }

        String idTabla = tblClasificaciones.getValueAt(fila, 0).toString();
        int resp = JOptionPane.showConfirmDialog(this, "¿Eliminar clasificación " + idTabla + "?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps = con.prepareStatement("DELETE FROM tmclasge WHERE TBL = ?");
                    ps.setString(1, idTabla);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Clasificación eliminada correctamente.");
                        cargarTablaClasificaciones();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró el registro para eliminar.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteClasificacionesActionPerformed

    private void btnEditClasificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClasificacionesActionPerformed
    if (tblClasificaciones.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una clasificación para editar.");
            return;
        }
        mostrarDialogoClasificacion(true);
    }//GEN-LAST:event_btnEditClasificacionesActionPerformed

private void mostrarDialogoClasificacion(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Clasificación Maestra" : "Agregar Clasificación Maestra";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(480, 230);
        dialogo.setLayout(null);
        dialogo.getContentPane().setBackground(Color.WHITE);
        dialogo.setLocationRelativeTo(this);
        dialogo.setResizable(false);

        // --- PANEL DE CAPTURA DIRECTA ---
        JPanel pnlDatos = new JPanel(null);
        pnlDatos.setBackground(Color.WHITE);
        pnlDatos.setBorder(BorderFactory.createTitledBorder("Datos de la Tabla (tmclasge)"));
        pnlDatos.setBounds(15, 10, 435, 110);

        JLabel lblTabla = new JLabel("ID Tabla:");
        lblTabla.setFont(new Font("Segoe UI", Font.BOLD, 12));
        lblTabla.setBounds(20, 25, 80, 25);
        pnlDatos.add(lblTabla);

        JTextField txtTabla = new JTextField();
        txtTabla.setBounds(110, 25, 90, 25);
        pnlDatos.add(txtTabla);

        JLabel lblDesc = new JLabel("Descripción:");
        lblDesc.setFont(new Font("Segoe UI", Font.BOLD, 12));
        lblDesc.setBounds(20, 65, 80, 25);
        pnlDatos.add(lblDesc);

        JTextField txtDesc = new JTextField();
        txtDesc.setBounds(110, 65, 300, 25);
        pnlDatos.add(txtDesc);

        dialogo.add(pnlDatos);

        // --- BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(120, 135, 100, 35);
        btnAceptar.setFont(new Font("Segoe UI", Font.BOLD, 12));

        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(240, 135, 100, 35);
        btnSalir.setFont(new Font("Segoe UI", Font.PLAIN, 12));

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        if (modoEdicion) {
            txtTabla.setEditable(false);
            int fila = tblClasificaciones.getSelectedRow();
            txtTabla.setText(tblClasificaciones.getValueAt(fila, 0).toString());
            txtDesc.setText(tblClasificaciones.getValueAt(fila, 1).toString());
        }

        btnSalir.addActionListener(e -> dialogo.dispose());

        btnAceptar.addActionListener(e -> {
            String tabla = txtTabla.getText().trim().toUpperCase();
            String descripcion = txtDesc.getText().trim().toUpperCase();

            if (tabla.isEmpty() || descripcion.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "El ID de la Tabla y la Descripción son obligatorios.", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try (Connection con = new ConDB().Conectar()) {
                if (con != null) {
                    if (!modoEdicion) {
                        PreparedStatement psCheck = con.prepareStatement("SELECT 1 FROM tmclasge WHERE TBL = ?");
                        psCheck.setString(1, tabla);
                        ResultSet rsCheck = psCheck.executeQuery();
                        if (rsCheck.next()) {
                            JOptionPane.showMessageDialog(dialogo, "La tabla [" + tabla + "] ya existe en el catálogo maestro.", "Duplicado", JOptionPane.WARNING_MESSAGE);
                            rsCheck.close();
                            psCheck.close();
                            return;
                        }
                        rsCheck.close();
                        psCheck.close();
                    }

                    PreparedStatement ps;
                    if (modoEdicion) {
                        String sql = "UPDATE tmclasge SET DES = ?, USER = 'Admin', FEAC = CURDATE(), HOAC = DATE_FORMAT(NOW(), '%r') WHERE TBL = ?";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, descripcion);
                        ps.setString(2, tabla);
                    } else {
                        String sql = "INSERT INTO tmclasge (TBL, DES, USER, FEAC, HOAC) VALUES (?, ?, 'Admin', CURDATE(), DATE_FORMAT(NOW(), '%r'))";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, tabla);
                        ps.setString(2, descripcion);
                    }

                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(dialogo, "Clasificación guardada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                        dialogo.dispose();
                        cargarTablaClasificaciones();
                    } else {
                        JOptionPane.showMessageDialog(dialogo, "No se pudo guardar la información.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    ps.close();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialogo, "Error SQL: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClasificaciones;
    private javax.swing.JButton btnDeleteClasificaciones;
    private javax.swing.JButton btnEditClasificaciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JTable tblClasificaciones;
    // End of variables declaration//GEN-END:variables
}
