/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Condiciones_Pago extends javax.swing.JPanel {
    

    /**
     * Creates new form Condiciones_Pago
     */
    public Condiciones_Pago() {
        initComponents();
    }

  private void cargarTablaCondicionesPago() {
        DefaultTableModel modelo = (DefaultTableModel) tblCPago.getModel();
        modelo.setRowCount(0); // Limpiamos antes de cargar

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                // Seleccionamos las columnas mapeando la tabla 'tgcpag'
                String sql = "SELECT CPAG, DCPA, DPP1, DPP2, DPP3, DLI1, DLI2, DLI3, DPPP, DPDP, USER, FEAC, HOAC FROM tgcpag";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[13]; 
                    fila[0] = rs.getString("CPAG");
                    fila[1] = rs.getString("DCPA");
                    fila[2] = rs.getString("DPP1");
                    fila[3] = rs.getString("DPP2");
                    fila[4] = rs.getString("DPP3");
                    fila[5] = rs.getString("DLI1");
                    fila[6] = rs.getString("DLI2");
                    fila[7] = rs.getString("DLI3");
                    fila[8] = rs.getString("DPPP");
                    fila[9] = rs.getString("DPDP");
                    fila[10] = rs.getString("USER");
                    fila[11] = rs.getString("FEAC");
                    fila[12] = rs.getString("HOAC");
                    modelo.addRow(fila);
                }
                rs.close(); ps.close(); db.Cerrar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla de Condiciones de Pago: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBg = new javax.swing.JPanel();
        btnAddCPago = new javax.swing.JButton();
        btnEditCPago = new javax.swing.JButton();
        btnDeleteCPago = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCPago = new javax.swing.JTable();

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));

        btnAddCPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCPago.setForeground(new java.awt.Color(26, 61, 99));
        btnAddCPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddCPago.setText("Añadir");
        btnAddCPago.addActionListener(this::btnAddCPagoActionPerformed);

        btnEditCPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditCPago.setForeground(new java.awt.Color(26, 61, 99));
        btnEditCPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditCPago.setText("Editar");
        btnEditCPago.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditCPago.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditCPago.addActionListener(this::btnEditCPagoActionPerformed);

        btnDeleteCPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteCPago.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteCPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteCPago.setText("Eliminar");
        btnDeleteCPago.addActionListener(this::btnDeleteCPagoActionPerformed);

        tblCPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Clave", "Descripción", "Dia pago 1", "Dia pago 2", "Dia pago 3", "Dia Lim.1", "Dia Lim. 2", "Dia Lim. 3", "Dias Pron. Pago", "% Desc. Pron. Pago", "Usuario", "Fecha Mod.", "Hora Mod."
            }
        ));
        jScrollPane1.setViewportView(tblCPago);

        javax.swing.GroupLayout pnlBgLayout = new javax.swing.GroupLayout(pnlBg);
        pnlBg.setLayout(pnlBgLayout);
        pnlBgLayout.setHorizontalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddCPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCPago)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        pnlBgLayout.setVerticalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBgLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCPago, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCPago, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCPago, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCPagoActionPerformed
        mostrarDialogoCondicionPago(false);
    }//GEN-LAST:event_btnAddCPagoActionPerformed

    private void btnDeleteCPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCPagoActionPerformed
       int fila = tblCPago.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una condición de pago para eliminar.");
            return;
        }

        String clave = tblCPago.getValueAt(fila, 0).toString();
        String desc = tblCPago.getValueAt(fila, 1).toString();
        
        int resp = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar la condición de pago:\n" + clave + " - " + desc + "?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    String sql = "DELETE FROM tgcpag WHERE CPAG = ?";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, clave);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Condición de pago eliminada correctamente.");
                        cargarTablaCondicionesPago(); // Refrescamos la tabla
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró el registro para eliminar.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteCPagoActionPerformed

    private void btnEditCPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCPagoActionPerformed
      if (tblCPago.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un registro para editar.");
            return;
        }
        mostrarDialogoCondicionPago(true);
    }//GEN-LAST:event_btnEditCPagoActionPerformed
private void mostrarDialogoCondicionPago(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Condición de Pago" : "Agregar Condición de Pago";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(520, 500);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. SECCIÓN SUPERIOR ---
        JLabel lblClave = new JLabel("Clave");
        lblClave.setBounds(20, 15, 80, 25);
        JTextField txtClave = new JTextField();
        txtClave.setBounds(100, 15, 80, 25);
        if (modoEdicion) txtClave.setEditable(false);

        JLabel lblDesc = new JLabel("Descripción");
        lblDesc.setBounds(20, 45, 80, 25);
        JTextField txtDesc = new JTextField();
        txtDesc.setBounds(100, 45, 380, 25);

        JLabel lblDiasNeto = new JLabel("Días Neto");
        lblDiasNeto.setBounds(20, 75, 80, 25);
        JTextField txtDiasNeto = new JTextField();
        txtDiasNeto.setBounds(100, 75, 80, 25);

        dialogo.add(lblClave); dialogo.add(txtClave);
        dialogo.add(lblDesc); dialogo.add(txtDesc);
        dialogo.add(lblDiasNeto); dialogo.add(txtDiasNeto);

        // --- 2. PESTAÑAS Y MARCOS ---
        JTabbedPane pestanas = new JTabbedPane();
        pestanas.setBounds(10, 115, 485, 290);

        JPanel pnlGenerales = new JPanel(null);

        // >> Marco: Días Programados
        JPanel pnlDiasProg = new JPanel(null);
        pnlDiasProg.setBorder(BorderFactory.createTitledBorder("Días Programados"));
        pnlDiasProg.setBounds(10, 15, 460, 150);

        JLabel lblProgPago = new JLabel("Días Programados para Pago");
        lblProgPago.setBounds(80, 20, 180, 20);
        JLabel lblDiaLim = new JLabel("Día Límite para programar pago");
        lblDiaLim.setBounds(260, 20, 180, 20);
        
        pnlDiasProg.add(lblProgPago); pnlDiasProg.add(lblDiaLim);

        // Cajas de texto
        JTextField txtProg1 = new JTextField("0"); txtProg1.setBounds(120, 45, 70, 25);
        JTextField txtProg2 = new JTextField("0"); txtProg2.setBounds(120, 75, 70, 25);
        JTextField txtProg3 = new JTextField("0"); txtProg3.setBounds(120, 105, 70, 25);

        JTextField txtLim1 = new JTextField("0"); txtLim1.setBounds(300, 45, 70, 25);
        JTextField txtLim2 = new JTextField("0"); txtLim2.setBounds(300, 75, 70, 25);
        JTextField txtLim3 = new JTextField("0"); txtLim3.setBounds(300, 105, 70, 25);

        pnlDiasProg.add(txtProg1); pnlDiasProg.add(txtProg2); pnlDiasProg.add(txtProg3);
        pnlDiasProg.add(txtLim1); pnlDiasProg.add(txtLim2); pnlDiasProg.add(txtLim3);

        // >> Marco: Descuento por Pronto Pago
        JPanel pnlDesc = new JPanel(null);
        pnlDesc.setBorder(BorderFactory.createTitledBorder("Descuento por Pronto Pago"));
        pnlDesc.setBounds(10, 175, 460, 70);

        JLabel lblDiasDesc = new JLabel("Días");
        lblDiasDesc.setBounds(90, 25, 40, 25);
        JTextField txtDiasDesc = new JTextField("0");
        txtDiasDesc.setBounds(130, 25, 70, 25);

        JLabel lblPorcDesc = new JLabel("Porcentaje");
        lblPorcDesc.setBounds(250, 25, 70, 25);
        JTextField txtPorcDesc = new JTextField("0");
        txtPorcDesc.setBounds(330, 25, 70, 25);

        pnlDesc.add(lblDiasDesc); pnlDesc.add(txtDiasDesc);
        pnlDesc.add(lblPorcDesc); pnlDesc.add(txtPorcDesc);

        pnlGenerales.add(pnlDiasProg);
        pnlGenerales.add(pnlDesc);
        pestanas.addTab("Datos Generales", pnlGenerales);
        dialogo.add(pestanas);

        // --- 3. BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(140, 415, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(260, 415, 100, 40);

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        // --- 4. SI ES MODO EDICIÓN, CARGAMOS LOS DATOS ---
        if (modoEdicion) {
            int fila = tblCPago.getSelectedRow();
            String clave = tblCPago.getValueAt(fila, 0) != null ? tblCPago.getValueAt(fila, 0).toString() : "";
            
            txtClave.setText(clave);
            txtDesc.setText(tblCPago.getValueAt(fila, 1) != null ? tblCPago.getValueAt(fila, 1).toString() : "");
            txtProg1.setText(tblCPago.getValueAt(fila, 2) != null ? tblCPago.getValueAt(fila, 2).toString() : "0");
            txtProg2.setText(tblCPago.getValueAt(fila, 3) != null ? tblCPago.getValueAt(fila, 3).toString() : "0");
            txtProg3.setText(tblCPago.getValueAt(fila, 4) != null ? tblCPago.getValueAt(fila, 4).toString() : "0");
            txtLim1.setText(tblCPago.getValueAt(fila, 5) != null ? tblCPago.getValueAt(fila, 5).toString() : "0");
            txtLim2.setText(tblCPago.getValueAt(fila, 6) != null ? tblCPago.getValueAt(fila, 6).toString() : "0");
            txtLim3.setText(tblCPago.getValueAt(fila, 7) != null ? tblCPago.getValueAt(fila, 7).toString() : "0");
            txtDiasDesc.setText(tblCPago.getValueAt(fila, 8) != null ? tblCPago.getValueAt(fila, 8).toString() : "0");
            txtPorcDesc.setText(tblCPago.getValueAt(fila, 9) != null ? tblCPago.getValueAt(fila, 9).toString() : "0");

            // Extraemos el campo 'Días Neto' (DVEN) directo de la BD, ya que no se muestra en la tabla
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps = con.prepareStatement("SELECT DVEN FROM tgcpag WHERE CPAG = ?");
                    ps.setString(1, clave);
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()) {
                        txtDiasNeto.setText(rs.getString("DVEN"));
                    }
                    rs.close(); ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                txtDiasNeto.setText("0"); // En caso de error, mostramos 0
            }
        }

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnAceptar.addActionListener(e -> {
            String clave = txtClave.getText().trim();
            if (clave.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "La clave no puede estar vacía.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Extraemos la información previniendo que los campos numéricos estén vacíos
            String desc = txtDesc.getText().trim();
            String diasNeto = txtDiasNeto.getText().trim().isEmpty() ? "0" : txtDiasNeto.getText().trim();
            String prog1 = txtProg1.getText().trim().isEmpty() ? "0" : txtProg1.getText().trim();
            String prog2 = txtProg2.getText().trim().isEmpty() ? "0" : txtProg2.getText().trim();
            String prog3 = txtProg3.getText().trim().isEmpty() ? "0" : txtProg3.getText().trim();
            String lim1 = txtLim1.getText().trim().isEmpty() ? "0" : txtLim1.getText().trim();
            String lim2 = txtLim2.getText().trim().isEmpty() ? "0" : txtLim2.getText().trim();
            String lim3 = txtLim3.getText().trim().isEmpty() ? "0" : txtLim3.getText().trim();
            String diasDesc = txtDiasDesc.getText().trim().isEmpty() ? "0" : txtDiasDesc.getText().trim();
            String porcDesc = txtPorcDesc.getText().trim().isEmpty() ? "0" : txtPorcDesc.getText().trim();

            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps;
                    
                    if (modoEdicion) {
                        // UPDATE (Actualizar registro)
                        String sql = "UPDATE tgcpag SET DCPA=?, DVEN=?, DPP1=?, DPP2=?, DPP3=?, DLI1=?, DLI2=?, DLI3=?, DPPP=?, DPDP=? WHERE CPAG=?";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, desc);
                        ps.setString(2, diasNeto);
                        ps.setString(3, prog1);
                        ps.setString(4, prog2);
                        ps.setString(5, prog3);
                        ps.setString(6, lim1);
                        ps.setString(7, lim2);
                        ps.setString(8, lim3);
                        ps.setString(9, diasDesc);
                        ps.setString(10, porcDesc);
                        ps.setString(11, clave);
                    } else {
                        // INSERT (Nuevo registro)
                        String sql = "INSERT INTO tgcpag (CPAG, DCPA, DVEN, DPP1, DPP2, DPP3, DLI1, DLI2, DLI3, DPPP, DPDP) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, clave);
                        ps.setString(2, desc);
                        ps.setString(3, diasNeto);
                        ps.setString(4, prog1);
                        ps.setString(5, prog2);
                        ps.setString(6, prog3);
                        ps.setString(7, lim1);
                        ps.setString(8, lim2);
                        ps.setString(9, lim3);
                        ps.setString(10, diasDesc);
                        ps.setString(11, porcDesc);
                    }

                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(dialogo, "Condición de Pago guardada con éxito.");
                        dialogo.dispose();
                        cargarTablaCondicionesPago(); // Refresca tu vista principal automáticamente
                    } else {
                        JOptionPane.showMessageDialog(dialogo, "No se pudo guardar la información.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialogo, "Error al guardar en BD: " + ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
            }
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCPago;
    private javax.swing.JButton btnDeleteCPago;
    private javax.swing.JButton btnEditCPago;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JTable tblCPago;
    // End of variables declaration//GEN-END:variables
}
