/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Consulta_Pagos extends javax.swing.JPanel {

    /**
     * Creates new form Consulta_Pagos
     */
    public Consulta_Pagos() {
        initComponents();
    }
private void configurarTablaBitacora() {
        // Configuramos las columnas de la tabla de fondo
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"ID Consulta", "Fecha de Consulta", "Usuario", "Módulo"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblCPagos.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCPagos = new javax.swing.JTable();
        btnAddCPagos = new javax.swing.JButton();
        btnEditCPagos = new javax.swing.JButton();
        btnDeleteCPagos = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblCPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCPagos);

        btnAddCPagos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCPagos.setForeground(new java.awt.Color(26, 61, 99));
        btnAddCPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddCPagos.setText("Añadir");
        btnAddCPagos.addActionListener(this::btnAddCPagosActionPerformed);

        btnEditCPagos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditCPagos.setForeground(new java.awt.Color(26, 61, 99));
        btnEditCPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditCPagos.setText("Editar");
        btnEditCPagos.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditCPagos.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditCPagos.addActionListener(this::btnEditCPagosActionPerformed);

        btnDeleteCPagos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteCPagos.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteCPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteCPagos.setText("Eliminar");
        btnDeleteCPagos.addActionListener(this::btnDeleteCPagosActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddCPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCPagos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCPagosActionPerformed
     mostrarDialogoConsultaPagos();
    }//GEN-LAST:event_btnAddCPagosActionPerformed

    private void btnEditCPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCPagosActionPerformed
       JOptionPane.showMessageDialog(this, "Esta es una pantalla de reportes. Para editar un pago, diríjase al módulo correspondiente.");
    }//GEN-LAST:event_btnEditCPagosActionPerformed

    private void btnDeleteCPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCPagosActionPerformed
       JOptionPane.showMessageDialog(this, "No se pueden eliminar pagos desde la pantalla de consultas.");
    }//GEN-LAST:event_btnDeleteCPagosActionPerformed

private void mostrarDialogoConsultaPagos() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Consulta de Pagos", true);
        dialogo.setSize(950, 650);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. DATOS DE SELECCIÓN ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createTitledBorder("Datos de selección"));
        pnlSel.setBounds(10, 10, 700, 90);

        pnlSel.add(new JLabel("Compañía")).setBounds(15, 20, 70, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12"})).setBounds(85, 20, 60, 25);

        pnlSel.add(new JLabel("C. Costos")).setBounds(200, 20, 70, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12100"})).setBounds(270, 20, 80, 25);

        pnlSel.add(new JLabel("Ciclo Escolar")).setBounds(400, 20, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(490, 20, 100, 25);

        pnlSel.add(new JLabel("Matrícula")).setBounds(15, 55, 70, 25);
        pnlSel.add(new JTextField()).setBounds(85, 55, 100, 25);

        pnlSel.add(new JLabel("Fecha Inicial")).setBounds(200, 55, 80, 25);
        pnlSel.add(new JTextField("04/06/2026")).setBounds(280, 55, 90, 25);

        pnlSel.add(new JLabel("Fecha Final")).setBounds(400, 55, 80, 25);
        pnlSel.add(new JTextField("04/06/2026")).setBounds(480, 55, 90, 25);

        dialogo.add(pnlSel);

        // --- 2. PANEL DERECHO (Filtro y Checkbox) ---
        JPanel pnlFiltro = new JPanel(null);
        pnlFiltro.setBorder(BorderFactory.createEtchedBorder());
        pnlFiltro.setBounds(720, 15, 200, 85);

        JCheckBox chkHoja = new JCheckBox("Hoja por Alumno");
        chkHoja.setBounds(10, 10, 150, 25);
        pnlFiltro.add(chkHoja);

        JButton btnFiltra = new JButton("Filtra Información");
        btnFiltra.setBounds(10, 45, 180, 30);
        pnlFiltro.add(btnFiltra);

        dialogo.add(pnlFiltro);

        // --- 3. TABLA DE CONCEPTOS PAGADOS ---
        JTable tblConceptos = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Compañía", "C. Costos", "C. Escolar", "Recibo", "Tipo", "Fecha Rec", "Concepto", "Descripción", "Moneda", "Importe MN", "Factura", "Tipo", "Fecha Fa"}
        ));
        // Como son muchas columnas, permitimos que se haga scroll horizontal
        tblConceptos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 

        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Conceptos Pagados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pnlTabla.setBounds(10, 110, 910, 430);
        
        JScrollPane scrollConceptos = new JScrollPane(tblConceptos);
        scrollConceptos.setBounds(10, 20, 890, 400);
        pnlTabla.add(scrollConceptos);
        
        dialogo.add(pnlTabla);

        // --- 4. BOTONES INFERIORES ---
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(350, 555, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(480, 555, 100, 40);

        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Filtrando pagos desde la base de datos... (Simulación)");
            // Aquí iría el SELECT con todos los JOINs para llenar tblConceptos
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando el reporte de pagos a la impresora... (Simulación)");
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCPagos;
    private javax.swing.JButton btnDeleteCPagos;
    private javax.swing.JButton btnEditCPagos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCPagos;
    // End of variables declaration//GEN-END:variables
}
