/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Detalle_Conceptos_Pagos extends javax.swing.JPanel {

    /**
     * Creates new form Detalle_Conceptos_Pagos
     */
    public Detalle_Conceptos_Pagos() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha Consulta", "Cajero Filtrado", "Concepto", "Tipo de Cuenta", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblDCPAgos.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDCPAgos = new javax.swing.JTable();
        btnAddDCPagos = new javax.swing.JButton();
        btnEditDCPagados = new javax.swing.JButton();
        btnDeleteDCPagados = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblDCPAgos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDCPAgos);

        btnAddDCPagos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddDCPagos.setForeground(new java.awt.Color(26, 61, 99));
        btnAddDCPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddDCPagos.setText("Añadir");
        btnAddDCPagos.addActionListener(this::btnAddDCPagosActionPerformed);

        btnEditDCPagados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditDCPagados.setForeground(new java.awt.Color(26, 61, 99));
        btnEditDCPagados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditDCPagados.setText("Editar");
        btnEditDCPagados.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditDCPagados.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditDCPagados.addActionListener(this::btnEditDCPagadosActionPerformed);

        btnDeleteDCPagados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteDCPagados.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteDCPagados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteDCPagados.setText("Eliminar");
        btnDeleteDCPagados.addActionListener(this::btnDeleteDCPagadosActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddDCPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditDCPagados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteDCPagados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDCPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditDCPagados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteDCPagados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDCPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDCPagosActionPerformed
        mostrarDialogoDetalleConceptos();
    }//GEN-LAST:event_btnAddDCPagosActionPerformed

    private void btnEditDCPagadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDCPagadosActionPerformed
        JOptionPane.showMessageDialog(this, "Esta pantalla es de consulta y reportes. Los detalles de pago no se pueden editar desde aquí.");
    }//GEN-LAST:event_btnEditDCPagadosActionPerformed

    private void btnDeleteDCPagadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDCPagadosActionPerformed
      JOptionPane.showMessageDialog(this, "No se pueden eliminar pagos desde el generador de reportes. Use Cancelación de Recibos.");
    }//GEN-LAST:event_btnDeleteDCPagadosActionPerformed
private void mostrarDialogoDetalleConceptos() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Detalle de Conceptos Pagados", true);
        dialogo.setSize(950, 640);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. DATOS DE SELECCIÓN (Panel Superior) ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createEtchedBorder());
        pnlSel.setBounds(10, 10, 720, 140);

        pnlSel.add(new JLabel("Compañía")).setBounds(20, 15, 70, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12"})).setBounds(90, 15, 80, 25);

        pnlSel.add(new JLabel("Centro Costos")).setBounds(200, 15, 100, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12100"})).setBounds(300, 15, 100, 25);

        pnlSel.add(new JLabel("Ciclo Escolar")).setBounds(440, 15, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(530, 15, 120, 25);

        pnlSel.add(new JLabel("Cajero")).setBounds(20, 50, 70, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(90, 50, 80, 25);

        pnlSel.add(new JLabel("Fecha Inicial")).setBounds(200, 50, 100, 25);
        pnlSel.add(new JTextField("04/06/2026")).setBounds(300, 50, 100, 25);

        pnlSel.add(new JLabel("Fecha Final")).setBounds(440, 50, 80, 25);
        pnlSel.add(new JTextField("04/06/2026")).setBounds(530, 50, 120, 25);

        pnlSel.add(new JLabel("Concepto")).setBounds(20, 85, 70, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(90, 85, 80, 25);

        pnlSel.add(new JLabel("Tipo Concepto")).setBounds(440, 85, 90, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(530, 85, 120, 25);

        dialogo.add(pnlSel);

        // --- 2. FORMATO ---
        JLabel lblFormato = new JLabel("Formato");
        lblFormato.setBounds(20, 160, 70, 25);
        JComboBox<String> cmbFormato = new JComboBox<>(new String[]{"01 DETALLE DE CONCEPTOS PAGADOS"});
        cmbFormato.setBounds(90, 160, 640, 25);
        
        dialogo.add(lblFormato);
        dialogo.add(cmbFormato);

        // --- 3. TIPO DE CUENTA Y BOTÓN (Panel Derecho) ---
        JPanel pnlTipoCta = new JPanel(null);
        pnlTipoCta.setBorder(BorderFactory.createTitledBorder("Tipo de Cuenta"));
        pnlTipoCta.setBounds(740, 10, 180, 100);

        JRadioButton rbOficial = new JRadioButton("Oficial", true);
        rbOficial.setBounds(20, 20, 80, 20);
        JRadioButton rbPart = new JRadioButton("Particular");
        rbPart.setBounds(20, 45, 100, 20);
        JRadioButton rbAmbos = new JRadioButton("Ambos");
        rbAmbos.setBounds(20, 70, 80, 20);

        ButtonGroup bgTipo = new ButtonGroup();
        bgTipo.add(rbOficial); bgTipo.add(rbPart); bgTipo.add(rbAmbos);
        
        pnlTipoCta.add(rbOficial); pnlTipoCta.add(rbPart); pnlTipoCta.add(rbAmbos);
        dialogo.add(pnlTipoCta);

        JButton btnFiltra = new JButton("Filtrar información");
        btnFiltra.setBounds(740, 120, 180, 30);
        dialogo.add(btnFiltra);

        // --- 4. TABLA DETALLE DE CONCEPTOS ---
        JTable tblDetalle = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Tipo", "Cve", "Concepto", "Matricula", "Nombre del Alumno", "Grado", "Grupo", "Cantidad", "Importe"}
        ));
        tblDetalle.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        
        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Detalle de Conceptos Pagados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pnlTabla.setBounds(10, 195, 910, 270);
        
        JScrollPane scrollDetalle = new JScrollPane(tblDetalle);
        scrollDetalle.setBounds(10, 20, 890, 240);
        pnlTabla.add(scrollDetalle);
        
        dialogo.add(pnlTabla);

        // --- 5. TOTALES INFERIORES ---
        JPanel pnlTotales = new JPanel(null);
        pnlTotales.setBorder(BorderFactory.createEtchedBorder());
        pnlTotales.setBounds(10, 470, 910, 45);

        JLabel lblTotales = new JLabel("Totales de Concepto");
        lblTotales.setBounds(630, 10, 120, 25);
        
        JTextField txtTotCant = new JTextField("0");
        txtTotCant.setHorizontalAlignment(JTextField.RIGHT);
        txtTotCant.setEditable(false);
        txtTotCant.setBounds(750, 10, 60, 25);

        JTextField txtTotImp = new JTextField("0.00");
        txtTotImp.setHorizontalAlignment(JTextField.RIGHT);
        txtTotImp.setEditable(false);
        txtTotImp.setBounds(820, 10, 80, 25);

        pnlTotales.add(lblTotales);
        pnlTotales.add(txtTotCant);
        pnlTotales.add(txtTotImp);

        dialogo.add(pnlTotales);

        // --- 6. BOTONES INFERIORES ---
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(350, 540, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(480, 540, 100, 40);

        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 7. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Extrayendo el detalle de pagos desde la base de datos... (Simulación)");
            // Aquí iría tu lógica SQL para llenar tblDetalle
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando el reporte detallado a la impresora... (Simulación)");
            dialogo.dispose();
        });

        // --- 8. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDCPagos;
    private javax.swing.JButton btnDeleteDCPagados;
    private javax.swing.JButton btnEditDCPagados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDCPAgos;
    // End of variables declaration//GEN-END:variables
}
