/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Estado_Cuenta_Detallado extends javax.swing.JPanel {

    /**
     * Creates new form Estado_Cuenta_Detallado
     */
    public Estado_Cuenta_Detallado() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha Consulta", "Matrícula Buscada", "Usuario", "Módulo"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblECDetallado.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCPagos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblECDetallado = new javax.swing.JTable();
        btnAddECDetallado = new javax.swing.JButton();
        btnEditECDetallado = new javax.swing.JButton();
        btnDeleteECDetallado = new javax.swing.JButton();

        tblCPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCPagos);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblECDetallado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblECDetallado);

        btnAddECDetallado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddECDetallado.setForeground(new java.awt.Color(26, 61, 99));
        btnAddECDetallado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddECDetallado.setText("Añadir");
        btnAddECDetallado.addActionListener(this::btnAddECDetalladoActionPerformed);

        btnEditECDetallado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditECDetallado.setForeground(new java.awt.Color(26, 61, 99));
        btnEditECDetallado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditECDetallado.setText("Editar");
        btnEditECDetallado.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditECDetallado.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditECDetallado.addActionListener(this::btnEditECDetalladoActionPerformed);

        btnDeleteECDetallado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteECDetallado.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteECDetallado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteECDetallado.setText("Eliminar");
        btnDeleteECDetallado.addActionListener(this::btnDeleteECDetalladoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddECDetallado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditECDetallado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteECDetallado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddECDetallado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditECDetallado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteECDetallado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddECDetalladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddECDetalladoActionPerformed
       mostrarDialogoEstadoCuenta();
    }//GEN-LAST:event_btnAddECDetalladoActionPerformed

    private void btnEditECDetalladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditECDetalladoActionPerformed
        JOptionPane.showMessageDialog(this, "Esta pantalla es de solo lectura (Reportes).\nPara modificar saldos o pagos, utilice los módulos de Cobranza.");
    }//GEN-LAST:event_btnEditECDetalladoActionPerformed

    private void btnDeleteECDetalladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteECDetalladoActionPerformed
       JOptionPane.showMessageDialog(this, "No se pueden eliminar registros desde un Estado de Cuenta.");
    }//GEN-LAST:event_btnDeleteECDetalladoActionPerformed
private void mostrarDialogoEstadoCuenta() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Estado de Cuenta Detallado", true);
        dialogo.setSize(950, 680);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. DATOS DE SELECCIÓN ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createEtchedBorder());
        pnlSel.setBounds(10, 10, 600, 120);

        pnlSel.add(new JLabel("Compañía")).setBounds(15, 20, 70, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12"})).setBounds(90, 20, 70, 25);

        pnlSel.add(new JLabel("Ctro de Costo")).setBounds(180, 20, 90, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12100"})).setBounds(270, 20, 80, 25);

        pnlSel.add(new JLabel("Ciclo Escolar")).setBounds(370, 20, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(460, 20, 100, 25);

        pnlSel.add(new JLabel("Grado")).setBounds(15, 55, 70, 25);
        pnlSel.add(new JTextField()).setBounds(90, 55, 70, 25);

        pnlSel.add(new JLabel("Matricula")).setBounds(15, 90, 70, 25);
        pnlSel.add(new JTextField()).setBounds(90, 90, 120, 25);

        dialogo.add(pnlSel);

        // --- 2. PANEL INCLUIR ---
        JPanel pnlIncluir = new JPanel(null);
        pnlIncluir.setBorder(BorderFactory.createTitledBorder("Incluir"));
        pnlIncluir.setBounds(620, 10, 120, 120);
        
        JCheckBox chkMensaje = new JCheckBox("Mensaje (3)");
        chkMensaje.setBounds(10, 30, 100, 25);
        pnlIncluir.add(chkMensaje);
        
        dialogo.add(pnlIncluir);

        // --- 3. PANEL TIPO DE CUENTA ---
        JPanel pnlTipoCta = new JPanel(null);
        pnlTipoCta.setBorder(BorderFactory.createTitledBorder("Tipo de Cuenta"));
        pnlTipoCta.setBounds(750, 10, 170, 85);

        JRadioButton rbOficial = new JRadioButton("Oficial", true);
        rbOficial.setBounds(10, 15, 80, 20);
        JRadioButton rbPart = new JRadioButton("Particular");
        rbPart.setBounds(10, 35, 100, 20);
        JRadioButton rbAmbos = new JRadioButton("Ambos");
        rbAmbos.setBounds(10, 55, 100, 20);

        ButtonGroup bgTipo = new ButtonGroup();
        bgTipo.add(rbOficial); bgTipo.add(rbPart); bgTipo.add(rbAmbos);
        pnlTipoCta.add(rbOficial); pnlTipoCta.add(rbPart); pnlTipoCta.add(rbAmbos);
        
        dialogo.add(pnlTipoCta);

        // --- BOTÓN FILTRAR ---
        JButton btnFiltra = new JButton("Filtrar información");
        btnFiltra.setBounds(750, 100, 170, 30);
        dialogo.add(btnFiltra);

        // --- 4. TABLA DETALLE DE CONCEPTOS ---
        JTable tblConceptos = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Matricula", "Concepto", "Descripcion", "Grad", "Gpo", "A Pagar", "Fec Venc", "Imp Pagado", "Fec Pago", "Ref Ban", "Saldo", "% Beca"}
        ));
        tblConceptos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 

        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Detalle de Conceptos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pnlTabla.setBounds(10, 140, 910, 360);
        
        JScrollPane scrollConceptos = new JScrollPane(tblConceptos);
        scrollConceptos.setBounds(10, 20, 890, 330);
        pnlTabla.add(scrollConceptos);
        
        dialogo.add(pnlTabla);

        // --- 5. TOTALES ---
        JLabel lblTotPagar = new JLabel("Total A Pagar"); lblTotPagar.setBounds(450, 510, 100, 20);
        JTextField txtTotPagar = new JTextField("0.00"); txtTotPagar.setBounds(450, 530, 120, 25);
        txtTotPagar.setHorizontalAlignment(JTextField.RIGHT); txtTotPagar.setEditable(false);

        JLabel lblTotPagado = new JLabel("Total Pagado"); lblTotPagado.setBounds(600, 510, 100, 20);
        JTextField txtTotPagado = new JTextField("0.00"); txtTotPagado.setBounds(600, 530, 120, 25);
        txtTotPagado.setHorizontalAlignment(JTextField.RIGHT); txtTotPagado.setEditable(false);

        JLabel lblTotSaldo = new JLabel("Total Saldo"); lblTotSaldo.setBounds(750, 510, 100, 20);
        JTextField txtTotSaldo = new JTextField("0.00"); txtTotSaldo.setBounds(750, 530, 120, 25);
        txtTotSaldo.setHorizontalAlignment(JTextField.RIGHT); txtTotSaldo.setEditable(false);

        dialogo.add(lblTotPagar); dialogo.add(txtTotPagar);
        dialogo.add(lblTotPagado); dialogo.add(txtTotPagado);
        dialogo.add(lblTotSaldo); dialogo.add(txtTotSaldo);

        // --- 6. BOTONES INFERIORES ---
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(350, 580, 110, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(480, 580, 110, 40);

        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 7. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Calculando y desglosando estado de cuenta... (Simulación)");
            // Aquí iría el SELECT complejo para llenar tblConceptos y sumar los totales
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando el Estado de Cuenta a la impresora... (Simulación)");
        });

        // --- 8. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddECDetallado;
    private javax.swing.JButton btnDeleteECDetallado;
    private javax.swing.JButton btnEditECDetallado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCPagos;
    private javax.swing.JTable tblECDetallado;
    // End of variables declaration//GEN-END:variables
}
