/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Estado_Resultados extends javax.swing.JPanel {

    /**
     * Creates new form Estado_Resultados
     */
    public Estado_Resultados() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha Consulta", "Año/Periodo", "Nivel", "Detalle CC", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblEResultados.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEResultados = new javax.swing.JTable();
        btnAddEResultados = new javax.swing.JButton();
        btnEditEResultados = new javax.swing.JButton();
        btnDeleteEResultados = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblEResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEResultados);

        btnAddEResultados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddEResultados.setForeground(new java.awt.Color(26, 61, 99));
        btnAddEResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddEResultados.setText("Añadir");
        btnAddEResultados.addActionListener(this::btnAddEResultadosActionPerformed);

        btnEditEResultados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditEResultados.setForeground(new java.awt.Color(26, 61, 99));
        btnEditEResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditEResultados.setText("Editar");
        btnEditEResultados.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditEResultados.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditEResultados.addActionListener(this::btnEditEResultadosActionPerformed);

        btnDeleteEResultados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteEResultados.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteEResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteEResultados.setText("Eliminar");
        btnDeleteEResultados.addActionListener(this::btnDeleteEResultadosActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddEResultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditEResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteEResultados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditEResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteEResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEResultadosActionPerformed
    mostrarDialogoEstadoResultados();
    }//GEN-LAST:event_btnAddEResultadosActionPerformed

    private void btnEditEResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEResultadosActionPerformed
        
JOptionPane.showMessageDialog(this, "El Estado de Resultados es un reporte calculado, no permite edición manual.");
    }//GEN-LAST:event_btnEditEResultadosActionPerformed

    private void btnDeleteEResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEResultadosActionPerformed
    JOptionPane.showMessageDialog(this, "No se pueden eliminar registros contables desde el visor de reportes.");
    }//GEN-LAST:event_btnDeleteEResultadosActionPerformed

private void mostrarDialogoEstadoResultados() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Estado de Resultados", true);
        dialogo.setSize(950, 680);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. DATOS DE SELECCIÓN (Panel Superior) ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createEtchedBorder());
        pnlSel.setBounds(10, 10, 915, 140);

        // Bloque Izquierdo
        pnlSel.add(new JLabel("Compañía")).setBounds(20, 15, 70, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12"})).setBounds(90, 15, 60, 25);
        pnlSel.add(new JLabel("UNIDAD ESCOLAR BENAVENTE, A.C.")).setBounds(160, 15, 250, 25);

        pnlSel.add(new JLabel("Año")).setBounds(20, 45, 50, 25);
        pnlSel.add(new JTextField("2026")).setBounds(90, 45, 60, 25);

        pnlSel.add(new JLabel("Periodo")).setBounds(20, 75, 60, 25);
        pnlSel.add(new JTextField("5")).setBounds(90, 75, 60, 25);

        // Niveles (1 al 9)
        pnlSel.add(new JLabel("Nivel")).setBounds(20, 105, 40, 25);
        ButtonGroup bgNivel = new ButtonGroup();
        int xPosNivel = 70;
        for (int i = 1; i <= 9; i++) {
            JRadioButton rb = new JRadioButton(String.valueOf(i));
            if(i == 3) rb.setSelected(true); // Seleccionado el nivel 3 por defecto
            rb.setBounds(xPosNivel, 105, 40, 25);
            bgNivel.add(rb);
            pnlSel.add(rb);
            xPosNivel += 45;
        }

        // Bloque Central (Tipos de Contabilidad)
        pnlSel.add(new JLabel("Tipo de Cont. Real")).setBounds(420, 45, 130, 25);
        pnlSel.add(new JComboBox<>(new String[]{"MN"})).setBounds(560, 45, 60, 25);

        pnlSel.add(new JLabel("Tipo de Cont. Presupuesto")).setBounds(420, 75, 140, 25);
        pnlSel.add(new JComboBox<>(new String[]{"PL"})).setBounds(560, 75, 60, 25);

        // Bloque Derecho (Casilla Detalle y Botones)
        JPanel pnlDetalle = new JPanel(null);
        pnlDetalle.setBorder(BorderFactory.createEtchedBorder());
        pnlDetalle.setBounds(730, 10, 165, 50);
        JCheckBox chkDetalle = new JCheckBox("Ver Detalle x CC");
        chkDetalle.setBounds(10, 15, 140, 20);
        pnlDetalle.add(chkDetalle);
        pnlSel.add(pnlDetalle);

        JButton btnSelecciona = new JButton("Selecciona");
        btnSelecciona.setBounds(730, 70, 165, 25);
        pnlSel.add(btnSelecciona);

        JButton btnFiltra = new JButton("Filtrar Información");
        btnFiltra.setBounds(730, 105, 165, 25);
        pnlSel.add(btnFiltra);

        dialogo.add(pnlSel);

        // --- 2. TABLA DE RESULTADOS ---
        JTable tblResultados = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Mes", "Presupuesto", "Diferencia", "Cuentas", "Acum. Año", "Ppto. Año"}
        ));
        tblResultados.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        
        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createEtchedBorder());
        pnlTabla.setBounds(10, 160, 915, 390);
        
        JScrollPane scrollResultados = new JScrollPane(tblResultados);
        scrollResultados.setBounds(10, 10, 895, 370);
        pnlTabla.add(scrollResultados);
        
        dialogo.add(pnlTabla);

        // --- 3. BOTONES INFERIORES ---
        JButton btnExportar = new JButton("Exporta");
        btnExportar.setBounds(300, 570, 100, 40);
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(420, 570, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(540, 570, 100, 40);

        dialogo.add(btnExportar);
        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 4. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnSelecciona.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Abre ventana para seleccionar cuentas de resultados... (Simulación)");
        });

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Calculando Estado de Resultados General... (Simulación)");
            // Aquí iría la lógica SQL para llenar tblResultados
        });

        btnExportar.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Exportando Estado de Resultados a Excel (.xlsx)... (Simulación)");
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando reporte a la impresora... (Simulación)");
        });

        // --- 5. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEResultados;
    private javax.swing.JButton btnDeleteEResultados;
    private javax.swing.JButton btnEditEResultados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEResultados;
    // End of variables declaration//GEN-END:variables
}
