/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Factores_Convercion_Unidad extends javax.swing.JPanel {

    /**
     * Creates new form Factores_Convercion_Unidad
     */
    public Factores_Convercion_Unidad() {
        initComponents();
    }
    
   private void cargarTablaFactores() {
        DefaultTableModel modelo = (DefaultTableModel) tblFCUnidad.getModel();
        modelo.setRowCount(0); 
 
        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                // Consulta con los nombres reales de la tabla tgcum
                String sql = "SELECT UMO, UMD, CART, FCONV, USER, FEAC, HOAC FROM tgcum";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[7]; 
                    fila[0] = rs.getString("UMO");
                    fila[1] = rs.getString("UMD");
                    fila[2] = rs.getString("CART");
                    fila[3] = rs.getString("FCONV");
                    fila[4] = rs.getString("USER");
                    fila[5] = rs.getString("FEAC");
                    fila[6] = rs.getString("HOAC");

                    modelo.addRow(fila);
                }
                rs.close(); ps.close(); db.Cerrar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla: " + e.getMessage());
        }
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBg = new javax.swing.JPanel();
        btnDeleteFCUnidad = new javax.swing.JButton();
        btnEditFCUnidad = new javax.swing.JButton();
        btnAddFCUnidad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFCUnidad = new javax.swing.JTable();

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));

        btnDeleteFCUnidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteFCUnidad.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteFCUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteFCUnidad.setText("Eliminar");
        btnDeleteFCUnidad.addActionListener(this::btnDeleteFCUnidadActionPerformed);

        btnEditFCUnidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditFCUnidad.setForeground(new java.awt.Color(26, 61, 99));
        btnEditFCUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditFCUnidad.setText("Editar");
        btnEditFCUnidad.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditFCUnidad.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditFCUnidad.addActionListener(this::btnEditFCUnidadActionPerformed);

        btnAddFCUnidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddFCUnidad.setForeground(new java.awt.Color(26, 61, 99));
        btnAddFCUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddFCUnidad.setText("Añadir");
        btnAddFCUnidad.addActionListener(this::btnAddFCUnidadActionPerformed);

        tblFCUnidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "UM Origen", "UM Destino", "Articulo", "Factor", "Usuario", "Fecha Mod.", "Hora Mod."
            }
        ));
        jScrollPane1.setViewportView(tblFCUnidad);

        javax.swing.GroupLayout pnlBgLayout = new javax.swing.GroupLayout(pnlBg);
        pnlBg.setLayout(pnlBgLayout);
        pnlBgLayout.setHorizontalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddFCUnidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditFCUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteFCUnidad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBgLayout.setVerticalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddFCUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditFCUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteFCUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFCUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFCUnidadActionPerformed
       mostrarDialogoFactor(false);
    }//GEN-LAST:event_btnAddFCUnidadActionPerformed

    private void btnDeleteFCUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFCUnidadActionPerformed
      int fila = tblFCUnidad.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un registro para eliminar.");
            return;
        }

        String origen = tblFCUnidad.getValueAt(fila, 0).toString();
        String destino = tblFCUnidad.getValueAt(fila, 1).toString();
        String articulo = tblFCUnidad.getValueAt(fila, 2).toString();
        
        int resp = JOptionPane.showConfirmDialog(this, 
            "¿Seguro que deseas eliminar la conversión de " + origen + " a " + destino + " para el artículo " + articulo + "?", 
            "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    // Borramos utilizando las 3 llaves primarias
                    String sql = "DELETE FROM tgcum WHERE UMO = ? AND UMD = ? AND CART = ?";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, origen);
                    ps.setString(2, destino);
                    ps.setString(3, articulo);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Registro eliminado correctamente.");
                        cargarTablaFactores();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró el registro para eliminar.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteFCUnidadActionPerformed

    private void btnEditFCUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFCUnidadActionPerformed
       if (tblFCUnidad.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una conversión para editar.");
            return;
        }
        mostrarDialogoFactor(true);
    }//GEN-LAST:event_btnEditFCUnidadActionPerformed
private void mostrarDialogoFactor(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Conversión de Unidad de Medida" : "Agregar Conversión de Unidad de Medida";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(480, 300);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. MARCO PRINCIPAL ---
        JPanel pnlCentral = new JPanel(null);
        pnlCentral.setBorder(BorderFactory.createEtchedBorder());
        pnlCentral.setBounds(15, 15, 435, 170);

        JLabel lblOrigen = new JLabel("Unidad Medida Origen");
        lblOrigen.setBounds(20, 20, 140, 25);
        JComboBox<String> cmbOrigen = new JComboBox<>(new String[]{"PZA", "LT", "KG", "ACT", "CJA"});
        cmbOrigen.setBounds(160, 20, 80, 25);
        JLabel lblDescOrigen = new JLabel("Piezas"); 
        lblDescOrigen.setBounds(250, 20, 100, 25);

        JLabel lblDestino = new JLabel("Unidad Medida Destino");
        lblDestino.setBounds(20, 55, 140, 25);
        JComboBox<String> cmbDestino = new JComboBox<>(new String[]{"CJA", "PZA", "KG", "LT", "ACT"});
        cmbDestino.setBounds(160, 55, 80, 25);
        JLabel lblDescDestino = new JLabel("Caja");
        lblDescDestino.setBounds(250, 55, 100, 25);

        JLabel lblProducto = new JLabel("Artículo");
        lblProducto.setBounds(20, 90, 140, 25);
        JTextField txtProducto = new JTextField();
        txtProducto.setBounds(160, 90, 150, 25);

        // Si es edición, no permitimos cambiar las llaves, solo el factor
        if (modoEdicion) { 
            cmbOrigen.setEnabled(false); 
            cmbDestino.setEnabled(false); 
            txtProducto.setEditable(false); 
        }

        JLabel lblFactor = new JLabel("Factor de Conversión");
        lblFactor.setBounds(20, 130, 140, 25);
        JTextField txtFactor = new JTextField();
        txtFactor.setBounds(160, 130, 80, 25);

        pnlCentral.add(lblOrigen); pnlCentral.add(cmbOrigen); pnlCentral.add(lblDescOrigen);
        pnlCentral.add(lblDestino); pnlCentral.add(cmbDestino); pnlCentral.add(lblDescDestino);
        pnlCentral.add(lblProducto); pnlCentral.add(txtProducto);
        pnlCentral.add(lblFactor); pnlCentral.add(txtFactor);

        dialogo.add(pnlCentral);

        // --- 2. BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(120, 200, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(240, 200, 100, 40);

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        // --- 3. SI ES MODO EDICIÓN, CARGAMOS LOS DATOS ---
        if (modoEdicion) {
            int fila = tblFCUnidad.getSelectedRow();
            
            cmbOrigen.setSelectedItem(tblFCUnidad.getValueAt(fila, 0) != null ? tblFCUnidad.getValueAt(fila, 0).toString() : "");
            cmbDestino.setSelectedItem(tblFCUnidad.getValueAt(fila, 1) != null ? tblFCUnidad.getValueAt(fila, 1).toString() : "");
            txtProducto.setText(tblFCUnidad.getValueAt(fila, 2) != null ? tblFCUnidad.getValueAt(fila, 2).toString() : "");
            txtFactor.setText(tblFCUnidad.getValueAt(fila, 3) != null ? tblFCUnidad.getValueAt(fila, 3).toString() : "0");
        }

        // --- 4. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnAceptar.addActionListener(e -> {
            String origen = cmbOrigen.getSelectedItem() != null ? cmbOrigen.getSelectedItem().toString() : "";
            String destino = cmbDestino.getSelectedItem() != null ? cmbDestino.getSelectedItem().toString() : "";
            String articulo = txtProducto.getText().trim();
            String factor = txtFactor.getText().trim();

            if (articulo.isEmpty() || factor.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "El artículo y el factor son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps;
                    
                    if (modoEdicion) {
                        // UPDATE (Actualizamos solo el Factor basándonos en las 3 llaves)
                        String sql = "UPDATE tgcum SET FCONV = ? WHERE UMO = ? AND UMD = ? AND CART = ?";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, factor);
                        ps.setString(2, origen);
                        ps.setString(3, destino);
                        ps.setString(4, articulo);
                    } else {
                        // INSERT (Nuevo registro)
                        String sql = "INSERT INTO tgcum (UMO, UMD, CART, FCONV) VALUES (?, ?, ?, ?)";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, origen);
                        ps.setString(2, destino);
                        ps.setString(3, articulo);
                        ps.setString(4, factor);
                    }

                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(dialogo, "Operación guardada con éxito.");
                        dialogo.dispose();
                        cargarTablaFactores(); 
                    } else {
                        JOptionPane.showMessageDialog(dialogo, "No se pudo guardar la información.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialogo, "Error de base de datos: " + ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
            }
        });

        // --- 5. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFCUnidad;
    private javax.swing.JButton btnDeleteFCUnidad;
    private javax.swing.JButton btnEditFCUnidad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JTable tblFCUnidad;
    // End of variables declaration//GEN-END:variables
}
