/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Grados_Escolares extends javax.swing.JPanel {

    /**
     * Creates new form Grados_Escolares
     */
    public Grados_Escolares() {
        initComponents();
    }
private void cargarTablaGrados() {
        // 1. Arreglamos las columnas de la tabla por código
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Compañía", "Centro Costo", "Grado", "Descripción", "Carrera", "Id Contable", "Excluido", "Usuario", "Fecha Mod."}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hacemos que la tabla no sea editable directamente
            }
        };
        jTable1.setModel(modelo);

        // 2. Cargamos los datos
        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                // ATENCIÓN: Cambia 'tabla_grados' por tu tabla real
                String sql = "SELECT compania, centro_costos, grado, descripcion, carrera, id_contable, excluido, usuario, fecha_mod FROM tabla_grados";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[9]; 
                    fila[0] = rs.getString("compania");
                    fila[1] = rs.getString("centro_costos");
                    fila[2] = rs.getString("grado");
                    fila[3] = rs.getString("descripcion");
                    fila[4] = rs.getString("carrera");
                    fila[5] = rs.getString("id_contable");
                    fila[6] = rs.getString("excluido");
                    fila[7] = rs.getString("usuario");
                    fila[8] = rs.getString("fecha_mod");
                    modelo.addRow(fila);
                }
                rs.close(); ps.close(); db.Cerrar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddGEscolar = new javax.swing.JButton();
        btnEditGEscolar = new javax.swing.JButton();
        btnDeleteGEscolar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAddGEscolar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddGEscolar.setForeground(new java.awt.Color(26, 61, 99));
        btnAddGEscolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddGEscolar.setText("Añadir");
        btnAddGEscolar.addActionListener(this::btnAddGEscolarActionPerformed);

        btnEditGEscolar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditGEscolar.setForeground(new java.awt.Color(26, 61, 99));
        btnEditGEscolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditGEscolar.setText("Editar");
        btnEditGEscolar.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditGEscolar.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditGEscolar.addActionListener(this::btnEditGEscolarActionPerformed);

        btnDeleteGEscolar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteGEscolar.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteGEscolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteGEscolar.setText("Eliminar");
        btnDeleteGEscolar.addActionListener(this::btnDeleteGEscolarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddGEscolar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditGEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteGEscolar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddGEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditGEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteGEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddGEscolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGEscolarActionPerformed
       mostrarDialogoGrado(false);
    }//GEN-LAST:event_btnAddGEscolarActionPerformed

    private void btnEditGEscolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditGEscolarActionPerformed
       if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un grado escolar para editar.");
            return;
        }
        mostrarDialogoGrado(true);
    }//GEN-LAST:event_btnEditGEscolarActionPerformed

    private void btnDeleteGEscolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGEscolarActionPerformed
       int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un grado escolar para eliminar.");
            return;
        }

        String compania = jTable1.getValueAt(fila, 0).toString();
        String cc = jTable1.getValueAt(fila, 1).toString();
        String grado = jTable1.getValueAt(fila, 2).toString();
        String desc = jTable1.getValueAt(fila, 3).toString();
        
        int resp = JOptionPane.showConfirmDialog(this, "¿Eliminar el grado " + desc + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    // ATENCIÓN: Cambia 'tabla_grados' por tu tabla real
                    String sql = "DELETE FROM tabla_grados WHERE compania = ? AND centro_costos = ? AND grado = ?";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, compania);
                    ps.setString(2, cc);
                    ps.setString(3, grado);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Grado escolar eliminado.");
                        cargarTablaGrados();
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteGEscolarActionPerformed

private void mostrarDialogoGrado(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Grado Escolar" : "Agregar Grado Escolar";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(550, 480);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. SECCIÓN SUPERIOR ---
        JLabel lblCia = new JLabel("Compañía");
        lblCia.setBounds(20, 15, 80, 25);
        JComboBox<String> cmbCia = new JComboBox<>(new String[]{"12"});
        cmbCia.setBounds(110, 15, 70, 25);
        JLabel lblCiaDesc = new JLabel("UNIDAD ESCOLAR BENAVENTE, A.C.");
        lblCiaDesc.setBounds(190, 15, 250, 25);

        JLabel lblCC = new JLabel("Centro Costos");
        lblCC.setBounds(20, 45, 90, 25);
        JComboBox<String> cmbCC = new JComboBox<>(new String[]{"12100", ""});
        cmbCC.setBounds(110, 45, 70, 25);
        JLabel lblCCDesc = new JLabel("UNIDAD ESCOLAR BENAVENTE (JARDIN)");
        lblCCDesc.setBounds(190, 45, 250, 25);

        JLabel lblGrado = new JLabel("Grado");
        lblGrado.setBounds(20, 75, 80, 25);
        JTextField txtGrado = new JTextField();
        txtGrado.setBounds(110, 75, 80, 25);

        JLabel lblDesc = new JLabel("Descripción");
        lblDesc.setBounds(20, 105, 80, 25);
        JTextField txtDesc = new JTextField();
        txtDesc.setBounds(110, 105, 400, 25);

        if (modoEdicion) {
            cmbCia.setEnabled(false);
            cmbCC.setEnabled(false);
            txtGrado.setEditable(false); // Llaves bloqueadas en edición
        }

        dialogo.add(lblCia); dialogo.add(cmbCia); dialogo.add(lblCiaDesc);
        dialogo.add(lblCC); dialogo.add(cmbCC); dialogo.add(lblCCDesc);
        dialogo.add(lblGrado); dialogo.add(txtGrado);
        dialogo.add(lblDesc); dialogo.add(txtDesc);

        // --- 2. PESTAÑAS Y MARCOS ---
        JTabbedPane pestanas = new JTabbedPane();
        pestanas.setBounds(15, 145, 500, 230);

        JPanel pnlGenerales = new JPanel(null);

        // >> Marco: Nivel Superior
        JPanel pnlNivel = new JPanel(null);
        pnlNivel.setBorder(BorderFactory.createTitledBorder("Nivel Superior"));
        pnlNivel.setBounds(10, 10, 475, 100);

        JLabel lblCarrera = new JLabel("Carrera");
        lblCarrera.setBounds(20, 25, 70, 25);
        JTextField txtCarrera = new JTextField();
        txtCarrera.setBounds(100, 25, 70, 25);
        JComboBox<String> cmbCarreraHelp = new JComboBox<>(); // Solo visual para la flechita
        cmbCarreraHelp.setBounds(170, 25, 20, 25);

        JLabel lblIdContable = new JLabel("Id Contable");
        lblIdContable.setBounds(20, 60, 70, 25);
        JTextField txtIdContable = new JTextField();
        txtIdContable.setBounds(100, 60, 70, 25);
        JLabel lblAvisoId = new JLabel("(Identificador para la contabilización detallada por carrera)");
        lblAvisoId.setBounds(180, 60, 290, 25);
        lblAvisoId.setFont(new java.awt.Font("Segoe UI", java.awt.Font.ITALIC, 11));

        pnlNivel.add(lblCarrera); pnlNivel.add(txtCarrera); pnlNivel.add(cmbCarreraHelp);
        pnlNivel.add(lblIdContable); pnlNivel.add(txtIdContable); pnlNivel.add(lblAvisoId);

        // >> Marco: Condiciones
        JPanel pnlCondiciones = new JPanel(null);
        pnlCondiciones.setBorder(BorderFactory.createTitledBorder("Condiciones"));
        pnlCondiciones.setBounds(10, 120, 475, 60);

        JLabel lblExcluir = new JLabel("Excluir de Lista de alumnos No Inscritos");
        lblExcluir.setBounds(100, 20, 230, 25);
        
        JRadioButton rbSi = new JRadioButton("Si");
        rbSi.setBounds(330, 20, 40, 25);
        JRadioButton rbNo = new JRadioButton("No", true); // "No" seleccionado por defecto
        rbNo.setBounds(380, 20, 50, 25);
        
        ButtonGroup bgExcluir = new ButtonGroup();
        bgExcluir.add(rbSi); bgExcluir.add(rbNo);

        pnlCondiciones.add(lblExcluir); pnlCondiciones.add(rbSi); pnlCondiciones.add(rbNo);

        pnlGenerales.add(pnlNivel);
        pnlGenerales.add(pnlCondiciones);

        pestanas.addTab("Datos Generales", pnlGenerales);
        pestanas.addTab("Reconocimiento", new JPanel()); // Pestaña vacía
        dialogo.add(pestanas);

        // --- 3. BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(150, 390, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(280, 390, 100, 40);

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        // --- 4. SI ES MODO EDICIÓN, CARGAMOS LOS DATOS ---
        if (modoEdicion) {
            int fila = jTable1.getSelectedRow();
            cmbCia.setSelectedItem(jTable1.getValueAt(fila, 0).toString());
            cmbCC.setSelectedItem(jTable1.getValueAt(fila, 1).toString());
            txtGrado.setText(jTable1.getValueAt(fila, 2).toString());
            txtDesc.setText(jTable1.getValueAt(fila, 3).toString());
            // Lógica para llenar Carrera, IdContable y RadioButtons
        }

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnAceptar.addActionListener(e -> {
            String grado = txtGrado.getText().trim();
            if (grado.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "El grado no puede estar vacío.");
                return;
            }

            // Aquí va la lógica SQL (INSERT / UPDATE)
            JOptionPane.showMessageDialog(dialogo, "Grado escolar guardado (Simulación).");
            
            dialogo.dispose();
            cargarTablaGrados(); 
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGEscolar;
    private javax.swing.JButton btnDeleteGEscolar;
    private javax.swing.JButton btnEditGEscolar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
