/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Impresion_Poliza extends javax.swing.JPanel {

    /**
     * Creates new form Impresion_Poliza
     */
    public Impresion_Poliza() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha Impresión", "Rango Pólizas", "Tipo de Póliza", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblIPoliza.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIPoliza = new javax.swing.JTable();
        btnAddIPoliza = new javax.swing.JButton();
        btnEditIPoliza = new javax.swing.JButton();
        btnDeleteIPoliza = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblIPoliza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIPoliza);

        btnAddIPoliza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddIPoliza.setForeground(new java.awt.Color(26, 61, 99));
        btnAddIPoliza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddIPoliza.setText("Añadir");
        btnAddIPoliza.addActionListener(this::btnAddIPolizaActionPerformed);

        btnEditIPoliza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditIPoliza.setForeground(new java.awt.Color(26, 61, 99));
        btnEditIPoliza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditIPoliza.setText("Editar");
        btnEditIPoliza.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditIPoliza.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditIPoliza.addActionListener(this::btnEditIPolizaActionPerformed);

        btnDeleteIPoliza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteIPoliza.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteIPoliza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteIPoliza.setText("Eliminar");
        btnDeleteIPoliza.addActionListener(this::btnDeleteIPolizaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddIPoliza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditIPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteIPoliza)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddIPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditIPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteIPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddIPolizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIPolizaActionPerformed
       mostrarDialogoImpresionPoliza();
    }//GEN-LAST:event_btnAddIPolizaActionPerformed

    private void btnEditIPolizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditIPolizaActionPerformed
       JOptionPane.showMessageDialog(this, "Esta pantalla es exclusivamente para imprimir pólizas. Para modificar datos, diríjase a 'Captura de Pólizas'.");
    }//GEN-LAST:event_btnEditIPolizaActionPerformed

    private void btnDeleteIPolizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteIPolizaActionPerformed
        JOptionPane.showMessageDialog(this, "No se pueden cancelar pólizas desde el módulo de impresión.");
    }//GEN-LAST:event_btnDeleteIPolizaActionPerformed
private void mostrarDialogoImpresionPoliza() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Impresión de Póliza", true);
        dialogo.setSize(580, 420);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- CLASE LOCAL PARA REUTILIZAR EL BUSCADOR FLOTANTE ---
        class BuscadorFlotante {
            void configurar(JTextField txtClave, JTextField txtDesc, JButton boton, Object[][] datos) {
                String[] columnas = {"Clave", "Descripción"};
                Runnable mostrarPopup = () -> {
                    javax.swing.JPopupMenu popup = new javax.swing.JPopupMenu();
                    popup.setFocusable(false);
                    javax.swing.table.DefaultTableModel mod = new javax.swing.table.DefaultTableModel(datos, columnas) {
                        @Override public boolean isCellEditable(int r, int c) { return false; }
                    };
                    javax.swing.JTable tabla = new javax.swing.JTable(mod);
                    tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                    tabla.getColumnModel().getColumn(0).setPreferredWidth(80);
                    tabla.getColumnModel().getColumn(1).setPreferredWidth(220);

                    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(mod);
                    tabla.setRowSorter(sorter);

                    tabla.addMouseListener(new java.awt.event.MouseAdapter() {
                        @Override
                        public void mouseReleased(java.awt.event.MouseEvent me) {
                            int viewRow = tabla.getSelectedRow();
                            if (viewRow != -1) {
                                int modelRow = tabla.convertRowIndexToModel(viewRow);
                                txtClave.setText(mod.getValueAt(modelRow, 0).toString());
                                if (txtDesc != null) {
                                    txtDesc.setText(mod.getValueAt(modelRow, 1).toString());
                                }
                                popup.setVisible(false);
                            }
                        }
                    });
                    javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(tabla);
                    scroll.setPreferredSize(new java.awt.Dimension(320, 150));
                    popup.add(scroll);

                    String texto = txtClave.getText().trim();
                    if (!texto.isEmpty()) sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto));
                    popup.show(txtClave, 0, txtClave.getHeight());
                    txtClave.requestFocus();
                };

                boton.addActionListener(e -> { txtClave.setText(""); mostrarPopup.run(); });
                txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
                    @Override
                    public void keyReleased(java.awt.event.KeyEvent e) {
                        int c = e.getKeyCode();
                        if (c == 27 || c == 10 || c == 38 || c == 40 || c == 37 || c == 39 || c == 9) return;
                        mostrarPopup.run();
                    }
                });
            }
        }
        BuscadorFlotante buscador = new BuscadorFlotante();

        // --- CARGA DE DATOS PARA EL BUSCADOR (Tipo de Póliza) ---
        java.util.function.Function<String, Object[][]> cargarDatos = (query) -> {
            java.util.List<Object[]> lista = new java.util.ArrayList<>();
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps = con.prepareStatement(query);
                    ResultSet rs = ps.executeQuery();
                    while(rs.next()) lista.add(new Object[]{rs.getString(1), rs.getString(2)});
                    rs.close(); ps.close(); db.Cerrar();
                }
            } catch(Exception e) {}
            return lista.toArray(new Object[0][0]);
        };

        Object[][] dTPol = cargarDatos.apply("SELECT CVE, DES FROM tmclas WHERE TBL = 'TPOL' ORDER BY CVE");

        // --- 1. SECCIÓN SUPERIOR (Filtros de Póliza) ---
        
        // Compañía (Dinámica)
        dialogo.add(new JLabel("Compañía")).setBounds(30, 20, 80, 25);
        JComboBox<String> cmbCia = new JComboBox<>();
        cmbCia.setBounds(130, 20, 70, 25);
        dialogo.add(cmbCia);
        JLabel lblNomCia = new JLabel();
        lblNomCia.setBounds(210, 20, 250, 25);
        dialogo.add(lblNomCia);
        
        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();
            if (con != null) {
                ResultSet rs = con.prepareStatement("SELECT CIA, NCIA FROM tmcias").executeQuery();
                while(rs.next()){ 
                    cmbCia.addItem(rs.getString("CIA")); 
                    lblNomCia.setText(rs.getString("NCIA")); // Toma la última o se puede atar al evento del combobox
                }
                rs.close(); db.Cerrar();
            }
        } catch (Exception ex) {}

        // Tipo de Póliza (Con Buscador Flotante)
        dialogo.add(new JLabel("Tipo de Póliza")).setBounds(30, 55, 90, 25);
        JTextField txtTipoPol = new JTextField();
        txtTipoPol.setBounds(130, 55, 60, 25);
        JButton btnTipoPol = new JButton("▼");
        btnTipoPol.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10));
        btnTipoPol.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTipoPol.setBounds(190, 55, 20, 25);
        
        buscador.configurar(txtTipoPol, null, btnTipoPol, dTPol);
        
        dialogo.add(txtTipoPol);
        dialogo.add(btnTipoPol);

        // Póliza Inicial / Final
        dialogo.add(new JLabel("Póliza Inicial")).setBounds(30, 90, 90, 25);
        dialogo.add(new JTextField()).setBounds(130, 90, 130, 25);

        dialogo.add(new JLabel("Póliza Final")).setBounds(300, 90, 80, 25);
        dialogo.add(new JTextField()).setBounds(390, 90, 130, 25);

        dialogo.add(new JLabel("Fecha Inicial")).setBounds(30, 125, 90, 25);
        dialogo.add(new JTextField("04/06/2026")).setBounds(130, 125, 100, 25);

        dialogo.add(new JLabel("Fecha Final")).setBounds(300, 125, 80, 25);
        dialogo.add(new JTextField("04/06/2026")).setBounds(390, 125, 100, 25);

        JCheckBox chkPagina = new JCheckBox("Imprimir una póliza por página");
        chkPagina.setBounds(30, 160, 250, 25);
        dialogo.add(chkPagina);

        // --- LÍNEA SEPARADORA ---
        JSeparator separador = new JSeparator();
        separador.setBounds(20, 195, 520, 10);
        dialogo.add(separador);

        // --- 2. SECCIÓN INFERIOR (Documento Original) ---
        dialogo.add(new JLabel("Documento Original")).setBounds(30, 215, 130, 25);
        dialogo.add(new JTextField()).setBounds(160, 215, 120, 25);

        // Opciones de Documento (Radio Buttons)
        JRadioButton rb1 = new JRadioButton("Factura de Venta"); rb1.setBounds(300, 205, 200, 20);
        JRadioButton rb2 = new JRadioButton("Recibo de Almacén"); rb2.setBounds(300, 225, 200, 20);
        JRadioButton rb3 = new JRadioButton("Factura de Recibo de Almacén"); rb3.setBounds(300, 245, 220, 20);
        JRadioButton rb4 = new JRadioButton("Documento de Cheque"); rb4.setBounds(300, 265, 200, 20);
        JRadioButton rb5 = new JRadioButton("Documento de Pago de Cliente"); rb5.setBounds(300, 285, 220, 20);

        ButtonGroup bgDocs = new ButtonGroup();
        bgDocs.add(rb1); bgDocs.add(rb2); bgDocs.add(rb3); bgDocs.add(rb4); bgDocs.add(rb5);

        dialogo.add(rb1); dialogo.add(rb2); dialogo.add(rb3); dialogo.add(rb4); dialogo.add(rb5);

        // --- 3. BOTONES INFERIORES ---
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(180, 330, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(300, 330, 100, 40);

        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 4. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Buscando pólizas y enviando formato a la impresora... (Simulación)");
            dialogo.dispose();
        });

        // --- 5. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddIPoliza;
    private javax.swing.JButton btnDeleteIPoliza;
    private javax.swing.JButton btnEditIPoliza;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIPoliza;
    // End of variables declaration//GEN-END:variables
}
