/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Ingresos_Periodo extends javax.swing.JPanel {

    /**
     * Creates new form Ingresos_Periodo
     */
    public Ingresos_Periodo() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha Consulta", "Rango de Fechas", "Tipo de Reporte", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblIPeriodo.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIPeriodo = new javax.swing.JTable();
        btnAddIPeriodo = new javax.swing.JButton();
        btnEditIPeriodo = new javax.swing.JButton();
        btnDeleteIPeriodo = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblIPeriodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIPeriodo);

        btnAddIPeriodo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddIPeriodo.setForeground(new java.awt.Color(26, 61, 99));
        btnAddIPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddIPeriodo.setText("Añadir");
        btnAddIPeriodo.addActionListener(this::btnAddIPeriodoActionPerformed);

        btnEditIPeriodo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditIPeriodo.setForeground(new java.awt.Color(26, 61, 99));
        btnEditIPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditIPeriodo.setText("Editar");
        btnEditIPeriodo.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditIPeriodo.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditIPeriodo.addActionListener(this::btnEditIPeriodoActionPerformed);

        btnDeleteIPeriodo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteIPeriodo.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteIPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteIPeriodo.setText("Eliminar");
        btnDeleteIPeriodo.addActionListener(this::btnDeleteIPeriodoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddIPeriodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditIPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteIPeriodo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddIPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditIPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteIPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddIPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIPeriodoActionPerformed
        mostrarDialogoIngresos();
    }//GEN-LAST:event_btnAddIPeriodoActionPerformed

    private void btnEditIPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditIPeriodoActionPerformed
       JOptionPane.showMessageDialog(this, "Esta pantalla es exclusivamente para generar reportes y no permite edición.");
    }//GEN-LAST:event_btnEditIPeriodoActionPerformed

    private void btnDeleteIPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteIPeriodoActionPerformed
      JOptionPane.showMessageDialog(this, "No se pueden eliminar ingresos desde el generador de reportes.");
    }//GEN-LAST:event_btnDeleteIPeriodoActionPerformed
private void mostrarDialogoIngresos() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Ingresos por Periodo", true);
        dialogo.setSize(980, 680);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. DATOS DE SELECCIÓN (Panel Izquierdo) ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createTitledBorder("Datos de selección"));
        pnlSel.setBounds(10, 10, 710, 95);

        pnlSel.add(new JLabel("Compañía")).setBounds(15, 20, 70, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12"})).setBounds(90, 20, 70, 25);

        pnlSel.add(new JLabel("C. Costos")).setBounds(175, 20, 70, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12100"})).setBounds(245, 20, 80, 25);

        pnlSel.add(new JLabel("Ciclo Escolar")).setBounds(340, 20, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(425, 20, 100, 25);
        
        pnlSel.add(new JLabel("Cajero")).setBounds(540, 20, 60, 25);
        pnlSel.add(new JTextField()).setBounds(590, 20, 100, 25);

        pnlSel.add(new JLabel("Forma pago")).setBounds(15, 55, 70, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(90, 55, 70, 25);

        pnlSel.add(new JLabel("Fecha Inicial")).setBounds(175, 55, 80, 25);
        pnlSel.add(new JTextField("04/06/2026")).setBounds(245, 55, 80, 25);

        pnlSel.add(new JLabel("Fecha Final")).setBounds(340, 55, 80, 25);
        pnlSel.add(new JTextField("04/06/2026")).setBounds(425, 55, 90, 25);

        pnlSel.add(new JLabel("Referencia")).setBounds(525, 55, 70, 25);
        pnlSel.add(new JTextField()).setBounds(590, 55, 100, 25);

        dialogo.add(pnlSel);

        // --- 2. TIPO DE CUENTA Y REPORTE (Panel Derecho) ---
        JPanel pnlOpciones = new JPanel(null);
        pnlOpciones.setBorder(BorderFactory.createTitledBorder("Tipo de Cuenta"));
        pnlOpciones.setBounds(730, 10, 220, 95);

        JRadioButton rbOficial = new JRadioButton("Oficial", true);
        rbOficial.setBounds(20, 15, 80, 20);
        JRadioButton rbPart = new JRadioButton("Particular");
        rbPart.setBounds(110, 15, 100, 20);
        ButtonGroup bgCta = new ButtonGroup(); bgCta.add(rbOficial); bgCta.add(rbPart);
        
        JRadioButton rbDetalle = new JRadioButton("Detalle", true);
        rbDetalle.setBounds(20, 40, 80, 20);
        JRadioButton rbResumen = new JRadioButton("Resumen");
        rbResumen.setBounds(110, 40, 100, 20);
        ButtonGroup bgRep = new ButtonGroup(); bgRep.add(rbDetalle); bgRep.add(rbResumen);

        JButton btnFiltra = new JButton("Filtra Información");
        btnFiltra.setBounds(15, 65, 190, 25);

        pnlOpciones.add(rbOficial); pnlOpciones.add(rbPart);
        pnlOpciones.add(rbDetalle); pnlOpciones.add(rbResumen);
        pnlOpciones.add(btnFiltra);
        
        dialogo.add(pnlOpciones);

        // --- 3. TABLA DE INGRESOS ---
        JTable tblIngresos = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Compañía", "C. Costos", "Ciclo", "Matrícula", "Nombre", "Grado", "Num Recibo", "Tipo", "Fec Recibo", "Fma Pago", "Banco", "Cta Pago", "Referencia", "Fec Pol", "Importe"}
        ));
        tblIngresos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        
        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Ingresos por Periodo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pnlTabla.setBounds(10, 110, 940, 360);
        
        JScrollPane scrollIngresos = new JScrollPane(tblIngresos);
        scrollIngresos.setBounds(10, 20, 920, 330);
        pnlTabla.add(scrollIngresos);
        
        dialogo.add(pnlTabla);

        // --- 4. TOTALES INFERIORES ---
        JPanel pnlTotales = new JPanel(null);
        pnlTotales.setBorder(BorderFactory.createTitledBorder("Totales"));
        pnlTotales.setBounds(10, 475, 940, 70);

        String[] lbls = {"Efectivo", "Cheques", "Dep. Bancario", "Tarjetas", "T. Electronica", "Total"};
        int xPos = 250;
        for (int i = 0; i < lbls.length; i++) {
            JLabel l = new JLabel(lbls[i], SwingUtilities.CENTER);
            l.setBounds(xPos, 15, 100, 20);
            JTextField t = new JTextField("0.00");
            t.setBounds(xPos, 35, 100, 25);
            t.setHorizontalAlignment(JTextField.RIGHT);
            t.setEditable(false);
            
            // Un pequeño salto extra antes del "Total" para separarlo visualmente (como en la imagen)
            if (i == lbls.length - 1) xPos += 40; 

            pnlTotales.add(l); pnlTotales.add(t);
            xPos += 110;
        }
        dialogo.add(pnlTotales);

        // --- 5. BOTONES INFERIORES ---
        JButton btnExportar = new JButton("Exporta");
        btnExportar.setBounds(280, 560, 110, 40);
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(410, 560, 110, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(620, 560, 110, 40);

        dialogo.add(btnExportar);
        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 6. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Extrayendo ingresos y calculando métodos de pago... (Simulación)");
            // Aquí iría la lógica SQL para llenar la tabla
        });
        
        btnExportar.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Exportando tabla a documento de Excel (.xlsx)... (Simulación)");
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando reporte de ingresos a la impresora... (Simulación)");
        });

        // --- 7. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddIPeriodo;
    private javax.swing.JButton btnDeleteIPeriodo;
    private javax.swing.JButton btnEditIPeriodo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIPeriodo;
    // End of variables declaration//GEN-END:variables
}
