/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Libro_Diario extends javax.swing.JPanel {

    /**
     * Creates new form Libro_Diario
     */
    public Libro_Diario() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha de Consulta", "Rango de Fechas", "Orden", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblLDiario.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLDiario = new javax.swing.JTable();
        btnAddLDiario = new javax.swing.JButton();
        btnEditLDiario = new javax.swing.JButton();
        btnDeleteLDiario = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblLDiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLDiario);

        btnAddLDiario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddLDiario.setForeground(new java.awt.Color(26, 61, 99));
        btnAddLDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddLDiario.setText("Añadir");
        btnAddLDiario.addActionListener(this::btnAddLDiarioActionPerformed);

        btnEditLDiario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditLDiario.setForeground(new java.awt.Color(26, 61, 99));
        btnEditLDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditLDiario.setText("Editar");
        btnEditLDiario.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditLDiario.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditLDiario.addActionListener(this::btnEditLDiarioActionPerformed);

        btnDeleteLDiario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteLDiario.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteLDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteLDiario.setText("Eliminar");
        btnDeleteLDiario.addActionListener(this::btnDeleteLDiarioActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddLDiario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditLDiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteLDiario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditLDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteLDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLDiarioActionPerformed
        mostrarDialogoLibroDiario();
    }//GEN-LAST:event_btnAddLDiarioActionPerformed

    private void btnEditLDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLDiarioActionPerformed
JOptionPane.showMessageDialog(this, "Esta pantalla es de consulta y reportes. Para editar una póliza, usa el módulo 'Captura de Pólizas'.");
        
    }//GEN-LAST:event_btnEditLDiarioActionPerformed

    private void btnDeleteLDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLDiarioActionPerformed
       JOptionPane.showMessageDialog(this, "No se pueden alterar ni eliminar los registros contables desde el visor del Libro de Diario.");
    }//GEN-LAST:event_btnDeleteLDiarioActionPerformed
private void mostrarDialogoLibroDiario() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Libro de Diario", true);
        dialogo.setSize(920, 650);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. DATOS DE SELECCIÓN (Panel Superior) ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createEtchedBorder());
        pnlSel.setBounds(10, 10, 885, 120);

        // Bloque Izquierdo
        pnlSel.add(new JLabel("Compañía")).setBounds(20, 15, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12"})).setBounds(100, 15, 70, 25);
        pnlSel.add(new JLabel("UNIDAD ESCOLAR BENAVENTE, A.C.")).setBounds(180, 15, 250, 25);

        pnlSel.add(new JLabel("Fecha Inicial")).setBounds(20, 45, 80, 25);
        pnlSel.add(new JTextField("04/06/2026")).setBounds(100, 45, 100, 25);

        pnlSel.add(new JLabel("Fecha Final")).setBounds(20, 75, 80, 25);
        pnlSel.add(new JTextField("04/06/2026")).setBounds(100, 75, 100, 25);

        // Bloque Central (Tipos)
        pnlSel.add(new JLabel("Tipo Contab.")).setBounds(450, 45, 100, 25);
        pnlSel.add(new JComboBox<>(new String[]{"MN"})).setBounds(560, 45, 70, 25);

        pnlSel.add(new JLabel("Tipo de Movimiento")).setBounds(430, 75, 120, 25);
        pnlSel.add(new JTextField()).setBounds(560, 75, 70, 25);

        // Bloque Derecho (Ordenar por y Botón)
        JPanel pnlOrden = new JPanel(null);
        pnlOrden.setBorder(BorderFactory.createTitledBorder("Ordenar por"));
        pnlOrden.setBounds(700, 10, 170, 70);

        JRadioButton rbFechaPoliza = new JRadioButton("Fecha y Póliza", true);
        rbFechaPoliza.setBounds(10, 15, 140, 20);
        JRadioButton rbPoliza = new JRadioButton("Póliza");
        rbPoliza.setBounds(10, 40, 140, 20);

        ButtonGroup bgOrden = new ButtonGroup();
        bgOrden.add(rbFechaPoliza); bgOrden.add(rbPoliza);
        pnlOrden.add(rbFechaPoliza); pnlOrden.add(rbPoliza);
        
        pnlSel.add(pnlOrden);

        JButton btnFiltra = new JButton("Filtrar Información");
        btnFiltra.setBounds(700, 85, 170, 25);
        pnlSel.add(btnFiltra);

        dialogo.add(pnlSel);

        // --- 2. TABLA DEL LIBRO DIARIO ---
        JTable tblDiario = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Fecha", "Póliza", "Tipo", "Cuenta", "Concepto", "Descripción", "Cargo", "Abono"}
        ));
        tblDiario.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        
        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createEtchedBorder());
        pnlTabla.setBounds(10, 140, 885, 390);
        
        JScrollPane scrollDiario = new JScrollPane(tblDiario);
        scrollDiario.setBounds(10, 10, 865, 370);
        pnlTabla.add(scrollDiario);
        
        dialogo.add(pnlTabla);

        // --- 3. BOTONES INFERIORES ---
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(330, 550, 110, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(460, 550, 110, 40);

        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 4. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Extrayendo pólizas y organizando Libro de Diario... (Simulación)");
            // Aquí iría la consulta SQL con su respectivo 'ORDER BY'
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando Libro de Diario a la impresora... (Simulación)");
        });

        // --- 5. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLDiario;
    private javax.swing.JButton btnDeleteLDiario;
    private javax.swing.JButton btnEditLDiario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLDiario;
    // End of variables declaration//GEN-END:variables
}
