/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Libro_Diario extends javax.swing.JPanel {

    /**
     * Creates new form Libro_Diario
     */
    public Libro_Diario() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha de Consulta", "Rango de Fechas", "Orden", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblLDiario.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLDiario = new javax.swing.JTable();
        btnAddLDiario = new javax.swing.JButton();
        btnEditLDiario = new javax.swing.JButton();
        btnDeleteLDiario = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblLDiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLDiario);

        btnAddLDiario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddLDiario.setForeground(new java.awt.Color(26, 61, 99));
        btnAddLDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddLDiario.setText("Añadir");
        btnAddLDiario.addActionListener(this::btnAddLDiarioActionPerformed);

        btnEditLDiario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditLDiario.setForeground(new java.awt.Color(26, 61, 99));
        btnEditLDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditLDiario.setText("Editar");
        btnEditLDiario.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditLDiario.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditLDiario.addActionListener(this::btnEditLDiarioActionPerformed);

        btnDeleteLDiario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteLDiario.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteLDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteLDiario.setText("Eliminar");
        btnDeleteLDiario.addActionListener(this::btnDeleteLDiarioActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddLDiario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditLDiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteLDiario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditLDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteLDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLDiarioActionPerformed
        mostrarDialogoLibroDiario();
    }//GEN-LAST:event_btnAddLDiarioActionPerformed

    private void btnEditLDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLDiarioActionPerformed
JOptionPane.showMessageDialog(this, "Esta pantalla es de consulta y reportes. Para editar una póliza, usa el módulo 'Captura de Pólizas'.");
        
    }//GEN-LAST:event_btnEditLDiarioActionPerformed

    private void btnDeleteLDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLDiarioActionPerformed
       JOptionPane.showMessageDialog(this, "No se pueden alterar ni eliminar los registros contables desde el visor del Libro de Diario.");
    }//GEN-LAST:event_btnDeleteLDiarioActionPerformed
private void mostrarDialogoLibroDiario() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Libro de Diario", true);
        dialogo.setSize(920, 650);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- CLASE LOCAL BUSCADOR FLOTANTE ---
        class BuscadorFlotante {
            void configurar(JTextField txtClave, JTextField txtDesc, JButton boton, Object[][] datos, String[] columnas, int[] anchos) {
                Runnable mostrarPopup = () -> {
                    javax.swing.JPopupMenu popup = new javax.swing.JPopupMenu();
                    popup.setFocusable(false);
                    javax.swing.table.DefaultTableModel mod = new javax.swing.table.DefaultTableModel(datos, columnas) {
                        @Override public boolean isCellEditable(int r, int c) { return false; }
                    };
                    javax.swing.JTable tabla = new javax.swing.JTable(mod);
                    tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                    for (int i = 0; i < anchos.length; i++) {
                        tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                    }

                    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(mod);
                    tabla.setRowSorter(sorter);

                    tabla.addMouseListener(new java.awt.event.MouseAdapter() {
                        @Override
                        public void mouseReleased(java.awt.event.MouseEvent me) {
                            int viewRow = tabla.getSelectedRow();
                            if (viewRow != -1) {
                                int modelRow = tabla.convertRowIndexToModel(viewRow);
                                txtClave.setText(mod.getValueAt(modelRow, 0).toString());
                                if (txtDesc != null && mod.getColumnCount() >= 2) {
                                    txtDesc.setText(mod.getValueAt(modelRow, 1).toString());
                                }
                                popup.setVisible(false);
                            }
                        }
                    });
                    
                    int widthTotal = 0; for(int w : anchos) widthTotal += w;
                    javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(tabla);
                    scroll.setPreferredSize(new java.awt.Dimension(widthTotal + 20, 150));
                    popup.add(scroll);

                    String texto = txtClave.getText().trim();
                    if (!texto.isEmpty()) sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto));
                    popup.show(txtClave, 0, txtClave.getHeight());
                    txtClave.requestFocus();
                };

                boton.addActionListener(e -> { txtClave.setText(""); mostrarPopup.run(); });
                txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
                    @Override
                    public void keyReleased(java.awt.event.KeyEvent e) {
                        int c = e.getKeyCode();
                        if (c == 27 || c == 10 || c == 38 || c == 40 || c == 37 || c == 39 || c == 9) return;
                        mostrarPopup.run();
                    }
                });
            }
        }
        BuscadorFlotante buscador = new BuscadorFlotante();

        // --- CARGA DE DATOS DESDE LA BASE DE DATOS ---
        java.util.function.BiFunction<String, Integer, Object[][]> cargarDatosMultiple = (query, numCols) -> {
            java.util.List<Object[]> lista = new java.util.ArrayList<>();
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps = con.prepareStatement(query);
                    ResultSet rs = ps.executeQuery();
                    while(rs.next()) {
                        Object[] row = new Object[numCols];
                        for(int i=0; i<numCols; i++) row[i] = rs.getString(i+1);
                        lista.add(row);
                    }
                    rs.close(); ps.close(); db.Cerrar();
                }
            } catch(Exception e) {}
            return lista.toArray(new Object[0][0]);
        };

        // Carga de datos para buscadores
        Object[][] dContab = cargarDatosMultiple.apply("SELECT CVE, DES FROM tmclas WHERE TBL = 'TCONT' ORDER BY CVE", 2);
        Object[][] dMov    = cargarDatosMultiple.apply("SELECT CVE, DES FROM tmclas WHERE TBL = 'TPOL' ORDER BY CVE", 2);

        // --- 1. DATOS DE SELECCIÓN (Panel Superior) ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createEtchedBorder());
        pnlSel.setBounds(10, 10, 885, 120);

        // Bloque Izquierdo: Compañía (tmcias)
        pnlSel.add(new JLabel("Compañía")).setBounds(20, 15, 80, 25);
        JComboBox<String> cmbCia = new JComboBox<>();
        cmbCia.setBounds(100, 15, 60, 25);
        JLabel lblCiaDesc = new JLabel();
        lblCiaDesc.setBounds(170, 15, 250, 25);

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();
            if (con != null) {
                ResultSet rs = con.prepareStatement("SELECT CIA, NCIA FROM tmcias ORDER BY CIA").executeQuery();
                while(rs.next()){ 
                    cmbCia.addItem(rs.getString("CIA")); 
                    lblCiaDesc.setText(rs.getString("NCIA")); 
                }
                rs.close(); db.Cerrar();
            }
        } catch (Exception ex) {}

        pnlSel.add(cmbCia);
        pnlSel.add(lblCiaDesc);

        // Fechas con JDateChooser
        pnlSel.add(new JLabel("Fecha Inicial")).setBounds(20, 45, 80, 25);
        com.toedter.calendar.JDateChooser txtFecIni = new com.toedter.calendar.JDateChooser();
        txtFecIni.setDateFormatString("dd/MM/yyyy"); txtFecIni.setBounds(100, 45, 110, 25);
        pnlSel.add(txtFecIni);

        pnlSel.add(new JLabel("Fecha Final")).setBounds(20, 75, 80, 25);
        com.toedter.calendar.JDateChooser txtFecFin = new com.toedter.calendar.JDateChooser();
        txtFecFin.setDateFormatString("dd/MM/yyyy"); txtFecFin.setBounds(100, 75, 110, 25);
        pnlSel.add(txtFecFin);

        // Bloque Central: Tipo Contab. (TCONT)
        pnlSel.add(new JLabel("Tipo Contab.")).setBounds(450, 45, 100, 25);
        JTextField txtContab = new JTextField("MN"); txtContab.setBounds(550, 45, 50, 25);
        JButton btnContab = new JButton("▼"); btnContab.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10)); btnContab.setMargin(new java.awt.Insets(0, 0, 0, 0)); btnContab.setBounds(600, 45, 20, 25);
        buscador.configurar(txtContab, null, btnContab, dContab, new String[]{"Clave", "Descripción"}, new int[]{60, 200});
        pnlSel.add(txtContab); pnlSel.add(btnContab);

        // Bloque Central: Tipo de Movimiento (TPOL)
        pnlSel.add(new JLabel("Tipo de Movimiento")).setBounds(430, 75, 120, 25);
        JTextField txtMov = new JTextField(); txtMov.setBounds(550, 75, 50, 25);
        JButton btnMov = new JButton("▼"); btnMov.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10)); btnMov.setMargin(new java.awt.Insets(0, 0, 0, 0)); btnMov.setBounds(600, 75, 20, 25);
        buscador.configurar(txtMov, null, btnMov, dMov, new String[]{"Clave", "Descripción"}, new int[]{60, 220});
        pnlSel.add(txtMov); pnlSel.add(btnMov);

        // Bloque Derecho: Ordenar por
        JPanel pnlOrden = new JPanel(null);
        pnlOrden.setBorder(BorderFactory.createTitledBorder("Ordenar por"));
        pnlOrden.setBounds(690, 10, 180, 70);

        JRadioButton rbFechaPoliza = new JRadioButton("Fecha y Póliza", true);
        rbFechaPoliza.setBounds(10, 15, 150, 20);
        JRadioButton rbPoliza = new JRadioButton("Póliza");
        rbPoliza.setBounds(10, 40, 150, 20);

        ButtonGroup bgOrden = new ButtonGroup();
        bgOrden.add(rbFechaPoliza); bgOrden.add(rbPoliza);
        pnlOrden.add(rbFechaPoliza); pnlOrden.add(rbPoliza);
        
        pnlSel.add(pnlOrden);

        // Botón Filtrar
        JButton btnFiltra = new JButton("Filtrar Información");
        btnFiltra.setBounds(690, 85, 180, 25);
        pnlSel.add(btnFiltra);

        dialogo.add(pnlSel);

        // --- 2. TABLA DEL LIBRO DIARIO ---
        JTable tblDiario = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Fecha", "Póliza", "Tipo", "Cuenta", "Concepto", "Descripción", "Cargo", "Abono"}
        ));
        tblDiario.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        
        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createEtchedBorder());
        pnlTabla.setBounds(10, 140, 885, 390);
        
        JScrollPane scrollDiario = new JScrollPane(tblDiario);
        scrollDiario.setBounds(10, 10, 865, 370);
        pnlTabla.add(scrollDiario);
        
        dialogo.add(pnlTabla);

        // --- 3. BOTONES INFERIORES ---
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(330, 550, 110, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(460, 550, 110, 40);

        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 4. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Extrayendo pólizas y organizando Libro de Diario... (Simulación)");
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando Libro de Diario a la impresora... (Simulación)");
        });

        // --- 5. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLDiario;
    private javax.swing.JButton btnDeleteLDiario;
    private javax.swing.JButton btnEditLDiario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLDiario;
    // End of variables declaration//GEN-END:variables
}
