/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Libro_Mayor extends javax.swing.JPanel {

    /**
     * Creates new form Libro_Mayor
     */
    public Libro_Mayor() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha Consulta", "Año", "Período", "Rango de Cuentas", "Nivel", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblLMayor.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLMayor = new javax.swing.JTable();
        btnAddLMayor = new javax.swing.JButton();
        btnEditLMayor = new javax.swing.JButton();
        btnDeleteLMayor = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblLMayor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLMayor);

        btnAddLMayor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddLMayor.setForeground(new java.awt.Color(26, 61, 99));
        btnAddLMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddLMayor.setText("Añadir");
        btnAddLMayor.addActionListener(this::btnAddLMayorActionPerformed);

        btnEditLMayor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditLMayor.setForeground(new java.awt.Color(26, 61, 99));
        btnEditLMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditLMayor.setText("Editar");
        btnEditLMayor.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditLMayor.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditLMayor.addActionListener(this::btnEditLMayorActionPerformed);

        btnDeleteLMayor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteLMayor.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteLMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteLMayor.setText("Eliminar");
        btnDeleteLMayor.addActionListener(this::btnDeleteLMayorActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddLMayor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditLMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteLMayor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditLMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteLMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLMayorActionPerformed
       mostrarDialogoLibroMayor();
    }//GEN-LAST:event_btnAddLMayorActionPerformed

    private void btnEditLMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLMayorActionPerformed
        JOptionPane.showMessageDialog(this, "El Libro Mayor es un reporte calculado de solo lectura. No permite edición manual.");

    }//GEN-LAST:event_btnEditLMayorActionPerformed

    private void btnDeleteLMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLMayorActionPerformed
      JOptionPane.showMessageDialog(this, "No se pueden alterar ni eliminar registros desde el visor de reportes.");
    }//GEN-LAST:event_btnDeleteLMayorActionPerformed

private void mostrarDialogoLibroMayor() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Libro Mayor", true);
        dialogo.setSize(850, 600);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. DATOS DE SELECCIÓN (Panel Izquierdo/Central) ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createEtchedBorder());
        pnlSel.setBounds(10, 10, 680, 140);

        pnlSel.add(new JLabel("Compañía")).setBounds(20, 15, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12"})).setBounds(110, 15, 70, 25);
        pnlSel.add(new JLabel("UNIDAD ESCOLAR BENAVENTE, A.C.")).setBounds(190, 15, 250, 25);

        pnlSel.add(new JLabel("Tpo/No.SSubCta")).setBounds(20, 45, 100, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(110, 45, 70, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(190, 45, 120, 25);

        pnlSel.add(new JLabel("De la cuenta")).setBounds(20, 75, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(110, 75, 150, 25);

        pnlSel.add(new JLabel("A la cuenta")).setBounds(20, 105, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(110, 105, 150, 25);

        // Niveles (1 al 9)
        pnlSel.add(new JLabel("Nivel")).setBounds(20, 135, 50, 25); // Ajuste visual debajo de las cuentas
        ButtonGroup bgNivel = new ButtonGroup();
        int xPosNivel = 110;
        for (int i = 1; i <= 9; i++) {
            JRadioButton rb = new JRadioButton(String.valueOf(i));
            if(i == 2) rb.setSelected(true); // Seleccionado el nivel 2 por defecto en la imagen
            rb.setBounds(xPosNivel, 135, 40, 25);
            bgNivel.add(rb);
            pnlSel.add(rb);
            xPosNivel += 40;
        }

        // Tipo de Contabilidad y Moneda
        pnlSel.add(new JLabel("Tipo Contab.")).setBounds(480, 75, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{"MN"})).setBounds(560, 75, 70, 25);

        pnlSel.add(new JLabel("Moneda")).setBounds(480, 105, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{"MXP"})).setBounds(560, 105, 70, 25);

        // Ajustamos la altura del panel principal para que quepan los niveles
        pnlSel.setSize(680, 170);
        dialogo.add(pnlSel);

        // --- 2. AÑO Y PERIODO (Panel Derecho) ---
        JPanel pnlPeriodo = new JPanel(null);
        pnlPeriodo.setBorder(BorderFactory.createEtchedBorder());
        pnlPeriodo.setBounds(700, 10, 120, 90);

        pnlPeriodo.add(new JLabel("Año")).setBounds(15, 15, 40, 25);
        pnlPeriodo.add(new JTextField("2026")).setBounds(55, 15, 50, 25);

        pnlPeriodo.add(new JLabel("Período")).setBounds(15, 50, 50, 25);
        pnlPeriodo.add(new JTextField("5")).setBounds(65, 50, 40, 25);

        dialogo.add(pnlPeriodo);

        // --- BOTÓN FILTRAR ---
        JButton btnFiltra = new JButton("Filtrar Información");
        btnFiltra.setBounds(700, 110, 120, 30);
        dialogo.add(btnFiltra);

        // --- 3. TABLA DEL LIBRO MAYOR ---
        JTable tblMayor = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Cuenta", "Descripción", "Saldo Inicial", "Cargos", "Abonos", "Saldo Final"}
        ));
        tblMayor.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        
        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createEtchedBorder());
        pnlTabla.setBounds(10, 190, 815, 300);
        
        JScrollPane scrollMayor = new JScrollPane(tblMayor);
        scrollMayor.setBounds(10, 10, 795, 280);
        pnlTabla.add(scrollMayor);
        
        dialogo.add(pnlTabla);

        // --- 4. BOTONES INFERIORES ---
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(290, 510, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(420, 510, 100, 40);

        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Agrupando movimientos a nivel de Mayor... (Simulación)");
            // Aquí agregarías la consulta SQL para llenar tblMayor
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando el reporte del Libro Mayor a la impresora... (Simulación)");
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLMayor;
    private javax.swing.JButton btnDeleteLMayor;
    private javax.swing.JButton btnEditLMayor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLMayor;
    // End of variables declaration//GEN-END:variables
}
