/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Libro_Mayor extends javax.swing.JPanel {

    /**
     * Creates new form Libro_Mayor
     */
    public Libro_Mayor() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha Consulta", "Año", "Período", "Rango de Cuentas", "Nivel", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblLMayor.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLMayor = new javax.swing.JTable();
        btnAddLMayor = new javax.swing.JButton();
        btnEditLMayor = new javax.swing.JButton();
        btnDeleteLMayor = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblLMayor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLMayor);

        btnAddLMayor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddLMayor.setForeground(new java.awt.Color(26, 61, 99));
        btnAddLMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddLMayor.setText("Añadir");
        btnAddLMayor.addActionListener(this::btnAddLMayorActionPerformed);

        btnEditLMayor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditLMayor.setForeground(new java.awt.Color(26, 61, 99));
        btnEditLMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditLMayor.setText("Editar");
        btnEditLMayor.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditLMayor.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditLMayor.addActionListener(this::btnEditLMayorActionPerformed);

        btnDeleteLMayor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteLMayor.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteLMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteLMayor.setText("Eliminar");
        btnDeleteLMayor.addActionListener(this::btnDeleteLMayorActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddLMayor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditLMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteLMayor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditLMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteLMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLMayorActionPerformed
       mostrarDialogoLibroMayor();
    }//GEN-LAST:event_btnAddLMayorActionPerformed

    private void btnEditLMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLMayorActionPerformed
        JOptionPane.showMessageDialog(this, "El Libro Mayor es un reporte calculado de solo lectura. No permite edición manual.");

    }//GEN-LAST:event_btnEditLMayorActionPerformed

    private void btnDeleteLMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLMayorActionPerformed
      JOptionPane.showMessageDialog(this, "No se pueden alterar ni eliminar registros desde el visor de reportes.");
    }//GEN-LAST:event_btnDeleteLMayorActionPerformed

private void mostrarDialogoLibroMayor() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Libro Mayor", true);
        dialogo.setSize(850, 600);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- CLASE LOCAL BUSCADOR FLOTANTE ---
        class BuscadorFlotante {
            void configurar(JTextField txtClave, JTextField txtDesc, JButton boton, Object[][] datos, String[] columnas, int[] anchos) {
                Runnable mostrarPopup = () -> {
                    javax.swing.JPopupMenu popup = new javax.swing.JPopupMenu();
                    popup.setFocusable(false);
                    javax.swing.table.DefaultTableModel mod = new javax.swing.table.DefaultTableModel(datos, columnas) {
                        @Override public boolean isCellEditable(int r, int c) { return false; }
                    };
                    javax.swing.JTable tabla = new javax.swing.JTable(mod);
                    tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                    for (int i = 0; i < anchos.length; i++) {
                        tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                    }

                    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(mod);
                    tabla.setRowSorter(sorter);

                    tabla.addMouseListener(new java.awt.event.MouseAdapter() {
                        @Override
                        public void mouseReleased(java.awt.event.MouseEvent me) {
                            int viewRow = tabla.getSelectedRow();
                            if (viewRow != -1) {
                                int modelRow = tabla.convertRowIndexToModel(viewRow);
                                txtClave.setText(mod.getValueAt(modelRow, 0).toString());
                                if (txtDesc != null && mod.getColumnCount() >= 2) {
                                    txtDesc.setText(mod.getValueAt(modelRow, 1).toString());
                                }
                                popup.setVisible(false);
                            }
                        }
                    });
                    
                    int widthTotal = 0; for(int w : anchos) widthTotal += w;
                    javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(tabla);
                    scroll.setPreferredSize(new java.awt.Dimension(widthTotal + 20, 150));
                    popup.add(scroll);

                    String texto = txtClave.getText().trim();
                    if (!texto.isEmpty()) sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto));
                    popup.show(txtClave, 0, txtClave.getHeight());
                    txtClave.requestFocus();
                };

                boton.addActionListener(e -> { txtClave.setText(""); mostrarPopup.run(); });
                txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
                    @Override
                    public void keyReleased(java.awt.event.KeyEvent e) {
                        int c = e.getKeyCode();
                        if (c == 27 || c == 10 || c == 38 || c == 40 || c == 37 || c == 39 || c == 9) return;
                        mostrarPopup.run();
                    }
                });
            }
        }
        BuscadorFlotante buscador = new BuscadorFlotante();

        // --- CARGA DE DATOS DESDE LA BASE DE DATOS ---
        java.util.function.BiFunction<String, Integer, Object[][]> cargarDatosMultiple = (query, numCols) -> {
            java.util.List<Object[]> lista = new java.util.ArrayList<>();
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps = con.prepareStatement(query);
                    ResultSet rs = ps.executeQuery();
                    while(rs.next()) {
                        Object[] row = new Object[numCols];
                        for(int i=0; i<numCols; i++) row[i] = rs.getString(i+1);
                        lista.add(row);
                    }
                    rs.close(); ps.close(); db.Cerrar();
                }
            } catch(Exception e) {}
            return lista.toArray(new Object[0][0]);
        };

        // Carga de arreglos para buscadores
        Object[][] dTssc    = cargarDatosMultiple.apply("SELECT CVE, DES FROM tmclas WHERE TBL = 'TSSC' ORDER BY CVE", 2);
        Object[][] dCta     = cargarDatosMultiple.apply("SELECT CCTA, CDES FROM tmctas ORDER BY CCTA", 2);
        Object[][] dContab  = cargarDatosMultiple.apply("SELECT CVE, DES FROM tmclas WHERE TBL = 'TCONT' ORDER BY CVE", 2);
        Object[][] dMoneda  = cargarDatosMultiple.apply("SELECT CVE, DES FROM tmclas WHERE TBL = 'TMON' ORDER BY CVE", 2);

        // --- 1. DATOS DE SELECCIÓN (Panel Superior/Izquierdo) ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createEtchedBorder());
        pnlSel.setBounds(10, 10, 680, 170);

        // Compañía (tmcias)
        pnlSel.add(new JLabel("Compañía")).setBounds(20, 15, 80, 25);
        JComboBox<String> cmbCia = new JComboBox<>();
        cmbCia.setBounds(110, 15, 60, 25);
        JLabel lblCiaDesc = new JLabel();
        lblCiaDesc.setBounds(180, 15, 250, 25);

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();
            if (con != null) {
                ResultSet rs = con.prepareStatement("SELECT CIA, NCIA FROM tmcias ORDER BY CIA").executeQuery();
                while(rs.next()){ 
                    cmbCia.addItem(rs.getString("CIA")); 
                    lblCiaDesc.setText(rs.getString("NCIA")); 
                }
                rs.close(); db.Cerrar();
            }
        } catch (Exception ex) {}

        pnlSel.add(cmbCia);
        pnlSel.add(lblCiaDesc);

        // Buscador Tpo/No.SSubCta (TSSC)
        pnlSel.add(new JLabel("Tpo/No.SSubCta")).setBounds(20, 45, 100, 25);
        JTextField txtTssc = new JTextField(); txtTssc.setBounds(110, 45, 50, 25);
        JButton btnTssc = new JButton("▼"); btnTssc.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10)); btnTssc.setMargin(new java.awt.Insets(0, 0, 0, 0)); btnTssc.setBounds(160, 45, 20, 25);
        buscador.configurar(txtTssc, null, btnTssc, dTssc, new String[]{"Clave", "Descripción"}, new int[]{60, 150});
        
        JTextField txtNumSub = new JTextField(); txtNumSub.setBounds(190, 45, 80, 25);
        JButton btnNumSub = new JButton("▼"); btnNumSub.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10)); btnNumSub.setMargin(new java.awt.Insets(0, 0, 0, 0)); btnNumSub.setBounds(270, 45, 20, 25);
        
        pnlSel.add(txtTssc); pnlSel.add(btnTssc);
        pnlSel.add(txtNumSub); pnlSel.add(btnNumSub);

        // Buscador De la cuenta (tmctas)
        pnlSel.add(new JLabel("De la cuenta")).setBounds(20, 75, 80, 25);
        JTextField txtCtaIni = new JTextField(); txtCtaIni.setBounds(110, 75, 120, 25);
        JButton btnCtaIni = new JButton("▼"); btnCtaIni.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10)); btnCtaIni.setMargin(new java.awt.Insets(0, 0, 0, 0)); btnCtaIni.setBounds(230, 75, 20, 25);
        buscador.configurar(txtCtaIni, null, btnCtaIni, dCta, new String[]{"Clave", "Descripción"}, new int[]{110, 250});
        pnlSel.add(txtCtaIni); pnlSel.add(btnCtaIni);

        // Buscador A la cuenta (tmctas)
        pnlSel.add(new JLabel("A la cuenta")).setBounds(20, 105, 80, 25);
        JTextField txtCtaFin = new JTextField(); txtCtaFin.setBounds(110, 105, 120, 25);
        JButton btnCtaFin = new JButton("▼"); btnCtaFin.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10)); btnCtaFin.setMargin(new java.awt.Insets(0, 0, 0, 0)); btnCtaFin.setBounds(230, 105, 20, 25);
        buscador.configurar(txtCtaFin, null, btnCtaFin, dCta, new String[]{"Clave", "Descripción"}, new int[]{110, 250});
        pnlSel.add(txtCtaFin); pnlSel.add(btnCtaFin);

        // Niveles (Radio Buttons 1 al 9)
        pnlSel.add(new JLabel("Nivel")).setBounds(20, 135, 50, 25);
        ButtonGroup bgNivel = new ButtonGroup();
        int xPosNivel = 110;
        for (int i = 1; i <= 9; i++) {
            JRadioButton rb = new JRadioButton(String.valueOf(i));
            if(i == 2) rb.setSelected(true); // Nivel 2 por defecto
            rb.setBounds(xPosNivel, 135, 40, 25);
            bgNivel.add(rb);
            pnlSel.add(rb);
            xPosNivel += 40;
        }

        // Buscador Tipo Contab. (TCONT)
        pnlSel.add(new JLabel("Tipo Contab.")).setBounds(480, 75, 80, 25);
        JTextField txtContab = new JTextField("MN"); txtContab.setBounds(560, 75, 40, 25);
        JButton btnContab = new JButton("▼"); btnContab.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10)); btnContab.setMargin(new java.awt.Insets(0, 0, 0, 0)); btnContab.setBounds(600, 75, 20, 25);
        buscador.configurar(txtContab, null, btnContab, dContab, new String[]{"Clave", "Descripción"}, new int[]{60, 200});
        pnlSel.add(txtContab); pnlSel.add(btnContab);

        // Buscador Moneda (TMON)
        pnlSel.add(new JLabel("Moneda")).setBounds(480, 105, 80, 25);
        JTextField txtMoneda = new JTextField("MXP"); txtMoneda.setBounds(560, 105, 40, 25);
        JButton btnMoneda = new JButton("▼"); btnMoneda.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10)); btnMoneda.setMargin(new java.awt.Insets(0, 0, 0, 0)); btnMoneda.setBounds(600, 105, 20, 25);
        buscador.configurar(txtMoneda, null, btnMoneda, dMoneda, new String[]{"Clave", "Descripción"}, new int[]{60, 150});
        pnlSel.add(txtMoneda); pnlSel.add(btnMoneda);

        dialogo.add(pnlSel);

        // --- 2. AÑO Y PERIODO (Panel Derecho) ---
        JPanel pnlPeriodo = new JPanel(null);
        pnlPeriodo.setBorder(BorderFactory.createEtchedBorder());
        pnlPeriodo.setBounds(700, 10, 125, 90);

        pnlPeriodo.add(new JLabel("Año")).setBounds(15, 15, 40, 25);
        pnlPeriodo.add(new JTextField("2026")).setBounds(55, 15, 50, 25);

        pnlPeriodo.add(new JLabel("Período")).setBounds(15, 50, 50, 25);
        pnlPeriodo.add(new JTextField("5")).setBounds(65, 50, 40, 25);

        dialogo.add(pnlPeriodo);

        // --- BOTÓN FILTRAR ---
        JButton btnFiltra = new JButton("Filtrar Información");
        btnFiltra.setBounds(700, 110, 125, 30);
        dialogo.add(btnFiltra);

        // --- 3. TABLA DEL LIBRO MAYOR ---
        JTable tblMayor = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Cuenta", "Descripción", "Saldo Inicial", "Cargos", "Abonos", "Saldo Final"}
        ));
        tblMayor.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        
        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createEtchedBorder());
        pnlTabla.setBounds(10, 190, 815, 300);
        
        JScrollPane scrollMayor = new JScrollPane(tblMayor);
        scrollMayor.setBounds(10, 10, 795, 280);
        pnlTabla.add(scrollMayor);
        
        dialogo.add(pnlTabla);

        // --- 4. BOTONES INFERIORES ---
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(290, 510, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(420, 510, 100, 40);

        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Agrupando movimientos a nivel de Mayor... (Simulación)");
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando el reporte del Libro Mayor a la impresora... (Simulación)");
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLMayor;
    private javax.swing.JButton btnDeleteLMayor;
    private javax.swing.JButton btnEditLMayor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLMayor;
    // End of variables declaration//GEN-END:variables
}
