/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Parametros_Compañia extends javax.swing.JPanel {

    /**
     * Creates new form Parametros_Compañia
     */
    public Parametros_Compañia() {
   initComponents();
        cargarTablaParametros();
    }
private void cargarTablaParametros() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Compañía", "Año", "Periodo", "Póliza", "Orden de", "Remisión", "Rec.Pago", "Orden de Comp.", "Aut.Vtas.", "Aut.Compras", "Usuario", "Fecha Mod.", "Hora Mod."}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblPCompañia.setModel(modelo);

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                // Consulta con los campos reales de tgpram
                String sql = "SELECT CIAACT, ANO, NPER, NPOL, ORDVEN, NUMREM, CONPAGSIG, CONCOMP, AUTFAC, AUTCOM, USER, FEAC, HOAC FROM tgpram";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[13]; 
                    fila[0] = rs.getString("CIAACT");
                    fila[1] = rs.getString("ANO");
                    fila[2] = rs.getString("NPER");
                    fila[3] = rs.getString("NPOL");
                    fila[4] = rs.getString("ORDVEN");
                    fila[5] = rs.getString("NUMREM");
                    fila[6] = rs.getString("CONPAGSIG");
                    fila[7] = rs.getString("CONCOMP");
                    fila[8] = rs.getString("AUTFAC");
                    fila[9] = rs.getString("AUTCOM");
                    fila[10] = rs.getString("USER");
                    fila[11] = rs.getString("FEAC");
                    fila[12] = rs.getString("HOAC");
                    modelo.addRow(fila);
                }
                rs.close(); ps.close(); db.Cerrar();
                
                adaptarTamañoColumnas();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla de Parámetros: " + e.getMessage());
        }
    }

    private void adaptarTamañoColumnas() {
        tblPCompañia.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        for (int i = 0; i < tblPCompañia.getColumnCount(); i++) {
            javax.swing.table.TableColumn columna = tblPCompañia.getColumnModel().getColumn(i);
            int anchoPreferido = 60; 
            java.awt.Component compCabecera = tblPCompañia.getTableHeader().getDefaultRenderer()
                    .getTableCellRendererComponent(tblPCompañia, columna.getHeaderValue(), false, false, 0, i);
            anchoPreferido = Math.max(anchoPreferido, compCabecera.getPreferredSize().width + 10);
            columna.setPreferredWidth(anchoPreferido); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddPCompañia = new javax.swing.JButton();
        btnEditPCompañia = new javax.swing.JButton();
        btnDeletePCompañia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPCompañia = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAddPCompañia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddPCompañia.setForeground(new java.awt.Color(26, 61, 99));
        btnAddPCompañia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddPCompañia.setText("Añadir");
        btnAddPCompañia.addActionListener(this::btnAddPCompañiaActionPerformed);

        btnEditPCompañia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditPCompañia.setForeground(new java.awt.Color(26, 61, 99));
        btnEditPCompañia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditPCompañia.setText("Editar");
        btnEditPCompañia.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditPCompañia.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditPCompañia.addActionListener(this::btnEditPCompañiaActionPerformed);

        btnDeletePCompañia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeletePCompañia.setForeground(new java.awt.Color(26, 61, 99));
        btnDeletePCompañia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeletePCompañia.setText("Eliminar");
        btnDeletePCompañia.addActionListener(this::btnDeletePCompañiaActionPerformed);

        tblPCompañia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Compañia", "Año", "Periodo", "Poliza", "Orden", "Remision", "Rec. Pago", "Orden de Comp.", "Aut. Ventas", "Aut. Compras", "Usuario", "Fecha Mod.", "Hora Mod."
            }
        ));
        jScrollPane1.setViewportView(tblPCompañia);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddPCompañia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditPCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeletePCompañia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditPCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletePCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPCompañiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPCompañiaActionPerformed
   mostrarDialogoParametros(false);
    }//GEN-LAST:event_btnAddPCompañiaActionPerformed

    private void btnEditPCompañiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPCompañiaActionPerformed
  if (tblPCompañia.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un parámetro para editar.");
            return;
        }
        mostrarDialogoParametros(true);
    }//GEN-LAST:event_btnEditPCompañiaActionPerformed

    private void btnDeletePCompañiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePCompañiaActionPerformed
    int fila = tblPCompañia.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una Compañía para eliminar sus parámetros.");
            return;
        }

        String cia = tblPCompañia.getValueAt(fila, 0).toString();
        
        int resp = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar los parámetros de la compañía " + cia + "?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps = con.prepareStatement("DELETE FROM tgpram WHERE CIAACT = ?");
                    ps.setString(1, cia);
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Parámetros eliminados correctamente.");
                        cargarTablaParametros(); 
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeletePCompañiaActionPerformed
  private void mostrarDialogoParametros(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Parámetros" : "Agregar Parámetros";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(750, 600); 
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- ENCABEZADO ---
        JPanel pnlHeader = new JPanel(null);
        pnlHeader.setBorder(BorderFactory.createEtchedBorder());
        pnlHeader.setBounds(10, 10, 715, 40);

        JLabel lblCia = new JLabel("Compañía");
        lblCia.setBounds(20, 10, 70, 20);
        JComboBox<String> cmbCia = new JComboBox<>();
        cmbCia.setBounds(90, 10, 250, 20);
        
        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();
            if (con != null) {
                ResultSet rs = con.prepareStatement("SELECT CIA, NCIA FROM tmcias").executeQuery();
                while (rs.next()) cmbCia.addItem(rs.getString("CIA") + " - " + rs.getString("NCIA"));
                rs.close(); db.Cerrar();
            }
        } catch (Exception ex) {}

        pnlHeader.add(lblCia);
        pnlHeader.add(cmbCia);
        dialogo.add(pnlHeader);

        // --- PESTAÑAS PRINCIPALES ---
        JTabbedPane pestanas = new JTabbedPane();
        pestanas.setBounds(10, 60, 715, 450);

        // --- 1. PESTAÑA: CONTABILIDAD ---
        JPanel pnlContabilidad = new JPanel(null);
        
        JPanel pnlDocsCont = new JPanel(null);
        pnlDocsCont.setBorder(BorderFactory.createTitledBorder("Documentos Contables"));
        pnlDocsCont.setBounds(10, 10, 320, 100);

        JLabel lblPolSigue = new JLabel("Póliza Siguiente");
        lblPolSigue.setBounds(20, 25, 110, 20);
        JTextField txtPolSigue = new JTextField("1");
        txtPolSigue.setBounds(130, 25, 100, 20);

        JLabel lblRecPagoSigue = new JLabel("Rec. Pago Siguiente");
        lblRecPagoSigue.setBounds(20, 60, 110, 20);
        JTextField txtRecPagoSigue = new JTextField("1");
        txtRecPagoSigue.setBounds(130, 60, 100, 20);

        pnlDocsCont.add(lblPolSigue); pnlDocsCont.add(txtPolSigue);
        pnlDocsCont.add(lblRecPagoSigue); pnlDocsCont.add(txtRecPagoSigue);

        JPanel pnlPeriodo = new JPanel(null);
        pnlPeriodo.setBorder(BorderFactory.createTitledBorder("Periodo Actual"));
        pnlPeriodo.setBounds(350, 10, 340, 100);
        
        JLabel lblAnio = new JLabel("Año");
        lblAnio.setBounds(50, 40, 30, 20);
        JTextField txtAnio = new JTextField("2026");
        txtAnio.setBounds(90, 40, 60, 20);
        
        JLabel lblPeriodo = new JLabel("Periodo");
        lblPeriodo.setBounds(180, 40, 50, 20);
        JTextField txtPeriodo = new JTextField("1");
        txtPeriodo.setBounds(240, 40, 60, 20);
        
        pnlPeriodo.add(lblAnio); pnlPeriodo.add(txtAnio);
        pnlPeriodo.add(lblPeriodo); pnlPeriodo.add(txtPeriodo);

        JPanel pnlInfoDefCont = new JPanel(null);
        pnlInfoDefCont.setBorder(BorderFactory.createTitledBorder("Información Default"));
        pnlInfoDefCont.setBounds(10, 120, 320, 130);
        
        JLabel lblCveImp = new JLabel("Clave de Impuesto");
        lblCveImp.setBounds(20, 30, 120, 20);
        JComboBox<String> cmbCveImp = new JComboBox<>(new String[]{"", "IVA16C", "IVA0C"});
        cmbCveImp.setBounds(140, 30, 100, 20);
        cmbCveImp.setEditable(true);
        pnlInfoDefCont.add(lblCveImp); pnlInfoDefCont.add(cmbCveImp);

        JPanel pnlAutCont = new JPanel(null);
        pnlAutCont.setBorder(BorderFactory.createTitledBorder("Autorizaciones"));
        pnlAutCont.setBounds(350, 120, 340, 130);

        JCheckBox chkAutVtas = new JCheckBox("Autorización en Ventas");
        chkAutVtas.setBounds(20, 30, 200, 20);
        
        JCheckBox chkAutCompras = new JCheckBox("Autorización en Compras");
        chkAutCompras.setBounds(20, 65, 200, 20);

        pnlAutCont.add(chkAutVtas);
        pnlAutCont.add(chkAutCompras);

        pnlContabilidad.add(pnlDocsCont); pnlContabilidad.add(pnlPeriodo);
        pnlContabilidad.add(pnlInfoDefCont); pnlContabilidad.add(pnlAutCont);

        // --- 2. PESTAÑA: FACTURACIÓN ---
        JPanel pnlFacturacion = new JPanel(null);
        
        JPanel pnlConsecFact = new JPanel(null);
        pnlConsecFact.setBorder(BorderFactory.createTitledBorder("Consecutivos Documentos"));
        pnlConsecFact.setBounds(10, 10, 340, 180);
        
        JLabel lblOrdVen = new JLabel("Orden de Venta"); lblOrdVen.setBounds(10, 30, 110, 20);
        JTextField txtOrdVenSig = new JTextField("1"); txtOrdVenSig.setBounds(130, 30, 70, 20);

        JLabel lblRemision = new JLabel("Remisión"); lblRemision.setBounds(10, 65, 110, 20);
        JTextField txtRemSig = new JTextField("1"); txtRemSig.setBounds(130, 65, 70, 20);

        JLabel lblOrdComp = new JLabel("Orden de Compra"); lblOrdComp.setBounds(10, 100, 110, 20);
        JTextField txtOrdCompSig = new JTextField("1"); txtOrdCompSig.setBounds(130, 100, 70, 20);
        
        pnlConsecFact.add(lblOrdVen); pnlConsecFact.add(txtOrdVenSig); 
        pnlConsecFact.add(lblRemision); pnlConsecFact.add(txtRemSig); 
        pnlConsecFact.add(lblOrdComp); pnlConsecFact.add(txtOrdCompSig); 

        JPanel pnlInfoDefFact = new JPanel(null);
        pnlInfoDefFact.setBorder(BorderFactory.createTitledBorder("Información Default"));
        pnlInfoDefFact.setBounds(10, 200, 340, 200);
        
        JLabel lblMoneda = new JLabel("Moneda"); lblMoneda.setBounds(20, 30, 60, 20);
        JComboBox<String> cmbMoneda = new JComboBox<>(new String[]{"MXP", "USD"}); cmbMoneda.setBounds(90, 30, 80, 20);
        
        JLabel lblMetPago = new JLabel("Met Pago"); lblMetPago.setBounds(20, 70, 60, 20);
        JComboBox<String> cmbMetPago = new JComboBox<>(new String[]{"PUE", "PPD"}); cmbMetPago.setBounds(90, 70, 80, 20);
        
        pnlInfoDefFact.add(lblMoneda); pnlInfoDefFact.add(cmbMoneda);
        pnlInfoDefFact.add(lblMetPago); pnlInfoDefFact.add(cmbMetPago);

        pnlFacturacion.add(pnlConsecFact); 
        pnlFacturacion.add(pnlInfoDefFact);

        pestanas.addTab("Contabilidad", pnlContabilidad);
        pestanas.addTab("Facturación", pnlFacturacion);
        
        dialogo.add(pestanas);

        // --- BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(250, 515, 100, 35);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(400, 515, 100, 35);

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        // --- CARGAR DATOS SI ES MODO EDICIÓN ---
        if (modoEdicion) {
            int fila = tblPCompañia.getSelectedRow();
            String ciaFila = tblPCompañia.getValueAt(fila, 0).toString();
            cmbCia.setEnabled(false);
            
            for (int i = 0; i < cmbCia.getItemCount(); i++) {
                if (cmbCia.getItemAt(i).startsWith(ciaFila)) {
                    cmbCia.setSelectedIndex(i); break;
                }
            }
            
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    PreparedStatement ps = con.prepareStatement("SELECT ANO, NPER, NPOL, CIMP, ORDVEN, NUMREM, CONPAGSIG, CONCOMP, AUTFAC, AUTCOM, CMON, METPAG FROM tgpram WHERE CIAACT = ?");
                    ps.setString(1, ciaFila);
                    ResultSet rs = ps.executeQuery();
                    
                    if (rs.next()) {
                        txtAnio.setText(String.valueOf(rs.getInt("ANO")));
                        txtPeriodo.setText(String.valueOf(rs.getInt("NPER")));
                        txtPolSigue.setText(String.valueOf(rs.getInt("NPOL")));
                        txtRecPagoSigue.setText(String.valueOf(rs.getInt("CONPAGSIG")));
                        cmbCveImp.setSelectedItem(rs.getString("CIMP") != null ? rs.getString("CIMP") : "");
                        txtOrdVenSig.setText(String.valueOf(rs.getInt("ORDVEN")));
                        txtRemSig.setText(String.valueOf(rs.getInt("NUMREM")));
                        txtOrdCompSig.setText(String.valueOf(rs.getInt("CONCOMP")));
                        
                        chkAutVtas.setSelected("S".equalsIgnoreCase(rs.getString("AUTFAC")) || "1".equals(rs.getString("AUTFAC")));
                        chkAutCompras.setSelected("S".equalsIgnoreCase(rs.getString("AUTCOM")) || "1".equals(rs.getString("AUTCOM")));

                        cmbMoneda.setSelectedItem(rs.getString("CMON") != null ? rs.getString("CMON") : "MXP");
                        cmbMetPago.setSelectedItem(rs.getString("METPAG") != null ? rs.getString("METPAG") : "PUE");
                    }
                    rs.close(); ps.close(); db.Cerrar();
                }
            } catch (Exception e) {}
        }

        // --- EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnAceptar.addActionListener(e -> {
            if (cmbCia.getSelectedItem() == null) return;
            String ciaRaw = cmbCia.getSelectedItem().toString();
            String cia = ciaRaw.split(" - ")[0].trim();
            
            String anioStr = txtAnio.getText().trim();
            String periodoStr = txtPeriodo.getText().trim();
            String polizaStr = txtPolSigue.getText().trim();
            String recPagoStr = txtRecPagoSigue.getText().trim();
            String cveImp = cmbCveImp.getSelectedItem() != null ? cmbCveImp.getSelectedItem().toString().trim() : "";
            String ordVenStr = txtOrdVenSig.getText().trim();
            String remisionStr = txtRemSig.getText().trim();
            String ordCompStr = txtOrdCompSig.getText().trim();
            
            String autFac = chkAutVtas.isSelected() ? "S" : "N";
            String autCom = chkAutCompras.isSelected() ? "S" : "N";

            String moneda = cmbMoneda.getSelectedItem() != null ? cmbMoneda.getSelectedItem().toString().trim() : "";
            String metPago = cmbMetPago.getSelectedItem() != null ? cmbMetPago.getSelectedItem().toString().trim() : "";

            if (anioStr.isEmpty() || periodoStr.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "El Año y Periodo son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int anio = 2026, periodo = 1, poliza = 1, recPago = 1, ordVen = 1, remision = 1, ordComp = 1;
            try {
                anio = Integer.parseInt(anioStr);
                periodo = Integer.parseInt(periodoStr);
                poliza = Integer.parseInt(polizaStr);
                recPago = Integer.parseInt(recPagoStr);
                ordVen = Integer.parseInt(ordVenStr);
                remision = Integer.parseInt(remisionStr);
                ordComp = Integer.parseInt(ordCompStr);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(dialogo, "Asegúrese de ingresar valores numéricos válidos en folios, año y periodo.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {

                    // 4. VALIDACIÓN DE DUPLICADOS AL INSERTAR
                    if (!modoEdicion) {
                        String sqlCheck = "SELECT 1 FROM tgpram WHERE CIAACT = ?";
                        PreparedStatement psCheck = con.prepareStatement(sqlCheck);
                        psCheck.setString(1, cia);
                        ResultSet rsCheck = psCheck.executeQuery();
                        if (rsCheck.next()) {
                            JOptionPane.showMessageDialog(dialogo, "Los parámetros de la compañía " + cia + " ya existen.", "Registro Duplicado", JOptionPane.WARNING_MESSAGE);
                            rsCheck.close(); psCheck.close(); db.Cerrar();
                            return;
                        }
                        rsCheck.close(); psCheck.close();
                    }

                    PreparedStatement ps;
                    if (modoEdicion) {
                        // 1. INCLUYE AUDITORÍA (USER, FEAC, HOAC)
                        String sql = "UPDATE tgpram SET ANO=?, NPER=?, NPOL=?, CONPAGSIG=?, CIMP=?, ORDVEN=?, NUMREM=?, CONCOMP=?, AUTFAC=?, AUTCOM=?, CMON=?, METPAG=?, "
                                + "USER='Admin', FEAC=CURDATE(), HOAC=DATE_FORMAT(NOW(), '%r') "
                                + "WHERE CIAACT=?";
                        ps = con.prepareStatement(sql);
                        ps.setInt(1, anio);
                        ps.setInt(2, periodo);
                        ps.setInt(3, poliza);
                        ps.setInt(4, recPago);
                        ps.setString(5, cveImp);
                        ps.setInt(6, ordVen);
                        ps.setInt(7, remision);
                        ps.setInt(8, ordComp);
                        ps.setString(9, autFac);
                        ps.setString(10, autCom);
                        ps.setString(11, moneda);
                        ps.setString(12, metPago);
                        ps.setString(13, cia);
                    } else {
                        // 1. INCLUYE AUDITORÍA (USER, FEAC, HOAC)
                        String sql = "INSERT INTO tgpram (CIAACT, ANO, NPER, NPOL, CONPAGSIG, CIMP, ORDVEN, NUMREM, CONCOMP, AUTFAC, AUTCOM, CMON, METPAG, USER, FEAC, HOAC) "
                                + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?, 'Admin', CURDATE(), DATE_FORMAT(NOW(), '%r'))";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, cia);
                        ps.setInt(2, anio);
                        ps.setInt(3, periodo);
                        ps.setInt(4, poliza);
                        ps.setInt(5, recPago);
                        ps.setString(6, cveImp);
                        ps.setInt(7, ordVen);
                        ps.setInt(8, remision);
                        ps.setInt(9, ordComp);
                        ps.setString(10, autFac);
                        ps.setString(11, autCom);
                        ps.setString(12, moneda);
                        ps.setString(13, metPago);
                    }

                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(dialogo, "Parámetros guardados con éxito.");
                        dialogo.dispose();
                        cargarTablaParametros();
                    } else {
                        JOptionPane.showMessageDialog(dialogo, "No se pudo guardar la información.");
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialogo, "Error SQL: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        // --- MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPCompañia;
    private javax.swing.JButton btnDeletePCompañia;
    private javax.swing.JButton btnEditPCompañia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPCompañia;
    // End of variables declaration//GEN-END:variables
}
