/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Poliza_Diario extends javax.swing.JPanel {

    /**
     * Creates new form Poliza_Diario
     */
    public Poliza_Diario() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha de Consulta", "Rango de Fechas", "Opción de Impresión", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblPDiario.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPDiario = new javax.swing.JTable();
        btnAddPDiario = new javax.swing.JButton();
        btnEditPDiario = new javax.swing.JButton();
        btnDeletePDiario = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblPDiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPDiario);

        btnAddPDiario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddPDiario.setForeground(new java.awt.Color(26, 61, 99));
        btnAddPDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddPDiario.setText("Añadir");
        btnAddPDiario.addActionListener(this::btnAddPDiarioActionPerformed);

        btnEditPDiario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditPDiario.setForeground(new java.awt.Color(26, 61, 99));
        btnEditPDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditPDiario.setText("Editar");
        btnEditPDiario.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditPDiario.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditPDiario.addActionListener(this::btnEditPDiarioActionPerformed);

        btnDeletePDiario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeletePDiario.setForeground(new java.awt.Color(26, 61, 99));
        btnDeletePDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeletePDiario.setText("Eliminar");
        btnDeletePDiario.addActionListener(this::btnDeletePDiarioActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddPDiario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditPDiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeletePDiario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditPDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletePDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPDiarioActionPerformed
      mostrarDialogoPolizaDiario();
    }//GEN-LAST:event_btnAddPDiarioActionPerformed

    private void btnEditPDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPDiarioActionPerformed
        JOptionPane.showMessageDialog(this, "Esta pantalla es de generación de reportes. Las pólizas deben editarse desde 'Captura de Pólizas'.");
    }//GEN-LAST:event_btnEditPDiarioActionPerformed

    private void btnDeletePDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePDiarioActionPerformed
     JOptionPane.showMessageDialog(this, "No se pueden eliminar pólizas desde el generador de reportes.");
    }//GEN-LAST:event_btnDeletePDiarioActionPerformed
private void mostrarDialogoPolizaDiario() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Póliza de Diario", true);
        dialogo.setSize(850, 600);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. DATOS DE SELECCIÓN (Panel Superior Integrado) ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createEtchedBorder());
        pnlSel.setBounds(10, 10, 815, 130);

        // Bloque Izquierdo
        pnlSel.add(new JLabel("Compañía")).setBounds(20, 15, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12"})).setBounds(110, 15, 70, 25);
        pnlSel.add(new JLabel("UNIDAD ESCOLAR BENAVENTE, A.C.")).setBounds(190, 15, 250, 25);

        pnlSel.add(new JLabel("Fecha Inicial")).setBounds(20, 50, 80, 25);
        pnlSel.add(new JTextField("04/06/2026")).setBounds(110, 50, 100, 25);

        pnlSel.add(new JLabel("Fecha Final")).setBounds(20, 85, 80, 25);
        pnlSel.add(new JTextField("04/06/2026")).setBounds(110, 85, 100, 25);

        // Bloque Central
        pnlSel.add(new JLabel("Tipo de Moneda")).setBounds(390, 50, 100, 25);
        pnlSel.add(new JComboBox<>(new String[]{"MXP"})).setBounds(490, 50, 70, 25);

        pnlSel.add(new JLabel("Tipo Contab.")).setBounds(390, 85, 100, 25);
        pnlSel.add(new JComboBox<>(new String[]{"MN"})).setBounds(490, 85, 70, 25);

        // Bloque Derecho (Opciones de Impresión)
        JPanel pnlOpciones = new JPanel(null);
        pnlOpciones.setBorder(BorderFactory.createTitledBorder("Opción de Impresión"));
        pnlOpciones.setBounds(630, 10, 170, 80);

        JRadioButton rbResumen = new JRadioButton("Resumen", true);
        rbResumen.setBounds(10, 15, 100, 20);
        JRadioButton rbDetalle = new JRadioButton("Detalle");
        rbDetalle.setBounds(10, 35, 100, 20);
        JRadioButton rbAmbos = new JRadioButton("Ambos");
        rbAmbos.setBounds(10, 55, 100, 20);

        ButtonGroup bgOpciones = new ButtonGroup();
        bgOpciones.add(rbResumen); bgOpciones.add(rbDetalle); bgOpciones.add(rbAmbos);
        
        pnlOpciones.add(rbResumen); pnlOpciones.add(rbDetalle); pnlOpciones.add(rbAmbos);
        pnlSel.add(pnlOpciones);

        JButton btnFiltra = new JButton("Filtrar Información");
        btnFiltra.setBounds(630, 95, 170, 25);
        pnlSel.add(btnFiltra);

        dialogo.add(pnlSel);

        // --- 2. TABLA DE REPORTE ---
        JTable tblReporte = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Fecha", "Tipo", "Póliza", "Concepto", "Cargos", "Abonos"}
        ));
        tblReporte.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        
        JScrollPane scrollReporte = new JScrollPane(tblReporte);
        scrollReporte.setBounds(10, 150, 815, 330);
        dialogo.add(scrollReporte);

        // --- 3. BOTONES INFERIORES ---
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(290, 500, 110, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(440, 500, 110, 40);

        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 4. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Extrayendo pólizas de diario desde la base de datos... (Simulación)");
            // Aquí iría tu lógica SQL para llenar la tabla
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando el reporte de Póliza de Diario a la impresora... (Simulación)");
        });

        // --- 5. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPDiario;
    private javax.swing.JButton btnDeletePDiario;
    private javax.swing.JButton btnEditPDiario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPDiario;
    // End of variables declaration//GEN-END:variables
}
