/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTabbedPane;
/**
 *
 * @author b17za
 */
public class Reeimpresion_Recibos extends javax.swing.JPanel {

    /**
     * Creates new form Reeimpresion_Recibos
     */
    public Reeimpresion_Recibos() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha Reimpresión", "Rango de Recibos", "Compañía", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblRRecibos.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRRecibos = new javax.swing.JTable();
        btnAddRRecibos = new javax.swing.JButton();
        btnEditRRecibos = new javax.swing.JButton();
        btnDeleteRRecibos = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblRRecibos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRRecibos);

        btnAddRRecibos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddRRecibos.setForeground(new java.awt.Color(26, 61, 99));
        btnAddRRecibos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddRRecibos.setText("Añadir");
        btnAddRRecibos.addActionListener(this::btnAddRRecibosActionPerformed);

        btnEditRRecibos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditRRecibos.setForeground(new java.awt.Color(26, 61, 99));
        btnEditRRecibos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditRRecibos.setText("Editar");
        btnEditRRecibos.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditRRecibos.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditRRecibos.addActionListener(this::btnEditRRecibosActionPerformed);

        btnDeleteRRecibos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteRRecibos.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteRRecibos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteRRecibos.setText("Eliminar");
        btnDeleteRRecibos.addActionListener(this::btnDeleteRRecibosActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddRRecibos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditRRecibos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteRRecibos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRRecibos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditRRecibos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteRRecibos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRRecibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRRecibosActionPerformed
      mostrarDialogoReimpresion();
    }//GEN-LAST:event_btnAddRRecibosActionPerformed

    private void btnEditRRecibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRRecibosActionPerformed
        JOptionPane.showMessageDialog(this, "Esta pantalla es exclusivamente para reimpresión. Si deseas editar un recibo, dirígete al módulo de cobranza.");
    }//GEN-LAST:event_btnEditRRecibosActionPerformed

    private void btnDeleteRRecibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRRecibosActionPerformed
        JOptionPane.showMessageDialog(this, "No se pueden eliminar recibos desde este módulo. Usa el módulo de Cancelación de Recibos.");
    }//GEN-LAST:event_btnDeleteRRecibosActionPerformed
   
    private void mostrarDialogoReimpresion() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Reimpresión de Recibos", true);
        dialogo.setSize(520, 390);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. PESTAÑA PRINCIPAL ---
        JTabbedPane pestanas = new JTabbedPane();
        pestanas.setBounds(10, 10, 485, 280);

        JPanel pnlImpresion = new JPanel(null);

        // --- CAMPOS SUPERIORES ---
        pnlImpresion.add(new JLabel("Compañía")).setBounds(30, 20, 100, 25);
        pnlImpresion.add(new JComboBox<>(new String[]{"12"})).setBounds(140, 20, 80, 25);

        pnlImpresion.add(new JLabel("Centro de Costo")).setBounds(30, 55, 100, 25);
        pnlImpresion.add(new JComboBox<>(new String[]{"12100"})).setBounds(140, 55, 80, 25);

        pnlImpresion.add(new JLabel("Desde Número")).setBounds(30, 90, 100, 25);
        pnlImpresion.add(new JTextField()).setBounds(140, 90, 80, 25);

        pnlImpresion.add(new JLabel("A")).setBounds(250, 90, 20, 25);
        pnlImpresion.add(new JTextField()).setBounds(280, 90, 80, 25);

        pnlImpresion.add(new JLabel("Fecha Inicial")).setBounds(30, 125, 100, 25);
        pnlImpresion.add(new JTextField("04/06/2026")).setBounds(140, 125, 90, 25);

        pnlImpresion.add(new JLabel("Fecha Final")).setBounds(250, 125, 80, 25);
        pnlImpresion.add(new JTextField("04/06/2026")).setBounds(330, 125, 90, 25);

        // --- 2. TIPO DE CUENTA ---
        JPanel pnlTipoCta = new JPanel(null);
        pnlTipoCta.setBorder(BorderFactory.createTitledBorder("Tipo de Cuenta"));
        pnlTipoCta.setBounds(30, 165, 190, 75);

        JRadioButton rbOficial = new JRadioButton("Oficial", true);
        rbOficial.setBounds(20, 15, 100, 20);
        JRadioButton rbPart = new JRadioButton("Particular");
        rbPart.setBounds(20, 40, 100, 20);

        ButtonGroup bgTipo = new ButtonGroup();
        bgTipo.add(rbOficial); bgTipo.add(rbPart);
        pnlTipoCta.add(rbOficial); pnlTipoCta.add(rbPart);
        
        pnlImpresion.add(pnlTipoCta);

        // --- 3. MENSAJES EN RECIBO ---
        JPanel pnlMensajes = new JPanel(null);
        pnlMensajes.setBorder(BorderFactory.createTitledBorder("Mensajes en Recibo"));
        pnlMensajes.setBounds(240, 165, 210, 75);

        JCheckBox chk1 = new JCheckBox("Mensaje 1"); chk1.setBounds(20, 15, 100, 15);
        JCheckBox chk2 = new JCheckBox("Mensaje 2"); chk2.setBounds(20, 35, 100, 15);
        JCheckBox chk3 = new JCheckBox("Mensaje 3"); chk3.setBounds(20, 55, 100, 15);
        
        pnlMensajes.add(chk1); pnlMensajes.add(chk2); pnlMensajes.add(chk3);
        
        pnlImpresion.add(pnlMensajes);

        pestanas.addTab("Impresión de Recibos", pnlImpresion);
        dialogo.add(pestanas);

        // --- 4. BOTONES INFERIORES ---
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(140, 300, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(260, 300, 100, 40);

        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Buscando recibos y enviando a la impresora... (Simulación)");
            dialogo.dispose();
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRRecibos;
    private javax.swing.JButton btnDeleteRRecibos;
    private javax.swing.JButton btnEditRRecibos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRRecibos;
    // End of variables declaration//GEN-END:variables
}
