/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Reeimpresion_Facturas extends javax.swing.JPanel {

    /**
     * Creates new form Reeimpresion_Facturas
     */
    public Reeimpresion_Facturas() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha Reimpresión", "Rango Facturas", "Tipo Documento", "Compañía", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblRFacturas.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRFacturas = new javax.swing.JTable();
        btnAddRFacturas = new javax.swing.JButton();
        btnEditRFacturas = new javax.swing.JButton();
        btnDeleteRFacturas = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblRFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRFacturas);

        btnAddRFacturas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddRFacturas.setForeground(new java.awt.Color(26, 61, 99));
        btnAddRFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddRFacturas.setText("Añadir");
        btnAddRFacturas.addActionListener(this::btnAddRFacturasActionPerformed);

        btnEditRFacturas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditRFacturas.setForeground(new java.awt.Color(26, 61, 99));
        btnEditRFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditRFacturas.setText("Editar");
        btnEditRFacturas.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditRFacturas.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditRFacturas.addActionListener(this::btnEditRFacturasActionPerformed);

        btnDeleteRFacturas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteRFacturas.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteRFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteRFacturas.setText("Eliminar");
        btnDeleteRFacturas.addActionListener(this::btnDeleteRFacturasActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddRFacturas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditRFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteRFacturas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditRFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteRFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRFacturasActionPerformed
       mostrarDialogoReimpresionFacturas();
    }//GEN-LAST:event_btnAddRFacturasActionPerformed

    private void btnEditRFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRFacturasActionPerformed
 JOptionPane.showMessageDialog(this, "Esta pantalla es exclusivamente para reimpresión de facturas. Para editar, dirígete al módulo correspondiente.");
    }//GEN-LAST:event_btnEditRFacturasActionPerformed

    private void btnDeleteRFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRFacturasActionPerformed
   JOptionPane.showMessageDialog(this, "Las facturas no pueden eliminarse desde este módulo. Si requieres cancelar una factura, usa el módulo de Impresión de Facturas.");
    }//GEN-LAST:event_btnDeleteRFacturasActionPerformed
private void mostrarDialogoReimpresionFacturas() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Reimpresión de Facturas", true);
        dialogo.setSize(480, 350);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. PESTAÑA PRINCIPAL ---
        JTabbedPane pestanas = new JTabbedPane();
        pestanas.setBounds(10, 10, 445, 230);

        JPanel pnlImpresion = new JPanel(null);

        // --- CAMPOS SUPERIORES ---
        pnlImpresion.add(new JLabel("Compañía")).setBounds(30, 20, 100, 25);
        pnlImpresion.add(new JComboBox<>(new String[]{"12"})).setBounds(140, 20, 70, 25);

        pnlImpresion.add(new JLabel("Desde Número")).setBounds(30, 75, 100, 25);
        pnlImpresion.add(new JTextField()).setBounds(140, 75, 80, 25);

        pnlImpresion.add(new JLabel("A")).setBounds(240, 75, 20, 25);
        pnlImpresion.add(new JTextField()).setBounds(270, 75, 80, 25);

        pnlImpresion.add(new JLabel("Tipo de Documento")).setBounds(30, 110, 110, 25);
        pnlImpresion.add(new JComboBox<>(new String[]{""})).setBounds(140, 110, 80, 25);

        // --- 2. INFORMACIÓN DE FACTURA ---
        JPanel pnlInfoFac = new JPanel(null);
        pnlInfoFac.setBorder(BorderFactory.createTitledBorder("Información de Factura"));
        pnlInfoFac.setBounds(20, 150, 400, 50);

        JCheckBox chkDetallada = new JCheckBox("Factura Detallada", true);
        chkDetallada.setBounds(20, 20, 150, 20);
        // Según la imagen, a veces esta casilla aparece bloqueada (gris), 
        // si quieres bloquearla descomenta la siguiente línea:
        // chkDetallada.setEnabled(false);
        
        JCheckBox chkRegenera = new JCheckBox("Regenera Factura");
        chkRegenera.setBounds(230, 20, 150, 20);

        pnlInfoFac.add(chkDetallada);
        pnlInfoFac.add(chkRegenera);
        
        pnlImpresion.add(pnlInfoFac);

        pestanas.addTab("Impresión de Factura", pnlImpresion);
        dialogo.add(pestanas);

        // --- 3. BOTONES INFERIORES ---
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(120, 260, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(240, 260, 100, 40);

        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 4. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Buscando facturas y enviando a la impresora... (Simulación)");
            dialogo.dispose();
        });

        // --- 5. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRFacturas;
    private javax.swing.JButton btnDeleteRFacturas;
    private javax.swing.JButton btnEditRFacturas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRFacturas;
    // End of variables declaration//GEN-END:variables
}
