/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Resultado_Grupo extends javax.swing.JPanel {

    /**
     * Creates new form Resultado_Grupo
     */
    public Resultado_Grupo() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha Consulta", "Año/Mes", "Nivel Seleccionado", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblRGrupo.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRGrupo = new javax.swing.JTable();
        btnAddRGrupo = new javax.swing.JButton();
        btnEditRGrupo = new javax.swing.JButton();
        btnDeleteRGrupo = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblRGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRGrupo);

        btnAddRGrupo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddRGrupo.setForeground(new java.awt.Color(26, 61, 99));
        btnAddRGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddRGrupo.setText("Añadir");
        btnAddRGrupo.addActionListener(this::btnAddRGrupoActionPerformed);

        btnEditRGrupo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditRGrupo.setForeground(new java.awt.Color(26, 61, 99));
        btnEditRGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditRGrupo.setText("Editar");
        btnEditRGrupo.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditRGrupo.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditRGrupo.addActionListener(this::btnEditRGrupoActionPerformed);

        btnDeleteRGrupo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteRGrupo.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteRGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteRGrupo.setText("Eliminar");
        btnDeleteRGrupo.addActionListener(this::btnDeleteRGrupoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddRGrupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditRGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteRGrupo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditRGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteRGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRGrupoActionPerformed
        mostrarDialogoEstadoResultados();
    }//GEN-LAST:event_btnAddRGrupoActionPerformed

    private void btnEditRGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRGrupoActionPerformed
        JOptionPane.showMessageDialog(this, "El Estado de Resultados es un reporte calculado, no permite edición manual.");
    
    }//GEN-LAST:event_btnEditRGrupoActionPerformed

    private void btnDeleteRGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRGrupoActionPerformed
        JOptionPane.showMessageDialog(this, "No se pueden eliminar registros contables desde el visor de reportes.");
    }//GEN-LAST:event_btnDeleteRGrupoActionPerformed

private void mostrarDialogoEstadoResultados() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Estado de Resultados x Grupo", true);
        dialogo.setSize(920, 680);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. DATOS DE SELECCIÓN (Panel Superior) ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createEtchedBorder());
        pnlSel.setBounds(10, 10, 885, 150);

        // Bloque Izquierdo
        pnlSel.add(new JLabel("Compañía")).setBounds(20, 15, 70, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12"})).setBounds(90, 15, 60, 25);
        pnlSel.add(new JLabel("UNIDAD ESCOLAR BENAVENTE, A.C.")).setBounds(160, 15, 250, 25);

        pnlSel.add(new JLabel("Año")).setBounds(20, 45, 50, 25);
        pnlSel.add(new JTextField("2026")).setBounds(90, 45, 60, 25);

        pnlSel.add(new JLabel("Mes")).setBounds(20, 75, 50, 25);
        pnlSel.add(new JTextField("5")).setBounds(90, 75, 60, 25);

        // Niveles (1 al 9)
        pnlSel.add(new JLabel("Nivel")).setBounds(170, 45, 40, 25);
        ButtonGroup bgNivel = new ButtonGroup();
        int xPosNivel = 210;
        for (int i = 1; i <= 9; i++) {
            JRadioButton rb = new JRadioButton(String.valueOf(i));
            if(i == 3) rb.setSelected(true); // Seleccionado el nivel 3 por defecto
            rb.setBounds(xPosNivel, 45, 40, 25);
            bgNivel.add(rb);
            pnlSel.add(rb);
            xPosNivel += 45;
        }

        // Fila de Combos para "Agrupar"
        pnlSel.add(new JLabel("Agrupar")).setBounds(20, 105, 60, 25);
        int xPosAgrupar = 90;
        for (int i = 0; i < 5; i++) {
            pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(xPosAgrupar, 105, 90, 25);
            xPosAgrupar += 105;
        }

        // Panel Lateral Derecho (Tipo Contabilidad)
        JPanel pnlTipoCont = new JPanel(null);
        pnlTipoCont.setBorder(BorderFactory.createTitledBorder("Tipo de Contabilidad"));
        pnlTipoCont.setBounds(680, 10, 190, 60);
        
        pnlTipoCont.add(new JLabel("Real")).setBounds(20, 20, 40, 20);
        pnlTipoCont.add(new JLabel("Ppto.")).setBounds(110, 20, 40, 20);
        pnlTipoCont.add(new JComboBox<>(new String[]{"MN"})).setBounds(10, 40, 70, 25);
        pnlTipoCont.add(new JComboBox<>(new String[]{"PL"})).setBounds(100, 40, 70, 25);
        
        pnlSel.add(pnlTipoCont);

        // Botones Laterales
        JButton btnSelecciona = new JButton("Selecciona");
        btnSelecciona.setBounds(680, 80, 190, 25);
        pnlSel.add(btnSelecciona);

        JButton btnFiltra = new JButton("Filtrar Información");
        btnFiltra.setBounds(680, 110, 190, 25);
        pnlSel.add(btnFiltra);

        dialogo.add(pnlSel);

        // --- 2. TABLA DE RESULTADOS ---
        JTable tblResultados = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Mes", "Ppto", "Dif", "Cuentas", "Acum Año", "Ppto Año"}
        ));
        tblResultados.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        
        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createEtchedBorder());
        pnlTabla.setBounds(10, 170, 885, 400);
        
        JScrollPane scrollResultados = new JScrollPane(tblResultados);
        scrollResultados.setBounds(10, 10, 865, 380);
        pnlTabla.add(scrollResultados);
        
        dialogo.add(pnlTabla);

        // --- 3. BOTONES INFERIORES ---
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(330, 590, 110, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(460, 590, 110, 40);

        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 4. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnSelecciona.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Abre ventana para seleccionar cuentas específicas... (Simulación)");
        });

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Calculando Estado de Resultados y comparando vs Presupuesto... (Simulación)");
            // Aquí iría la lógica SQL para llenar tblResultados
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando Estado de Resultados a la impresora... (Simulación)");
        });

        // --- 5. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRGrupo;
    private javax.swing.JButton btnDeleteRGrupo;
    private javax.swing.JButton btnEditRGrupo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRGrupo;
    // End of variables declaration//GEN-END:variables
}
