/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Resumen_Inscripciones extends javax.swing.JPanel {

    /**
     * Creates new form Resumen_Inscripciones
     */
    public Resumen_Inscripciones() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha Consulta", "Ciclo Escolar", "Tipo Reporte", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblRInscripciones.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRInscripciones = new javax.swing.JTable();
        btnAddRInscripciones = new javax.swing.JButton();
        btnEditRInscripciones = new javax.swing.JButton();
        btnDeleteRInscripciones = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblRInscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRInscripciones);

        btnAddRInscripciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddRInscripciones.setForeground(new java.awt.Color(26, 61, 99));
        btnAddRInscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddRInscripciones.setText("Añadir");
        btnAddRInscripciones.addActionListener(this::btnAddRInscripcionesActionPerformed);

        btnEditRInscripciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditRInscripciones.setForeground(new java.awt.Color(26, 61, 99));
        btnEditRInscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditRInscripciones.setText("Editar");
        btnEditRInscripciones.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditRInscripciones.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditRInscripciones.addActionListener(this::btnEditRInscripcionesActionPerformed);

        btnDeleteRInscripciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteRInscripciones.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteRInscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteRInscripciones.setText("Eliminar");
        btnDeleteRInscripciones.addActionListener(this::btnDeleteRInscripcionesActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddRInscripciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditRInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteRInscripciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditRInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteRInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRInscripcionesActionPerformed
       mostrarDialogoResumen();
    }//GEN-LAST:event_btnAddRInscripcionesActionPerformed

    private void btnEditRInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRInscripcionesActionPerformed
        JOptionPane.showMessageDialog(this, "Esta pantalla es para generar reportes, no para editar registros.");
    }//GEN-LAST:event_btnEditRInscripcionesActionPerformed

    private void btnDeleteRInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRInscripcionesActionPerformed
        JOptionPane.showMessageDialog(this, "No se pueden eliminar datos desde el generador de reportes.");
    }//GEN-LAST:event_btnDeleteRInscripcionesActionPerformed
private void mostrarDialogoResumen() {
    Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
    JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Resumen de Inscripciones", true);
    dialogo.setSize(620, 520);
    dialogo.setLayout(null);
    dialogo.setResizable(false);

    // --- CLASE LOCAL BUSCADOR FLOTANTE ---
    class BuscadorFlotante {
        void configurar(JTextField txtClave, JTextField txtDesc, JButton boton, Object[][] datos, String[] columnas, int[] anchos) {
            Runnable mostrarPopup = () -> {
                javax.swing.JPopupMenu popup = new javax.swing.JPopupMenu();
                popup.setFocusable(false);
                javax.swing.table.DefaultTableModel mod = new javax.swing.table.DefaultTableModel(datos, columnas) {
                    @Override public boolean isCellEditable(int r, int c) { return false; }
                };
                javax.swing.JTable tabla = new javax.swing.JTable(mod);
                tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                for (int i = 0; i < anchos.length; i++) {
                    tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                }

                javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(mod);
                tabla.setRowSorter(sorter);

                tabla.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseReleased(java.awt.event.MouseEvent me) {
                        int viewRow = tabla.getSelectedRow();
                        if (viewRow != -1) {
                            int modelRow = tabla.convertRowIndexToModel(viewRow);
                            txtClave.setText(mod.getValueAt(modelRow, 0).toString());
                            if (txtDesc != null && mod.getColumnCount() >= 2) {
                                txtDesc.setText(mod.getValueAt(modelRow, 1).toString());
                            }
                            popup.setVisible(false);
                        }
                    }
                });
                
                int widthTotal = 0; for(int w : anchos) widthTotal += w;
                javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(tabla);
                scroll.setPreferredSize(new java.awt.Dimension(widthTotal + 20, 150));
                popup.add(scroll);

                String texto = txtClave.getText().trim();
                if (!texto.isEmpty()) sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto));
                popup.show(txtClave, 0, txtClave.getHeight());
                txtClave.requestFocus();
            };

            boton.addActionListener(e -> { txtClave.setText(""); mostrarPopup.run(); });
            txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
                @Override
                public void keyReleased(java.awt.event.KeyEvent e) {
                    int c = e.getKeyCode();
                    if (c == 27 || c == 10 || c == 38 || c == 40 || c == 37 || c == 39 || c == 9) return;
                    mostrarPopup.run();
                }
            });
        }
    }
    BuscadorFlotante buscador = new BuscadorFlotante();

    // --- CARGA DE DATOS PARA BUSCADORES ---
    java.util.function.BiFunction<String, Integer, Object[][]> cargarDatosMultiple = (query, numCols) -> {
        java.util.List<Object[]> lista = new java.util.ArrayList<>();
        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();
            if (con != null) {
                PreparedStatement ps = con.prepareStatement(query);
                ResultSet rs = ps.executeQuery();
                while(rs.next()) {
                    Object[] row = new Object[numCols];
                    for(int i=0; i<numCols; i++) row[i] = rs.getString(i+1);
                    lista.add(row);
                }
                rs.close(); ps.close(); db.Cerrar();
            }
        } catch(Exception e) {}
        return lista.toArray(new Object[0][0]);
    };

    Object[][] dCiclo = cargarDatosMultiple.apply("SELECT CESC, CDSC FROM tescesc ORDER BY CESC DESC", 2);

    // --- 1. DATOS DE SELECCIÓN ---
    JPanel pnlSel = new JPanel(null);
    pnlSel.setBorder(BorderFactory.createEtchedBorder());
    pnlSel.setBounds(15, 15, 330, 115);

    pnlSel.add(new JLabel("Compañía")).setBounds(20, 15, 100, 25);
    JComboBox<String> cmbCia = new JComboBox<>();
    cmbCia.setBounds(130, 15, 80, 25);
    pnlSel.add(cmbCia);

    pnlSel.add(new JLabel("Centro de Costo")).setBounds(20, 45, 100, 25);
    JComboBox<String> cmbCC = new JComboBox<>();
    cmbCC.setBounds(130, 45, 100, 25);
    cmbCC.addItem(""); // Opción para consultar todos los Centros de Costo
    pnlSel.add(cmbCC);

    try {
        ConDB db = new ConDB();
        Connection con = db.Conectar();
        if (con != null) {
            ResultSet rsCia = con.prepareStatement("SELECT CIA FROM tmcias ORDER BY CIA").executeQuery();
            while(rsCia.next()) cmbCia.addItem(rsCia.getString("CIA"));
            rsCia.close();

            ResultSet rsCC = con.prepareStatement("SELECT CVE FROM tgcc WHERE CVE IN ('12100', '12200', '12300', '12400') ORDER BY CVE").executeQuery();
            while(rsCC.next()) cmbCC.addItem(rsCC.getString("CVE"));
            rsCC.close();
            db.Cerrar();
        }
    } catch (Exception ex) {}

    pnlSel.add(new JLabel("Ciclo Escolar")).setBounds(20, 75, 100, 25);
    JTextField txtCiclo = new JTextField(); txtCiclo.setBounds(130, 75, 70, 25);
    JButton btnCiclo = new JButton("▼"); btnCiclo.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10)); btnCiclo.setMargin(new java.awt.Insets(0, 0, 0, 0)); btnCiclo.setBounds(200, 75, 25, 25);
    buscador.configurar(txtCiclo, null, btnCiclo, dCiclo, new String[]{"Clave", "Descripción"}, new int[]{60, 200});
    pnlSel.add(txtCiclo); pnlSel.add(btnCiclo);

    dialogo.add(pnlSel);

    // --- 2. TIPO REPORTE ---
    JPanel pnlTipoReporte = new JPanel(null);
    pnlTipoReporte.setBorder(BorderFactory.createTitledBorder("Tipo Reporte"));
    pnlTipoReporte.setBounds(360, 15, 230, 80);

    JRadioButton rbDetalle = new JRadioButton("Imprimir Detalle");
    rbDetalle.setBounds(20, 20, 150, 20);
    JRadioButton rbResumen = new JRadioButton("Imprimir Resumen", true);
    rbResumen.setBounds(20, 45, 150, 20);

    ButtonGroup bgTipo = new ButtonGroup();
    bgTipo.add(rbDetalle); bgTipo.add(rbResumen);
    
    pnlTipoReporte.add(rbDetalle); pnlTipoReporte.add(rbResumen);
    dialogo.add(pnlTipoReporte);

    JButton btnFiltra = new JButton("Filtrar información");
    btnFiltra.setBounds(360, 100, 230, 30);
    dialogo.add(btnFiltra);

    // --- 3. TABLA DE RESULTADOS ---
    DefaultTableModel modResumen = new DefaultTableModel(
        new Object[][]{}, 
        new String[]{"CC", "Sección", "Grado", "Descripción / Matrícula", "Total / Nombre"}
    ) { @Override public boolean isCellEditable(int r, int c) { return false; } };

    JTable tblResumen = new JTable(modResumen);
    tblResumen.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    tblResumen.getColumnModel().getColumn(3).setPreferredWidth(180);
    tblResumen.getColumnModel().getColumn(4).setPreferredWidth(200);

    JPanel pnlTabla = new JPanel(null);
    pnlTabla.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Resumen de Inscripciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
    pnlTabla.setBounds(15, 145, 575, 240);
    
    JScrollPane scrollResumen = new JScrollPane(tblResumen);
    scrollResumen.setBounds(10, 20, 555, 210);
    pnlTabla.add(scrollResumen);
    
    dialogo.add(pnlTabla);

    // --- 4. TOTALES ---
    JLabel lblTotalInsc = new JLabel("Total de Inscripciones");
    lblTotalInsc.setBounds(360, 395, 140, 25);
    JTextField txtTotal = new JTextField("0");
    txtTotal.setHorizontalAlignment(JTextField.RIGHT);
    txtTotal.setEditable(false);
    txtTotal.setBounds(510, 395, 80, 25);

    dialogo.add(lblTotalInsc);
    dialogo.add(txtTotal);

    // --- 5. BOTONES INFERIORES ---
    JButton btnImprimir = new JButton("Imprimir");
    btnImprimir.setBounds(190, 435, 100, 40);
    JButton btnSalir = new JButton("Salir");
    btnSalir.setBounds(310, 435, 100, 40);

    dialogo.add(btnImprimir);
    dialogo.add(btnSalir);

    // --- 6. EVENTOS ---
    btnSalir.addActionListener(e -> dialogo.dispose());

   btnImprimir.addActionListener(e -> {
        if (modResumen.getRowCount() == 0) {
            JOptionPane.showMessageDialog(dialogo, "No hay datos en la tabla para imprimir.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            java.awt.print.PrinterJob job = java.awt.print.PrinterJob.getPrinterJob();
            job.setJobName("Reporte de Resumen de Inscripciones");

            String tituloReporte = rbResumen.isSelected() ? "RESUMEN DE INSCRIPCIONES" : "DETALLE DE ALUMNOS INSCRITOS";
            String ciaSel = cmbCia.getSelectedItem() != null ? cmbCia.getSelectedItem().toString() : "";
            String ccSel = cmbCC.getSelectedItem() != null ? cmbCC.getSelectedItem().toString() : "";
            String cicloSel = txtCiclo.getText().trim();
            String totalTexto = txtTotal.getText();

            job.setPrintable((g, pf, pageIndex) -> {
                int filasPorPagina = 28;
                int totalPaginas = (int) Math.ceil((double) modResumen.getRowCount() / filasPorPagina);
                if (totalPaginas == 0) totalPaginas = 1;

                if (pageIndex >= totalPaginas) {
                    return java.awt.print.Printable.NO_SUCH_PAGE;
                }

                java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
                g2d.translate(pf.getImageableX(), pf.getImageableY());

                int y = 40;

                // --- ENCABEZADO PRINCIPAL ---
                g2d.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
                g2d.drawString("UNIDAD ESCOLAR BENAVENTE, A.C.", 40, y); y += 20;

                g2d.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 11));
                g2d.drawString(tituloReporte, 40, y); y += 15;

                g2d.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 9));
                g2d.drawString("Compañía: " + ciaSel + " | C. Costo: " + (ccSel.isEmpty() ? "TODOS" : ccSel) + " | Ciclo Escolar: " + cicloSel, 40, y); y += 15;
                g2d.drawLine(40, y, 530, y); y += 15;

                // --- CABECERA DE TABLA DE IMPRESIÓN ---
                g2d.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 9));
                g2d.drawString("CC", 40, y);
                g2d.drawString("SECC", 80, y);
                g2d.drawString("GRADO", 130, y);
                g2d.drawString(rbResumen.isSelected() ? "DESCRIPCIÓN / TIPO" : "MATRÍCULA", 180, y);
                g2d.drawString(rbResumen.isSelected() ? "TOTAL" : "NOMBRE DEL ALUMNO", 360, y);
                y += 5;
                g2d.drawLine(40, y, 530, y); y += 15;

                // --- FILAS DE REGISTROS ---
                g2d.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 8));
                int inicioRow = pageIndex * filasPorPagina;
                int finRow = Math.min(inicioRow + filasPorPagina, modResumen.getRowCount());

                for (int r = inicioRow; r < finRow; r++) {
                    String cCC = modResumen.getValueAt(r, 0) != null ? modResumen.getValueAt(r, 0).toString() : "";
                    String cSecc = modResumen.getValueAt(r, 1) != null ? modResumen.getValueAt(r, 1).toString() : "";
                    String cGrado = modResumen.getValueAt(r, 2) != null ? modResumen.getValueAt(r, 2).toString() : "";
                    String cDesc = modResumen.getValueAt(r, 3) != null ? modResumen.getValueAt(r, 3).toString() : "";
                    String cTot = modResumen.getValueAt(r, 4) != null ? modResumen.getValueAt(r, 4).toString() : "";

                    g2d.drawString(cCC, 40, y);
                    g2d.drawString(cSecc, 80, y);
                    g2d.drawString(cGrado, 130, y);

                    if (cDesc.length() > 30) cDesc = cDesc.substring(0, 27) + "...";
                    if (cTot.length() > 35) cTot = cTot.substring(0, 32) + "...";

                    g2d.drawString(cDesc, 180, y);
                    g2d.drawString(cTot, 360, y);
                    y += 12;
                }

                // --- RESUMEN Y PIE EN ÚLTIMA PÁGINA ---
                if (pageIndex == totalPaginas - 1) {
                    y += 10;
                    g2d.drawLine(40, y, 530, y); y += 15;
                    g2d.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 10));
                    g2d.drawString("TOTAL DE INSCRIPCIONES ACTIVAS:", 250, y);
                    g2d.drawString(totalTexto, 470, y);
                }

                // Indicador de página
                g2d.setFont(new java.awt.Font("SansSerif", java.awt.Font.ITALIC, 8));
                g2d.drawString("Página " + (pageIndex + 1) + " de " + totalPaginas, 450, 750);

                return java.awt.print.Printable.PAGE_EXISTS;
            });

            if (job.printDialog()) {
                job.print();
                JOptionPane.showMessageDialog(dialogo, "Reporte de inscripciones impreso correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(dialogo, "Error al enviar a la impresora: " + ex.getMessage(), "Error de Impresión", JOptionPane.ERROR_MESSAGE);
        }
    });

    dialogo.setLocationRelativeTo(this);
    dialogo.setVisible(true);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRInscripciones;
    private javax.swing.JButton btnDeleteRInscripciones;
    private javax.swing.JButton btnEditRInscripciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRInscripciones;
    // End of variables declaration//GEN-END:variables
}
