/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Resumen_Inscripciones extends javax.swing.JPanel {

    /**
     * Creates new form Resumen_Inscripciones
     */
    public Resumen_Inscripciones() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha Consulta", "Ciclo Escolar", "Tipo Reporte", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblRInscripciones.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRInscripciones = new javax.swing.JTable();
        btnAddRInscripciones = new javax.swing.JButton();
        btnEditRInscripciones = new javax.swing.JButton();
        btnDeleteRInscripciones = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblRInscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRInscripciones);

        btnAddRInscripciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddRInscripciones.setForeground(new java.awt.Color(26, 61, 99));
        btnAddRInscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddRInscripciones.setText("Añadir");
        btnAddRInscripciones.addActionListener(this::btnAddRInscripcionesActionPerformed);

        btnEditRInscripciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditRInscripciones.setForeground(new java.awt.Color(26, 61, 99));
        btnEditRInscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditRInscripciones.setText("Editar");
        btnEditRInscripciones.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditRInscripciones.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditRInscripciones.addActionListener(this::btnEditRInscripcionesActionPerformed);

        btnDeleteRInscripciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteRInscripciones.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteRInscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteRInscripciones.setText("Eliminar");
        btnDeleteRInscripciones.addActionListener(this::btnDeleteRInscripcionesActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddRInscripciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditRInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteRInscripciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditRInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteRInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRInscripcionesActionPerformed
       mostrarDialogoResumen();
    }//GEN-LAST:event_btnAddRInscripcionesActionPerformed

    private void btnEditRInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRInscripcionesActionPerformed
        JOptionPane.showMessageDialog(this, "Esta pantalla es para generar reportes, no para editar registros.");
    }//GEN-LAST:event_btnEditRInscripcionesActionPerformed

    private void btnDeleteRInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRInscripcionesActionPerformed
        JOptionPane.showMessageDialog(this, "No se pueden eliminar datos desde el generador de reportes.");
    }//GEN-LAST:event_btnDeleteRInscripcionesActionPerformed
private void mostrarDialogoResumen() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Resumen de Inscripciones", true);
        dialogo.setSize(620, 520);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. DATOS DE SELECCIÓN (Panel Izquierdo) ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createEtchedBorder());
        pnlSel.setBounds(15, 15, 330, 115);

        pnlSel.add(new JLabel("Compañía")).setBounds(20, 15, 100, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12"})).setBounds(130, 15, 80, 25);

        pnlSel.add(new JLabel("Centro de Costo")).setBounds(20, 45, 100, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12100"})).setBounds(130, 45, 100, 25);

        pnlSel.add(new JLabel("Ciclo Escolar")).setBounds(20, 75, 100, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(130, 75, 100, 25);

        dialogo.add(pnlSel);

        // --- 2. TIPO REPORTE (Panel Derecho) ---
        JPanel pnlTipoReporte = new JPanel(null);
        pnlTipoReporte.setBorder(BorderFactory.createTitledBorder("Tipo Reporte"));
        pnlTipoReporte.setBounds(360, 15, 230, 80);

        JRadioButton rbDetalle = new JRadioButton("Imprimir Detalle");
        rbDetalle.setBounds(20, 20, 150, 20);
        JRadioButton rbResumen = new JRadioButton("Imprimir Resumen", true); // Seleccionado por defecto
        rbResumen.setBounds(20, 45, 150, 20);

        ButtonGroup bgTipo = new ButtonGroup();
        bgTipo.add(rbDetalle); bgTipo.add(rbResumen);
        
        pnlTipoReporte.add(rbDetalle); pnlTipoReporte.add(rbResumen);
        dialogo.add(pnlTipoReporte);

        // --- BOTÓN FILTRAR ---
        JButton btnFiltra = new JButton("Filtrar información");
        btnFiltra.setBounds(360, 100, 230, 30);
        dialogo.add(btnFiltra);

        // --- 3. TABLA DE RESUMEN ---
        JTable tblResumen = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"CC", "Tipo", "Grado", "Descripcion", "Total"}
        ));
        
        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Resumen de Inscripciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pnlTabla.setBounds(15, 145, 575, 240);
        
        JScrollPane scrollResumen = new JScrollPane(tblResumen);
        scrollResumen.setBounds(10, 20, 555, 210);
        pnlTabla.add(scrollResumen);
        
        dialogo.add(pnlTabla);

        // --- 4. TOTALES ---
        JLabel lblTotalInsc = new JLabel("Total de Inscripciones");
        lblTotalInsc.setBounds(380, 395, 140, 25);
        JTextField txtTotal = new JTextField("0");
        txtTotal.setHorizontalAlignment(JTextField.RIGHT);
        txtTotal.setEditable(false);
        txtTotal.setBounds(510, 395, 80, 25);

        dialogo.add(lblTotalInsc);
        dialogo.add(txtTotal);

        // --- 5. BOTONES INFERIORES ---
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(190, 435, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(310, 435, 100, 40);

        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 6. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Agrupando y sumando las inscripciones de la base de datos... (Simulación)");
            // Aquí iría tu consulta con "GROUP BY" y "COUNT()" para llenar la tabla
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando el resumen a la impresora... (Simulación)");
        });

        // --- 7. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRInscripciones;
    private javax.swing.JButton btnDeleteRInscripciones;
    private javax.swing.JButton btnEditRInscripciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRInscripciones;
    // End of variables declaration//GEN-END:variables
}
