/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Resumen_Conceptos_Pagados extends javax.swing.JPanel {

    /**
     * Creates new form Resumen_Conceptos_Pagados
     */
    public Resumen_Conceptos_Pagados() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha Consulta", "Cajero Filtrado", "Rango de Fechas", "Tipo de Cuenta", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblRCPagados.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRCPagados = new javax.swing.JTable();
        btnAddRCPagados = new javax.swing.JButton();
        btnEditRCPagados = new javax.swing.JButton();
        btnDeleteRCPagados = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblRCPagados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRCPagados);

        btnAddRCPagados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddRCPagados.setForeground(new java.awt.Color(26, 61, 99));
        btnAddRCPagados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddRCPagados.setText("Añadir");
        btnAddRCPagados.addActionListener(this::btnAddRCPagadosActionPerformed);

        btnEditRCPagados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditRCPagados.setForeground(new java.awt.Color(26, 61, 99));
        btnEditRCPagados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditRCPagados.setText("Editar");
        btnEditRCPagados.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditRCPagados.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditRCPagados.addActionListener(this::btnEditRCPagadosActionPerformed);

        btnDeleteRCPagados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteRCPagados.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteRCPagados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteRCPagados.setText("Eliminar");
        btnDeleteRCPagados.addActionListener(this::btnDeleteRCPagadosActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddRCPagados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditRCPagados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteRCPagados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRCPagados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditRCPagados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteRCPagados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRCPagadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRCPagadosActionPerformed
        mostrarDialogoResumenConceptos();
    }//GEN-LAST:event_btnAddRCPagadosActionPerformed

    private void btnEditRCPagadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRCPagadosActionPerformed
        JOptionPane.showMessageDialog(this, "Esta pantalla es de consulta y reportes. Los pagos no se pueden editar desde aquí.");
    }//GEN-LAST:event_btnEditRCPagadosActionPerformed

    private void btnDeleteRCPagadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRCPagadosActionPerformed
        JOptionPane.showMessageDialog(this, "No se pueden eliminar pagos desde el generador de reportes.");
    }//GEN-LAST:event_btnDeleteRCPagadosActionPerformed
private void mostrarDialogoResumenConceptos() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Resumen de Conceptos Pagados", true);
        dialogo.setSize(950, 640);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. DATOS DE SELECCIÓN ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createEtchedBorder());
        pnlSel.setBounds(10, 10, 600, 95);

        pnlSel.add(new JLabel("Compañía")).setBounds(15, 20, 70, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12"})).setBounds(90, 20, 70, 25);

        pnlSel.add(new JLabel("Centro de Costo")).setBounds(180, 20, 100, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12100"})).setBounds(280, 20, 80, 25);

        pnlSel.add(new JLabel("Ciclo Escolar")).setBounds(380, 20, 80, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(470, 20, 100, 25);

        pnlSel.add(new JLabel("Cajero")).setBounds(15, 55, 70, 25);
        pnlSel.add(new JTextField()).setBounds(90, 55, 70, 25);

        pnlSel.add(new JLabel("Fecha Inicial")).setBounds(180, 55, 80, 25);
        pnlSel.add(new JTextField("04/06/2026")).setBounds(280, 55, 90, 25);

        pnlSel.add(new JLabel("Fecha Final")).setBounds(380, 55, 80, 25);
        pnlSel.add(new JTextField("04/06/2026")).setBounds(470, 55, 100, 25);

        dialogo.add(pnlSel);

        // --- 2. ORDEN ---
        JPanel pnlOrden = new JPanel(null);
        pnlOrden.setBorder(BorderFactory.createTitledBorder("Orden"));
        pnlOrden.setBounds(620, 10, 110, 95);
        
        JCheckBox chkGrado = new JCheckBox("Por Grado");
        chkGrado.setBounds(10, 30, 90, 25);
        pnlOrden.add(chkGrado);
        
        dialogo.add(pnlOrden);

        // --- 3. TIPO DE CUENTA ---
        JPanel pnlTipoCta = new JPanel(null);
        pnlTipoCta.setBorder(BorderFactory.createTitledBorder("Tipo de Cuenta"));
        pnlTipoCta.setBounds(740, 10, 180, 95);

        JRadioButton rbOficial = new JRadioButton("Oficial", true);
        rbOficial.setBounds(20, 15, 80, 20);
        JRadioButton rbPart = new JRadioButton("Particular");
        rbPart.setBounds(20, 40, 100, 20);
        JRadioButton rbAmbos = new JRadioButton("Ambos");
        rbAmbos.setBounds(20, 65, 80, 20);

        ButtonGroup bgTipo = new ButtonGroup();
        bgTipo.add(rbOficial); bgTipo.add(rbPart); bgTipo.add(rbAmbos);
        
        pnlTipoCta.add(rbOficial); pnlTipoCta.add(rbPart); pnlTipoCta.add(rbAmbos);
        dialogo.add(pnlTipoCta);

        // --- BOTÓN FILTRAR ---
        JButton btnFiltra = new JButton("Filtrar información");
        btnFiltra.setBounds(740, 115, 180, 30);
        dialogo.add(btnFiltra);

        // --- 4. TABLA DE RESUMEN DE CONCEPTOS PAGADOS ---
        JTable tblResumen = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Grado", "Cve", "Concepto", "Cantidad", "Importe", "Becas", "Desc.", "Rec", "Pagado"}
        ));
        
        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Resumen de Conceptos Pagados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pnlTabla.setBounds(10, 155, 910, 300);
        
        JScrollPane scrollResumen = new JScrollPane(tblResumen);
        scrollResumen.setBounds(10, 20, 890, 270);
        pnlTabla.add(scrollResumen);
        
        dialogo.add(pnlTabla);

        // --- 5. TOTALES INFERIORES ---
        JPanel pnlTotales = new JPanel(null);
        pnlTotales.setBorder(BorderFactory.createEtchedBorder());
        pnlTotales.setBounds(10, 465, 910, 50);

        pnlTotales.add(new JLabel("Totales de Conceptos")).setBounds(170, 15, 150, 20);

        String[] lbls = {"Cantidad", "Importe", "Becas", "Desc", "Rec", "Pagado"};
        int xPos = 350;
        for (int i = 0; i < lbls.length; i++) {
            JLabel l = new JLabel(lbls[i], SwingUtilities.CENTER);
            l.setBounds(xPos, 5, 80, 15);
            JTextField t = new JTextField(i == 0 ? "0" : "0.00");
            t.setBounds(xPos, 20, 80, 20);
            t.setHorizontalAlignment(JTextField.RIGHT);
            t.setEditable(false);
            
            pnlTotales.add(l); pnlTotales.add(t);
            xPos += 90;
        }
        dialogo.add(pnlTotales);

        // --- 6. BOTONES INFERIORES ---
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(350, 535, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(480, 535, 100, 40);

        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 7. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Agrupando cobros por concepto y calculando totales... (Simulación)");
            // Aquí iría tu lógica SQL con GROUP BY y SUM()
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando el reporte de conceptos pagados a la impresora... (Simulación)");
            dialogo.dispose();
        });

        // --- 8. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRCPagados;
    private javax.swing.JButton btnDeleteRCPagados;
    private javax.swing.JButton btnEditRCPagados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRCPagados;
    // End of variables declaration//GEN-END:variables
}
