/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Resumen_Alumnos_No_Inscritos extends javax.swing.JPanel {

    /**
     * Creates new form Resumen_Alumnos_No_Inscritos
     */
    public Resumen_Alumnos_No_Inscritos() {
        initComponents();
    }
private void configurarTablaBitacora() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Fecha Consulta", "Ciclo Escolar", "Tipo Reporte", "Usuario"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblRAInscritos.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRAInscritos = new javax.swing.JTable();
        btnAddRAInscritos = new javax.swing.JButton();
        btnEditRInscritos = new javax.swing.JButton();
        btnDeleteRAInscritos = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblRAInscritos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRAInscritos);

        btnAddRAInscritos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddRAInscritos.setForeground(new java.awt.Color(26, 61, 99));
        btnAddRAInscritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddRAInscritos.setText("Añadir");
        btnAddRAInscritos.addActionListener(this::btnAddRAInscritosActionPerformed);

        btnEditRInscritos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditRInscritos.setForeground(new java.awt.Color(26, 61, 99));
        btnEditRInscritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditRInscritos.setText("Editar");
        btnEditRInscritos.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditRInscritos.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditRInscritos.addActionListener(this::btnEditRInscritosActionPerformed);

        btnDeleteRAInscritos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteRAInscritos.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteRAInscritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteRAInscritos.setText("Eliminar");
        btnDeleteRAInscritos.addActionListener(this::btnDeleteRAInscritosActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddRAInscritos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditRInscritos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteRAInscritos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRAInscritos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditRInscritos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteRAInscritos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRAInscritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRAInscritosActionPerformed
        mostrarDialogoAlumnosNoInscritos();
    }//GEN-LAST:event_btnAddRAInscritosActionPerformed

    private void btnEditRInscritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRInscritosActionPerformed
        JOptionPane.showMessageDialog(this, "Esta pantalla es de consulta y reportes. Los datos no se pueden editar desde aquí.");
    }//GEN-LAST:event_btnEditRInscritosActionPerformed

    private void btnDeleteRAInscritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRAInscritosActionPerformed
        JOptionPane.showMessageDialog(this, "No se pueden eliminar registros desde el generador de reportes.");
    }//GEN-LAST:event_btnDeleteRAInscritosActionPerformed
private void mostrarDialogoAlumnosNoInscritos() {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, "Resumen de Alumnos No Inscritos", true);
        dialogo.setSize(620, 620);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. DATOS DE SELECCIÓN (Panel Izquierdo) ---
        JPanel pnlSel = new JPanel(null);
        pnlSel.setBorder(BorderFactory.createEtchedBorder());
        pnlSel.setBounds(15, 15, 330, 115);

        pnlSel.add(new JLabel("Compañía")).setBounds(20, 15, 100, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12"})).setBounds(130, 15, 80, 25);

        pnlSel.add(new JLabel("Centro de Costo")).setBounds(20, 45, 100, 25);
        pnlSel.add(new JComboBox<>(new String[]{"12100"})).setBounds(130, 45, 100, 25);

        pnlSel.add(new JLabel("Ciclo Escolar")).setBounds(20, 75, 100, 25);
        pnlSel.add(new JComboBox<>(new String[]{""})).setBounds(130, 75, 100, 25);

        dialogo.add(pnlSel);

        // --- 2. TIPO REPORTE (Panel Derecho) ---
        JPanel pnlTipoReporte = new JPanel(null);
        pnlTipoReporte.setBorder(BorderFactory.createTitledBorder("Tipo Reporte"));
        pnlTipoReporte.setBounds(360, 15, 230, 80);

        JRadioButton rbDetalle = new JRadioButton("Imprimir Detalle");
        rbDetalle.setBounds(20, 20, 150, 20);
        JRadioButton rbResumen = new JRadioButton("Imprimir Resumen", true); // Seleccionado por defecto
        rbResumen.setBounds(20, 45, 150, 20);

        ButtonGroup bgTipo = new ButtonGroup();
        bgTipo.add(rbDetalle); bgTipo.add(rbResumen);
        
        pnlTipoReporte.add(rbDetalle); pnlTipoReporte.add(rbResumen);
        dialogo.add(pnlTipoReporte);

        // --- BOTÓN FILTRAR ---
        JButton btnFiltra = new JButton("Filtrar información");
        btnFiltra.setBounds(360, 100, 230, 30);
        dialogo.add(btnFiltra);

        // --- 3. TABLA DE RESUMEN ---
        JTable tblResumen = new JTable(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Grado", "Descripcion", "Total"}
        ));
        
        JPanel pnlTabla = new JPanel(null);
        pnlTabla.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Resumen de Alumnos No Inscritos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pnlTabla.setBounds(15, 145, 575, 330);
        
        JScrollPane scrollResumen = new JScrollPane(tblResumen);
        scrollResumen.setBounds(10, 20, 555, 300);
        pnlTabla.add(scrollResumen);
        
        dialogo.add(pnlTabla);

        // --- 4. TOTALES ---
        JPanel pnlTotales = new JPanel(null);
        pnlTotales.setBorder(BorderFactory.createEtchedBorder());
        pnlTotales.setBounds(15, 485, 575, 45);

        JLabel lblTotalInsc = new JLabel("Total de Alumnos No Inscritos");
        lblTotalInsc.setBounds(290, 10, 180, 25);
        JTextField txtTotal = new JTextField("0");
        txtTotal.setHorizontalAlignment(JTextField.RIGHT);
        txtTotal.setEditable(false);
        txtTotal.setBounds(480, 10, 80, 25);

        pnlTotales.add(lblTotalInsc);
        pnlTotales.add(txtTotal);
        dialogo.add(pnlTotales);

        // --- 5. BOTONES INFERIORES ---
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.setBounds(190, 540, 100, 40);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(310, 540, 100, 40);

        dialogo.add(btnImprimir);
        dialogo.add(btnSalir);

        // --- 6. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnFiltra.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Buscando alumnos no inscritos en la base de datos... (Simulación)");
            // Aquí iría tu consulta SQL para llenar la tabla y sumar el total
        });

        btnImprimir.addActionListener(e -> {
            JOptionPane.showMessageDialog(dialogo, "Enviando el resumen a la impresora... (Simulación)");
        });

        // --- 7. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRAInscritos;
    private javax.swing.JButton btnDeleteRAInscritos;
    private javax.swing.JButton btnEditRInscritos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRAInscritos;
    // End of variables declaration//GEN-END:variables
}
