/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;
import com.mycompany.benaedu.db.ConDB;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author b17za
 */
public class Tipo_Cambio extends javax.swing.JPanel {

    /**
     * Creates new form Tipo_Cambio_mensual
     */
    public Tipo_Cambio() {
        initComponents();
    }

    private void cargarTablaTCMensual() {
        DefaultTableModel modelo = (DefaultTableModel) tblTCambioMensual.getModel();
        modelo.setRowCount(0); 

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                // ATENCIÓN: Cambia 'tabla_tc_mensual' por el nombre de tu tabla real
                String sql = "SELECT anio, mon_origen, mon_destino, periodo, tc_inicial, tc_final, tc_promedio, usuario, fecha_mod, hora_mod FROM tabla_tc_mensual";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[10]; 
                    fila[0] = rs.getString("anio");
                    fila[1] = rs.getString("mon_origen");
                    fila[2] = rs.getString("mon_destino");
                    fila[3] = rs.getString("periodo");
                    fila[4] = rs.getString("tc_inicial");
                    fila[5] = rs.getString("tc_final");
                    fila[6] = rs.getString("tc_promedio");
                    fila[7] = rs.getString("usuario");
                    fila[8] = rs.getString("fecha_mod");
                    fila[9] = rs.getString("hora_mod");

                    modelo.addRow(fila);
                }
                rs.close(); ps.close(); db.Cerrar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBg = new javax.swing.JPanel();
        btnAddTCambioMensual = new javax.swing.JButton();
        btnEditTCambioMensual = new javax.swing.JButton();
        btnDeleteTCambioMensual = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTCambioMensual = new javax.swing.JTable();

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));

        btnAddTCambioMensual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddTCambioMensual.setForeground(new java.awt.Color(26, 61, 99));
        btnAddTCambioMensual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddTCambioMensual.setText("Añadir");
        btnAddTCambioMensual.addActionListener(this::btnAddTCambioMensualActionPerformed);

        btnEditTCambioMensual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditTCambioMensual.setForeground(new java.awt.Color(26, 61, 99));
        btnEditTCambioMensual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditTCambioMensual.setText("Editar");
        btnEditTCambioMensual.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditTCambioMensual.setMinimumSize(new java.awt.Dimension(93, 31));
        btnEditTCambioMensual.addActionListener(this::btnEditTCambioMensualActionPerformed);

        btnDeleteTCambioMensual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteTCambioMensual.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteTCambioMensual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteTCambioMensual.setText("Eliminar");
        btnDeleteTCambioMensual.addActionListener(this::btnDeleteTCambioMensualActionPerformed);

        tblTCambioMensual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Año", "Moneda Origen", "Moneda Destino", "Periodo", "Inicial", "Final", "Promedio", "Usuario", "Fecha Mod.", "Hora Mod."
            }
        ));
        jScrollPane1.setViewportView(tblTCambioMensual);

        javax.swing.GroupLayout pnlBgLayout = new javax.swing.GroupLayout(pnlBg);
        pnlBg.setLayout(pnlBgLayout);
        pnlBgLayout.setHorizontalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddTCambioMensual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditTCambioMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteTCambioMensual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        );
        pnlBgLayout.setVerticalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBgLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTCambioMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditTCambioMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteTCambioMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTCambioMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTCambioMensualActionPerformed
       mostrarDialogoTCMensual(false);
    }//GEN-LAST:event_btnAddTCambioMensualActionPerformed

    private void btnDeleteTCambioMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTCambioMensualActionPerformed
        if (tblTCambioMensual.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un registro para editar.");
            return;
        }
        mostrarDialogoTCMensual(true);
    }//GEN-LAST:event_btnDeleteTCambioMensualActionPerformed

    private void btnEditTCambioMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTCambioMensualActionPerformed
        int fila = tblTCambioMensual.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un registro para eliminar.");
            return;
        }

        String anio = tblTCambioMensual.getValueAt(fila, 0).toString();
        String periodo = tblTCambioMensual.getValueAt(fila, 3).toString();
        
        int resp = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar el registro del periodo " + periodo + " del " + anio + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                if (con != null) {
                    // Cambia 'tabla_tc_mensual' por el nombre de tu tabla
                    // Se usan 2 llaves para eliminar un registro mensual específico
                    PreparedStatement ps = con.prepareStatement("DELETE FROM tabla_tc_mensual WHERE anio = ? AND periodo = ?");
                    ps.setString(1, anio);
                    ps.setString(2, periodo);
                    
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Registro eliminado.");
                        cargarTablaTCMensual();
                    }
                    ps.close(); db.Cerrar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEditTCambioMensualActionPerformed

private void mostrarDialogoTCMensual(boolean modoEdicion) {
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        String tituloVentana = modoEdicion ? "Modificar Tipo de Cambio" : "Agregar tipo de cambio mensual";

        JDialog dialogo = new JDialog((java.awt.Frame) ventanaPadre, tituloVentana, true);
        dialogo.setSize(450, 360);
        dialogo.setLayout(null);
        dialogo.setResizable(false);

        // --- 1. SECCIÓN SUPERIOR (Marco Código de Moneda) ---
        JPanel pnlMoneda = new JPanel(null);
        pnlMoneda.setBorder(BorderFactory.createTitledBorder("Código de Moneda"));
        pnlMoneda.setBounds(20, 10, 400, 90);

        JLabel lblOrigen = new JLabel("Origen");
        lblOrigen.setBounds(20, 20, 60, 25);
        JComboBox<String> cmbOrigen = new JComboBox<>(new String[]{"MXP", "USD", "EUR"});
        cmbOrigen.setBounds(80, 20, 70, 25);
        JLabel lblDescOrigen = new JLabel("PESOS"); 
        lblDescOrigen.setBounds(160, 20, 100, 25);

        JLabel lblDestino = new JLabel("Destino");
        lblDestino.setBounds(20, 50, 60, 25);
        JComboBox<String> cmbDestino = new JComboBox<>(new String[]{"USD", "MXP", "EUR"});
        cmbDestino.setBounds(80, 50, 70, 25);
        JLabel lblDescDestino = new JLabel("DOLARES");
        lblDescDestino.setBounds(160, 50, 100, 25);

        pnlMoneda.add(lblOrigen); pnlMoneda.add(cmbOrigen); pnlMoneda.add(lblDescOrigen);
        pnlMoneda.add(lblDestino); pnlMoneda.add(cmbDestino); pnlMoneda.add(lblDescDestino);
        dialogo.add(pnlMoneda);

        // --- 2. CAMPOS CENTRALES ---
        JLabel lblEjercicio = new JLabel("Ejercicio");
        lblEjercicio.setBounds(60, 115, 60, 25);
        JTextField txtEjercicio = new JTextField();
        txtEjercicio.setBounds(120, 115, 60, 25);
        if (modoEdicion) txtEjercicio.setEditable(false); // Llave primaria

        JLabel lblPeriodo = new JLabel("Periodo");
        lblPeriodo.setBounds(210, 115, 60, 25);
        JComboBox<String> cmbPeriodo = new JComboBox<>(new String[]{"01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"});
        cmbPeriodo.setBounds(270, 115, 50, 25);
        if (modoEdicion) cmbPeriodo.setEnabled(false); // Llave primaria

        JLabel lblTcInicial = new JLabel("Tipo de Cambio Inicial");
        lblTcInicial.setBounds(60, 160, 150, 25);
        JTextField txtTcInicial = new JTextField("0.0000");
        txtTcInicial.setBounds(220, 160, 100, 25);

        JLabel lblTcPromedio = new JLabel("Tipo de Cambio Promedio");
        lblTcPromedio.setBounds(60, 190, 150, 25);
        JTextField txtTcPromedio = new JTextField("0.0000");
        txtTcPromedio.setBounds(220, 190, 100, 25);

        JLabel lblTcCierre = new JLabel("Tipo de Cambio de Cierre");
        lblTcCierre.setBounds(60, 220, 150, 25);
        JTextField txtTcCierre = new JTextField("0.0000");
        txtTcCierre.setBounds(220, 220, 100, 25);

        dialogo.add(lblEjercicio); dialogo.add(txtEjercicio);
        dialogo.add(lblPeriodo); dialogo.add(cmbPeriodo);
        dialogo.add(lblTcInicial); dialogo.add(txtTcInicial);
        dialogo.add(lblTcPromedio); dialogo.add(txtTcPromedio);
        dialogo.add(lblTcCierre); dialogo.add(txtTcCierre);

        // --- 3. BOTONES INFERIORES ---
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBounds(110, 270, 100, 35);
        JButton btnSalir = new JButton("Salir");
        btnSalir.setBounds(230, 270, 100, 35);

        dialogo.add(btnAceptar);
        dialogo.add(btnSalir);

        // --- 4. SI ES EDICIÓN, LLENAMOS DATOS ---
        if (modoEdicion) {
            int fila = tblTCambioMensual.getSelectedRow();
            
            // Ojo: Ajusta estos índices según las columnas de tu tabla tblTCambioMensual
            txtEjercicio.setText(tblTCambioMensual.getValueAt(fila, 0).toString());
            cmbOrigen.setSelectedItem(tblTCambioMensual.getValueAt(fila, 1).toString());
            cmbDestino.setSelectedItem(tblTCambioMensual.getValueAt(fila, 2).toString());
            cmbPeriodo.setSelectedItem(tblTCambioMensual.getValueAt(fila, 3).toString());
            
            txtTcInicial.setText(tblTCambioMensual.getValueAt(fila, 4).toString());
            txtTcCierre.setText(tblTCambioMensual.getValueAt(fila, 5).toString()); // Columna Final
            txtTcPromedio.setText(tblTCambioMensual.getValueAt(fila, 6).toString()); 
        }

        // --- 5. EVENTOS ---
        btnSalir.addActionListener(e -> dialogo.dispose());

        btnAceptar.addActionListener(e -> {
            String ejercicio = txtEjercicio.getText().trim();
            if (ejercicio.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "El campo de Ejercicio es obligatorio.");
                return;
            }

            // Aquí va la lógica SQL (INSERT INTO o UPDATE)
            JOptionPane.showMessageDialog(dialogo, "Tipo de cambio mensual guardado (Simulación)");
            
            dialogo.dispose();
            cargarTablaTCMensual(); 
        });

        // --- 6. MOSTRAR ---
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTCambioMensual;
    private javax.swing.JButton btnDeleteTCambioMensual;
    private javax.swing.JButton btnEditTCambioMensual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JTable tblTCambioMensual;
    // End of variables declaration//GEN-END:variables
}
