/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benaedu.views;

/**
 *
 * @author b17za
 */
public class Tipos_Cambio_Diario extends javax.swing.JPanel {

    /**
     * Creates new form Tipos_Cambio_Diario
     */
    public Tipos_Cambio_Diario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCambioDiario = new javax.swing.JTable();
        btnAddCDiario = new javax.swing.JButton();
        btnEditCDiario = new javax.swing.JButton();
        btnDeleteCDiario = new javax.swing.JButton();

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));

        tblCambioDiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Moneda Origen", "Moneda Destino", "Fecha", "Tipo Cambio", "Usuario", "Fecha Mod.", "Hora Mod."
            }
        ));
        jScrollPane1.setViewportView(tblCambioDiario);

        btnAddCDiario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCDiario.setForeground(new java.awt.Color(26, 61, 99));
        btnAddCDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddCDiario.setText("Añadir");
        btnAddCDiario.addActionListener(this::btnAddCDiarioActionPerformed);

        btnEditCDiario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditCDiario.setForeground(new java.awt.Color(26, 61, 99));
        btnEditCDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditCDiario.setText("Editar");
        btnEditCDiario.setMaximumSize(new java.awt.Dimension(93, 31));
        btnEditCDiario.setMinimumSize(new java.awt.Dimension(93, 31));

        btnDeleteCDiario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteCDiario.setForeground(new java.awt.Color(26, 61, 99));
        btnDeleteCDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteCDiario.setText("Eliminar");
        btnDeleteCDiario.addActionListener(this::btnDeleteCDiarioActionPerformed);

        javax.swing.GroupLayout pnlBgLayout = new javax.swing.GroupLayout(pnlBg);
        pnlBg.setLayout(pnlBgLayout);
        pnlBgLayout.setHorizontalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddCDiario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCDiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCDiario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBgLayout.setVerticalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCDiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCDiarioActionPerformed

    private void btnDeleteCDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCDiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCDiarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCDiario;
    private javax.swing.JButton btnDeleteCDiario;
    private javax.swing.JButton btnEditCDiario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JTable tblCambioDiario;
    // End of variables declaration//GEN-END:variables
}
