/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.benaedu;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author b17za
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
       cargarMenuArbol();
        InitStyles();
    System.out.println(
    getClass().getResource("/images/home.png")
);
    }

    private void InitStyles(){
    lblMessage.putClientProperty( "FlatLaf.style", "font: 30" );
    lblMessage.setForeground(Color.white);
    lblTitle.putClientProperty( "FlatLaf.style", "font: 30 " );
    lblTitle.setForeground(Color.white);
    lblDate.putClientProperty( "FlatLaf.style", "font: 30 " );
    lblDate.setForeground(Color.white);
    
}
    
    private void toggleMenu(JPanel panel) {
    panel.setVisible(!panel.isVisible());
    // Esto obliga al BoxLayout a recalcular los espacios
    this.revalidate();
    this.repaint();
}
    
    private void cargarMenuArbol() {
    // 1. Crear el nodo raíz (El principal que contiene todo)
    DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Menú de Opciones");

    // 2. Crear las categorías principales
    DefaultMutableTreeNode general = new DefaultMutableTreeNode("00 General");
    DefaultMutableTreeNode contabilidad = new DefaultMutableTreeNode("01 Contabilidad");
    DefaultMutableTreeNode cuentasPagar = new DefaultMutableTreeNode("07 Cuentas por Pagar");

    // 3. Crear sub-categorías (como la de tu imagen)
    DefaultMutableTreeNode infoMaestra = new DefaultMutableTreeNode("20 Información Maestra");
    
    // 4. Agregar los "Hijos" (las opciones finales) a la sub-categoría
    infoMaestra.add(new DefaultMutableTreeNode("Catálogo de Compañías"));
    infoMaestra.add(new DefaultMutableTreeNode("Catálogo de Centros de Costo"));
    infoMaestra.add(new DefaultMutableTreeNode("Ejercicio Fiscal"));
    infoMaestra.add(new DefaultMutableTreeNode("Catálogo de Empleados"));
    
    // 5. Armar el árbol (meter los hijos en sus padres)
    general.add(infoMaestra); // Metemos infoMaestra dentro de general
    
    // Metemos las categorías principales en la raíz
    raiz.add(general);
    raiz.add(contabilidad);
    raiz.add(cuentasPagar);

    // 6. Aplicar el modelo al componente visual JTree
    DefaultTreeModel modeloArbol = new DefaultTreeModel(raiz);
    trMenu.setModel(modeloArbol);
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        background = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        trMenu = new javax.swing.JTree();
        jpHeader = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jpContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));

        jpMenu.setBackground(new java.awt.Color(0, 2, 156));
        jpMenu.setPreferredSize(new java.awt.Dimension(270, 640));

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("BENAEDU");

        trMenu.setBackground(new java.awt.Color(95, 143, 255));
        trMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        trMenu.setForeground(new java.awt.Color(255, 255, 255));
        trMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(trMenu);

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 78, Short.MAX_VALUE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblTitle)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpHeader.setBackground(new java.awt.Color(95, 143, 255));
        jpHeader.setPreferredSize(new java.awt.Dimension(744, 150));

        lblMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage.setText("Buenas Tardes, Usuario");

        lblDate.setText("Hoy es {dayname} de {month} del {year}  ");

        javax.swing.GroupLayout jpHeaderLayout = new javax.swing.GroupLayout(jpHeader);
        jpHeader.setLayout(jpHeaderLayout);
        jpHeaderLayout.setHorizontalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addGroup(jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessage)
                    .addComponent(lblDate))
                .addGap(0, 533, Short.MAX_VALUE))
        );
        jpHeaderLayout.setVerticalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addComponent(lblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDate)
                .addGap(0, 112, Short.MAX_VALUE))
        );

        jpContainer.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpContainerLayout = new javax.swing.GroupLayout(jpContainer);
        jpContainer.setLayout(jpContainerLayout);
        jpContainerLayout.setHorizontalGroup(
            jpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpContainerLayout.setVerticalGroup(
            jpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addComponent(jpContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(jpHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void trMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trMenuMouseClicked
      // Obtener el nodo que el usuario acaba de seleccionar
DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) trMenu.getLastSelectedPathComponent();

// Si no seleccionó nada, salir
if (nodoSeleccionado == null) return;

// Si es un nodo final (que no tiene hijos adentro)
if (nodoSeleccionado.isLeaf()) {
    String opcion = nodoSeleccionado.getUserObject().toString();
    
    if (opcion.equals("Catálogo de Compañías")) {
        System.out.println("Abrir pantalla de Compañías...");
        // Aquí llamas a tu panel o ventana
    } else if (opcion.equals("Catálogo de Empleados")) {
        System.out.println("Abrir pantalla de Empleados...");
    }
}
    }//GEN-LAST:event_trMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMTMaterialLighterIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    private javax.swing.JPanel jpContainer;
    private javax.swing.JPanel jpHeader;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTree trMenu;
    // End of variables declaration//GEN-END:variables
}
