/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.benaedu;
import com.mycompany.benaedu.db.ConDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
/**
 *
 * @author b17za
 */
public class EditarUsuario extends javax.swing.JFrame {
    private String usuarioOriginal;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarUsuario.class.getName());
// Modifica tu constructor para que reciba los parámetros
    public EditarUsuario(String usuario, String correo, String rol) {
        initComponents();
        
        //Se manda a llamar :P
        aplicarDiseñoPersonalizado();
        
        this.usuarioOriginal = usuario;
        
        // Llenar los campos con los datos recibidos
        txtUser.setText(usuario);
        txtEmail.setText(correo); // Asegúrate de haber cambiado el txtPassword por txtCorreo
        cmbRol.setSelectedItem(rol);
        
     
    }
    /**
     * Creates new form EditarUsuario
     */
    public EditarUsuario() {
        initComponents();
        
        //Aquí por si se abre la ventana vacía :P
        aplicarDiseñoPersonalizado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                      
    
    // --- Diseño visual: no modifica eventos ni lógica de base de datos ---
    private void aplicarDiseñoPersonalizado() {
        java.awt.Color fondo = new java.awt.Color(21, 45, 74);
        java.awt.Color tarjeta = new java.awt.Color(248, 250, 252);
        java.awt.Color azulPrincipal = new java.awt.Color(45, 111, 171);
        java.awt.Color azulPrincipalHover = new java.awt.Color(36, 91, 143);
        java.awt.Color azulPrincipalPresionado = new java.awt.Color(29, 73, 116);
        java.awt.Color azulSecundario = new java.awt.Color(220, 235, 244);
        java.awt.Color azulSecundarioHover = new java.awt.Color(201, 222, 235);
        java.awt.Color azulSecundarioPresionado = new java.awt.Color(184, 210, 226);
        java.awt.Color texto = new java.awt.Color(25, 54, 82);
        java.awt.Color borde = new java.awt.Color(184, 204, 221);

        pnlBg.setBackground(fondo);

        // La tarjeta utiliza un borde redondeado y conserva todos sus componentes.
        pnlTarejeta.setOpaque(false);
        pnlTarejeta.setBackground(tarjeta);
        pnlTarejeta.setBorder(new RoundedPanelBorder(
                tarjeta,
                new java.awt.Color(215, 227, 237),
                22,
                1
        ));

        estilizarBotonRedondeado(
                btnSave,
                azulPrincipal,
                azulPrincipalHover,
                azulPrincipalPresionado,
                java.awt.Color.WHITE
        );
        estilizarBotonRedondeado(
                btnBack,
                azulSecundario,
                azulSecundarioHover,
                azulSecundarioPresionado,
                texto
        );

        estilizarCampo(txtUser, texto, borde);
        estilizarCampo(txtEmail, texto, borde);
        estilizarCampo(cmbRol, texto, borde);

        java.awt.Font fuenteLabels = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14);
        lblUser.setFont(fuenteLabels);
        lblUser.setForeground(texto);
        lblCorreo.setFont(fuenteLabels);
        lblCorreo.setForeground(texto);
        lblRol.setFont(fuenteLabels);
        lblRol.setForeground(texto);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
        lblTitulo.setForeground(java.awt.Color.WHITE);
    }

    private void estilizarBotonRedondeado(
            javax.swing.JButton boton,
            java.awt.Color normal,
            java.awt.Color hover,
            java.awt.Color presionado,
            java.awt.Color colorTexto) {

        boton.setBackground(normal);
        boton.setForeground(colorTexto);
        boton.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        boton.setFocusPainted(false);
        boton.setBorderPainted(false);
        boton.setContentAreaFilled(false);
        boton.setOpaque(false);
        boton.setRolloverEnabled(true);
        boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 18, 8, 18));

        // Se conserva la integración con FlatLaf y se fuerza el arco visual.
        boton.putClientProperty("JButton.buttonType", "roundRect");
        boton.putClientProperty("FlatLaf.style", "arc: 18; focusWidth: 0; borderWidth: 0");

        boton.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                javax.swing.AbstractButton button = (javax.swing.AbstractButton) c;
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(
                        java.awt.RenderingHints.KEY_ANTIALIASING,
                        java.awt.RenderingHints.VALUE_ANTIALIAS_ON
                );

                java.awt.Color colorActual = normal;
                if (button.getModel().isPressed()) {
                    colorActual = presionado;
                } else if (button.getModel().isRollover()) {
                    colorActual = hover;
                }

                g2.setColor(colorActual);
                g2.fillRoundRect(0, 0, c.getWidth() - 1, c.getHeight() - 1, 18, 18);
                g2.dispose();

                super.paint(g, c);
            }
        });
    }

    private void estilizarCampo(javax.swing.JComponent campo, java.awt.Color texto, java.awt.Color borde) {
        campo.setBackground(java.awt.Color.WHITE);
        campo.setForeground(texto);
        campo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        campo.putClientProperty("Component.arc", 12);
        campo.putClientProperty("FlatLaf.style", "arc: 12; focusWidth: 1");
        campo.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(borde, 1, true),
                javax.swing.BorderFactory.createEmptyBorder(5, 9, 5, 9)
        ));

        if (campo instanceof javax.swing.JComponent) {
            campo.setPreferredSize(new java.awt.Dimension(206, 35));
        }
    }

    private static final class RoundedPanelBorder extends javax.swing.border.AbstractBorder {
        private final java.awt.Color fill;
        private final java.awt.Color line;
        private final int arc;
        private final int thickness;

        private RoundedPanelBorder(java.awt.Color fill, java.awt.Color line, int arc, int thickness) {
            this.fill = fill;
            this.line = line;
            this.arc = arc;
            this.thickness = thickness;
        }

        @Override
        public java.awt.Insets getBorderInsets(java.awt.Component c) {
            int padding = 14 + thickness;
            return new java.awt.Insets(padding, padding, padding, padding);
        }

        @Override
        public void paintBorder(
                java.awt.Component c,
                java.awt.Graphics g,
                int x,
                int y,
                int width,
                int height) {

            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            g2.setRenderingHint(
                    java.awt.RenderingHints.KEY_ANTIALIASING,
                    java.awt.RenderingHints.VALUE_ANTIALIAS_ON
            );

            g2.setColor(fill);
            g2.fillRoundRect(x, y, width - 1, height - 1, arc, arc);
            g2.setColor(line);
            g2.setStroke(new java.awt.BasicStroke(thickness));
            g2.drawRoundRect(x, y, width - 1, height - 1, arc, arc);
            g2.dispose();
        }
    }
    // -----------------------------------------------------------

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        pnlBg = new javax.swing.JPanel();
        pnlTarejeta = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cmbRol = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBg.setBackground(javax.swing.UIManager.getDefaults().getColor("List.cellFocusColor"));
        pnlBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTarejeta.setBackground(new java.awt.Color(235, 233, 223));

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userN.png"))); // NOI18N
        lblUser.setText("USUARIO:");

        lblCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmailN.png"))); // NOI18N
        lblCorreo.setText("CORREO:");

        lblRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RolN.png"))); // NOI18N
        lblRol.setText("      ROL:");

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado" }));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuardarN.png"))); // NOI18N
        btnSave.setText("Guardar");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        javax.swing.GroupLayout pnlTarejetaLayout = new javax.swing.GroupLayout(pnlTarejeta);
        pnlTarejeta.setLayout(pnlTarejetaLayout);
        pnlTarejetaLayout.setHorizontalGroup(
            pnlTarejetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarejetaLayout.createSequentialGroup()
                .addGroup(pnlTarejetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTarejetaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pnlTarejetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCorreo)
                            .addComponent(lblUser)
                            .addComponent(lblRol))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTarejetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTarejetaLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnSave)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlTarejetaLayout.setVerticalGroup(
            pnlTarejetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarejetaLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(pnlTarejetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(pnlTarejetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlTarejetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRol)
                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pnlBg.add(pnlTarejeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 133, 380, 400));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Editar Usuario");
        pnlBg.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 58, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RegresarN.png"))); // NOI18N
        btnBack.setText("Regresar");
        btnBack.addActionListener(this::btnBackActionPerformed);
        pnlBg.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 155, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondoTest6.png"))); // NOI18N
        pnlBg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String nuevoUsuario = txtUser.getText().trim();
        String nuevoCorreo = txtEmail.getText().trim(); 
        String nuevoRol = cmbRol.getSelectedItem().toString();

        if (nuevoUsuario.isEmpty() || nuevoCorreo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor completa todos los campos.");
            return;
        }

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con == null) {
                JOptionPane.showMessageDialog(this, "Error de conexión a la base de datos.");
                return;
            }

            // Actualizamos la tabla clients. Usamos el usuarioOriginal en el WHERE.
            String sql = "UPDATE users SET nombre_usuario=?, correo=?, rol=? WHERE nombre_usuario=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, nuevoUsuario);
            ps.setString(2, nuevoCorreo);
            ps.setString(3, nuevoRol);
            ps.setString(4, usuarioOriginal); // Buscamos por el nombre antes de modificarlo

            int resultado = ps.executeUpdate();

            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.");
                
                // Si todo sale bien, regresamos a la pantalla de gestión
                this.dispose();
                FlatMTMaterialLighterIJTheme.setup();
                GestionarUsuario gestionar = new GestionarUsuario();
                gestionar.setLocationRelativeTo(null);
                gestionar.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el usuario.");
            }

            ps.close();
            db.Cerrar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
// Simplemente cerramos esta ventana y volvemos a la tabla
        this.dispose();
        FlatMTMaterialLighterIJTheme.setup();
        GestionarUsuario gestionar = new GestionarUsuario();
        gestionar.setLocationRelativeTo(null);
        gestionar.setVisible(true);      
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JPanel pnlTarejeta;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
