/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.benaedu;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
import com.mycompany.benaedu.db.ConDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.mindrot.jbcrypt.BCrypt;
/**
 *
 * @author b17za
 */
public class GestionarUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionarUsuario.class.getName());

    /**
     * Creates new form GestionarUsuario
     */
    public GestionarUsuario() {
        initComponents();
        cargarUsuarios();
    }
    
    private void cargarUsuarios() {
        // Obtenemos el modelo de la tabla para poder modificar sus filas
        DefaultTableModel modelo = (DefaultTableModel) tblUsers.getModel();
        modelo.setRowCount(0); // Esto limpia la tabla antes de cargar nuevos datos

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con != null) {
                // Consultamos los datos que nos interesan
                PreparedStatement ps = con.prepareStatement("SELECT nombre_usuario,nombre,apellidos, correo, rol FROM users");
                ResultSet rs = ps.executeQuery();

                // Recorremos los resultados y los agregamos fila por fila
                while (rs.next()) {
                    Object[] fila = new Object[5];
                    fila[0] = rs.getString("nombre_usuario");
                    fila[1] = rs.getString("nombre");
                    fila[2] = rs.getString("apellidos");
                    fila[3] = rs.getString("correo");
                    fila[4] = rs.getString("rol");
                    modelo.addRow(fila);
                }

                rs.close();
                ps.close();
                db.Cerrar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los usuarios: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBg = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnEditUser = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnDeleteUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RegresarN.png"))); // NOI18N
        btnBack.setText("Regresar");
        btnBack.addActionListener(this::btnBackActionPerformed);
        pnlBg.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 130, 40));

        btnEditUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEditUser.setText("Editar");
        btnEditUser.addActionListener(this::btnEditUserActionPerformed);
        pnlBg.add(btnEditUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, 120, 40));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Gestionar Usuarios");
        pnlBg.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        btnDeleteUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteUser.setText("Eliminar");
        btnDeleteUser.addActionListener(this::btnDeleteUserActionPerformed);
        pnlBg.add(btnDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 130, 40));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Usuario", "Nombre", "Apellidos", "Correo", "Rol"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        pnlBg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 800, 400));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondoTest6.png"))); // NOI18N
        pnlBg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-570, -20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
       // 1. Verificar si hay una fila seleccionada
        int filaSeleccionada = tblUsers.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un usuario de la tabla para eliminar.");
            return;
        }

        // 2. Obtener el nombre del usuario seleccionado (columna 0)
        String usuarioAEliminar = tblUsers.getValueAt(filaSeleccionada, 0).toString();

        // 3. Pedir la contraseña del administrador
        javax.swing.JPasswordField pwdField = new javax.swing.JPasswordField();
        int opcion = JOptionPane.showConfirmDialog(
            this,
            pwdField,
            "Ingrese la contraseña de un Administrador para confirmar",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (opcion == JOptionPane.OK_OPTION) {
            String claveIngresada = new String(pwdField.getPassword()).trim();

            if (claveIngresada.isEmpty()) {
                JOptionPane.showMessageDialog(this, "La contraseña no puede estar vacía.");
                return;
            }

            try {
                ConDB db = new ConDB();
                Connection con = db.Conectar();

                if (con == null) {
                    JOptionPane.showMessageDialog(this, "Error de conexión a la base de datos.");
                    return;
                }

                // 4. Validar que la clave pertenece a un administrador
                PreparedStatement psAdmin = con.prepareStatement("SELECT contrasena FROM users WHERE rol = 'Administrador'");
                ResultSet rsAdmin = psAdmin.executeQuery();
                boolean adminValido = false;

                while (rsAdmin.next()) {
                    if (BCrypt.checkpw(claveIngresada, rsAdmin.getString("contrasena"))) {
                        adminValido = true;
                        break;
                    }
                }

                rsAdmin.close();
                psAdmin.close();

                // 5. Si la clave es válida, eliminamos al usuario
                if (adminValido) {
                    PreparedStatement psDelete = con.prepareStatement("DELETE FROM users WHERE nombre_usuario = ?");
                    psDelete.setString(1, usuarioAEliminar);
                    
                    int eliminado = psDelete.executeUpdate();

                    if (eliminado > 0) {
                        JOptionPane.showMessageDialog(this, "Usuario '" + usuarioAEliminar + "' eliminado correctamente.");
                        cargarUsuarios(); // Recargar la tabla para que desaparezca visualmente
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo eliminar al usuario.");
                    }
                    psDelete.close();
                } else {
                    JOptionPane.showMessageDialog(this, "Contraseña incorrecta o no pertenece a un administrador. Operación cancelada.");
                }

                db.Cerrar();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
            this.dispose(); // Cierra la ventana actual
    FlatMTMaterialLighterIJTheme.setup();
    CrearUsuarios crearUsuario = new CrearUsuarios();
    crearUsuario.setSize(893, 540);
    crearUsuario.setLocationRelativeTo(null);
    crearUsuario.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
         int filaSeleccionada = tblUsers.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un usuario de la tabla para editar.");
            return;
        }

        // Obtener los datos de la fila seleccionada
        String usuario = tblUsers.getValueAt(filaSeleccionada, 0).toString();
        String correo = tblUsers.getValueAt(filaSeleccionada, 3).toString();
        String rol = tblUsers.getValueAt(filaSeleccionada, 4).toString();

        // Cerrar ventana actual y abrir EditarUsuario pasándole los datos
        this.dispose();
        FlatMTMaterialLighterIJTheme.setup();
        
        // Llamamos a un nuevo constructor que crearemos en el siguiente paso
        EditarUsuario editar = new EditarUsuario(usuario, correo, rol); 
        editar.setLocationRelativeTo(null);
        editar.setVisible(true);
    }//GEN-LAST:event_btnEditUserActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
