/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.benaedu;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
import java.awt.Color;
import com.mycompany.benaedu.db.ConDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author b17za
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        initStyles();
     
    }
    
    private void initStyles(){
     lblUsuario.putClientProperty("FlatLaf.style", "font: bold 20");
     lblUsuario.setForeground(new Color(179,207,229));
     lblContraseña.putClientProperty("FlatLaf.style", "font: bold 20");
     lblContraseña.setForeground(new Color(179,207,229));
     lblTitulo.putClientProperty("FlatLaf.style", "font: bold 20");
     lblTitulo.setForeground(new Color(179,207,229));
    }
    

 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnCreateUser = new javax.swing.JButton();
        btnForgotPassword = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTitulo.setText("Bienvenido");

        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userIcon.png"))); // NOI18N
        lblUsuario.setText("Usuario:");

        txtUser.addActionListener(this::txtUserActionPerformed);

        lblContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/passwordIcon.png"))); // NOI18N
        lblContraseña.setText("Contraseña:");

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setText("INGRESAR");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        btnCreateUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateUser.setText("CREAR USUARIO");
        btnCreateUser.addActionListener(this::btnCreateUserActionPerformed);

        btnForgotPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnForgotPassword.setText("Olvidaste tu contraseña?");
        btnForgotPassword.addActionListener(this::btnForgotPasswordActionPerformed);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgescudo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblContraseña)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUsuario))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btnLogin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnCreateUser))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lblTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 134, Short.MAX_VALUE)
                .addComponent(btnForgotPassword)
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnForgotPassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 450, 510));
        pnlBg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 92, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo.png"))); // NOI18N
        pnlBg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
          // Pedir contraseña
        javax.swing.JPasswordField pwdField = new javax.swing.JPasswordField();
        int opcion = JOptionPane.showConfirmDialog(
            this,
            pwdField,
            "Ingrese la contraseña de un Administrador",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (opcion == JOptionPane.OK_OPTION) {
            String claveIngresada = new String(pwdField.getPassword()).trim();

            if (claveIngresada.isEmpty()) {
                JOptionPane.showMessageDialog(this, "La contraseña no puede estar vacía.");
                return;
            }

            try {
                // Usamos tu clase ConDB para mantener la conexión limpia
                ConDB db = new ConDB();
                Connection con = db.Conectar();
                
                if (con == null) {
                    JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos.");
                    return;
                }

                // Consultamos las contraseñas (hashes) de TODOS los administradores de la tabla clients
                PreparedStatement ps = con.prepareStatement("SELECT contrasena FROM users WHERE rol = 'Administrador'");
                ResultSet rs = ps.executeQuery();

                boolean adminValido = false;

                // Recorremos los resultados y comparamos la clave con los hashes usando BCrypt
                while (rs.next()) {
                    String hashAdmin = rs.getString("contrasena");
                    
                    if (BCrypt.checkpw(claveIngresada, hashAdmin)) {
                        adminValido = true;
                        break; // Si hay coincidencia, dejamos de buscar
                    }
                }

                if (adminValido) {
                    // Contraseña válida, abrir formulario
                    this.dispose(); // cerrar login
                    FlatMTMaterialLighterIJTheme.setup();
                    CrearUsuarios crear = new CrearUsuarios();
                    crear.setSize(893, 540); // Descomenta si necesitas un tamaño fijo
                    crear.setLocationRelativeTo(null);
                    crear.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Contraseña incorrecta o no pertenece a un administrador.");
                }

                rs.close();
                ps.close();
                db.Cerrar();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotPasswordActionPerformed
        this.dispose(); // Cierra la ventana actual
    FlatMTMaterialLighterIJTheme.setup();
    RecuperarContraseña recuperarContraseña = new RecuperarContraseña();
    recuperarContraseña.setSize(893, 540);
    recuperarContraseña.setLocationRelativeTo(null);
    recuperarContraseña.setVisible(true);
    }//GEN-LAST:event_btnForgotPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String usuario = txtUser.getText().trim();
        String clave = new String(txtPassword.getPassword()).trim(); 

        if (usuario.isEmpty() || clave.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor completa todos los campos.");
            return;
        }

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();
            
            if (con == null) {
                JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos.");
                return;
            }

            // 1. MODIFICACIÓN: Agregamos 'nombre' y 'apellidos' a la consulta
            PreparedStatement ps = con.prepareStatement("SELECT contrasena, rol, temporal, nombre, apellidos FROM users WHERE nombre_usuario=?");
            ps.setString(1, usuario);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String hashBD = rs.getString("contrasena"); 
                String rol = rs.getString("rol");
                boolean esTemporal = rs.getBoolean("temporal");
                
                // 2. MODIFICACIÓN: Obtenemos el nombre y apellido, previniendo que vengan vacíos (nulos)
                String nombreReal = rs.getString("nombre") != null ? rs.getString("nombre") : "";
                String apellidosReal = rs.getString("apellidos") != null ? rs.getString("apellidos") : "";
                
                // Juntamos el nombre y apellido en una sola variable
                String nombreCompleto = (nombreReal + " " + apellidosReal).trim();
                
                // Si por alguna razón el usuario no tiene nombre registrado, usamos su nombre de usuario como respaldo
                if (nombreCompleto.isEmpty()) {
                    nombreCompleto = usuario;
                }

                if (BCrypt.checkpw(clave, hashBD)) {
                    
                    if (esTemporal) {
                        JOptionPane.showMessageDialog(this, "Por seguridad, debes restablecer tu contraseña.");
                        this.dispose(); 
                        
                        RestablecerContraseña ventanaRestablecer = new RestablecerContraseña(usuario);
                        ventanaRestablecer.setLocationRelativeTo(null); 
                        ventanaRestablecer.setVisible(true); 
                        return;
                    }

                    // 3. MODIFICACIÓN: Cambiamos el mensaje de bienvenida y le pasamos el nombreCompleto al Dashboard
                    JOptionPane.showMessageDialog(this, "¡Bienvenido " + nombreCompleto + " (" + rol + ")!");
                    
                    this.dispose(); // Cierra la ventana de Login
                    
                    // Aquí le pasamos el nombre completo (Juan Pérez) en lugar de (juanp123)
                    Dashboard ventanaDashboard = new Dashboard(nombreCompleto);
                    ventanaDashboard.setLocationRelativeTo(null); 
                    ventanaDashboard.setVisible(true); 
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.");
            }

            rs.close();
            ps.close();
            db.Cerrar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en el sistema: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMTMaterialLighterIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnForgotPassword;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
