/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.benaedu;
import com.mycompany.benaedu.db.ConDB;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.UUID;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
/**
 *
 * @author b17za
 */
public class RecuperarContraseña extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName());

    /**
     * Creates new form RecuperarContrasenia
     */
    public RecuperarContraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBg = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                // Aquí le decimos a Java dónde está la imagen
                java.net.URL url = getClass().getResource("/resources/fondoTest.png");

                if (url != null) {
                    java.awt.Image img = new javax.swing.ImageIcon(url).getImage();
                    // Esto dibuja la imagen y la estira al tamaño exacto de la ventana
                    g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
                } else {
                    System.out.println("No se encontró la imagen en la ruta especificada.");
                }
            }
        };
        lblTitulo = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        lblTitulo.setText("Recuperar Contraseña");
        pnlBg.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 500, -1));

        lblText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblText.setText("Ingrese el correo electronico del usuario");
        pnlBg.add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmailN.png"))); // NOI18N
        lblEmail.setText("Correo:");
        pnlBg.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlBg.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 320, 40));

        btnSend.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSend.setText("Enviar");
        btnSend.addActionListener(this::btnSendActionPerformed);
        pnlBg.add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, -1, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RegresarN.png"))); // NOI18N
        btnBack.setText("Regresar");
        btnBack.addActionListener(this::btnBackActionPerformed);
        pnlBg.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoTest4.png"))); // NOI18N
        jLabel1.setToolTipText("");
        pnlBg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 0, 2010, 1240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
      String correo = txtEmail.getText().trim();

        if (correo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa el correo electrónico.");
            return;
        }

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con == null) {
                JOptionPane.showMessageDialog(this, "Error de conexión a la base de datos.");
                return;
            }

            // 1. Verificar si el correo existe en la tabla clients
            PreparedStatement psVerificar = con.prepareStatement("SELECT nombre_usuario FROM users WHERE correo = ?");
            psVerificar.setString(1, correo);
            ResultSet rs = psVerificar.executeQuery();

            if (rs.next()) {
                String nombreUsuario = rs.getString("nombre_usuario");

                // 2. Generar una contraseña temporal aleatoria de 8 caracteres
                String claveTemporal = UUID.randomUUID().toString().substring(0, 8);

                // 3. Encriptar la contraseña temporal
                String hashTemporal = BCrypt.hashpw(claveTemporal, BCrypt.gensalt());

                // 4. Actualizar la base de datos (guardar el hash y marcar temporal = 1)
                PreparedStatement psActualizar = con.prepareStatement("UPDATE users SET contrasena = ?, temporal = 1 WHERE correo = ?");
                psActualizar.setString(1, hashTemporal);
                psActualizar.setString(2, correo);
                
                int actualizado = psActualizar.executeUpdate();

             if (actualizado > 0) {
                    // INTENTAMOS ENVIAR EL CORREO REAL AQUÍ
                    try {
                        // Llamamos al método que envía el correo
                        enviarCorreoReal(correo, claveTemporal);
                        
                        JOptionPane.showMessageDialog(this, "¡Correo enviado con éxito a " + correo + "!");
                        txtEmail.setText(""); // Limpiar el campo
                        
                    } catch (MessagingException ex) {
                        // Si falla el envío del correo (ej. sin internet o clave mal puesta)
                        JOptionPane.showMessageDialog(this, "La base de datos se actualizó, pero hubo un error enviando el correo: " + ex.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar actualizar la contraseña.");
                }
                
                psActualizar.close();

            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún usuario registrado con ese correo.");
            }

            rs.close();
            psVerificar.close();
            db.Cerrar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void enviarCorreoReal(String correoDestino, String claveTemporal) throws MessagingException {
        // Tu correo de Gmail y la contraseña de aplicación de 16 dígitos que generaste
        String miCorreo = "b17zaithlc@gmail.com"; 
        String miContraseñaApp = "iauq cclw xinn otsh"; // Reemplaza con tu clave de aplicación

        // Configuración del servidor SMTP de Google
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587"); // Puerto seguro TLS
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");

        // Autenticación de la sesión
        Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(miCorreo, miContraseñaApp);
            }
        });

        // Creación del mensaje
        Message message = new MimeMessage(session);
        message.setFrom(new InternetAddress(miCorreo));
        message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(correoDestino));
        message.setSubject("Recuperación de Contraseña - Sistema BenaEdu");
        
        // Cuerpo del correo
        String mensajeCuerpo = "Hola,\n\n"
                + "Se ha solicitado el restablecimiento de tu contraseña.\n\n"
                + "Tu contraseña temporal es: " + claveTemporal + "\n\n"
                + "Por favor, inicia sesión con esta contraseña. El sistema te pedirá que la cambies inmediatamente por motivos de seguridad.\n\n"
                + "Saludos,\nAdministración BenaEdu.";
        
        message.setText(mensajeCuerpo);

        // Enviar el correo
        Transport.send(message);
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
     this.dispose(); 
        FlatMTMaterialLighterIJTheme.setup();
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

   
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
