/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.benaedu;
import com.mycompany.benaedu.db.ConDB;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.UUID;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
/**
 *
 * @author b17za
 */
public class RecuperarContraseña extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName());

    /**
     * Creates new form RecuperarContrasenia
     */
    public RecuperarContraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBg = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setText("Recuperar Contraseña");

        lblText.setText("Ingrese el correo electronico del usuario");

        lblEmail.setText("Correo:");

        btnSend.setText("Enviar");
        btnSend.addActionListener(this::btnSendActionPerformed);

        btnBack.setText("Regresar");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout pnlBgLayout = new javax.swing.GroupLayout(pnlBg);
        pnlBg.setLayout(pnlBgLayout);
        pnlBgLayout.setHorizontalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBgLayout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(lblTitulo))
                    .addGroup(pnlBgLayout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(lblEmail)
                        .addGap(57, 57, 57)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                .addGap(111, 111, 111)
                .addComponent(btnBack)
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBgLayout.createSequentialGroup()
                        .addComponent(lblText)
                        .addGap(258, 258, 258))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBgLayout.createSequentialGroup()
                        .addComponent(btnSend)
                        .addGap(341, 341, 341))))
        );
        pnlBgLayout.setVerticalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(btnBack))
                .addGap(94, 94, 94)
                .addComponent(lblText)
                .addGap(11, 11, 11)
                .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnSend)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
      String correo = txtEmail.getText().trim();

        if (correo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa el correo electrónico.");
            return;
        }

        try {
            ConDB db = new ConDB();
            Connection con = db.Conectar();

            if (con == null) {
                JOptionPane.showMessageDialog(this, "Error de conexión a la base de datos.");
                return;
            }

            // 1. Verificar si el correo existe en la tabla clients
            PreparedStatement psVerificar = con.prepareStatement("SELECT nombre_usuario FROM users WHERE correo = ?");
            psVerificar.setString(1, correo);
            ResultSet rs = psVerificar.executeQuery();

            if (rs.next()) {
                String nombreUsuario = rs.getString("nombre_usuario");

                // 2. Generar una contraseña temporal aleatoria de 8 caracteres
                String claveTemporal = UUID.randomUUID().toString().substring(0, 8);

                // 3. Encriptar la contraseña temporal
                String hashTemporal = BCrypt.hashpw(claveTemporal, BCrypt.gensalt());

                // 4. Actualizar la base de datos (guardar el hash y marcar temporal = 1)
                PreparedStatement psActualizar = con.prepareStatement("UPDATE users SET contrasena = ?, temporal = 1 WHERE correo = ?");
                psActualizar.setString(1, hashTemporal);
                psActualizar.setString(2, correo);
                
                int actualizado = psActualizar.executeUpdate();

             if (actualizado > 0) {
                    // INTENTAMOS ENVIAR EL CORREO REAL AQUÍ
                    try {
                        // Llamamos al método que envía el correo
                        enviarCorreoReal(correo, claveTemporal);
                        
                        JOptionPane.showMessageDialog(this, "¡Correo enviado con éxito a " + correo + "!");
                        txtEmail.setText(""); // Limpiar el campo
                        
                    } catch (MessagingException ex) {
                        // Si falla el envío del correo (ej. sin internet o clave mal puesta)
                        JOptionPane.showMessageDialog(this, "La base de datos se actualizó, pero hubo un error enviando el correo: " + ex.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar actualizar la contraseña.");
                }
                
                psActualizar.close();

            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún usuario registrado con ese correo.");
            }

            rs.close();
            psVerificar.close();
            db.Cerrar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void enviarCorreoReal(String correoDestino, String claveTemporal) throws MessagingException {
        // Tu correo de Gmail y la contraseña de aplicación de 16 dígitos que generaste
        String miCorreo = "b17zaithlc@gmail.com"; 
        String miContraseñaApp = "iauq cclw xinn otsh"; // Reemplaza con tu clave de aplicación

        // Configuración del servidor SMTP de Google
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587"); // Puerto seguro TLS
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");

        // Autenticación de la sesión
        Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(miCorreo, miContraseñaApp);
            }
        });

        // Creación del mensaje
        Message message = new MimeMessage(session);
        message.setFrom(new InternetAddress(miCorreo));
        message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(correoDestino));
        message.setSubject("Recuperación de Contraseña - Sistema BenaEdu");
        
        // Cuerpo del correo
        String mensajeCuerpo = "Hola,\n\n"
                + "Se ha solicitado el restablecimiento de tu contraseña.\n\n"
                + "Tu contraseña temporal es: " + claveTemporal + "\n\n"
                + "Por favor, inicia sesión con esta contraseña. El sistema te pedirá que la cambies inmediatamente por motivos de seguridad.\n\n"
                + "Saludos,\nAdministración BenaEdu.";
        
        message.setText(mensajeCuerpo);

        // Enviar el correo
        Transport.send(message);
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
     this.dispose(); 
        FlatMTMaterialLighterIJTheme.setup();
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

   
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
